Handle network disconnection
sourcegraph/cody pull request #107
Opened 2023-07-12 07:23 UTC by deepak2431

This PR closes #43

2023-07-12 18:12 UTC, deepak2431 commented
@abeatrix Can I have a review, please?

2023-07-13 03:22 UTC, abeatrix requested changes
i left some comments inline with some minor change request, the rest looks good to me!
Will defer to tim on the design :D

2023-07-13 03:22 UTC, abeatrix commented on vscode/src/chat/ChatViewProvider.ts
> +                const endpoint = message.serverEndpoint.length ? message.serverEndpoint : this.config.serverEndpoint
Can you tell me more about this change? 
This is called when a user input the endpoint and access token manually, so it doesn't make sense to me to replace them with the ones from this.config if those are not available 👀

2023-07-13 03:22 UTC, abeatrix commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
i think instead of `this.sendErrorToWebview()`, we should use `this.transcript.addErrorAsAssistantResponse()` (or both) to avoid having missing bot response item: 
<img width="378" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/f5ff098f-785e-4fbf-81c2-b560ff7b6ddf">

 i think the only time we can have a boy response item is when the message is aborted manually, what do you think? 😄

2023-07-13 03:22 UTC, abeatrix commented on vscode/webviews/Error.tsx
> +                    <p>{AUTH_ERRORS.NETWORK_ERROR}</p>
I like this! Maybe we can show the endpoint address to let the user know which instance is having network issue?

2023-07-13 03:22 UTC, abeatrix commented on vscode/webviews/Error.tsx
> +                    <VSCodeButton className={styles.button} type="button" onClick={handleReload}>
maybe update the button styles to have full width like the rest of the buttons in the login page? Will defer to @toolmantim who will be back next week from his PTO :)

2023-07-13 03:22 UTC, abeatrix commented on vscode/webviews/Error.tsx
> +                    <VSCodeButton className={styles.button} type="button" onClick={handleReload}>
maybe update the button styles to have full width like the rest of the buttons in the login page? Will defer to @toolmantim who will be back next week from his PTO :)

2023-07-13 08:05 UTC, deepak2431 commented on vscode/webviews/Error.tsx
> +                    <VSCodeButton className={styles.button} type="button" onClick={handleReload}>
Yes, we can have that so it would be align to the style with all other buttons.

2023-07-13 08:06 UTC, deepak2431 commented on vscode/webviews/Error.tsx
> +                    <p>{AUTH_ERRORS.NETWORK_ERROR}</p>
That would be a good add on, I will update it.

2023-07-13 08:07 UTC, deepak2431 commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
It would be good to have both of them, as ENOTFOUND error as error assistant response shows up. So, this won't be much clear for the user as to why this is happening, so it would be better to include both. LMK, if you agree to this?

2023-07-13 08:14 UTC, deepak2431 commented
@abeatrix Thanks for the review! Can network errors be handled when the Sign In is done using Cody App? I tried this but couldn't get a working solution. 
Also, do you mind testing it once for the enterprise test customer instance to ensure it works perfectly for that cases too?

2023-07-13 08:28 UTC, abeatrix commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
Yea let's see what tim thinks but what what you suggested makes sense to me :)

2023-07-13 14:14 UTC, deepak2431 commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
Sure, will wait for him to confirm.

2023-07-23 17:29 UTC, deepak2431 commented
@toolmantim Can you please look at this and add your comments about the flow and the button CSS so I can make those changes?

2023-07-24 06:16 UTC, deepak2431 commented on vscode/webviews/Error.tsx
> +                    <VSCodeButton className={styles.button} type="button" onClick={handleReload}>
Got it, thanks @toolmantim

2023-07-24 06:16 UTC, deepak2431 commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
@toolmantim  What about this?

2023-07-24 06:47 UTC, toolmantim commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
I think outputting it into the chat as a bot response is enough, we don't need an additional error at the top also. We could restyle the error bot responses to be red or make it clearer, but that can happen in a follow-up.

2023-07-24 07:04 UTC, deepak2431 commented on vscode/src/chat/ChatViewProvider.ts
> +                    void this.sendErrorToWebview(
That sounds good to me. To mention, for now, there's an implementation of ErrAssistantResponse to show in the chat so after removing this webview error that would be displayed in case of an error.

2023-07-24 17:22 UTC, abeatrix commented
Left an in-line comment. Also adding @umpox as reviewer as he's working on refactoring the chat view that could be related 😃

2023-07-24 17:32 UTC, deepak2431 commented
@abeatrix I think you forgot to submit the inline comments as I can't see them. Looking forward to review from @umpox

2023-07-24 20:01 UTC, abeatrix reviewed
See inline comment.
Will defer to @umpox for final approval as this made changes in the refactoring work he is working on.

2023-07-25 05:34 UTC, deepak2431 commented on vscode/src/chat/ChatViewProvider.ts
> +                const token = message.accessToken.length ? message.accessToken : this.config.accessToken
Yeah, agree that would be the case here based on the implementation logic. It would be better to separate this in different messages as `reload`, in which we check the config values and` login` the user. WDYT, LMK?

2023-07-25 10:12 UTC, umpox reviewed
Left a couple of comments!

2023-07-25 10:12 UTC, umpox commented on vscode/webviews/Error.tsx
> +        'Due to network-related problems, Cody cannot be reached. Try again after checking it! Once your connection is restored, attempt a reload.',
```suggestion
    NETWORK_ERROR:
        'Connection failed due to a network problem. Please check your internet connection and try again.',
```

Small copy change to make this a bit simpler

2023-07-25 10:12 UTC, umpox commented on vscode/src/chat/ChatViewProvider.ts
> +                const token = message.accessToken.length ? message.accessToken : this.config.accessToken
I think separating this into `reload` is a good idea 👍

2023-07-25 11:01 UTC, deepak2431 commented
@umpox @abeatrix Made all the requested changes. Also, I updated the error message in the assistant response in case of network error to be clear about that. Check the updated video in the PR description for the final behaviour.

2023-07-25 20:33 UTC, abeatrix commented
@deepak2431 

> @umpox @abeatrix Made all the requested changes. Also, I updated the error message in the assistant response in case of network error to be clear about that. Check the updated video in the PR description for the final behaviour.

can you resolve the merge conflicts before we check out the branch please? Thanks!

2023-07-26 07:31 UTC, deepak2431 commented
@abeatrix Resolved the conflicts and updated the code as per the refactor of ChatView.

2023-07-26 21:44 UTC, abeatrix approved these changes
worked as expected! Thanks @deepak2431 !!

2023-07-27 09:55 UTC, umpox approved these changes
🚀

2023-07-27 15:26 UTC, merged