refactor: expand code action range
sourcegraph/cody pull request #1163
Opened 2023-09-25 19:46 UTC by abeatrix

Refactor: expand code action range

Expand the range used for code actions to the range of the function rather than just the current line. This improves the quality of fixup actions by providing more context.

The range is now obtained by calling getTargetFoldingRange() instead of just expanding to the range of the curret line. 

The getCursorFoldingRange() utility was renamed to getTargetFoldingRange() to better reflect its purpose.

## Test plan

#### Before

https://github.com/sourcegraph/cody/assets/68532117/9c31b619-14a4-4e4c-9c53-2a1d63cfb96b

#### After

https://github.com/sourcegraph/cody/assets/68532117/2df34653-6cfe-4385-b348-a1d2406808a7

2023-09-25 20:37 UTC, philipp-spiess approved these changes

2023-09-25 20:37 UTC, philipp-spiess commented on vscode/src/editor/utils/folding-ranges.ts
> +export async function getOuterClassFoldingRanges(
If this is just a helper function, why is it exported from the module? 🦭

2023-09-25 20:37 UTC, philipp-spiess commented on vscode/src/editor/utils/folding-ranges.ts
> +export async function getTargetFoldingRange(uri: vscode.Uri, target: number): Promise<vscode.Selection | undefined> {
I think the fact that these use the folding range API is not really important for the caller, is it? I say this because I think we can just name this `getSmartRanges` or `getSections` or whatever instead, to better explain that this is _more_ than just the folding range provider

2023-09-25 20:38 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +export async function getOuterClassFoldingRanges(
good points, let me remove the export for helpers!

2023-09-25 21:19 UTC, dominiccooney requested changes
Comments inline. I think we can simplify this somewhat.

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> + * @returns Array of combined folding ranges with overlapping ranges nested.
```suggestion
 * @returns Array of combined folding ranges with overlapping ranges merged.
```

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +        if (prevRange && prevRange.end === range.start - 1) {
What's the -1 about, here? Seems very specific.

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +            chains = [lastCombinedRange, range]
The condition on line 229 seems very close to line 222.

The modification of chains is hard to follow... there's only zero/one/two items in there for the body of the loop. Can you just track the start and end in variables?

Can this method be simplified? It seems a lot like the method for removing overlapping ranges, but it should only consider ranges which start at end-1 to be overlapping.

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +    return prompt + '\nHere is the code: \n<Code>' + code + '</Code>'
`<code>` is a HTML tag, does that make it good to use (LLM gets the meaning) or not (more likely to appear in the code we are quoting and gets confusing)?

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/index.ts
> +export async function getFoldingRanges(uri: vscode.Uri, type?: string): Promise<vscode.FoldingRange[]> {
If type can only be specific strings, then let's type it to only allow those strings.

Even better, can we use the VScode folding range type that we're filtering on here? It will simplify this method a bit.

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/index.ts
> +                r => r.kind !== vscode.FoldingRangeKind.Imports && r.kind !== vscode.FoldingRangeKind.Comment
VScode has FoldingRangeKind.Region, why not use that?

2023-09-25 21:19 UTC, dominiccooney commented on vscode/src/editor/utils/index.ts
> +    const symbols =
Just return it directly?

2023-09-25 21:33 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    const textBaseLangIds = ['markdown', 'plaintext', 'json', 'sql']
Because we use the symbol class to filter the class range, but for files that do not have symbols supported, we can still try to select the closest range through this step. Or do you think we should just not support these type of files at all?

2023-09-25 21:35 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +     * NOTE (bee) The purpose of filtering to keep only folding ranges that contain other folding ranges is to find
This step is just to remove all the nested folding ranges returned by the API, if the outermost folding range does not contain other folding range, we will still be able to capture the outermost ranges:
<img width="703" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/6cd685d7-a3bd-4839-b483-76e2c7554460">

2023-09-25 21:37 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +        .filter((r, i) => firstLines[i].includes('class') || firstLines[i].startsWith('object'))
this was inspired by [scala singleton object](https://docs.scala-lang.org/tour/singleton-objects.html) that structures similar to `class`

2023-09-25 21:46 UTC, abeatrix commented on vscode/src/editor/utils/index.ts
> +export async function getFoldingRanges(uri: vscode.Uri, type?: string): Promise<vscode.FoldingRange[]> {
> can we use the VScode folding range type that we're filtering on here
True! Will updated this!

2023-09-25 21:47 UTC, abeatrix commented on vscode/src/editor/utils/index.ts
> +                r => r.kind !== vscode.FoldingRangeKind.Imports && r.kind !== vscode.FoldingRangeKind.Comment
i wanted to make sure comments and imports are not included in regions, but you're right, that'd be different than what is defined by the folding range kind so i will update this to use FoldingRangeKind.Region, thanks!

2023-09-25 23:30 UTC, philipp-spiess commented on vscode/src/editor/utils/folding-ranges.ts
> +    return new vscode.Selection(targetRange.start, 0, targetRange.end + 2, 0)
@abeatrix If we add another line, don't we have to set the the selection end character to something > 0`?

2023-09-25 23:35 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +        cur => !filtered.some(next => next !== cur && next.start <= cur.start && next.end >= cur.end)
Two things 
1. even if the ranges are identical but are different objects, they will not filter each other out. The condition 
`next !== cur`  in the inner  `some()` function checks for object identity, not for equality of the range values.

In this code, a 'cur' range will only be removed if there's another 'next' range that is not the same object` (
next !== cur
) `and that completely encompasses 'cur' `(
next.start <= cur.start && next.end >= cur.end
)`. Thus, two identical ranges (same start and end but different objects) will not remove each other.

2. There is no chance of having identical ranges because all the folding ranges are a directed acyclic graph. See [this](https://github.com/sourcegraph/cody/pull/1116#discussion_r1336323775)

2023-09-26 01:38 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +    const classRanges = isSupported ? classes : await getOuterClassFoldingRanges(ranges, uri)
```suggestion
    const classRanges = doc.languageId ? classes : await getOuterClassFoldingRanges(ranges, uri)
```

isSupported is the check for textBasedLanguages but you wanna run `getOuterClassFoldingRanges` for languages that don't support langserver and you want to do that when the language id is not available so then you use heuristics to find class ranges.

In the case of Json, plaintext, sql, markdown the whole concept of classes doesn't make sense so you get empty array of classes(which is what you want)

2023-09-26 01:46 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +    const targetRange = getNonClassOutermostFoldingRanges(classRanges, ranges, target, isSupported)
```suggestion
    const isPlainText = !isSupported
    const targetRange = getNonClassOutermostFoldingRanges(classRanges, ranges, target, isPlainText)
```

Fundamentally the idea is that `isSupported` is the inverse of `isPlainText`. You wanted an isPlainText check to combine neighbour ranges for plaintext documents as shown [here](https://github.com/sourcegraph/cody/pull/1163/files#diff-7a994af9d659344fecd4e2771e864229c0cf1158c4ce5acbe08957b906cf765aR172) 

But the inverse was missed in the document flow so now the `combineNeiborFoldingRanges` actually works for NON text based files(I.E. Normal files like typescript etc)  which I don't think was your intention.

2023-09-26 01:56 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +function combineNeiborFoldingRanges(ranges: vscode.FoldingRange[]): vscode.FoldingRange[] {
My first thought was that this function's logic can be greatly simplified. I checked it and found as simple Linear time algo for exactly the same thing 

```
function combineNeighboringFoldingRanges(ranges: vscode.FoldingRange[]): vscode.FoldingRange[] {
    const combinedRanges: vscode.FoldingRange[] = [];

    for (const range of ranges) {
        const lastCombinedRange = combinedRanges[combinedRanges.length - 1];

        if (lastCombinedRange && lastCombinedRange.end === range.start - 1) {
            // Expand the last combined range to include the current range
            lastCombinedRange.end = range.end;
        } else {
            // Current range is not connected; push it as a new combined range
            combinedRanges.push(range);
        }
    }

    return combinedRanges;
}
```

But now i am not able to understand how this function helps the algorithm for extending folding ranges and if the algorithm would be dysfunctional without this.
For the text based use cases or even for non-text use cases(Typescript etc). Can you elaborate on the reasoning for having this?

2023-09-26 02:12 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +    const textBaseLangIds = ['markdown', 'plaintext', 'json', 'sql']
Some thoughts on this https://drive.google.com/file/d/1R7IccCtYln0xcf7_-I2iCp0wwSzoCUot/view?usp=sharing

2023-09-26 09:30 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    return new vscode.Selection(targetRange.start, 0, targetRange.end + 2, 0)
@philipp-spiess the + 1 includes the line where the bracket that was missing, and the extra +1 at 0 position is to capture the missing bracket, while not breaking even if the line after the bracket does not exist because the character position is at 0. See the example here where the line after the bracket is already at the end of file, and we were still able to capture the whole block:
![eof](https://github.com/sourcegraph/cody/assets/68532117/3d8adc02-8b98-4c81-bea6-738ddd3158cc)

2023-09-26 10:03 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    const targetRange = getNonClassOutermostFoldingRanges(classRanges, ranges, target, isSupported)
OMG yes this was where i messed up! Thanks for finding this i was wondering why it wasn't working anymore 😆 

#### Before your change

Doc added on top of the wrong folding range:

<img width="776" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/9589528b-89d8-495d-99c2-9b9620151683">


#### After your change

Doc is added at the correct folding range

<img width="942" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/663733b7-7900-4590-a713-9982d7fdd4f4">

THANK YOU!

2023-09-26 10:19 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    const classRanges = isSupported ? classes : await getOuterClassFoldingRanges(ranges, uri)
doc.languageId returns 'plaintext' for code files that do not have lang server support, which I am trying to capture here. I will add a comment to reflect this, thanks!

2023-09-26 10:35 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    return prompt + '\nHere is the code: \n<Code>' + code + '</Code>'
refactor to <review> 👍

2023-09-26 13:03 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +    const textBaseLangIds = ['markdown', 'plaintext', 'json', 'sql']
Thanks @arafatkatze that has cleared up a bunch.

Let's revise the comment and mention that it isn't whether there's regions, but symbols, that we care about.

Next questions though:

Later we're looking for regions which contain the selection. Why do we need symbols for that?

For markdown folding @arafatkatze demonstrated that H1 folding is really broad. But isn't this analogous to the class level folding?

2023-09-26 13:20 UTC, dominiccooney requested changes

2023-09-26 13:20 UTC, dominiccooney commented on vscode/src/code-actions/fixup.ts
> +        return `/${intent} Fix the following error${diagnostics.length > 1 ? 's' : ''}: ${diagnostics
With the broader selection, how does Cody know where specifically the error is now?

2023-09-26 13:20 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> + * NOTE: Use getSmartSelection from utils/index.ts instead
Let's update this with more justification for why to use `getSmartSelection`. This might not be enough context to motivate people to do it.

2023-09-26 13:20 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +    // Remove text-based languages that don't support symbols or folding ranges
We've seen from @arafatkatze that these languages all support folding ranges. I expect there's some packages that add symbols for sql. Can we make this more transparent about the intent... the results for folding aren't good for these languages so we want to exclude them, something like that? It will help people maintain this list correctly.

2023-09-26 13:20 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +    // NOTE (bee) The purpose of filtering to keep only folding ranges that contain other folding ranges is to find
I don't think "folding range which contain other folding ranges" is what you want. You want the outermost folding range. You can be outermost without containing another folding range.

For example, if I have a JavaScript file with a top-level function, then that might be a range which doesn't contain any other ranges. But you would want to include that range, right?

2023-09-26 13:20 UTC, dominiccooney commented on vscode/src/editor/utils/folding-ranges.ts
> +    // By filtering to ranges that contain other ranges, it removes the inner nested ranges and keeps only the outermost parent ranges.
This also doesn't sound right. If you have A contains B contains C, do you want B or not? B is not outermost, so it sounds like "no." But B contains C, so it sounds like "yes" you do want it.

Let's get the intent clear in the comment and explain a bit about why and then we can review whether the code achieves the intent.

2023-09-26 13:29 UTC, philipp-spiess commented on vscode/src/editor/utils/folding-ranges.ts
> +    return new vscode.Selection(targetRange.start, 0, targetRange.end + 2, 0)
@abeatrix This only works if there is a trailing newline though does it? Otherwise it might pick a line that is higher than the total lines of the document. Trailing newlines are inserted automatically in vscode but I think you can disable that

2023-09-26 13:31 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    return new vscode.Selection(targetRange.start, 0, targetRange.end + 2, 0)
in the example there is no line 36, do you mean trailing newline will add an invisible line 36? If yes, I wasn't aware of that setting, but i will add a math.max just in case 👍

2023-09-26 13:35 UTC, philipp-spiess commented on vscode/src/editor/utils/folding-ranges.ts
> +    return new vscode.Selection(targetRange.start, 0, targetRange.end + 2, 0)
Yeah that's the case! In that case returning line 36 makes no sense and might break for some callers. Math.max also won't help because that would exclude the character on the last line. I think we need to get the number of chars on the last line and use that for the end

2023-09-26 13:37 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> + * NOTE: Use getSmartSelection from utils/index.ts instead
Will do! (we dont want to motivate people to do it btw 😅  will add my reasons to the comments, thanks for pointing this out!)

2023-09-26 17:22 UTC, arafatkatze commented on vscode/src/code-actions/fixup.ts
> +        return `/${intent} Fix the following error${diagnostics.length > 1 ? 's' : ''}: ${diagnostics
This could be the answer for it https://github.com/sourcegraph/cody/commit/a974e7bac94d9ab92aaeeec45bad78ebdd302629

2023-09-26 17:30 UTC, arafatkatze commented on vscode/src/code-actions/fixup.ts
> +        return `/${intent} Fix the following error${diagnostics.length > 1 ? 's' : ''}: ${diagnostics
Currently for an error here
<img width="740" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/827768a0-eb42-4471-a032-7d695be9b730">

The prompt going to LLM is 
```

The user has the following code in their selection:
  <selectedCode>    private postProcess(rawResponse: string): string {
        let completion = extractFromCodeBlock(rawResponse)

        const trimmedPrefixContainNewline = this.options.docContext.prefix
            .slice(this.options.docContext.prefix.trimEnd().length)
            .includes('\n')
        if (trimmedPrefixContainNewline) {
            // The prefix already contains a `\n` that Claude was not aware of, so we remove any
            // leading `\n` followed by whitespace that Claude might add.
            completion  completion.replace(/^\s*\n\s*/, '')
        } else {
            completion = trimLeadingWhitespaceUntilNewline(completion)
        }

        // Remove bad symbols from the start of the completion string.
        completion = fixBadCompletionStart(completion)

        return completion
    }
</selectedCode>

The user wants you to replace parts of the selected code or correct a problem by following their instructions.
Provide your generated code using the following instructions:
<instructions>
/edit Fix the following error: ```Unexpected keyword or identifier.```
</instructions>
'
```


The prompt doesn't have the granularity so as far as the LLM is concerned the error could be anywhere.  I added some prompt engineering which gives it the exact location of the error which has improved results a bit. So now the prompt is 

```
he user has the following code in their selection:
<selectedCode>    private postProcess(rawResponse: string): string {
        let completion = extractFromCodeBlock(rawResponse)

        const trimmedPrefixContainNewline = this.options.docContext.prefix
            .slice(this.options.docContext.prefix.trimEnd().length)
            .includes('\n')
        if (trimmedPrefixContainNewline) {
            // The prefix already contains a `\n` that Claude was not aware of, so we remove any
            // leading `\n` followed by whitespace that Claude might add.
            completion  completion.replace(/^\s*\n\s*/, '')
        } else {
            completion = trimLeadingWhitespaceUntilNewline(completion)
        }

        // Remove bad symbols from the start of the completion string.
        completion = fixBadCompletionStart(completion)

        return completion
    }
</selectedCode>

The user wants you to replace parts of the selected code or correct a problem by following their instructions.
Provide your generated code using the following instructions:
<instructions>
/edit Fix the following error: ```Unexpected keyword or identifier.``` in the line "            completion  completion.replace(/^\s*\n\s*/, '')"
</instructions>
'
``` 

This way the llm knows where to make the change and has the additional context so that it doesn't do something absurd or makes a change at the wrong place.

2023-09-26 17:57 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +        cur => !filtered.some(next => next !== cur && next.start <= cur.start && next.end >= cur.end)
@dominiccooney I tried this out and you are right https://github.com/sourcegraph/cody/pull/1163#issuecomment-1735513161 

Because they are different objects `next !== cur ` holds true and because of similar values `next.start <= cur.start && next.end >= cur.end` holds true.

Thanks for the clarification on language.

2023-09-26 18:57 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +function combineNeiborFoldingRanges(ranges: vscode.FoldingRange[]): vscode.FoldingRange[] {
@abeatrix Sorry for ping. Hope this doesn't get lost in the sea of comments about this PR.

2023-09-26 19:09 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    return new vscode.Selection(targetRange.start, 0, targetRange.end + 2, 0)
fixed!

2023-09-26 19:10 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    // Remove text-based languages that don't support symbols or folding ranges
updated

2023-09-26 19:29 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +function combineNeiborFoldingRanges(ranges: vscode.FoldingRange[]): vscode.FoldingRange[] {
Hey @arafatkatze thanks for the pings! I;ve updated logic for this functions too, do you think your suggestion aligns with the update?

2023-09-26 19:29 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +    const textBaseLangIds = ['markdown', 'plaintext', 'json', 'sql']
1.  > Later we're looking for regions which contain the selection. Why do we need symbols for that?

I am sure you already know this but keeping it here just for understanding. 
https://github.com/sourcegraph/cody/blob/461262872679375be45d599d9da736d22c8f2043/vscode/src/editor/utils/folding-ranges.ts#L39-L44
This comment covers it. The only thing I would add to this comment is 
>  filter the filtered folding ranges to only include the outer ranges containing target line(Ideally this is a function)

2. 

> For markdown folding @arafatkatze demonstrated that H1 folding is really broad. But isn't this analogous to the class level folding?
Yes it very much is. The different levels of headings H1->H2->H3 follow the nesting structure of a class -> function -> function etc. Sub-nesting in this is fairly straight forward. 

The one thing I would add is that I am not sure if having smart selection would benefit so much for those cases. Markdown/free form text would benefit the most from autocomplete. I doubt if accounting for smart selection would be helpful in any way.

2023-09-26 19:31 UTC, arafatkatze commented on vscode/src/code-actions/fixup.ts
> +        return `/${intent} Fix the following error${diagnostics.length > 1 ? 's' : ''}: ${diagnostics
@abeatrix ^

2023-09-26 19:41 UTC, arafatkatze commented on vscode/src/editor/utils/folding-ranges.ts
> +function combineNeiborFoldingRanges(ranges: vscode.FoldingRange[]): vscode.FoldingRange[] {
@abeatrix My question was predominantly about the utility of this function the logic is fine. I see that this function is supposed to work for things that don't have lang server so i tried it in this file 

```
package com.example

// Top-level comment
object Main {

  // Object-level comment
  
  // Nested object
  object NestedObject {
    def nestedMethod(): Unit = {
      // Implementation here
    }
  }

  // First class
  /**
   * NestedClass class nested inside FirstClass
   * anotherMethod() method in NestedClass 
   * Does something
   */
  class FirstClass {
    // Nested class
    class NestedClass {
      def anotherMethod(): Unit = {
        // Do something
      }
    }
    
    def methodOne(): Unit = {
      if (true) {
        // Inside if statement
      } else {
        // Inside else statement
      }
    }
  }

  // Second class
  class SecondClass {
    def methodTwo(): Unit = {
      // Second method
    }
  }
  
  def main(args: Array[String]): Unit = {
    // Main method body
    for (i <- 1 to 10) {
      // Inside for loop
    }
  }
}
``` 

And I saw that this function helped in combining a few ranges for the if/else condition. And then also another case where there was a docstring and a function right after it. But I don't understand the utility of having this function. IF you are gonna remove nested ranges  etc. Why have this function? 

Basically I can't figure out if this function should be a part of the algorithm? Does it do a marginal improvement? Yes, absolutely. But maybe there is a more elaborate reasoning for the existence of this function and I can't pick that up. The logic is okay though.

2023-09-29 14:00 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +function combineNeiborFoldingRanges(ranges: vscode.FoldingRange[]): vscode.FoldingRange[] {
>  I see that this function is supposed to work for things that don't have lang server so i tried it in this file

if you save the file as a plaintext file, you should be able to see how it works in action, but basically if you have a plaintext file that looks like:

```
class FirstClass {
  // Nested class
  class NestedClass {
    def method(
      params1: String = "",
      params2: String = ""
    ) {
        // Do something
    }
  }
}
```

Without this, it would returns:

```
    def method(
      params1: String = "",
      params2: String = ""
    ) {
```

when we want:

```
    def method(
      params1: String = "",
      params2: String = ""
    ) {
        // Do something
    }
```

2023-09-29 14:06 UTC, abeatrix commented on vscode/src/editor/utils/folding-ranges.ts
> +    // By filtering to ranges that contain other ranges, it removes the inner nested ranges and keeps only the outermost parent ranges.
updated!

2023-09-29 15:35 UTC, abeatrix commented
@dominiccooney i'm going to merge to unblock my other work since i know you'll be traveling! i've updated the code based on your suggestions and confirmed with Philipp that this works, (also as seen in our demo session yesterday), but I will schedule a live review session with you to walk through them, thanks!

2023-09-29 15:35 UTC, merged