Code Action: Allow enabling/disabling and improve ranking of explain
sourcegraph/cody pull request #1211
Opened 2023-09-27 17:47 UTC by umpox

## Description

## Test plan

2023-09-27 17:57 UTC, umpox commented on vscode/src/code-actions/fixup.ts
> -        action.isPreferred = true
Doesn't affect our ranking, just means users can't trigger this automatically with a keyboard shortcut (wasn't happening anyway AFAICT)

2023-09-27 17:58 UTC, umpox commented on vscode/src/code-actions/explain.ts
> +        action.diagnostics = diagnostics
Means that the code action will appear right alongside the fix action, no other impact

2023-09-27 22:19 UTC, abeatrix requested changes
Currently `Ask Cody to Explain` does nothing when inline chat is disabled. Should we show a pop-up or fall back to sidebar chat when inline chat is not enabled?


https://github.com/sourcegraph/cody/assets/68532117/5a902304-c21b-4eee-8be9-bb7065669c87

2023-09-29 05:17 UTC, toolmantim commented on vscode/src/services/StatusBar.ts
> +                    'Enable Cody to fix or explain errors and warnings, directly in your code.',
```suggestion
                    'Enable Cody fix and explain options in the Quick Fix menu',
```

or:

```suggestion
                    'Enable Cody in the Quick Fix menu for fixing and explaining code errors and warnings',
```

2023-09-29 12:29 UTC, abeatrix approved these changes
awesome! 
Not a block: is this a good place to register code action to listen for inline cofig change? https://github.com/sourcegraph/cody/blob/0176b8c7e69b98569f7c39c92791f3ffd3421eb7/vscode/src/services/InlineController.ts#L76-L89

2023-09-29 13:54 UTC, umpox commented on vscode/src/services/StatusBar.ts
> +                    'Enable Cody to fix or explain errors and warnings, directly in your code.',
Thanks! I like the first suggestion, will update

2023-09-29 13:56 UTC, umpox commented
@abeatrix Thought about it but I think it's OK to just keep the basic implementation for now. Doesn't feel like users will often enable/disable inline chat, and the extra overhead of having to register/deregister the action to ensure we don't have duplicate code actions isn't worth it IMO. We can adjust if we get feedback from users that we need this

2023-09-29 14:47 UTC, merged