Autocomplete: Simplify injected prefix handling and fix logging issue
sourcegraph/cody pull request #1255
Opened 2023-09-29 18:57 UTC by philipp-spiess

When the suggestion widget is visible and we decide to use that option to steer the autocomplete, we currently patch the prefix as part of the doc context function. Since the prefix is now longer, we have to "adjust" for this in post processing. Right now this happens as part of the VS Code specific transformation.

This, however, will mean that the prefix in post processing is wrong and any syntactic parsing (or analytical processing) is not correct (since this runs _before_ the VS Code specific transformation is applied). This PR fixes this and extends the completion with the injected prefix in the shared post processing logic.

## Test plan

<table>
<tr>
 <td><img width="645" alt="Screenshot 2023-09-29 at 14 49 47" src="https://github.com/sourcegraph/cody/assets/458591/5ac01cc0-52cb-44a7-a041-3a977c5d4890">
 <td><img width="1113" alt="Screenshot 2023-09-29 at 14 51 15" src="https://github.com/sourcegraph/cody/assets/458591/e653d681-5684-4fe2-8d1f-bcb9214d721d">
<tr>
 <td><img width="434" alt="Screenshot 2023-09-29 at 14 49 27" src="https://github.com/sourcegraph/cody/assets/458591/c550ed7a-3f8d-4afc-b3da-bfa7dd83a548">
 <td><img width="1086" alt="Screenshot 2023-09-29 at 14 49 41" src="https://github.com/sourcegraph/cody/assets/458591/4ff29fe8-d829-4d54-ab94-b6eb4dc65112">
</table>

2023-09-30 03:48 UTC, arafatkatze commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +        withInjectedPrefix = { ...completion, insertText: docContext.injectedPrefix + completion.insertText }
Such an interesting PR and I loved playing with the `completeSuggestWidgetSelection` the only question that really perplexes me is. How was this even working at all BEFORE this PR? 

I thought somehow the parsing would fail, you don't have to answer this coz I will look into but very interesting PR and feature.

2023-10-02 12:17 UTC, philipp-spiess commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +        withInjectedPrefix = { ...completion, insertText: docContext.injectedPrefix + completion.insertText }
> How was this even working at all BEFORE this PR? I thought somehow the parsing would fail

I didn't change much on the behavior. We had the same `insertText` rewriting but at a later point in the pipeline, here: https://github.com/sourcegraph/cody/pull/1255/files#diff-a2dca3f7cbfa2847ddc325842db1723618f70febf6f26d372c7f8adf3d475bafL400-L405

I noticed that my diff is hard to read as it fixes the spacing in comments issue

> On some selections available in the widget it doesn't show anything with the autocomplete. I wonder why that is the case.

VS Code only shows inline suggestions if the current document text matches the selection. so if the document says `console.l` for example but you select `console.dir` in the dropdown, VS Code won't ever show the completion unfortunately.

2023-10-02 12:44 UTC, arafatkatze commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +        withInjectedPrefix = { ...completion, insertText: docContext.injectedPrefix + completion.insertText }
Thanks for the explanation

2023-10-02 12:46 UTC, arafatkatze approved these changes

2023-10-02 16:17 UTC, abeatrix approved these changes

2023-10-02 18:34 UTC, beyang requested changes

2023-10-02 18:34 UTC, beyang commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +        withInjectedPrefix = { ...completion, content: docContext.injectedPrefix + completion.content }
`docContext.injectedPrefix` could be null, so should this be `(docContext.injectedPrefix || '') + completion.content`?

2023-10-02 18:35 UTC, beyang approved these changes

2023-10-03 11:23 UTC, merged