Adding Smart Selection to FixupRecipe
sourcegraph/cody pull request #1317
Opened 2023-10-04 23:20 UTC by arafatkatze

Original PR -> https://github.com/sourcegraph/cody/pull/1083 (Closed because @abeatrix added some really amazing folding range functions to get the resize the selection range)

Related Issues -> https://github.com/sourcegraph/cody/issues/585 and https://github.com/sourcegraph/cody/issues/223 

## Problem Summary
Currently the selection made by users is not always fully inclusive of the entire range where changes might need to be made by Cody to satisfy the request of fixup by the user. Because we're limiting the changes to only the region that was selected by the user, that creates quite a few problems:
1. Empty Selections don't work( shown by  @sqs ) 
<img width="814" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/115da45a-b142-4d40-94f5-baf91f2c8a64">

2. Variable renaming within a function would miss some parts of the function with the original variable name that wasn't selected
4. Bad selection boundaries cause issues with indentation with the changes are applied coz the diffs function doesn't work perfectly in some edge cases 
5. Refactors -> If you only selected the return value then any refactor would miss other parts of the function where changes need to be applied 
6. Imperfect selection boundaries sometimes lead to repetition of code outside the selection range and sometimes it doesn't generate outputs 
7. Hard mode Problem:  Its hard to do a mega refactor where change request is on a small selection but that edits multiple files and other places in the codebase to make it all work together in synergy. 

## Original solution
Originally i leveraged an LLM call to decide the folding range and that was a cool algorithm but it had the latency of an extra LLM call. Now that @abeatrix added some really cool folding range functions I can just leverage them to get a better range for the selection. 

## Video

### Before

https://github.com/sourcegraph/cody/assets/11155207/53d63ee7-8650-4c03-b935-dfcb64d38c01
https://github.com/sourcegraph/cody/assets/11155207/5ab30335-6c2d-4142-849d-47234d6f4100

## After

## Test plan

2023-10-05 08:28 UTC, dominiccooney requested changes
Like the direction this is going in but have some suggestions inline.

2023-10-05 08:28 UTC, dominiccooney commented on lib/shared/src/chat/recipes/fixup.ts
> +                finalFixupTask = (await fixupController.getTaskRecipeData(taskId)) || originalFixupTask
When would `fixupController.getTaskRecipeData(taskId)` return nothing, but `originalFixupTask` still be worth pursuing? The task IDs are the same.

2023-10-05 08:28 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +        if (!selection?.start.line) {
0 is falsy, so this means you can't start the selection on line 0. Which will exclude people who did "select all", etc. So don't do this. Just check `if (selection)`

2023-10-05 08:28 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        const document = await vscode.workspace.openTextDocument(task.fixupFile.uri)
The Fixup object hangs onto the original text for applying diffs, but that text should really be a property of each submission to the LLM, and not the Fixup object itself. See the TODO in `getTaskRecipeData`.

The idea is you can create fixup tasks and then they track the ranges they apply to and can re-fetch that original text to respin the LLM if there's conflicting edits, etc.

Because `getTaskRecipeData` sets the original text (and gets the preceding and successive text) you don't need to update `original`. Just update the selection and call `getTaskRecipeData`. If that return undefined then the task is cancelled, etc. and you shouldn't continue with the task (new OR old... it's the same task.)

2023-10-05 17:13 UTC, arafatkatze commented
@dominiccooney Thanks a lot for the helpful comments. I fixed all the suggestions.

2023-10-10 05:46 UTC, dominiccooney requested changes
This needs more work. Sorry for the slow reply.

2023-10-10 05:46 UTC, dominiccooney commented on lib/shared/src/chat/recipes/fixup.ts
> +                finalFixupTask = (await fixupController.getTaskRecipeData(taskId)) || finalFixupTask
You don't want `|| finalFixupTask` here. It's the same task. If you're holding onto a reference to it, but the fixup controller has abandoned it, then there's no point continuing with it.

2023-10-10 05:46 UTC, dominiccooney commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
This can just be one variable, `fixupTask`. It's the same task, you're just changing the selection range and text associated with it.

2023-10-10 05:46 UTC, dominiccooney commented on lib/shared/src/editor/index.ts
> +    public getActiveFixupTextEditorSmartSelection(): Promise<vscode.Range | null> {
It is not JavaScripty to use null as much as this interface does. just make it `vscode.Range | undefined`.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +     *          Returns null if no active editor is found or if the starting line of the selection is not defined.
When would the start line of the selection not be defined?

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +     * 5. Returns this combined range as the final "smart" selection.
These comments make it sound more complicated than it is.

```suggestion
     * 2. If the selection starts in a folding range, moves the selection start back to the start of that folding range.
     * 3. If the selection ends in a folding range, moves the selection end forward to the end of that folding range.
```

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +        const foldingRangeStart =
This isn't a good variable name, because sometimes it's *not* a folding range. Sometimes it is the original selection.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +        const activeCursorStartPosition = selection.start.line
Improve this variable name; it is a line, not a position.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +        const activeCursorEndPosition = selection.end.line
Same feedback about names above applies to these two.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +        const combinedFoldingRange = new vscode.Selection(foldingRangeStart.start.line, 0, foldingRangeEnd.end.line, 0)
This doesn't look right because you set the end character to 0. So you might make the selection smaller if there's no folding range or if the folding range ends on the same line the selection ends on.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +    }
Use `return ... ? ... : ...` for succinctness. Also because you used early return null all along it looks odd to vary from that now.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +     * OverWrites the selectionRange of the FixupTask and selects new text corresponding to that range
OverWrites &rarr; Overwrites

In what sense does it "select" new text? Not really. You want to leave the selected text as-is anyway so if there's a task in flight it can detect that the selected text changed so it should respin and not try to merge the result.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/non-stop/FixupTask.ts
> +    public overwriteSelectionRange(newRange: vscode.Range): void {
Gut feel, do this through the fixup controller so if we need to update requests in flight the controller can do it. Who uses this anyway? It looks duplicative of `resetSelectionRange` on the fixup controller. And it has a name which varies from the name on the controller, seems like it is making a distinction, but is it? It seems to be doing exactly the same thing.

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +     * @returns A Promise that resolves to an `ActiveTextEditorSelection` which represents the combined "smart" selection.
It is declared to return vscode.Range, not ActiveTextEditorSelection.

2023-10-10 05:46 UTC, dominiccooney commented on agent/src/editor.ts
> +    public getActiveFixupTextEditorSmartSelection(): Promise<ActiveTextEditorSelection | null> {
This design seems weak. What's the difference between this and `getActiveTextEditorSmartSelection`? If it is for a fixup, why does it operate on the text editor's active selection and not a fixup task's selection?

2023-10-10 05:46 UTC, dominiccooney commented on vscode/src/editor/vscode-editor.ts
> +        const selection = activeEditor.selection
This does not seem right. Fixups have selections. If you're doing something to fixups' selections, you should be doing it to the fixup task, not based on the active text editor.

We want to make a system for doing edits to documents. It's OK to look at the active editor and selection when creating the fixup task, but after that point it is an independent object that is updated to track changes in the editor it was based off of. Dipping into the active editor this way goes against that.

So I would either expand the selection when you're creating the fixup task in the first place, and to be so focused on editing the fixup. I think this is best.

Or if you really want to edit fixups, then edit a fixup... don't dip back into the active editor but use the editor associated with the fixup and ignore that editor's active selection.

2023-10-11 01:25 UTC, arafatkatze commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
So some thoughts for this comment + [this comment](https://github.com/sourcegraph/cody/pull/1317#discussion_r1351508071) 

I had a few different considerations here but most of the absurdity came from `const` and `let` keyword.

If I were to use `const` then the subsequent calls to ` await fixupController.getTaskRecipeData(taskId)` would NOT change the value of `originalFixupTask.selectionRange` verified this in console so I decided to use the original and the final fixup task but you bought up a very important point that it's essentially the same fixup which is true.

So now I have to use the `let` key word but the keyword but the keyword can only be used if I do a reset of the `fixupTask` variable which is what I did in the. current solution has to do this 
 https://github.com/sourcegraph/cody/blob/fc363aeb1fb7006f37875eb73ce41873c9e9b81e/lib/shared/src/chat/recipes/fixup.ts#L78-L82

But that's to pass the nullity check of the original function, It's absurd but I couldn't think of a cleaner way.

2023-10-11 01:26 UTC, arafatkatze commented on lib/shared/src/editor/index.ts
> +    public getActiveFixupTextEditorSmartSelection(): Promise<vscode.Range | null> {
Totally agree(given the rest of the codebase) but I wanted to maintain consensus with the current file itself so for now i would prefer to keep this and will change it in a separate PR AFTER this is merged

2023-10-11 01:27 UTC, arafatkatze commented on vscode/src/editor/vscode-editor.ts
> +     *          Returns null if no active editor is found or if the starting line of the selection is not defined.
Great catch(It's a bad idea to rely on LLms too much), I updated the commentary

2023-10-11 01:27 UTC, arafatkatze commented on vscode/src/editor/vscode-editor.ts
> +     * 5. Returns this combined range as the final "smart" selection.
Good catch, I changed this.

2023-10-11 02:16 UTC, arafatkatze commented on vscode/src/editor/vscode-editor.ts
> +        const foldingRangeStart =
Changed it to `newSelectionStartingPosition` but happy to do something else if you prefer.
Also added a comment too.

2023-10-11 02:20 UTC, arafatkatze commented on vscode/src/editor/vscode-editor.ts
> +        const combinedFoldingRange = new vscode.Selection(foldingRangeStart.start.line, 0, foldingRangeEnd.end.line, 0)
Great catch. I made the change to include characters too.

2023-10-11 02:23 UTC, arafatkatze commented on vscode/src/non-stop/FixupController.ts
> +     * OverWrites the selectionRange of the FixupTask and selects new text corresponding to that range
Great point. I made the change.

2023-10-11 02:24 UTC, arafatkatze commented on vscode/src/non-stop/FixupTask.ts
> +    public overwriteSelectionRange(newRange: vscode.Range): void {
This is redundant so i removed it.

2023-10-11 02:35 UTC, arafatkatze commented on vscode/src/editor/vscode-editor.ts
> +        const selection = activeEditor.selection
> This does not seem right. Fixups have selections. If you're doing something to fixups' selections, you should be doing it to the fixup task, not based on the active text editor. We want to make a system for doing edits to documents. It's OK to look at the active editor and selection when creating the fixup task, but after that point it is an independent object that is updated to track changes in the editor it was based off of. Dipping into the active editor this way goes against that. So I would either expand the selection when you're creating the fixup task in the first place, and to be so focused on editing the fixup. I think this is best.

I totally agree I contemplated this idea and wanted to do expansion right at the start of the fixup recipe. Here

https://github.com/sourcegraph/cody/blob/aecdd88b1258d84db5183efdc1053cb9fff34b2b/vscode/src/main.ts#L284-L295

The only problem was that doing the expansion here would render the `add` intent basically untouchable coz we can't have the "no selection" case. 
 https://github.com/sourcegraph/cody/blob/aecdd88b1258d84db5183efdc1053cb9fff34b2b/lib/shared/src/chat/recipes/fixup.ts#L87-L90

That's why I had do it at the place that I did. I also totally understand why you are hesitant about using active editor 
so 
```    public async getFixupRecipeSmartSelection(
        selectionRange: ActiveTextEditorSelectionRange,
        fileName: string
    ): Promise<vscode.Range | null> {
        if (!selectionRange) {
            return null
        }
        const documentUri = vscode.Uri.file(fileName)

        // Retreive the start position of the current selection
        const activeCursorStartPosition = selectionRange.start
        // If we find a new expanded selection positon then we set it as the new start position
        // and if we don't then we fallback to the original selection made by the user
        const newSelectionStartingPosition =
            (await getSmartSelection(documentUri, activeCursorStartPosition.line))?.start || selectionRange.start

        // Retreive the ending line of the current selection
        const activeCursorEndPosition = selectionRange.end
        // If we find a new expanded selection positon then we set it as the new ending position
        // and if we don't then we fallback to the original selection made by the user
        const newSelectionEndingPosition =
            (await getSmartSelection(documentUri, activeCursorEndPosition.line))?.end || selectionRange.end

        // Create a new range that starts from the beginning of the folding range at the start position
        // and ends at the end of the folding range at the end position.
        return new vscode.Range(
            newSelectionStartingPosition.line,
            newSelectionStartingPosition.character,
            newSelectionEndingPosition.line,
            newSelectionEndingPosition.character
        )
    }
```

SO now it doesn't use the active editor at all. I only put this function here coz I just wanted to use `getSmartSelection` and I couldn't think of a better way than this but it doesn't even tough any objects of the activeEditor. I think this is better than before but I am open to new ideas to improve things.

2023-10-11 02:47 UTC, arafatkatze commented
@dominiccooney Big thanks for the thorough review! Took your feedback on board and made the necessary tweaks. I realize the initial version wasn’t up to par—sorry about that. After another look and your pointers, I think it's in better shape now. Let me know if anything else jumps out.

2023-10-11 02:51 UTC, dominiccooney requested changes
OK, thanks for clarifying! I have some suggestions inline.

2023-10-11 02:51 UTC, dominiccooney commented on lib/shared/src/chat/recipes/fixup.ts
> +                finalFixupTask = (await fixupController.getTaskRecipeData(taskId)) || finalFixupTask
If the task is removed from `FixupController.tasks` and `getTaskRecipeData` returns undefined, then it doesn't matter what happens after this—the FixupController is not going to process the result. You are done. You should stop processing the task. Returning undefined or whatever it takes to signal the caller to also stop is fine.

2023-10-11 02:51 UTC, dominiccooney commented on lib/shared/src/chat/recipes/fixup.ts
> +        if (truncateText(originalFixupTask.selectedText, quarterFileContext * 2) !== originalFixupTask.selectedText) {
Just curious but why did we change this? Is this a fudge factor so that when it broadens, it probably fits the budget?

2023-10-11 02:51 UTC, dominiccooney commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
OK, I understand what you're grappling with here!

I missed that `getTaskRecipeData` isn't returning the FixupTask, but a bag of properties based on it. You need to get the updated bag of properties after you modify the selection of the underlying FixupTask and the types including undefined is a pain.

The design of FixupController/FixupTask is weak at this point. I think we are missing a third kind of object, which is that snapshot of the state when you make a submission to the LLM. Original text should definitely live on that object, for example. But let's NOT try to clean that up now.

We are also missing an opportunity to start intent detection earlier and be more consistent. It's not 100% clear to me if every fixup task routes through this recipe, but maybe intent detection and task modification could/should be part of the fixup controller and the task's life cycle. (Today we have idle, working, ready, applying, fixed, error in CodyTaskState; maybe we can have a setup step where they get intent detection and adjustment.)

It's also clear that some paths want to skip intent detection, and the way that happens is a bit clumsy: IF the secret word `/edit` appears then skip intent detection. Probably because intent detection will be so slow, and it only detects "edit" or "document", which does not sound super high value (but could be if we generalize fixups so they can put their output in other places.) Instead `createTask` could have a hint about what intent detection the caller wants.

This are big clean-ups and I would like @abeatrix 's input/buy in on them too.

Here's what I suggest you do, short term:

- Make `getActiveFixupTextEditorSmartSelection` *not* use the active editor. Using the active editor couples creating the task, and doing this manipulation, in time. That coupling will be fragile (if some intervening Promise, like the intent detector, slows down now it is more likely that the active editor has changed and you're reading the wrong document.) Instead, use the FixupTask and its document to get the updated range and text. Be bold digging into the FixupController and friends and making an API that's nice for this.
- Consider making the intent detector work with the FixupTask and not the bag of data, although if it needs to retrieve the bag of data within the detector that's fine.
- In the code you're modifying here, retrieve the fixup task from the controller.
- If the intent is to edit, update the fixup's task range. That should happen through the controller and not by modifying the task directly because later if we had fixup requests in flight at this point, we might want to stop them, and that would involve the controller. Also we might need to coordinate with the document edit watcher.
- Then, finally, get the bag of task data.

How does that sound?

2023-10-11 03:03 UTC, abeatrix commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
> Make getActiveFixupTextEditorSmartSelection not use the active editor 

That sounds good to me. @arafatkatze created `getActiveFixupTextEditorSmartSelection` for Fixup, so I don't think it would break other things that are using the old `getActiveTextEditorSmartSelection` and what you suggested makes sense.

@umpox is the one who added intent detector for Fixup, so he might have more insights to share.

2023-10-11 03:17 UTC, dominiccooney commented
> I realize the initial version wasn’t up to par—sorry about that.

Don't be! I like the direction of this change and I'm always happy to discuss. I'm just trying to process how we can use this to make the fixups system easier to use. Sorry for all the loaded footguns we left lying around.

2023-10-11 04:15 UTC, arafatkatze commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
@domiccooney sounds great!! Lemme do this tomorrow.

2023-10-11 04:15 UTC, arafatkatze commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
@domiccooney sounds great!! Lemme do this tomorrow.

2023-10-11 21:13 UTC, arafatkatze commented on lib/shared/src/chat/recipes/fixup.ts
> +        let finalFixupTask = originalFixupTask
@dominiccooney Here's the response to your comments. 
> Make getActiveFixupTextEditorSmartSelection not use the active editor. Using the active editor couples creating the task, and doing this manipulation, in time. That coupling will be fragile (if some intervening Promise, like the intent detector, slows down now it is more likely that the active editor has changed and you're reading the wrong document.) Instead, use the FixupTask and its document to get the updated range and text. Be bold digging into the FixupController and friends and making an API that's nice for this.

I've eliminated the editor's role entirely and transitioned the entire logic to a private function within fixupController. It's now designed to execute only when enableSmartSelection is truthy, which primarily occurs when the intent is _edit_.

>Consider making the intent detector work with the FixupTask and not the bag of data, although if it needs to retrieve the bag of data within the detector that's fine.

I've integrated it into fixupController to leverage FixupTask directly, bypassing the initial reliance on the bag of data. This seemed more fitting, given the data bag's downstream utility and its limited relevance for intent detection. I trust this aligns with your vision.


>In the code you're modifying here, retrieve the fixup task from the controller.
If the intent is to edit, update the fixup's task range. That should happen through the controller and not by modifying the task directly because later if we had fixup requests in flight at this point, we might want to stop them, and that would involve the controller. Also we might need to coordinate with the document edit watcher.

I've centralized the task range modification within fixupController, ensuring better coordination, especially in potential scenarios where we might need synchronization with the document edit watcher.


>Then, finally, get the bag of task data.  

This has been streamlined to ensure we fetch the data bag only once.

I hope these modifications resonate with your initial suggestions. While I acknowledge further refactoring potential, I'm hoping these changes fit the current PR's scope. If you see areas for further refinement, please guide me accordingly. I'm more than happy to iterate further.

2023-10-13 08:26 UTC, dominiccooney approved these changes
Looks good! Some feedback inline. Definitely need `&&` and not `||` in the condition noted below.

2023-10-13 08:26 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        // Retreive the start position of the current selection
```suggestion
        // Retrieve the start position of the current selection
```

2023-10-13 08:26 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        // If we find a new expanded selection positon then we set it as the new start position
```suggestion
        // If we find a new expanded selection position then we set it as the new start position
```

2023-10-13 08:26 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        // Retreive the ending line of the current selection
```suggestion
        // Retrieve the ending line of the current selection
```

2023-10-13 08:26 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        // If we find a new expanded selection positon then we set it as the new ending position
```suggestion
        // If we find a new expanded selection position then we set it as the new ending position
```

2023-10-13 08:26 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        enableSmartSelection: boolean
I'm not a fan of boolean parameters because they are mysterious to the reader at callsites (just `true`, etc.) and as soon as you have more than one it is easy to mix them up without the type checker complaining.

What about making this a bag of options with `{enableSmartSelection: boolean}`? Or add an enum with "selection kind" or something?

2023-10-13 08:26 UTC, dominiccooney commented on vscode/src/non-stop/FixupController.ts
> +        if (enableSmartSelection || task.selectionRange) {
```suggestion
        if (enableSmartSelection && task.selectionRange) {
```

2023-10-13 15:06 UTC, arafatkatze commented on vscode/src/non-stop/FixupController.ts
> +        if (enableSmartSelection || task.selectionRange) {
Good catch

2023-10-13 15:29 UTC, arafatkatze commented
@dominiccooney Thanks a lot for the feedback. I made all the changes and tested things one last time. You can merge this after you take a look.

2023-10-16 02:39 UTC, dominiccooney commented
test:e2e passed locally for me on macOS. Will follow up with dev experience about why those integration tests are failing because secrets.

2023-10-16 03:36 UTC, arafatkatze commented
> Will follow up with dev experience about why those integration tests are failing because secrets.

@dominiccooney That's expected behaviour: By default, GitHub does not pass secrets to workflows that are triggered from forked repositories. This is a measure to prevent malicious users from creating PRs in open-source projects and using workflows to extract secret values.
My e2e tests have always failed coz of secrets.

[1 week ago ](https://github.com/sourcegraph/cody/actions/runs/6449294349/job/17523335681)
[3 weeks ago](https://github.com/sourcegraph/cody/actions/runs/6257115780/job/17124496404)

2023-10-16 03:59 UTC, dominiccooney commented
@arafatkatze Yep, I guessed as much, but I didn't know the workflow for actually merging this because branch protection prevents me from doing that. Seems I create a copy of your PR #1398 to run the tests and then this one picks up the results.

2023-10-16 04:55 UTC, arafatkatze commented
@dominiccooney that works too thank you!!

2023-10-16 06:27 UTC, merged