Expose convertGitCloneURLToCodebaseName endpoint
sourcegraph/cody pull request #1425
Opened 2023-10-18 10:14 UTC by mkondratek

2023-10-18 10:55 UTC, olafurpg commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    public convertGitCloneURLToCodebaseName(cloneURL: string) : string | null {
This function seems unnecessary. We should be able to call `convertGitCloneURLToCodebaseName` directly from agent.ts

2023-10-18 11:26 UTC, olafurpg commented on agent/src/agent.ts
> +        this.registerRequest('convertGitCloneURLToCodebaseName', ({ cloneURL }) => {
Conventionally, we use a prefix in the request name. I propose we use something like
```suggestion
        this.registerRequest('git/codebaseName', ({ cloneURL }) => {
```

2023-10-19 00:29 UTC, dominiccooney commented
Thanks for doing this. There's other problems with the renaming heuristic, like it requires remotes in the first place; it needs names with slashes (IIRC); etc. But getting everyone using the same thing is a good start.

2023-10-19 18:52 UTC, mkondratek commented on lib/shared/src/utils.test.ts
> +        expect(convertGitCloneURLToCodebaseName('ssh://git@gitlab-my-company.net:20022/path/repo.git')).toEqual(
this is the original url that caused the issue in the first place

2023-10-20 08:29 UTC, dominiccooney requested changes

2023-10-20 08:29 UTC, dominiccooney commented on agent/src/agent.ts
> +            return Promise.resolve(typeof result === 'string' ? result : null)
Just return the result; you don't need a resolved Promise here.

2023-10-20 08:37 UTC, olafurpg commented on agent/src/agent.ts
> +            return Promise.resolve(typeof result === 'string' ? result : null)
I think you do, `registerResult` expects a `Promise`-like object. We use `.then` on the result.

2023-10-20 08:38 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'git/codebaseName': [[cloneURL: string], string | null]
Is there a reason this is an array instead of object?
```suggestion
    'git/codebaseName': [{cloneURL: string}, string | null]
```

2023-10-20 09:23 UTC, mkondratek commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'git/codebaseName': [[cloneURL: string], string | null]
I was initially attempting to use `{ cloneURL: string }` as the argument type here. However, the issue was that despite the specified argument type (`string`), the method `convertGitCloneURLToCodebaseName(cloneURL: string)` was receiving an object instead. It caused `TypeError: undefined is not a function` at `cloneURL.replace(...)` call.

2023-10-20 09:28 UTC, mkondratek commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'git/codebaseName': [[cloneURL: string], string | null]
I guess I can use an object, and change the argument type in jetbrains to smth like:
```java
public class CloneUrl {
  public final String url;

  public CloneUrl(String url) {
    this.url = url;
  }
}
```

2023-10-20 19:20 UTC, mkondratek commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'git/codebaseName': [[cloneURL: string], string | null]
I did it like this for consistency.

2023-10-23 02:25 UTC, dominiccooney commented on agent/src/agent.ts
> +            return Promise.resolve(typeof result === 'string' ? result : null)
Missed that the function was not async. Sorry for the spam.

2023-10-23 09:23 UTC, merged