Add secondary telemetry to AuthProvider
sourcegraph/cody pull request #1517
Opened 2023-10-26 22:06 UTC by nathan-downs

## Test plan

run extension in debug mode
check test eventlogs on dotcom for event emission
check bigquery for event reception

2023-10-27 05:05 UTC, dominiccooney commented
Same feedback I wrote on https://github.com/sourcegraph/cody/pull/1519 applies here:

- Bit of background about the motivation for the change.
- Detail in the test plan so someone who's not familiar can reproduce it relatively easily.
- Ideally, an automated test.

2023-10-27 05:10 UTC, dominiccooney requested changes
Let's introduce these changes as simply as possible.

2023-10-27 05:10 UTC, dominiccooney commented on vscode/src/services/AuthProvider.ts
> +            telemetryRecorder.recordEvent(`cody.auth.selectSigninMenu${type ?? ''}`, 'clicked', {
You can simplify this, because you know type is falsy here.

2023-10-27 05:10 UTC, dominiccooney commented on vscode/src/services/AuthProvider.ts
> +        if (type) {
This duplicates a lot of code just for the purpose of inserting a `.`. Float the condition down so it is obvious what's different about these two branches.

2023-10-27 05:10 UTC, dominiccooney commented on vscode/src/services/AuthProvider.ts
> +        }
Eliminate the redundancy here and highlight what's going on by putting the condition close to the effect it has:

```suggestion
        telemetryRecorder.recordEvent('cody.auth.fromToken', authState?.isLoggedIn ? 'succeeded' : 'failed')
```

2023-10-27 05:47 UTC, nathan-downs commented on vscode/src/services/AuthProvider.ts
> +        }
Implemented, thanks!

2023-10-27 05:50 UTC, nathan-downs commented on vscode/src/services/AuthProvider.ts
> +        if (type) {
Reworked the `feature` building logic so that it still complies with the enumerated EventFeature type

```
let eventName: EventFeature
eventName = 'cody.auth.selectSigninMenu'
if (type) {
    eventName = `${eventName}.${type}`
}
```

2023-10-30 07:00 UTC, dominiccooney approved these changes
Looks good.

I was thinking, instead of `{ hasV2Event: true }` you could do this logging in a closure and associate the V2 event that way. But it is up to you... if you trust people won't start copy-pasting `{ hasV2Event: true }` everywhere, this is fine. I am guessing all these old events go away very soon?

2023-11-03 17:45 UTC, bobheadxi commented
Thanks @dominiccooney! I like your idea, but because we used a shared interface over at https://github.com/sourcegraph/telemetry (in hopes of unifying how we interact with events in our various clients, instead of having bespoke contracts in each place), it does make this a bit trickier to add.

I think the `hasV2Event` copy-pasta risk is acceptable, as for _new_ events going forward, we should not be adding legacy events, and as you mention we will hopefully get to a point where it can be removed soon. I also think having the callsites next to each other and a `hasV2Event` is sufficient for us to find all the usages later and get rid of them, and we can toggle a no-op switch within the legacy logger directly as well.

WDYT @nathan-downs ?

2023-12-02 08:23 UTC, nathan-downs commented
replaced by https://github.com/sourcegraph/cody/pull/2060

2023-12-02 08:23 UTC, closed without merging