refactor: simplify auth state management
sourcegraph/cody pull request #1518
Opened 2023-10-26 22:29 UTC by abeatrix

refactor: simplify auth state management on start-up

Came across this when I was working on the new chat UI -- it looks like we have both `cody.auth.sync` and `authProvider.addChangeListener` to handle auth change events. This PR proposes addressing auth state changes in one central auth listener to remove the need to have multiple places to auth update events.

- Move auth state update logic into dedicated auth change listener
- Consolidate status bar indicator, completions setup, and other auth-dependent services into auth change handler
- Remove redundant auth sync logic
- Pass auth status object on auth change to status bar indicator instead of re-checking
- Fetch access token before setting in symfRunner to avoid null errors

## Test plan

All the current tests should pass and everything should work as before.

Try login and then logout, and then log back in, everything should work as before.

2023-10-26 22:55 UTC, abeatrix commented on vscode/src/main.ts
> -            // Important that we return a promise here to allow `AuthProvider`
When `'cody.auth.sync'` is called, the AuthStatus has already been updated and stored by AuthProvider, so I don't think it would affect auth config changes, @chwarwick can you confirm if this comment is still true?

2023-10-27 04:48 UTC, dominiccooney requested changes
Thanks for working on this, this area will certainly benefit from simplification. Some feedback inline.

2023-10-27 04:48 UTC, dominiccooney commented on vscode/src/main.ts
> +    updateAuthStatusBarIndicator(authProvider.getAuthStatus())
Would it be possible to set up the callback, and then call it once? Because you have two duplicated lines here... and maybe contextProvider and featureFlag provider also need the initial auth status?

2023-10-27 04:48 UTC, dominiccooney commented on vscode/src/services/AuthProvider.ts
> +    private syncAuthStatus(authStatus: AuthStatus): void {
Let's rename this `setAuthStatus`, `set authStatus()` or `updateAuthStatus`, something like that. It doesn't do any syncing now.

2023-10-27 04:48 UTC, dominiccooney commented on vscode/src/chat/ContextProvider.ts
> +    public async syncAuthStatus(authStatus?: AuthStatus): Promise<void> {
Today we have a bunch of methods called "syncAuthStatus" all doing different things. Let's call this `onAuthStatusChange`. It consumes updates from the auth provider, I think that name makes it clear it consumes changes, it doesn't produce them.

2023-10-27 04:48 UTC, dominiccooney commented on vscode/src/chat/ContextProvider.ts
> +        if (!authStatus) {
Why do we have *this*? Seems dodgy, if we're being passed the authstatus, to turn around and grab it again.

2023-10-27 04:48 UTC, dominiccooney commented on vscode/src/chat/ContextProvider.ts
> +        const isLoggedOut = !authStatus.isLoggedIn && !authStatus.endpoint && !authStatus.showInvalidAccessTokenError
Clean up this to be `!(a || b || c)`; this is hard to read.

Where did `showInvalidAccessTokenError` come from? It seems weird to have `isLoggedOut` be anything more than `!authStatus.isLoggedIn`. Does `isLoggedOut` need a more accurate name?

2023-10-27 13:27 UTC, chwarwick commented on vscode/src/main.ts
> -            // Important that we return a promise here to allow `AuthProvider`
This was related to an issue that occurred when initializing the agent prior to having a credentials setup and then later authenticating.  There were unit tests added to the agent for this case so if they continue to pass it shouldn't be a problem.

2023-10-27 19:18 UTC, abeatrix commented on vscode/src/main.ts
> -            // Important that we return a promise here to allow `AuthProvider`
Awesome, thanks for the context 🙇‍♀️

2023-10-27 20:11 UTC, abeatrix commented on vscode/src/chat/ContextProvider.ts
> +    public async syncAuthStatus(authStatus?: AuthStatus): Promise<void> {
Yea that makes sense. Updated syncAuthStatus to onAuthStatusChange for ContextProvider and FeatureFlagProvider

2023-12-28 17:18 UTC, closed without merging