JetBrains: Agent: Adjusting agent to handle lookup elements from intellij
sourcegraph/cody pull request #1611
Opened 2023-11-02 10:32 UTC by Sa1to

This is needed to fix [JetBrains: integrate autocomplete with lookup manager#57335](https://github.com/sourcegraph/sourcegraph/issues/57335).

It appends element from IntelliJ's lookup manager to the file in place of autocompletions, in order to generate completion including part from lookup manager.

## Test plan
Test requires changes on Jetbrains part so it is not possible at the moment. Those changes should not affect regular autocompletion behaviour.

2023-11-02 12:14 UTC, mkondratek commented on agent/src/agent.ts
> +                const firstPart = document.content.slice(0, params.offset)
Can you pls explain to me what is 
- offset
- firstPart
- lastPart
❓

2023-11-02 12:15 UTC, mkondratek approved these changes
LGTM.
I guess it would be nice to test it with the changes to `jetbrains` BEFORE merging this.
btw, please fix the PR title

2023-11-02 12:23 UTC, olafurpg requested changes

2023-11-02 12:23 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    lookupElement?: string
Can we add comments explaining how these fields are used?

2023-11-02 12:23 UTC, olafurpg commented on agent/src/agent.ts
> +                document.content = firstPart + lookup + lastPart
This solution feels like a hack. We want `document.content` to reflect the actual content in the editor buffer. For example, what happens when we send multiple subsequent requests with a different `lookupElement`. Ideally, we should use the same API as VS Code for the suggestion widget. Have you looked at `InlineCompletionContext.selectedCompletionInfo`?

2023-11-06 11:13 UTC, Sa1to commented
Updated PR. Here is example how it works with my local changes in JetBrains plugin part:

https://github.com/sourcegraph/cody/assets/9321940/2429f648-0947-4d41-8e13-7cef2928985d

2023-11-06 11:23 UTC, olafurpg requested changes
One blocking comment, otherwise, this looks good

2023-11-06 11:54 UTC, mkondratek approved these changes
the demo looks great 🚀 pls apply Olaf's suggestions, lgtm

2023-11-08 10:41 UTC, exigow approved these changes
This is one of the features that is compatible with native look & feel in IntelliJ. IMO most of the users will prefer using this default lookup manager than custom one invoked by different keybindings. Can't wait!

About code: it looks fine :+1:, though I'm not yet comfortable with the TS agent's code so I might be missing something.

2023-11-08 12:21 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +import { SelectedCompletionInfo } from 'vscode'
Let's inline the definition of this interface and remove the import from `vscode` here because 1) the types are incompatible and 2) agent-protocol should be as standalone as possible meaning we should limit external imports. Re 1) the type for `.range` is a class in `vscode` while in the protocol it should be an interface.

2023-11-08 12:21 UTC, olafurpg approved these changes
Approving to unblock merge but please address the last comment before merging 🙇🏻

2023-11-09 11:49 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +export interface SelectedCompletionInfo {
Thank you! LGTM

2023-11-09 11:59 UTC, merged