Issue1684
sourcegraph/cody pull request #1716
Opened 2023-11-12 18:09 UTC by fyasla

# Cody Agent: shim vscode.workspace.fs issue #1684

Here is the beginning of my first attempt of implementing the `FileSystem` interface for the shim VSCode API.
I have two main questions:

### 1. How to implement the `useTrash` option in the `delete` method ?
Here is [one implementation](https://sourcegraph.com/github.com/microsoft/vscode@901d3e5c5f08e424562a42f43397a733bf6a21c1/-/blob/src/vs/workbench/api/common/extHostFileSystemConsumer.ts?L121:10-121:16) in the VSCode source code.

- If i understand correctly, we should also implement our own FileSystemProvider (at least Partially?) if we want to act like VSCode API
- Or we coulde use [a node module](https://github.com/sindresorhus/trash) for handling _moving to trash_ actions (or write the platform dependent logic for trash folder ourselves?)

### 2.How to implement the `isWritableFileSystem` method:

- We need either to access the [FileSystemProviderCapabilities](https://sourcegraph.com/github.com/microsoft/vscode/-/blob/src/vs/platform/files/common/files.ts?L597:2#tab=references) which in [this implementation again](https://sourcegraph.com/github.com/microsoft/vscode/-/blob/src/vs/workbench/api/common/extHostFileSystemConsumer.ts?L151:4&popover=pinned) is accessed through the `fileSystemInfo` injected dependency

- Or we could just switch case between [these values](https://sourcegraph.com/github.com/microsoft/vscode/-/blob/src/vs/base/common/network.ts?L10:18&popover=pinned) ?

## Test plan

Unit tests added in [vscode-shim.test.ts](https://github.com/sourcegraph/cody/blob/main/agent/src/vscode-shim.test.ts)

2023-11-12 18:13 UTC, fyasla commented on agent/src/vscode-shim.ts
> +        isWritableFileSystem: scheme => {
Point 2 in my pull request

2023-11-12 18:13 UTC, fyasla commented on agent/src/vscode-shim.ts
> +                // move file to trash folder
Point 1 in my pull request

2023-11-14 21:46 UTC, jdorfman commented
Thanks @fyasla! Someone will take a look asap.

2023-11-15 08:06 UTC, olafurpg requested changes
Thank you for this contribution @fyasla ! 🙏🏻 

This is a great improvement, and I appreciate your attention to detail in getting the implementation correct. My long-term goal with the shim is to make it 100% correct because it will save time debugging why the behavior is different with/without the shim. However, in the short/medium-term I think it's not worth the effort to get the tiniest details right esp. for APIs that we don't use in the Cody extension.

A few minor but blocking comments, otherwise LGTM 👍🏻 

Out of curiosity, what is your motivation for this change? 😊

2023-11-15 08:06 UTC, olafurpg commented on agent/src/vscode-shim.ts
> +                case 'http':
These can be removed since they fallback to `default` anyways

2023-11-15 08:06 UTC, olafurpg commented on agent/src/vscode-shim.ts
> +                case 'git':
I think it's fine to be conservative and only support writing to `file`. We call this API in the Cody so it's not a huge deal if the implementation is not perfect yet.

2023-11-15 17:31 UTC, fyasla commented
Thank you for the detailed review, feedback, and clarifications regarding this shim, @olafurpg ! 
I will address your comments and commit the changes as soon as possible.

I wasn't motivated by this change in particular, but rather by the Cody project itself. I like it and want to contribute to it, so I started with this "good first issue" (by the way, thanks to the Sourcegraph team for making such issues available! :+1: ). 

Hoping to contribute more! :rocket:

2023-11-16 22:23 UTC, fyasla commented on agent/src/vscode-shim.ts
> +                throw new Error(
No, I will get back to throwing original error

2023-11-21 11:33 UTC, olafurpg approved these changes
LGTM 👍🏻 Thank you @fyasla for this great contribution! 🙏🏻

2023-11-21 11:36 UTC, olafurpg commented
@fyasla I took the liberty to update the PR title and description. I will merge the PR once the merge conflicts have been resolved :)

2023-11-21 12:46 UTC, fyasla commented
@olafurpg  Thank you for your feedback!

2023-12-13 11:13 UTC, olafurpg commented
@fyasla I am sorry for the slow turnaround. I thought this PR was already merged and I only noticed that it wasn't merged because I had a failing test case caused by an error that is fixed by this PR. I pushed a formatting fix to your branch and it should be good to merge now 👍🏻

2023-12-13 11:17 UTC, merged