Edit: Add further code actions for editing and documenting code
sourcegraph/cody pull request #1724
Opened 2023-11-13 16:57 UTC by umpox

## Test plan

2023-11-17 04:52 UTC, valerybugakov reviewed
Got language blocks leaking into the document when using the "generate" action:

<img width="324" alt="Screenshot 2023-11-17 at 12 51 24" src="https://github.com/sourcegraph/cody/assets/3846380/1b99066f-6086-4f75-b4e2-252eac1e4b16">

Filepath: `vscode/src/logged-rerank.ts`
Prompt: `function that outputs ASCII art to the console with a cat image`

2023-11-17 04:58 UTC, valerybugakov reviewed
The "document" action removed the interface field a couple of times after adding a comment. For example, here, I asked it to document the `triggerKind` property:

<img width="840" alt="Screenshot 2023-11-17 at 12 56 12" src="https://github.com/sourcegraph/cody/assets/3846380/a96d9a03-abf2-4afe-992a-d7bac7ad9b8c">

Filepath: `src/completions/get-inline-completions.ts`
Property: `InlineCompletionsParams['triggerKind']`

2023-11-17 05:07 UTC, valerybugakov reviewed
The "edit" action most worked as expected, but the results show that the LLM has a poor understanding of the surrounding code. The UX is awesome. I'd love to use it with a smarter model and better context. Noob q: what model do we use for quick actions?

2023-11-17 06:39 UTC, valerybugakov approved these changes
Love the new actions! Especially "document" and "generate" ones. Going to use them locally and report issues in Slack 🙌

2023-11-17 06:39 UTC, valerybugakov commented on vscode/src/code-actions/document.ts
> +        const [documentableNode] = execQueryWrapper(document, range.start, 'getDocumentableNode')
Noice!

2023-11-17 06:41 UTC, valerybugakov commented on vscode/src/code-actions/document.ts
> +        const [documentableNode] = execQueryWrapper(document, range.start, 'getDocumentableNode')
@umpox, let me know if you noticed any confusing parts about our tree-sitter setup 🙂

2023-11-17 14:28 UTC, abeatrix requested changes
Found some issues with the code actions, but love the idea in general! Curious to know why we need a different prompt and action for the Documentation Code Action instead of using the existing one?

## Document Code Lens

Break the code and the undo button does not work

https://github.com/sourcegraph/cody/assets/68532117/9f9f5df8-6089-4b4c-9d22-5c861aa55791

## Undo button always remove the last line that it did not line

Issue unrelated to this PR but related to the feature 😅 

https://github.com/sourcegraph/cody/assets/68532117/0b413813-044f-4dcf-8da3-ae13565fe28c

## Retry Code Lens breaks the code before applying new changes

https://github.com/sourcegraph/cody/assets/68532117/9f073959-ab5a-428a-a484-b1b682e6890e

2023-11-17 14:40 UTC, abeatrix commented on vscode/src/code-actions/edit.ts
> +        const source = 'code-action'
What do you think about adding the type of action to the end of source, e.g. `code-action:generate`, `code-action:edit` so we can create a dashboard for each code action usages?

2023-11-17 14:41 UTC, abeatrix commented on vscode/src/code-actions/document.ts
> +        const [documentableNode] = execQueryWrapper(document, range.start, 'getDocumentableNode')
This is super cool! Can we add it as an option for the commands/custom commands? Think it'd be helpful with the /explain and /test commands!!!

2023-11-20 11:22 UTC, umpox commented on vscode/src/code-actions/document.ts
> +        const [documentableNode] = execQueryWrapper(document, range.start, 'getDocumentableNode')
@valerybugakov The tests are great and the SDK is super easy to use and build from.

I found it helpful to take the contents from a page at https://learnxinyminutes.com/ and then put it into [this playground](https://tree-sitter.github.io/tree-sitter/playground) when writing the queries. Covers quite a lot of cases.

2023-11-20 11:23 UTC, umpox commented on vscode/src/code-actions/document.ts
> +        const [documentableNode] = execQueryWrapper(document, range.start, 'getDocumentableNode')
@abeatrix Maybe, do you have any ideas? I think we could possibly use this with the scope expansion too, e.g. expanding to nearest function etc if we want more control over different scenarios.

I think we don't make this available for custom commands yet, it's quite hard to write these queries so not sure if anyone will want to integrate them with a custom command. Possibly there's future work to integrate pre-written ones though, like `useNearestFunctionAsSelection` or something

2023-11-20 11:55 UTC, valerybugakov commented on vscode/src/code-actions/document.ts
> +        const [documentableNode] = execQueryWrapper(document, range.start, 'getDocumentableNode')
> I found it helpful to take the contents from a page at https://learnxinyminutes.com/ 

TIL, thanks for sharing! I've been asking GPT-4 to generate a file with all syntax constructs, but using the website you shared is a bit more reliable 😛

2023-11-22 14:45 UTC, umpox commented
@abeatrix Thanks for reporting the "undo" bugs! I took a look and everything you mentioned was related to weird "undo" logic we had.

The problem was that we were incorrectly using the `selectionRange` when **appending** or **prepending** new code to the target range. Our code assumed that any edits that happened immediately before or after the target range, was completely unrelated - so it wouldn't include this in the edit, or in the code lens or diff.

For fixups we do care about appending or prepending, so I've updated this logic to support expanding the range if there is a partial overlap (`change.range.end === selectionRange.start` or `change.range.start === selectionRange.end`). 

This also has the benefit of improving the diff highlighting for the /doc output, as previously we mostly ignored this.

2023-11-22 16:40 UTC, abeatrix commented
Thanks for working on this!

Confirmed the following are fixed
- [ ] Document Code Lense
- [x] Undo button always remove the last line that it did not line
- [x] Retry Code Lens breaks the code before applying new changes

https://github.com/sourcegraph/cody/assets/68532117/74026086-95ff-4e62-a2e7-5e8a66ba76ec


There are some issues with the`Document Code Lense`where the generated doc string will replace the current line of text, and the undo button will remove the last line of the current range:

https://github.com/sourcegraph/cody/assets/68532117/111ff0db-bf8a-4d8d-9b09-08383c64d157

2023-11-23 13:59 UTC, umpox commented
@abeatrix Can't replicate the issue with the line being removed 🤔 Please could you output the logs if you see it again?

The only things I can think are:
- Maybe the formatter you use has different behavior to mine
- The LLM had a moment and produced some weird output

Going to update this with `main` and merge this (aware you're on PTO until next week) to avoid long lived branches. Further work to imrpove the response reliablity is related to this issue https://github.com/sourcegraph/cody/issues/1790

2023-11-23 14:31 UTC, merged