Fuzzy search for @-ing files and symbols
sourcegraph/cody pull request #1889
Opened 2023-11-27 08:51 UTC by toolmantim

This updates the @-file UI with cleaned up styles, fuzzy matching, and putting symbol search behind it's own `@#` syntax.

Fixes #1838
Fixes #1837
Fixes #1840
Replaces #1851

Changes:

- Shows the UI immediately after typing `@`
- Does fuzzy matching, similar to VS Code’s finder, over files and symbols
- Symbol search is behind `#`
- Symbol search API is finicky and can easily return zero results, so add a little UI hint to help them (alternatively: we could disable it and do per-file drill-down instead like originally intended)
- Rewrite labels and clean up styles
- Handle file search cancellations properly
- De-dupe tab file names
- Tests

Not included:
- Handling of large files
- Drilling down from a file to its symbols (i.e. `@some-file.ts#SymbolName`)

| Before | After |
| - | - |
| <img width="479" alt="Screenshot 2023-11-27 at 7 24 48 pm" src="https://github.com/sourcegraph/cody/assets/153/623697b6-90fb-4b7e-94d9-4556b67b5006"> | <img width="479" alt="Screenshot 2023-11-27 at 7 33 11 pm" src="https://github.com/sourcegraph/cody/assets/153/be82df64-b6d6-45f0-a87a-adb6e1ffedbb"> |
| <img width="479" alt="Screenshot 2023-11-27 at 7 24 03 pm" src="https://github.com/sourcegraph/cody/assets/153/64cef618-de9b-4d3c-9ed4-3069ea436913"> | <img width="479" alt="Screenshot 2023-11-27 at 7 33 31 pm" src="https://github.com/sourcegraph/cody/assets/153/1808aaa7-b7aa-4130-b0cf-338c54683d93"> |
| <img width="479" alt="Screenshot 2023-11-27 at 7 23 34 pm" src="https://github.com/sourcegraph/cody/assets/153/53a04b55-c18e-438d-a186-2917169e508e"> | <img width="479" alt="Screenshot 2023-11-27 at 7 33 46 pm" src="https://github.com/sourcegraph/cody/assets/153/47f3d61a-79be-4f0d-9f9d-780a33be5b0a"> |
| <img width="479" alt="Screenshot 2023-11-27 at 7 23 04 pm" src="https://github.com/sourcegraph/cody/assets/153/1a9c1e03-d9b5-4327-96aa-45d92b4d22b5"> | |
| <img width="479" alt="Screenshot 2023-11-27 at 5 10 26 pm" src="https://github.com/sourcegraph/cody/assets/153/818b97c6-048c-4c99-87fa-f7818e2b8b29"> | <img width="479" alt="Screenshot 2023-11-27 at 7 34 54 pm" src="https://github.com/sourcegraph/cody/assets/153/b9969e17-c5e1-4e9d-90ee-af61d5ba5fa6"> |
| <img width="479" alt="Screenshot 2023-11-27 at 7 23 24 pm" src="https://github.com/sourcegraph/cody/assets/153/b2aef6bc-f08f-453e-a1ce-fd6d1975434d"> | |

## Test plan

- Manual:
  - Tested on sourcegraph/cody, soucregraph/sourcegraph & chromium/chromium
  - Open the repo, start a chat, type @
- Automated tests

2023-11-27 09:24 UTC, toolmantim commented on vscode/package.json
> +    "fuzzysort": "^2.0.4",
I tried a few but this was the fastest and smallest

2023-11-27 19:14 UTC, abeatrix requested changes
Great job on supporting fuzzy search! It doesn't fixes the issue mentioned in https://github.com/sourcegraph/cody/issues/1837 as I mentioned in https://github.com/sourcegraph/cody/pull/1851 that the only one to get perfectly consistent results is to remove the limit for `MAX_RESULTS` which is currently set to 20 in your branch. You can see the last item is sometimes different when doing the same search when testing from your branch:

https://github.com/sourcegraph/cody/assets/68532117/06d2eb3f-2e75-4c35-809e-a94d93842711

Other than that, I think we should group the editorTab into ContextFileType and this should be good to go? Wdyt?

2023-11-27 19:14 UTC, abeatrix commented on vscode/src/editor/utils/editor-context.ts
> +    editorTab?: boolean
```suggestion
```

Let's set kind to `editor-tab` instead of making a new field?

2023-11-27 19:14 UTC, abeatrix commented on vscode/webviews/UserContextSelector.tsx
> +                        const icon =
is it intended to not display icon for file results?

2023-11-27 23:18 UTC, toolmantim commented on lib/shared/src/codebase-context/messages.ts
> +    editorTab?: boolean
Good catch. `editorTab` was accidentally left in, and wasn't even used. I've just removed it instead?

2023-11-27 23:30 UTC, toolmantim commented on vscode/webviews/UserContextSelector.tsx
> +                        const icon =
Yeah, unless we can do extension-specific file icons (there's no support for that in webviews is there?) there's no need, especially now that files aren't intermingled with symbols.

2023-11-27 23:53 UTC, toolmantim commented
> It doesn't fixes the issue mentioned in https://github.com/sourcegraph/cody/issues/1837 as I mentioned in https://github.com/sourcegraph/cody/pull/1851 that the only one to get perfectly consistent results is to remove the limit for MAX_RESULTS which is currently set to 20 in your branch.

That's unexpected… it should return every file in the workspace because of `undefined` here:
https://github.com/sourcegraph/cody/pull/1889/files#diff-315ecedea695e410a04a36543d5d788b07f05d75885cedffceb922c3f33cd569R18

I'll check what’s going on here… 🤔

2023-11-28 01:48 UTC, abeatrix commented
@toolmantim I found a solution that works and created a separate PR to merge it into this PR (to avoid making direct changes to your PR in case it doesn't work for you): https://github.com/sourcegraph/cody/pull/1917

2023-11-28 02:32 UTC, toolmantim commented
Thanks @abeatrix ! I've updated this with your code from #1917 but tweaked a little. I think this is ready to go!

2023-11-28 03:15 UTC, abeatrix approved these changes
Confirmed:
- [x] Results are consistently sorted
- [x] Support fuzzy search
- [x] Search is not case-sensitive
- [x] Search support extension search

https://github.com/sourcegraph/cody/assets/68532117/0d9b2d7f-1acb-4e24-ab68-90647e4bc6d5

I noticed the search results are not sorted alphabetically. If this is the intended behavior then I think it's good to go. Thanks for working on this!

2023-11-28 03:19 UTC, merged