setup gcs bucket in eventlogger, add sync
sourcegraph/cody pull request #1976
Opened 2023-11-29 04:43 UTC by abeatrix

Replaces https://github.com/sourcegraph/cody/pull/1856

tbc

## Test plan

2023-12-04 17:51 UTC, akalia25 commented on vscode/src/services/telemetry.ts
> +            await syncChat(JSON.stringify(filteredChats), fileLocation)
Would it be possible to send the chats as a JSONL instead of JSON? BigQuery has [limitations](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json#limitations) where it only accepts a GCS <> BQ connection when the data is newline delimited. Each JSON object must be on a separate line in the file.  i.e.
`{...}  \n
{...}  \n
{...} \n` 

If this would be a huge lift, we can investigate something on the data-eng side to transform the json :) 🙇

2023-12-04 21:43 UTC, abeatrix commented on vscode/src/services/telemetry.ts
> +            await syncChat(JSON.stringify(filteredChats), fileLocation)
Yea just updated the code to reflect this :)

2023-12-04 21:52 UTC, akalia25 commented on vscode/src/services/telemetry.ts
> +            await syncChat(JSON.stringify(filteredChats), fileLocation)
amazing 🎉 !! Is there any way to send an updated file to the bucket with the new JSONL and I can verify things on the BQ side? :)

2023-12-04 23:20 UTC, abeatrix commented on vscode/src/services/telemetry.ts
> +            await syncChat(JSON.stringify(filteredChats), fileLocation)
Oh since this is uploading to the storage directly it shouldn't reach BQ at all (I thought that's what Dan wanted)?

2023-12-05 00:18 UTC, akalia25 commented on vscode/src/services/telemetry.ts
> +            await syncChat(JSON.stringify(filteredChats), fileLocation)
You're right - the chat transcript data would not go directly into BigQuery and is going to be stored onto cloud storage. I'm creating an external table that connects to the Cloud Storage bucket holding the transcript data ([ref](https://cloud.google.com/bigquery/docs/external-data-cloud-storage)). This would allow the team to access the transcripts through BigQuery or the raw files in Cloud Storage, with the external table providing a schema overlay.

The transcripts would reside in their own table, we get the benefit of keeping this large data separate from our production table but also allowing us to join against it when needed for the AI/ML folks :) (i.e. [accomplish this](https://sourcegraph.slack.com/archives/C065NKGD1BM/p1701695420457929?thread_ts=1700702538.931369&cid=C065NKGD1BM))

Does that help? :)

2023-12-05 19:51 UTC, nathan-downs commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
>                                          ...codeCount,
If there are V2 events that exist can we add the changes to these as well? So adding `requestID` to the metadata of the `telemetryRecorder.recordEvent()` call. The legacy telemtryService will be deprecated at some point, so we want to make sure not to lose anything.

2023-12-05 21:12 UTC, bobheadxi commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
>                                          ...codeCount,
Note that there is a special field in `recordEvent` for `requestID`, `interactionID`

2023-12-08 23:08 UTC, akalia25 commented on vscode/src/services/telemetry.ts
> +            const fileLocation = `cody/vscode/chatTranscript/${TODAYS_DATE()}/${globalAnonymousUserID}.json`
Could we make the `fileLocation` as such: `cody/vscode/{event_name}/YYYY/MM/DD/{anon_user_id}/{uuidv4().slice(0, 8)}.json`. 

This would help us:
1.  isolate the different types of events within the bucket (i.e. `syncChatInteraction` vs `chatResponse`, `chatSubmitted`).
2. By adding `{uuid}`, we'd eliminate the chance of overwriting any data we stored in the past

2023-12-09 00:43 UTC, dadlerj commented on vscode/src/services/telemetry.ts
> +export async function syncChatInteraction(endpoint?: string, interaction?: Interaction): Promise<void> {
Why aren't we calling `localStorage.lastSyncedTimestamp(new Date(...))` in this function? I know there's a goal to record old chat history if no other syncs have been logged, but this setup seems to ensure that we'll log both (1) all chats as they occur _and_ (2) every-7-day historical transcripts going forward. 

For the future, don't we only want one or the other?

2023-12-09 01:25 UTC, akalia25 commented on vscode/src/services/telemetry.ts
> +        const fileLocation = `cody/vscode/chatInteraction/${globalAnonymousUserID}/${TODAYS_DATE()}/${interactionTimestamp}.json`
I think this `fileLocation` has the ordering mixed up should be `TODAYS_DATE` first and then `globalAnonymousUserID` ?

2023-12-09 01:30 UTC, akalia25 commented on vscode/src/services/telemetry.ts
> +            await syncChat(filteredChats.map(chat => JSON.stringify(chat)).join('\n'), fileLocation)
would it be possible to add the `fileLocation` as a top level property within the JSON? This would help with mapping it back to the event, if it also lives within the JSON data. Thoughts? :)

2023-12-11 18:01 UTC, evict requested changes
How do we prevent arbitrary writes to the bucket? We cannot store the key on the client-side.

Can we add the transcript creation not to the DotCom backend? See comment: https://github.com/sourcegraph/cody/pull/1976/files#r1422891856.

2023-12-11 18:01 UTC, evict commented on lib/shared/src/telemetry/EventLogger.ts
> +    public async sync(history: string, fileLocation: string): Promise<void> {
Can we add some server-side code to handle the transcript upload? That way we can ensure there's proper authentication in place, also to the bucket writes.

2023-12-11 18:06 UTC, dadlerj commented
@evict this PR is only a short-term solution to the question at hand. Sharing a thread with you now in Slack.

2023-12-11 22:43 UTC, dadlerj commented on lib/shared/src/telemetry/EventLogger.ts
> +    public async sync(history: string, fileLocation: string): Promise<void> {
Just FYI, @evict and I discussed—this is a short-term solution and will be replaced in the coming months. For now, the risk of high costs due to unauthenticated uploads is acceptable and @akalia25 is setting alerts.

2023-12-12 11:15 UTC, closed without merging