add telemetry for LLM selection and CTA clicks
sourcegraph/cody pull request #2052
Opened 2023-12-01 20:53 UTC by abeatrix

feat: add telemetry for LLM selection and CTA clicks

Track events when users click on the Cody Pro upgrade CTA and when they select an AI model from the dropdown.

## Test plan

https://github.com/sourcegraph/cody/assets/68532117/976a5981-db66-4697-b115-e46859ba7643

2023-12-01 21:45 UTC, chenkc805 requested changes
Just left a small change request. Other LGTM

2023-12-01 21:45 UTC, chenkc805 commented on vscode/webviews/Components/ChatModelDropdownMenu.tsx
> +                    eventName: 'CodyVSCodeExtension:upgradeCTA:clicked',
@abeatrix I'm seeing this event labeled as `CodyVSCodeExtension:upsellUsageLimitCTA:clicked` in the video, which is different from what I see here. 

Let's change this event to say `CodyVSCodeExtension:upgradeLLMChoiceCTA:clicked`

2023-12-01 21:54 UTC, abeatrix commented on vscode/webviews/Components/ChatModelDropdownMenu.tsx
> +                    eventName: 'CodyVSCodeExtension:upgradeCTA:clicked',
renamed

2023-12-01 21:55 UTC, chenkc805 approved these changes
LGTM

2023-12-04 09:07 UTC, philipp-spiess approved these changes

2023-12-04 09:27 UTC, philipp-spiess approved these changes

2023-12-04 11:45 UTC, merged