Add V2 telemetry to remaining Cody events
sourcegraph/cody pull request #2060
Opened 2023-12-02 07:02 UTC by nathan-downs

## Test plan

Instrument V2 event
run `sg start`
verify in `event_logs` and/or debug console
ensure all integration tests pass

2023-12-04 18:16 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +                    privateMetadata: { op: 'cancel' },
I wonder if we can remove the metadata here entirely? the operation `cancel` is already part of the event names (ditto for all the `privateMetadata: { op: '...' }` events here

2023-12-04 18:17 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +                telemetryRecorder.recordEvent('cody.fixup.codeLens.error', 'error', {
I wonder if a more appropriate translation for this particular event might be:

```suggestion
                telemetryService.log('CodyVSCodeExtension:fixup:codeLens:clicked', {
                    op: 'show_error',
                    hasV2Event: true,
                })
                telemetryRecorder.recordEvent('cody.fixup.codeLens.show_error', 'clicked', {
```

2023-12-04 18:19 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +        telemetryRecorder.recordEvent('cody.fixup.reverted', 'clicked', {
```suggestion
        telemetryService.log('CodyVSCodeExtension:fixup:reverted', tokenCount, { hasV2Event: true })
        telemetryRecorder.recordEvent('cody.fixup.reverted', 'clicked', {
```

2023-12-04 18:20 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +                    tokenCount: countCode(replacementText),
same here, can tokenCount be non-private if numeric?

2023-12-04 18:20 UTC, bobheadxi commented on vscode/src/services/AuthProvider.ts
> +            },
booleans can be translated to `0` or `1` and retained in `metadata` instead 👍

2023-12-04 18:21 UTC, bobheadxi commented on vscode/src/services/utils/codeblock-action-tracker.ts
> +    })
`args` has a mix of numeric-looking and arbitrary metadata, in #1913 I added a `splitSafeMetadata` helper you can use here

2023-12-04 18:22 UTC, bobheadxi commented on vscode/src/services/utils/codeblock-action-tracker.ts
> +            },
same here, let's split this into metadata and privateMetadata more granularly

2023-12-08 08:30 UTC, ttloves2 commented on vscode/src/local-context/local-keyword-context-fetcher.ts
> +import { telemetryRecorder } from '../services/telemetry-v2'
import { telemetryRecorder } from '../services/telemetry-v2'

2023-12-12 22:02 UTC, bobheadxi commented on vscode/src/commands/CommandRunner.ts
> +                useShellCommand: !!command.context?.command,
Booleans should just live in `metadata` so that they get exported, e.g.

```
metadata {
  useCodebaseContex: command.context?.codebase ? 1 : 0,
  useShellCommand: command.context?.command ? 1 : 0,
} 
```

2023-12-12 22:03 UTC, bobheadxi commented on vscode/src/commands/CommandRunner.ts
> +                requestID: command.requestID,
There is a first-class field for this ID: https://sourcegraph.com/github.com/sourcegraph/telemetry/-/blob/src/index.ts?L203:1-210:26

The Cody telemetry exporter will put this in privateMetadata if the instance is < 5.2.4 - if you want, you can put this ID in both `interactionID` and privateMetadata

2023-12-12 22:04 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +                telemetryRecorder.recordEvent('cody.fixup.codeLens.undo', 'clicked', {})
If there is nothing in parameters you can omit it entirely:

```suggestion
                telemetryRecorder.recordEvent('cody.fixup.codeLens.undo', 'clicked')
```

2023-12-12 22:05 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +                })
Do we need `op: regenerate` here? The other events below don't keep the `op` (it seems redundant since we already have `retry`?

Also, general pattern here - right now, we have:

```
feature: cody.fixup.codeLens.retry
action: clicked
```

Would it be more descriptive to use:

```
feature: cody.fixup.codeLens
action: retry
```

ditto for the events below

2023-12-12 22:06 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +        })
tokenCount already only has numeric values:

```suggestion
        telemetryService.log('CodyVSCodeExtension:fixup:reverted', tokenCount, { hasV2Event: true })
        telemetryRecorder.recordEvent('cody.fixup.reverted', 'clicked', {
            metadata: tokenCount,
        })
```

2023-12-12 22:07 UTC, bobheadxi commented on vscode/src/non-stop/FixupController.ts
> +                    tokenCount: countCode(replacementText),
bump on this - tokenCount is numeric, let's put it in `metadata` so that it can be exported

2023-12-12 22:08 UTC, bobheadxi commented on vscode/src/services/AuthProvider.ts
>          })
should there only be one event here?

Also, is the appropriate `action` still "clicked" in this event?

2023-12-12 22:10 UTC, bobheadxi commented on vscode/src/services/utils/codeblock-action-tracker.ts
> +        telemetryRecorder.recordEvent(`cody.${eventType}:Paste`, 'clicked', {
Reopening this conversation, is `clicked` really the best "action" here? `paste` seems more descriptive

2023-12-12 22:12 UTC, bobheadxi requested changes
Nice work, overall comments:

1. Let's be more explicit about privateMetadata vs metadata, and think carefully about how we can represent data in metadata, and only use privateMetadata as a last resort
2. I think `action` can be used better. Right now most of these events just seem to have `"clicked"` as an action (even when it seems to have nothing to do with a click), but using action better allows better grouping of events by `feature`, and possibly query performance gains as well

2023-12-12 22:36 UTC, akalia25 commented on vscode/src/services/AuthProvider.ts
>          })
Great catch on the duplicate event! I think "auth" could be its own action, but would want to make sure we migrate that everywhere; and if we should separate logging in vs logging out as different actions. I can work with Kelsey on scoping this further on a different PR?

2023-12-12 22:37 UTC, bobheadxi commented on vscode/src/services/AuthProvider.ts
>          })
Oh I'm specifically talking about there being 2x `cody.auth.signin.token` `clicked` events here 😁

2023-12-12 22:39 UTC, akalia25 commented on vscode/src/services/AuthProvider.ts
>          })
yup! Removed one of them. :)

2023-12-12 23:07 UTC, bobheadxi commented on vscode/src/services/utils/codeblock-action-tracker.ts
> +    const { metadata, privateMetadata } = splitSafeMetadata(args)
nit - instead of `splitSafeMetadata` the args are pretty well-defined above this, let's construct `metadata` and `privateMetadata` directly and explicitly. `splitSafeMetadata` is meant as a last resort to quickly migrate callsites that have unknown args, but here it's known

2023-12-12 23:07 UTC, bobheadxi commented on vscode/src/services/utils/codeblock-action-tracker.ts
>          })
same here, the metadata are pretty well-defined, let's construct `metadata` and `privateMetadata` directly and explicitly

2023-12-12 23:12 UTC, akalia25 commented on vscode/src/services/utils/codeblock-action-tracker.ts
>          })
sounds good! I added `interactionId = requestID` here as well, let me know if thats an issue :)

2023-12-12 23:46 UTC, bobheadxi approved these changes
overall LGTM 😁 one last lingering nit, thank you!

2023-12-12 23:46 UTC, bobheadxi commented on vscode/src/services/AuthProvider.ts
> +            },
both `callback` and `web` are already in the event `feature` - do we need to duplicate it into metadata? (duplicating event names into metadata seems really common in the existing events, curious whether we really need to do that).

If not, it might be worthwhile to do a brief audit and remove this kind of stuff. IMO most of these the event feature/actions alone should be sufficient?

2023-12-12 23:46 UTC, bobheadxi commented on vscode/src/services/utils/codeblock-action-tracker.ts
>          })
Love it 😁

2023-12-12 23:51 UTC, akalia25 commented on vscode/src/services/AuthProvider.ts
> +            },
Totally agree with you! removed the `privateMetadata` and also realized we were recording this twice 🙈 so thanks for calling!

2023-12-13 00:02 UTC, merged