Fix clicking on context files with absolute paths on Windows
sourcegraph/cody pull request #2400
Opened 2023-12-15 15:38 UTC by DanTup

Fixes https://github.com/sourcegraph/cody/issues/2399 by removing a duplicate call to open a file which [expects a file URI](https://code.visualstudio.com/api/references/commands#:~:text=of%20InlineValue%20objects-,vscode.open,-%2D%20Opens%20the%20provided) but was given a path, and only tries to join a path with the workspace URI if it's a relative path.

https://github.com/sourcegraph/cody/assets/1078012/787806c8-05e2-43a4-a6fe-59e574298092

I'm not certain if there really should be absolute paths in this list if things are inside my workspace, but it probably makes sense for this code to tolerate them.

@kalanchan 

## Test plan

- `@`-mention a file on Windows
- expand the list of context files
- click on an absolute path

2023-12-15 15:46 UTC, DanTup commented on vscode/src/services/utils/workspace-action.ts
> -    void vscode.commands.executeCommand('vscode.open', filePath)
@abeatrix looks like this call was added in 343f626e6ec106fb75a9a586e0b2dc00d5730d7c but as far as I can tell it is redundant (because the code below opens the file).

My fix here is removing it because I don't think it's doing anything, but if there's a reason to have it we can also fix by changing it from a path to a file URI.

2023-12-21 03:55 UTC, dominiccooney requested changes
There's a hard coded path in here?

2023-12-21 03:55 UTC, dominiccooney commented on vscode/src/services/utils/workspace-action.ts
> +    filePath = 'lib\\main.dart'
???

2023-12-22 11:34 UTC, DanTup commented on vscode/src/services/utils/workspace-action.ts
> +    filePath = 'lib\\main.dart'
😱

Thanks for catching this. I've added a test that clicks one of these links and verifies an editor tab opens. The test is broken before removing this and passing on Windows when I removed this.

However, on Mac/Linux it's failing because apparently we have a full path without the leading slash:

![image](https://github.com/sourcegraph/cody/assets/1078012/1b29d60f-eac9-4461-8052-2ed1ebc99db0)

Looking into that..

2023-12-22 12:12 UTC, DanTup commented
Ok, I tracked down the Linux/macOS test failures down to this code which is removing the leading slash from absolute file paths:

https://github.com/sourcegraph/cody/blob/bcd49b3694082f529d47681354310a47ea99d195/vscode/src/chat/chat-view/chat-helpers.ts#L74-L77

It's not clear to me what the purpose of this is.. on Windows it's not being done and the tests are passing (although it's not clear to me if we wanted absolute or relative paths in the context file list). On Linux/Mac this is stripping the first `/` which makes it seem like a relative path, but it's not clear what it's relative to).

I think this needs some input from someone who is more familiar with this (perhaps @abeatrix ?). And I know I've said this before, but I think we need to get better at being very explicit with comments on all "filename-like" fields what they really are... Are they URI paths (always forward slashes), native paths (backslashes on Windows), absolute, relative (if so, relative to what).

2023-12-22 12:14 UTC, DanTup commented
FWIW if I just completely remove the code noted above, then Mac behaves the same as Windows (we show an absolute path, and clicking it works):

<img width="667" alt="Screenshot 2023-12-22 at 12 13 23" src="https://github.com/sourcegraph/cody/assets/1078012/2a930bf1-90a7-43a0-9fa0-70b2158a551e">

I don't know what implications there are of doing this (for files that come from places other than these `@`-mentions) though.

2023-12-27 14:26 UTC, DanTup commented
@beyang the code quoted above was added in https://github.com/sourcegraph/cody/commit/c958112f6a3f257e0010a1db1a9b318cfaafb472 but it's a big change so I don't know if it was just moved/copied from elsewhere. If you authored it, do you remember what the reason was for just removing the first `/`?

It's causing issues because it looks like a relative path not absolute, and since Windows paths don't start with `/` it means the paths are inconsistent across the platforms.

2023-12-29 12:41 UTC, DanTup commented
The test here will be impacted by the question at https://github.com/sourcegraph/cody/pull/2408 - it turns out user-selected files weren't intended to show up here, so the test added for this issue won't work once they're filtered out (when https://github.com/sourcegraph/cody/pull/2408 lands).

Depending on the response there, we may need to change the test for this (assuming the original issue is even still valid with that change).

2024-01-12 11:30 UTC, DanTup commented
> The test here will be impacted by the question at https://github.com/sourcegraph/cody/pull/2408 - it turns out user-selected files weren't intended to show up here, so the test added for this issue won't work once they're filtered out (when https://github.com/sourcegraph/cody/pull/2408 lands).

This decision was reverted in https://github.com/sourcegraph/cody/pull/2679 so user-mentioned files will show up again. However this change might be impacted by https://github.com/sourcegraph/cody/pull/2653 so I'll come back to this after that merges.

2024-01-19 12:27 UTC, DanTup commented
This change is no longer necessary, the big was already fixed on main by changes @sqs made to tidy up use of paths vs URIs etc. :-)

https://github.com/sourcegraph/cody/assets/1078012/928dd4d4-a566-4816-99ec-ad65ed2ac682

2024-01-19 12:27 UTC, closed without merging