Adding support to save the locally selected model so that new chats don´t require repeated model selection
sourcegraph/cody pull request #2438
Opened 2023-12-19 04:51 UTC by arafatkatze

<img width="805" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/3b803f37-9142-4a23-8160-d0aefa011fff">

I was quite frustrated with the loading issue as well so I changed it. The video is pretty self explanatory. It saves the state even after you quit and load Cody again. 

I have a strong suspicion that a lot of users will switch to GPT 4-Turbo once and then never switch back

https://github.com/sourcegraph/cody/assets/11155207/189fe1b3-5e26-49ce-adf1-f156a020608d

## Test plan

2023-12-19 07:39 UTC, valerybugakov approved these changes
I also started looking into it because I want GPT-4 by default. TY!

2023-12-19 08:55 UTC, philipp-spiess reviewed
This is awesome! I would expect some kind of validation to go on though, did you look into this?

Removing @valerybugakov's approval not to merge this too eagerly since it could cause some nasty errors

2023-12-19 08:55 UTC, philipp-spiess commented on vscode/src/chat/chat-view/ChatPanelsManager.ts
> -                  defaultModelID: defaultModel.model,
We should check if the saved model is actually a valid model name for the current configuration. Otherwise, if you switch from a dotcom account to enterprise or from pro to free, this may result in a wrong model identifier which, when used, might cause errors.

2023-12-19 17:14 UTC, beyang requested changes

2023-12-19 17:14 UTC, beyang commented on vscode/src/chat/protocol.ts
> +    | { command: 'saveModel'; model: string }
The `chatModel` command already exists; why not use that one?

2023-12-19 17:14 UTC, beyang commented on vscode/src/chat/chat-view/ChatPanelsManager.ts
> +        const savedModel = localStorage.get('model')
Let's give the key a more distinctive name, like "lastSelectedModelID"

2023-12-19 17:14 UTC, beyang commented on vscode/src/chat/chat-view/ChatPanelsManager.ts
> -                  defaultModelID: defaultModel.model,
It seems strange that we write the last selected model ID in SimpleChatPanelProvider, but read it in ChatPanelsManager to pass into SimpleChatPanelProvider as a constructor param. Where possible, it's better to localize state management. Could we move the `localStorage.get` call to an `onReady` method in SimpleChatPanelProvider that runs when we receive the `ready` message?

2023-12-20 22:04 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatPanelsManager.ts
> -                  defaultModelID: defaultModel.model,
Moved the model selection to this function 

https://github.com/sourcegraph/cody/blob/2b9310b2828a66dc9d5b94d03f68a79013b8faf6/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts#L176-L192

Also it takes into account that the model selected is valid for that user. 

> Could we move the localStorage.get call to an onReady method in SimpleChatPanelProvider that runs when we receive the ready message?

Not sure if I fully understand this but hopefully moving the model selection to a single place makes the code better than before.

2023-12-20 22:05 UTC, arafatkatze commented on vscode/src/chat/protocol.ts
> +    | { command: 'saveModel'; model: string }
Need to store and load from storage.

2023-12-21 12:44 UTC, philipp-spiess commented on vscode/src/chat/protocol.ts
> +    | { command: 'saveModel'; model: string }
@arafatkatze Not sure I follow: If we already send a `chatModel` message, why would we need another one to save that if the behavior is "always save the last one as default"? 🤔

2023-12-21 12:47 UTC, philipp-spiess reviewed
This looks crisp now but I’m still unsure why we need a new notification for this instead of reusing. Do you mind elaborating?

2023-12-21 16:49 UTC, philipp-spiess approved these changes
Sharp! This looks good now. Let's add a change log entry though 🙇

2023-12-21 16:52 UTC, philipp-spiess commented
I wonder why the test still fails 🤔  Did you create the PR in a _fork_ of the cody repo? You can now create your branches on this repo instead, that should help!

2023-12-21 16:56 UTC, philipp-spiess requested changes
I found one more nit I’m afraid. I don't feel great that we have a compute function but keep a copy of the value in the class properties. Can we avoid this somehow?

2023-12-21 16:56 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +    private readonly modelID: string
Do we need this as a member now that we can compute it based on the localStorage? Asking because I just noticed that we have `this.modelID` and `this.chatmodel.modelID` and we only update one at some point. It's better to not keep duplicate references around I think.

2023-12-21 16:56 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
>                  this.chatModel.modelID = message.model
Should this also update `this.modelID` (and if yes, can we make it so that there is no duplication?)

2023-12-21 17:04 UTC, philipp-spiess approved these changes
Bliss

2023-12-21 17:34 UTC, merged