Edit: Refactor away from `MessageProvider` and `Recipe`
sourcegraph/cody pull request #2549
Opened 2024-01-03 11:54 UTC by umpox

## Description

Edit is now:
- Using it's own logic instead of sharing `MessageProvider`. 
- No longer a recipe, all logic lives inside of `/edit` and `non-stop`. In a follow up PR I will consolidate the logic in `non-stop` into this directory too and clean that up.

## Test plan

Edit test plan incoming...

2024-01-08 15:59 UTC, abeatrix requested changes
I tried the build from this branch but the comments are not working for me:


Doc command is not working:

https://github.com/sourcegraph/cody/assets/68532117/7ba40757-2dfd-4ae2-a419-4727adb28a9d

Edit command is also not working:

https://github.com/sourcegraph/cody/assets/68532117/8dea235c-fd6b-4cdc-99ff-219c81c4d18d

Other non-edit commands will open a new chat panel but they are all stuck in loading screen: 

![image](https://github.com/sourcegraph/cody/assets/68532117/a87f5b24-1ea5-4395-bd79-1049af5a9f8b)

2024-01-08 16:32 UTC, umpox commented
@abeatrix I can't replicate 🤔 Do you have any logs in your console (VS Code dev tools or the Cody Output log)? The diff should definitely not affect any chat related code, it seems like the extension hasn't activated properly.

https://github.com/sourcegraph/cody/assets/9516420/ac80ef28-e317-4269-917c-af5e10fa927a

2024-01-08 17:27 UTC, abeatrix approved these changes
That was my bad. I was testing it on files that were added to my `.cody/ignore` file so they were not showing up as expected 😅 

Confirmed the edit commands are working correctly after the change!

Uploading Screen Recording 2024-01-08 at 9.26.02 AM.mov…

2024-01-08 17:32 UTC, abeatrix commented on vscode/src/edit/manager.ts
> +            console.error('File was ignored by Cody.')
```suggestion
            void vscode.window.showInformationMessage('Cannot edit Cody ignored file.')
```

2024-01-08 20:20 UTC, abeatrix commented
we can also remove 'registerTreeView' and `taskViewProvider` from FixupController?

2024-01-09 08:46 UTC, umpox commented
@abeatrix I think so, I'll do it in a follow up PR

2024-01-09 08:46 UTC, umpox commented on vscode/src/edit/manager.ts
> +            console.error('File was ignored by Cody.')
Good idea 👍

2024-01-09 08:57 UTC, merged