Move VS Code chat attribution search to extension process
sourcegraph/cody pull request #2550
Opened 2024-01-03 13:50 UTC by cbart

Part of sourcegraph#58993

Early draft - goal is to move the attribution search to the extension process out of the webview process.

Here this is done through:

- extending the protocol with a `attribution-search` command and an `attribution` result message type.
- a `GuardrailsPost` object that synchronizes between a back-and-forth on guardrails searches (per snippet).
  - This object when asked to perform search, issues a `Promise`
  - and fires a call back (which in use is a `postMessage` to the extension process).
  - Once the extension returns back with a `postMessage` with attribution (or error), it notifies the object, and thus the `Promise`. 

## Test plan

TBD

2024-01-03 18:39 UTC, arafatkatze commented on lib/shared/src/guardrails/index.ts
> +class DeferredAttributionSearch {
Confused by the naming: The results are blocking on this and not deferred so how is this called deferred?

2024-01-03 18:55 UTC, arafatkatze approved these changes
Looks okay for now I  would love to see it all in action eventually.

2024-01-04 09:37 UTC, cbart commented on lib/shared/src/guardrails/index.ts
> +class DeferredAttributionSearch {
Good point, generally it's a synchronization point with a `Promise` and a `resolve` for a single attribution search. Do you have a good idea for a name?

2024-01-05 03:24 UTC, arafatkatze commented on lib/shared/src/guardrails/index.ts
> +class DeferredAttributionSearch {
`BlockingAttributionSearch` or `SynchronousAttributionSearch` could be a good fit.

2024-01-10 12:46 UTC, cbart commented on lib/shared/src/guardrails/index.ts
> +class DeferredAttributionSearch {
Good ideas! Amended.

2024-01-10 15:33 UTC, arafatkatze approved these changes
Approving again

2024-01-10 16:03 UTC, philipp-spiess requested changes
I do think the `currentRequests` is leaking memory so rejecting to avoid merging this, otherwise this looks good to me!

2024-01-10 16:03 UTC, philipp-spiess commented on lib/shared/src/guardrails/index.ts
> +        })
Should we add a timeout here too in case something in the RPC goes wrong? It does feel a bit brittle, doesn't it? 😅

2024-01-10 18:23 UTC, cbart commented on lib/shared/src/guardrails/index.ts
> +    private currentRequests: Map<string, AttributionSearchSync> = new Map()
Thanks for pointing this out! I was going to perform garbage-collection in notify methods but forgot.

2024-01-10 18:26 UTC, cbart commented on lib/shared/src/guardrails/index.ts
> +    private currentRequests: Map<string, AttributionSearchSync> = new Map()
Done now.

2024-01-10 18:33 UTC, cbart commented on lib/shared/src/guardrails/index.ts
> +        })
Added in GuardrailsPost, so that notify* method is invoked.

2024-01-10 18:34 UTC, cbart commented
Thanks @philipp-spiess ! Please take another look!

2024-01-10 19:09 UTC, philipp-spiess approved these changes
Awesome!

2024-01-10 19:35 UTC, merged