WIP Site Config
sourcegraph/cody pull request #2559
Opened 2024-01-04 02:13 UTC by arafatkatze

## Test plan

2024-01-08 11:10 UTC, toolmantim reviewed
Thanks @arafatkatze! Looking good. Left some suggested comments on the UI copy.

2024-01-08 11:10 UTC, toolmantim commented on vscode/src/chat/chat-view/ChatManager.ts
> +            void vscode.window.showErrorMessage('This is feature has been disabled on Cody by site admin.')
```suggestion
            void vscode.window.showErrorMessage('This feature has been disabled by your Enterprise instance site administrator.')
```

2024-01-08 11:10 UTC, toolmantim commented on vscode/src/completions/inline-completion-item-provider.ts
> +                description: 'Contact Sourcegraph Site Admin to enable autocomplete',
```suggestion
                description: 'Contact your Enterprise instance site administrator to enable autocomplete',
```

2024-01-08 11:10 UTC, toolmantim commented on vscode/src/main.ts
> +            void vscode.window.showErrorMessage('This is feature has been disabled on Cody by site admin.')
```suggestion
            void vscode.window.showErrorMessage('This feature has been disabled by your Enterprise instance site administrator.')
```

2024-01-08 11:10 UTC, toolmantim commented on vscode/webviews/Chat.tsx
> +    const disabledPlaceHolder = 'SiteAdmin has disabled chat and commands for Cody'
```suggestion
    const disabledPlaceHolder = 'Chat and commands have been disabled by your Enterprise instance site administrator'
```

2024-01-08 13:07 UTC, arafatkatze commented
@toolmantim Thanks for the recommendations, All comments resolved.

2024-01-08 21:39 UTC, slimsag commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        setInterval(() => {
Question: `setInterval` doesn't run immediately (so this logic will wait 30s, then `fetchConfigFeatures`. If say someone signs in and uses Cody really quickly, before that 30s and before `fetchConfigFeatures` has run for the first time.. what is the default? Will they have access, then it gets taken away after 30s?

2024-01-08 21:40 UTC, slimsag commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        setInterval(() => {
Perhaps you should also immediately call `this.fetchConfigFeatures().catch(console.error)` outside the `setInterval` so as to not delay the first request

2024-01-08 21:41 UTC, slimsag commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    } | null> {
Instead of this ever returning `null`, perhaps we could have the default values defined here. i.e., if it would be null, then fill out the defaults here and return them.

That way we can clearly find that list of default access controls - without chasing down every usage of `getConfigFeatures()`

2024-01-08 21:43 UTC, slimsag commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            this.configFeatures = null // Set the value of Config Features as null incase it doesn't exist or incase of errors
I am imagining this scenario:

* Temporarily for some reason the config features GraphQL request fails, e.g. server error, your wifi has issues temporarily, etc.
* This would then get set to `null`, meaning you'd get the default access controls..
* That could mean someone might report an issue like:

> Normally Cody says "my admin disabled chat", but sometimes I see that chat has been enabled seemingly at random.. and then like 30s later it gets disabled again. What's going on?

So perhaps in the case of an error, if we already fetched configFeatures successfully at least one time, we should use the old configFeatures instead of `null`/defaults.

2024-01-08 21:44 UTC, slimsag commented on vscode/src/chat/chat-view/ChatManager.ts
> +                'This feature has been disabled by your Enterprise instance site administrator.'
```suggestion
                'This feature has been disabled by your Sourcegraph site administrator.'
```

Suggesting wording improvement, feel free to ignore if someone else said to use the current wording.

2024-01-08 21:44 UTC, slimsag commented on vscode/src/completions/inline-completion-item-provider.ts
> +                description: 'Contact your Enterprise instance site administrator to enable autocomplete',
```suggestion
                description: 'Contact your Sourcegraph site administrator to enable autocomplete',
```

2024-01-08 21:45 UTC, slimsag commented on vscode/src/main.ts
> +                'This feature has been disabled by your Enterprise instance site administrator.'
```suggestion
                'This feature has been disabled by your Sourcegraph site administrator.'
```

2024-01-08 21:47 UTC, slimsag commented on vscode/webviews/Chat.tsx
> +    const disabledPlaceHolder = 'Chat and commands have been disabled by your Enterprise instance site administrator'
```suggestion
    const disabledPlaceHolder = 'Chat and commands have been disabled by your Sourcegraph instance site admin'
```

I think this text should change depending on what is disable, right?

* Chat AND commands are disabled -> `Chat and commands have been disabled by your Sourcegraph site admin`
* Only Chat is disabled -> `Chat has been disabled by your Sourcegraph site admin`

2024-01-08 21:48 UTC, slimsag commented on vscode/webviews/Chat.tsx
> +    const disabledPlaceHolder = 'Chat and commands have been disabled by your Enterprise instance site administrator'
Also, an edge case I had not thought about: if chat is enabled, but commands are disabled.. how does the user know commands are disabled? where do we tell them?

2024-01-08 21:50 UTC, slimsag reviewed
Left a bunch of comments, generally looking good to me otherwise.

One question: If you run this against a Sourcegraph instance that does NOT have the new GraphQL API, what happens? Want to make sure that this doesn't e.g. immediately lock out all Cody users whose Sourcegraph instance does not have the new GraphQL API :)

2024-01-08 23:28 UTC, abeatrix reviewed
I havent set up an instance to test the config (will do it tomorrow), but i've left some comments / questions inline based on the code change

2024-01-08 23:28 UTC, abeatrix commented on vscode/src/main.ts
> +        const configFeatures = await ConfigFeaturesSingleton.getInstance().getConfigFeatures()
it might be better to move this to [handleChatRequest](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L587-643) in SimpleChatPanelProvider to make sure the checks are run for all outgoing chat and command requests.

2024-01-08 23:28 UTC, abeatrix commented on vscode/src/main.ts
> +            commandsEnabled = configFeatures.commands
this would block chat questions submitted from the command palette: 

![image](https://github.com/sourcegraph/cody/assets/68532117/0013a8ec-87f7-4e3c-a7ce-bfc35d8c0c23)

2024-01-08 23:57 UTC, toolmantim commented on vscode/src/chat/chat-view/ChatManager.ts
> +                'This feature has been disabled by your Enterprise instance site administrator.'
(We also use "Enterprise Instance" in the UI for login etc)

2024-01-09 00:48 UTC, slimsag commented on vscode/src/main.ts
> +            commandsEnabled = configFeatures.commands
I'd say not the end of the world if this is the case - since it is technically a command and we do want admins to enable commands generally, so the more reasons users pester their site admin to enable them the better :)

2024-01-09 00:53 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        setInterval(() => {
<img width="513" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/451eb172-ccbf-4eed-b3e0-583bccb91196">
Everytime we use this singleton instance we use public `getConfigFeatures`.  The first time we call it, there is a request made to GQL only once.

All the GQL calling is behind a private method.

So this solves the underlying edge case suggested.

2024-01-09 00:58 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatManager.ts
> +                'This feature has been disabled by your Enterprise instance site administrator.'
Good thinking folks!!

2024-01-09 01:13 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            this.configFeatures = null // Set the value of Config Features as null incase it doesn't exist or incase of errors
Makes perfect Sense

2024-01-09 01:25 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +    const disabledPlaceHolder = 'Chat and commands have been disabled by your Enterprise instance site administrator'
Currently we say this 
https://sourcegraph.com/github.com/sourcegraph/cody@ara/site-config/-/blob/vscode/src/chat/chat-view/ChatManager.ts?L97%3A18-97%3A34 

But instead of saying this feature I can also say commands disabled. 
![image](https://github.com/sourcegraph/cody/assets/11155207/95a00aaa-c057-4b87-9f71-aa1f7461a893)
The UI looks like this. 

Chat disabled commentary and command disabled commentary are separate things so they should be expressed separately in the UX. That was my thinking

2024-01-09 01:26 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +    const disabledPlaceHolder = 'Chat and commands have been disabled by your Enterprise instance site administrator'
I fixed the wording to just say "Chat has been disabled by your Sourcegraph instance site admin "

2024-01-09 01:28 UTC, arafatkatze commented on vscode/src/main.ts
> +            commandsEnabled = configFeatures.commands
_this would block chat questions submitted from the command palette:_

@abeatrix That was done on purpose. I wanted to disable commands from being sent if they were disabled by the admin so I wanted to show errors in case of edit code etc. But if you feel the UI should behave differently then lemme know. My reasoning was same as Stephen's reasoning.

2024-01-09 01:33 UTC, toolmantim commented on vscode/src/chat/chat-view/ChatManager.ts
> +                'This feature has been disabled by your Enterprise instance site administrator.'
Thanks for the brain dump @slimsag!

@arafatkatze if we want to leave off Enterprise, "your Sourcegraph instance site admin" sounds like the best bet… let's use that.

2024-01-09 01:37 UTC, arafatkatze commented on vscode/src/main.ts
> +        const configFeatures = await ConfigFeaturesSingleton.getInstance().getConfigFeatures()
Great suggestion but there were reasons not to do it

1. I wanted to decouple Chat/commands. Coz its possible to have Chat Enabled/Commands disabled and vice versa
2. Incase of Chat I wanted to show this UI change where the text box is greyed out
![image](https://github.com/sourcegraph/cody/assets/11155207/5fee169a-b120-4719-82a8-cdda5de046f7)

The greyed out UI is good but it requires a change in the react components and thats why I moved the GQL query there instead of simplechatpanelprovider

3. I wanted to communicate the commands not being enabled with this UI 
![image](https://github.com/sourcegraph/cody/assets/11155207/9f62e36b-ad3d-4a3b-b3e4-14875fa155db)

Which looks different from the UI for chat disabled so thats why this had to be here. It would be harder to. do the UI communication had the blockers been elsewhere.



Feel free to offer suggestions on how to do this differently.

2024-01-09 01:39 UTC, arafatkatze commented
@abeatrix @slimsag 
Thanks for the review.
Offered commentary on most changes but feel free to push back on choices and offer more suggestions.

2024-01-09 06:51 UTC, dominiccooney requested changes
Can you use the VSCode context APIs and "when" enablement in the commands so users don't see commands they can't use in command palettes, editor tab strip, tree views, etc.?

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * retrieve the cached config features.
Let's revise this to be shorter and clearer. Fetches/retrieve is awkward.

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * The constructor is private to enforce the singleton pattern.
I don't think details like this are worth it.

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * getInstance() provides access to the singleton instance.
Let's put method documentation on the methods themselves.

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * the cached value. It ensures the config is only fetched once from the caller's perspective.
Why does perspective matter about the number of fetches? Be direct: The config is only fetched once.

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +export class ConfigFeaturesSingleton {
Naming this is awkward because the thing it does—fetches and caches the config features—should be transparent to the user. The fact that it is a singleton is the least interesting thing about it, to me. Don't think it is worth naming it around that.

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * handles errors, and caches the result. It runs every 30 seconds
Why would we poll every 30 seconds? This sounds like the exact opposite of the config only being fetched once.

If the config changes, how are clients meant to detect and respond to that change?

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        if (!this.configFeatures && !this.isFetching) {
There's a simpler way to do this "join async operation in progress", and that is to store the Promise of the fetch operation in the class and simply await or return that.

When you think about it, if all you need is the result, then you can simply always do it that way. You don't need to special case "is fetching" at all.

2024-01-09 06:51 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        setInterval(() => {
Reopening this thread...

If we fetch the features lazily, and there's no way to subscribe for updates, what's the benefit of this polling? New calls will sometimes get an updated value?

2024-01-09 08:13 UTC, slimsag commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        setInterval(() => {
I want a few behaviors from this PR:

1. On startup, quickly ask the server for which features can be used. Don't make Cody startup times slower.
2. If a site admin changes this setting on the server while people are using Cody, we should respect their change in a reasonably quick timeframe (e.g. a minute or so) without requiring users to restart Cody/vscode.
3. Do not increase the latency of autocomplete/chat requests. For example, let's not send a 'Can I use Cody chat?' request directly before every autocomplete/chat API request.
4. If for some reason we can't fetch the config on Cody startup, just let the user make use of the features.
5. If someone is using Cody but e.g. Chat is disabled,and then there's some intermittent failure fetching the updated config, don't give them access to chat only to be blocked from using it shortly after. i.e. use whatever last config we did successfully query.

2024-01-09 10:43 UTC, arafatkatze commented
> Can you use the VSCode context APIs and "when" enablement in the commands so users don't see commands they can't use in command palettes, editor tab strip, tree views, etc.?

@slimsag @toolmantim  Selective UI to only show the enabled commands look much better UX than what I have now. 
If you are cool too I am down to implement it?

2024-01-09 10:47 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * getInstance() provides access to the singleton instance.
Agree!!

2024-01-09 11:15 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +export class ConfigFeaturesSingleton {
I agree with your point but I called it singleton coz the idea is that you could potentially be calling the SAME thing from many different places to get the GQL config of what is and isn't visible(the pull a subset of the key/value pair). Those things could potentially HAMMER the GQL if they all get a chance to make a GQL request.

So how about we call it `CachedConfigFeaturesSingleton` would that be better? CC @slimsag

2024-01-09 11:19 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * handles errors, and caches the result. It runs every 30 seconds
Apologies for the lack of clarification, I am fixing the comments basically the idea is that the GQL config must be fetched every 30 seconds so that it stays in sync. 

We don't want to HAMMER GQL with requests so we use a singleton and because sometimes those requests can potentially be time consuming etc we only do 1 every 30 seconds to keep config in sync.

2024-01-09 11:20 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * the cached value. It ensures the config is only fetched once from the caller's perspective.
Agree, Fixing all the commentary.

2024-01-09 11:33 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    } | null> {
Great Catch!!

Fixed!!

2024-01-09 12:25 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        if (!this.configFeatures && !this.isFetching) {
Great point. I fixed it

2024-01-10 05:21 UTC, slimsag commented
> so users don't see commands they can't use in command palettes, editor tab strip, tree views, etc.?

Rather than **remove them** so users can't see them, what about still having them be there but just communicating on each clearly they are disabled by their admin?

I imagine two possibilities:

1. User doesn't see commands -> doesn't know Cody has those features -> assumes Cody is not as good as it actually is -> user values Cody less.
1. User sees commands -> sees that their admin disabled them -> voices opinion internally at company that their company should enable cody commands -> admin enables them -> users and us win

I'm hoping for option 2 above. Thoughts?

2024-01-10 05:34 UTC, toolmantim commented
Option 2 is my preference too

2024-01-10 16:23 UTC, arafatkatze commented
@slimsag Option 2 makes a lot of sense now that you explain. 

So hopefully this PR is good to go. Let me know if you have any concerns and I will fix the whole thing(merge conflicts etc) and we can merge this today.

2024-01-11 01:00 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +export class ConfigFeaturesSingleton {
How about `CachedConfigFeatures`?

2024-01-11 01:06 UTC, dominiccooney approved these changes
Improvements look good, approving to unblock. However...

Other times we started with config objects like this that could change, we ended up having to add plumbing to respond to changes. And because we didn't design for it, sometimes didn't go well... Change events refreshed unrelated state; change events caused cycles; etc.

Could you explain why callers don't need to subscribe to changes? If component X sees one config and component Y another then the product could be configured in a weird/broken state that's hard to reproduce.

2024-01-11 07:34 UTC, abeatrix commented on vscode/src/completions/inline-completion-item-provider.ts
> +                if (!configFeatures.autoComplete) {
When I'm connected to the [demo instance](https://demo.sourcegraph.com/), the autocompletion stopped working for me, and i can see the error fires every n seconds.

cc @philipp-spiess @valerybugakov to confirm if this is the best place to disable autoComplete

<img width="707" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/44089f43-18a9-4a29-8456-c576975eace9">

- Commands also doesn't work:

<img width="1234" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/1d7df8e8-ba92-4789-ae45-86b8aaa4e701">

- Chat works fine though!

<img width="1226" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/d19f91f2-fedd-4025-afc3-89597ab8a892">

2024-01-16 05:11 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatManager.ts
> +            void vscode.window.showErrorMessage('This feature has been disabled by your Sourcegraph site admin.')
Totally

2024-01-16 05:28 UTC, arafatkatze commented on vscode/src/completions/inline-completion-item-provider.ts
> +                if (!configFeatures.autoComplete) {
<img width="1542" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/6943f217-b33f-4313-9e9d-478fd0e54383">
Thats more of Demo instance issue coz it cant recognize the GQL of the new things I added. 

<img width="1578" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/ce383e12-8936-47a3-a668-d87e61a3566b">
My test instance can recognize that GQL and same for Dotcom(Ideally I would test this with the test instance coz it does have that GQL to be able to make it work). 

I am rather surprized coz the demo instance says its on version 5.2.6 so it should have my changes 
<img width="270" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/42d628d4-dff5-4ead-996b-acae50ab615b">

2024-01-16 06:00 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        setInterval(() => this.refreshConfigFeatures(), 30000)
Great catch I fixed it

2024-01-16 06:01 UTC, arafatkatze commented
@abeatrix Can I get 💚 if there aren't major blockers on this? Its rather hard to fix this PR as it touches many files that get changed with refactors in other places. If majority of the PR works good I am happy to merge this one then do follow up items on top of it if that works.

Thanks for the careful catches on the things I missed.

2024-01-16 13:34 UTC, abeatrix commented
> @abeatrix Can I get 💚 if there aren't major blockers on this? Its rather hard to fix this PR as it touches many files that get changed with refactors in other places. If majority of the PR works good I am happy to merge this one then do follow up items on top of it if that works.
> 
> Thanks for the careful catches on the things I missed.

no problem! The only major blockers I am seeing when connected to an older Sourcegraph instance (e.g. demo) are:
1. Autocompletes not working
2.  this error message when a new chat is created:

![image](https://github.com/sourcegraph/cody/assets/68532117/29c689ff-fe12-4649-8e9c-fa8d3c9be23e)


@arafatkatze @slimsag I don't want to block anything for your team though, so if you think these are expected then feel free to ignore me 😄

2024-01-16 13:35 UTC, abeatrix commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +interface EnterpriseCurrentUserInfoResponse {
looks like this can be removed?

2024-01-16 13:37 UTC, abeatrix commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    private async fetchConfigFeatures(): Promise<{
should we check their instance version (`getSiteVersion()`) to make sure they support the graphQL query before ` graphqlClient.getCodyConfigFeatures()` ?

2024-01-16 14:09 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +interface EnterpriseCurrentUserInfoResponse {
Yes it can be I am fixing tests now

2024-01-16 14:10 UTC, arafatkatze commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    private async fetchConfigFeatures(): Promise<{
Thats a good one, lemme try this.

2024-01-16 14:11 UTC, arafatkatze commented
@abeatrix That chaining cycle thing is a LEGIT issue that for some reason I didn't see in my debugger tests but it exists in testing. Apologies for this but lemme fix this stuff properly.

2024-01-16 20:11 UTC, abeatrix approved these changes
Tested on DotCom, S2 and Demo and confirmed autocomplete, chat, and commands are all working at the latest commit, great work :D !

2024-01-16 20:30 UTC, merged