fix: check active editor before executing commands
sourcegraph/cody pull request #2614
Opened 2024-01-08 18:06 UTC by abeatrix

CLOSE https://github.com/sourcegraph/cody/issues/2302

Fix issue listed in the linked issue.

- Check if an editor is active and not ignored before executing commands. 
  - Exist early if false
- Show error message if no editor is active or active editor is ignored.

## Test plan

1. Execute a command without opening an editor
2. Only the native VS Code error notification is posted, and both the request and response is never added to the transcript.

![image](https://github.com/sourcegraph/cody/assets/68532117/3bcab34c-360d-461b-8e82-10eec7784a39)

2024-01-09 06:55 UTC, dominiccooney requested changes
I think the "ignored" error message needs to be more helpful.

2024-01-09 06:55 UTC, dominiccooney commented on vscode/src/commands/CommandsController.ts
> +                ? 'The active editor is ignored.'
This is mildly mysterious. Sourcegraph style we'd give a pointer about why or what to do about this?

2024-01-09 07:07 UTC, abeatrix commented on vscode/src/commands/CommandsController.ts
> +                ? 'The active editor is ignored.'
@toolmantim any suggestion on what the updated copy should be? 👋

2024-01-12 03:55 UTC, abeatrix commented
> I think the "ignored" error message needs to be more helpful.

Do you think the updated message would do?

2024-01-12 11:22 UTC, DanTup approved these changes
Small suggestion, but LGTM

2024-01-12 11:22 UTC, DanTup commented on vscode/src/commands/CommandsController.ts
> +                ? 'The file is on the .cody/ignore list. Please remove it from the list and try again.'
Maybe "The active file is ignored by a .cody/ignore file..."? Using "a" instead of "the" might make it clearer that there could be one of these files in the tree (it might be easy to look in the wrong one and think this is a bug if you weren't the one to create them in the repository).

2024-01-12 21:25 UTC, abeatrix commented on vscode/src/commands/CommandsController.ts
> +                ? 'The file is on the .cody/ignore list. Please remove it from the list and try again.'
Makes sense, updated. Thank you so much for the suggestion!

2024-01-12 21:25 UTC, merged