hold: display edit buttons on all human messages
sourcegraph/cody pull request #2739
Opened 2024-01-15 19:05 UTC by abeatrix

close https://github.com/sourcegraph/cody/issues/2619

## This PR is outdated - moving to a new branch

The goal of this PR is to address the following items described in the design figma:

![image](https://github.com/sourcegraph/cody/assets/68532117/7a2cf932-f2af-4182-8a3d-d5210aff1c52)

![image](https://github.com/sourcegraph/cody/assets/68532117/326efdc5-4778-4a3a-a189-325bb0c8ab6e)

This PR includes the following changes:
- display edit button on each human message
- update the `handleEdit` function in SimpleChat to support commands and regular chat input properly
  - instead of only able to edit the last human message, user can now choose any human messages in their chat session to edit
  - also updated to support `/commands` in edited messages 

New tests added to cover the new changes
- update tests for the edit function in agent 
- add new e2e test for the updated user journey for editing chat messages

## Follow-up

- the new design update for the edit text area https://github.com/sourcegraph/cody/issues/2762

![image](https://github.com/sourcegraph/cody/assets/68532117/1d31d9f3-2ac1-46a7-9f81-d331b05743fb)

## Test plan

1. Build from this branch
2. in debug mode, ask Cody multiple questions, including using chat commands (e.g, /explain)
  - confirm edit button shows up on each message submitted when no message is in progress
3. click on an edit button to start the editing process
  - confirm the edit text area only shows up for the message you clicked the edit button on
4. update the message to something else and then submit the edit
  - confirm all the messages after the edited messages are removed (similar to how editing old messages work in chatGPT)
  - confirm the previous message has been replaced by the updated message
  - confirm cody is responding to your updated message when replying

Added new tests to agent to cover this updated behavior for edit. All tests are passing locally:

![image](https://github.com/sourcegraph/cody/assets/68532117/5e4f4ba0-5b30-4c96-965c-85b9d214ad48)

## Demo

https://github.com/sourcegraph/cody/assets/68532117/4a1b1cc5-f87f-4e2e-a491-412de82120b4

2024-01-18 19:41 UTC, abeatrix commented on lib/ui/src/chat/Transcript.tsx
> +                    showEditButton={!messageInProgress?.speaker && message.speaker === 'human'}
show edit buttons on all human messages

2024-01-19 03:05 UTC, dominiccooney requested changes
Nice start, let's try to simplify this a bit.

2024-01-19 03:05 UTC, dominiccooney commented on lib/ui/src/chat/TranscriptItem.tsx
> +        [setBeingEdited]
We should add tests where you start editing more than one message at a time, etc. if that is possible. (Would be nice if you had to cancel one edit before starting another...)

2024-01-19 03:05 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatModel.ts
> +    public removeMessagesFromIndex(index: number, expectedSpeaker: 'human' | 'assistant'): void {
Why do we need `expectedSpeaker`? Seems like you're taking a later error, where the speakers have become inconsistent, and are bringing it closer to the likely bug. That's a good idea, but I'm curious why we can't go further.

2024-01-19 03:05 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatModel.ts
> +            throw new Error(`SimpleChatModel.removeHumanMessageByIndex: ${expectedSpeaker} is not the expected speaker`)
This message is confusing, `${expectedSpeaker}` is the expected speaker. Just echo both, label which is which, and highlight that they are different.

2024-01-19 03:05 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +     * TODO (bee) support userContextFiles and addEnhancedContext
Let's do it?

2024-01-19 03:05 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +     * Removes any existing messages at the provided index before submitting
Would it be simpler to always take an index?

2024-01-19 03:10 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +     * TODO (bee) support userContextFiles and addEnhancedContext
for addEnhancedContext, it is done in https://github.com/sourcegraph/cody/pull/2806

2024-01-19 03:35 UTC, abeatrix commented on lib/ui/src/chat/TranscriptItem.tsx
> +    const [isItemBeingEdited, setIsItemBeingEdited] = useState<boolean>(false)
addessed in https://github.com/sourcegraph/cody/pull/2808!

2024-01-19 03:36 UTC, abeatrix commented on lib/ui/src/chat/TranscriptItem.tsx
> +        [setBeingEdited]
Covered by the e2e test to ensure all edit items are hidden when an edit is happening :)

2024-01-19 10:50 UTC, abeatrix commented
more works are being done in a newer branch for the latest change in the figma design 🚧 

https://github.com/sourcegraph/cody/pull/2811

2024-01-19 11:04 UTC, abeatrix commented on lib/ui/src/chat/TranscriptItem.tsx
> +    const initValue = message.displayText?.startsWith('/')
It is currently not supported, but we can add the tests once https://github.com/sourcegraph/cody/pull/2473 is merged 👍

2024-01-19 20:25 UTC, olafurpg commented on agent/src/index.test.ts
>          it(
FYI You can import this helper here and use it like this https://sourcegraph.com/github.com/sourcegraph/cody@8968a9b51794e046781c7c98bc8aff337e4fb429/-/blob/agent/src/cli/evaluate-autocomplete/AutocompleteMatcher.test.ts?L18%3A10-18%3A18
```suggestion
        it.skipIf(isNode16())(
```

2024-01-20 03:31 UTC, abeatrix commented
repalced by https://github.com/sourcegraph/cody/pull/2826

2024-01-20 03:31 UTC, closed without merging