refactor: convert fs paths to uris in test file utils
sourcegraph/cody pull request #2765
Opened 2024-01-17 00:28 UTC by abeatrix

refactor: convert filesystem paths to uris in test file utils

Refactored the new test file utils to use URIs instead of filesystem paths. This provides more flexibility for integrating with editors and allows us to work with untitled files.

### Changes

- convertFsPathToTestFile -> convertFileUriToTestFileUri
- Updated method signatures to use URI instead of strings 
- Updated tests to construct URI objects
- Generate new file requests using URI.parse instead of strings

## Test plan

- all current tests are passing
- the /unit command (behind cody.internal.unstable config) works as expected
- 
![image](https://github.com/sourcegraph/cody/assets/68532117/8ed2214e-1040-4950-995f-40910efa4cc8)

2024-01-17 01:45 UTC, dominiccooney requested changes
Looks good, but can we make the Windows path handling and test coverage more robust while we're here?

2024-01-17 01:45 UTC, dominiccooney commented on vscode/src/edit/provider.ts
> +                const newFileUri = URI.parse(fileExists ? testFileUri.fsPath : `untitled:${testFileUri.fsPath}`)
I know you're just maintaining the status quo with this edit, but does the `fileExists` case, `URI.parse(testFileUri.fsPath)`, work on Windows? `URI.parse('C:\\my\\file.txt')` produces a URI with scheme "C" which isn't right.

Think this should be something like:

```
const newFileUri = fileExists ? testFileUri : URI.parse(`untitled:${testFileUri.fsPath}`)
```

2024-01-17 01:45 UTC, dominiccooney commented on vscode/src/commands/utils/new-test-file.test.ts
>      it('should generate the default spec file path for ruby when no exisiting test files is found', () => {
Would be great to add some tests for Windows-style file paths, if that is possible. Maybe you can pass the directory separator as an optional parameter which defaults to the OS separator, so you can override it just for running the Windows-style path tests on macOS and Linux.

2024-01-17 04:35 UTC, sqs commented on vscode/src/commands/utils/new-test-file.ts
> +    if (isValidTestFileName(currentFileUri.fsPath)) {
In general, you want to avoid `uri.fsPath` unless you are writing to the file system directly (which you want to avoid because that won't work in webviews or on VS Code Web).

Here, you can pass the uri to `isValidTestFileName` (and make it accept a uri if it doesn't already).

Instead of using `basename` `dirname` from Node's `fs` module, use them from `path/posix` and operate on `uri.path` instead of `uri.fsPath`. The reason to use `path/posix` is that it always operates on paths with forward slashes, and the reason to use `uri.path` is because it always has forward slashes. On Windows, Node's `path` module will work with backslashes, and `fsPath` will have backslashes. It might seem that on Windows both would be backslashes so it would work out, but it turns out that in webviews and on VS Code Web, vite or webpack will bundle `path-browserify` for Node's `path` module, which always uses forward slashes.

This is tricky, and I have another branch that should help with this (`sqs/multiroot` but WIP).

tl;dr is:

- avoid `uri.fsPath`, use `uri.path` instead
- avoid `basename` `dirname` from Node `path`, use Node `path/posix` instead
- avoid `vscode.Uri.file(...)` and `URI.file(...)` - you should only use these if you are reading a file path from something like an external process - within the extension code, just pass around URIs and use `vscode.Uri.joinPath`

2024-01-17 05:49 UTC, sqs commented on vscode/src/commands/utils/new-test-file.test.ts
> +        const expected = URI.file('/path/to/file_test.py')
For ease of readability, I recommend not pulling out the expected value into a separate variable. Just inline it. And same for the value inside `expect(...)` unless it's long.

So like:

```typescript
expect(convertFileUriToTestFileUri(URI.file('...'), ...).toString()).toBe('file:///whatever')
```

(also `.toString()` is helpful when comparing URIs since the objects are not equal, only the string representations are)

2024-01-17 05:51 UTC, sqs commented
@abeatrix Just noticed this when calling `vscode.Uri.joinPath` on a `vscode-uri.URI` value as the first arg. Will get it merged soon, and you might find it useful to rebase this PR on that for your tests.

https://github.com/sourcegraph/cody/pull/2772

2024-01-17 06:55 UTC, abeatrix commented on vscode/src/commands/utils/new-test-file.ts
> +    if (isValidTestFileName(currentFileUri.fsPath)) {
@sqs Oh wow this is super helpful, will definitely keep this in mind, thank you so much for sharing this with me! 
I've updated the PR with your suggestions. Will try to finalize this and update the tests to cover paths on different OS like @dominiccooney suggested tomorrow. Thank you both again for the constructive feedback and reviews 🙇‍♀️

2024-01-17 07:46 UTC, sqs commented on vscode/src/commands/utils/new-test-file.ts
> +    if (isValidTestFileName(currentFileUri.fsPath)) {
Yep! I had to figure this all out over the last week or so, and I'm about to send up a PR with cleaner APIs for doing this and some eslint rules to flag code.

2024-01-17 08:02 UTC, sqs approved these changes
Added some comments, LGTM, thanks! Super helpful for me as I'm working on a cleaner API for working with URIs in our codebase too.

2024-01-17 23:27 UTC, sqs approved these changes
Code LGTM (minor comments)

2024-01-17 23:27 UTC, sqs commented on vscode/src/commands/utils/new-test-file.ts
> +            const testFileName = parsedTestFile.name.toLowerCase()
Why toLowerCase? I think it's rare for uppercase letters in a filename to have no meaning. Is it necessary to toLowerCase this value?

2024-01-17 23:27 UTC, sqs commented on vscode/src/commands/utils/new-test-file.ts
> +                const newTestFileName = parsedTestFile.name.replace(/existing/i, parsedCurrentFile.name)
What would make a filename contain the string `existing`?

2024-01-17 23:27 UTC, sqs commented on vscode/src/edit/provider.ts
> +            // an exisiting test file from codebase
typo: existing

2024-01-17 23:27 UTC, sqs commented on vscode/src/commands/utils/new-test-file.ts
> +            // Check if the existing test file has a non-alphanumeric character at the test character index
What's an example of a test file that has a non-alphanumeric character at the test character index? Like `_test`?

2024-01-17 23:28 UTC, abeatrix commented on vscode/src/editor-context/helpers.ts
> +            const isFileNameIncludesTest = isValidTestFile(vscode.Uri.file(fileName))
Good callout on the abstraction break with isValidTestFile! I agree it would be cleaner to split that into separate checks, but for now I've updated it to focus on consolidating the main test file generation logic since this is the only exception where we need to generate the URI for the file manually (i've updated the uri generated here to be more accurate as well via `Utils.joinPath(dirUri, fileName)` as you suggested as well).

I've also removed the `node_modules ` check from the function as it was added previously before I know how to [filter node_modules out via excludePattern](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/editor-context/helpers.ts?L89), so this is no longer necessary IMO but I will keep an eye out and add it back if an issue occur :)

2024-01-18 01:50 UTC, abeatrix commented on vscode/src/commands/utils/new-test-file.ts
> +                const newTestFileName = parsedTestFile.name.replace(/existing/i, parsedCurrentFile.name)
LOL this is fixed! It comes from an old PR I worked on before but forgot to update the code lol Also updated comments to address the questions you raised.

Note: Will try to improve this in a follow-up PR as this currently doesn't get called often, and only when Cody failed to suggest a test file name for the new test command that's behind the internal unstable flag.

2024-01-18 15:09 UTC, merged