escape custom html tags to support regular expressions
sourcegraph/cody pull request #280
Opened 2023-07-17 22:17 UTC by tobias-mayer

fixes https://github.com/sourcegraph/cody/issues/41

I noticed that all online markdown editors I tried that also support inline HTML and are based on markedjs seem to have this problem.

The problem is that <myLabel> in the regular expression is detected as a HTML token in markedjs tokenizer. As myLabel isn't listed in the ALLOWED_TAGS, DOMPurify will later on remove it. 

I tried several ideas but the only one that worked and doesn't introduce new security issues due to worse sanitizing is to escape all unknown HTML tags.

The regular expression is now displayed correctly and the highlighting will still work as you can see below:
![Screenshot from 2023-07-17 23-53-06](https://github.com/sourcegraph/cody/assets/56530704/967e68f8-54a6-44b1-860d-78bdcf5d5353)

2023-07-18 05:03 UTC, sqs commented
Thank you for the contribution! I would like to suggest 2 alternative impls that I think would be better:

1. In the example you gave, the tag-like things are in Markdown backticks, right? (Or does the LLM respond with `<code>` instead of backticks?) If backticks, we should be able to treat those specially and just fully escape their contents. That might be what already happens.
2. For other cases, I would feel more comfortable whitelisting certain safe tags (such as `a`) instead of your admittedly clever document.createElement technique.

cc @abeatrix @dominiccooney who worked on this stuff

2023-07-18 06:52 UTC, tobias-mayer commented
Thanks for the review!

1. As you can see in the following screenshot, if the LLM responds with backticks, everything works fine and the code is also highlighted (lower half of the screenshot). This has worked before and my changes don't affect this behavior. 
My changes affect the user input (at the top of the screenshot). There we don't have backticks or <code>, so <myLabel> is just plain text that gets converted to a marked HTML-Token. 

Thats why I only care about HTML tokens in `walkTokens`.

![2  Here we don't have the problem as the LLM responds with backticks which are converted to a codespan token in markedjs](https://github.com/sourcegraph/cody/assets/56530704/840b4b06-f458-42c3-af4a-aaaa893a8176)

2. I think about it the same way. That will probably also be significantly more efficient. I just pushed the change. I took a list of default HTML5 tags that I found online. It's quite long and there are probably many that we might never need. So feel free to make suggestions about that. 
One note about the list: It also contains unsafe tags like `<script>` which is intentional. They shouldn't be escaped because they are later on completely removed by DOMPurify.

2023-07-19 07:57 UTC, dominiccooney requested changes
This is good but let's handle case and parse a bit more accurately.

2023-07-19 07:57 UTC, dominiccooney commented on lib/shared/src/common/markdown/markdown.ts
> +export const isValidHTMLTag = (tag: string): boolean => HTML_TAGS_NO_ESCAPE.has(tag)
HTML tags are not case sensitive, so you should lowercase this string before searching for it. Elaborate the tests to cover this case, too.

2023-07-19 07:57 UTC, dominiccooney commented on lib/shared/src/common/markdown/markdown.ts
> +    htmlToken = htmlToken.replace(/<\/?/, '')
Let's just simplify this into one regular expression which extracts the tag name.

HTML parsing is non-trivial but something with a regex should be good enough for our purposes and can certainly handle what's happening here so far.

You should be more permissive with your tagname matching. `<p-list>` is not a paragraph tag.

2023-07-19 08:58 UTC, tobias-mayer commented on lib/shared/src/common/markdown/markdown.ts
> +export const isValidHTMLTag = (tag: string): boolean => HTML_TAGS_NO_ESCAPE.has(tag)
Thanks for noticing. Totally missed that.

2023-08-18 19:40 UTC, abeatrix reviewed
Sorry, I just found this in my inbox.  The change looks fine to me, but I wonder if everything in the new HTML_TAGS_NO_ESCAPE set is valid, so I would appreciate it if someone else on the team who is more familiar with this part of the code could take an extra look. Adding the VS Code team as a reviewer. 

@dominiccooney does the update address your initial concern?

2023-08-18 19:59 UTC, abeatrix commented on lib/shared/src/common/markdown/markdown.ts
> +const HTML_TAGS_NO_ESCAPE: Set<string> = new Set([
i'm not sure if we want to escape all of them - would this cause escape issues during display?

2023-08-23 06:44 UTC, dominiccooney reviewed
Some comments inline.

2023-08-23 06:44 UTC, dominiccooney commented on lib/shared/src/common/markdown/markdown.ts
> +const HTML_TAGS_NO_ESCAPE: Set<string> = new Set([
The tag list looks good to me.

2023-08-23 06:44 UTC, dominiccooney commented on lib/shared/src/common/markdown/markdown.ts
> +export const isValidHTMLTag = (tag: string): boolean => HTML_TAGS_NO_ESCAPE.has(tag.toLowerCase())
A few nits with the naming:

1. The case of HTML differs from `extractHtmlTagName`; let's try for consistency.
2. "Valid" is a loaded word. HTML validation isn't really a thing anymore; names you reject here are still "valid" in the sense that the HTML parser attaches some meaning to them.
3. The parameter is "tag" but it just takes the element name, maybe we can be more precise.

Can we retreat to something descriptive about the purpose? Like `shouldEscapeTagsWithElementName` or something even better?

2023-08-23 06:50 UTC, abeatrix commented on lib/shared/src/common/markdown/markdown.ts
> +const HTML_TAGS_NO_ESCAPE: Set<string> = new Set([
@dominiccooney we recently removed h tags from the allowed list in https://github.com/sourcegraph/cody/pull/742 

Not sure if this is the same list but if it is, we might want to remove the h tags and maybe small from the list?

2023-09-04 10:49 UTC, dominiccooney commented on lib/shared/src/common/markdown/markdown.ts
> +const HTML_TAGS_NO_ESCAPE: Set<string> = new Set([
@abeatrix This runs before DOMpurify. They are different lists.

If we remove h1 and friends from this list, then we will get `<h1>` appearing literally in the output, which is not what we want.

2023-09-07 11:48 UTC, tobias-mayer commented on lib/shared/src/common/markdown/markdown.ts
> +export const isValidHTMLTag = (tag: string): boolean => HTML_TAGS_NO_ESCAPE.has(tag.toLowerCase())
Thanks for the review and sorry for the late reply!
Agree with all three points and I also like `shouldEscapeTagWithElementName`.

2023-09-07 11:53 UTC, tobias-mayer commented on lib/shared/src/common/markdown/markdown.ts
> +const HTML_TAGS_NO_ESCAPE: Set<string> = new Set([
@abeatrix @dominiccooney Exactly. It's an additional step before DOMPurify. That's also why even `script` is in there. We don't want to escape them as DOMPurify will later on safely remove them.

2023-09-08 03:35 UTC, abeatrix commented on lib/shared/src/common/markdown/markdown.ts
> +const HTML_TAGS_NO_ESCAPE: Set<string> = new Set([
Thanks for clarifying @tobias-mayer @dominiccooney !

2024-02-09 01:45 UTC, closed without merging