Add `graphql/getCurrentUserCodySubscription` endpoint
sourcegraph/cody pull request #2858
Opened 2024-01-22 21:34 UTC by mkondratek

2024-01-24 18:43 UTC, mkondratek commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            currentPeriodStartAt: string
or should it be `Date`?

2024-01-24 18:43 UTC, mkondratek commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentPeriodStartAt: string
(`Date` here too?)

2024-01-24 18:51 UTC, kalanchan requested changes

2024-01-24 18:51 UTC, kalanchan commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            isPro: boolean
the `codySubscription` schema has changed a bit, `isPro` is now `pro`

https://github.com/sourcegraph/sourcegraph/blob/da169dc09733d36a917e8bf96b79618a708a926a/cmd/frontend/graphqlbackend/schema.graphql#L6388

2024-01-24 18:51 UTC, kalanchan commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentPeriodStartAt: string
yeah should be datetime

https://github.com/sourcegraph/sourcegraph/blob/da169dc09733d36a917e8bf96b79618a708a926a/cmd/frontend/graphqlbackend/schema.graphql#L6388

2024-01-24 18:51 UTC, kalanchan commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            currentPeriodStartAt: string
yup should be datetime

https://github.com/sourcegraph/sourcegraph/blob/da169dc09733d36a917e8bf96b79618a708a926a/cmd/frontend/graphqlbackend/schema.graphql#L6388

2024-01-24 18:57 UTC, mkondratek commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            isPro: boolean
you mean the field is `plan` now, right?

2024-01-24 18:58 UTC, kalanchan commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +            isPro: boolean
woops yes good catch, sorry haha!

2024-01-24 19:06 UTC, mkondratek commented on lib/shared/src/experimentation/FeatureFlagProvider.ts
> +
Note: I added these feature flags too.

2024-01-24 21:34 UTC, vdavid approved these changes
Looks pretty boilerplate-y, not much to go wrong here 👍

2024-01-25 12:51 UTC, pkukielka commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentUser: {
Can you give me some examples what could be values of those fields?

2024-01-25 14:38 UTC, mkondratek commented on agent/src/agent.ts
> +        this.registerRequest('graphql/getCurrentUserCodySubscription', async () => {
looks like a good point - @vdavid  , can you confirm?

2024-01-25 14:39 UTC, mkondratek commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentUser: {
please take a look at the related document:

https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit

2024-01-25 20:54 UTC, vdavid commented on agent/src/agent.ts
> +        this.registerRequest('graphql/getCurrentUserCodySubscription', async () => {
Errm, could you rephrase the question? I've never used either function, so not sure what it does. I suppose `registerAuthenticatedRequest` only works if the user has a valid access token with dotcom, while `registerRequest` works without it? If this is the case, then I suppose we need the authed one because anonymous users don't have subscriptions.

2024-01-26 14:47 UTC, mkondratek commented on agent/src/agent.ts
> +        this.registerRequest('graphql/getCurrentUserCodySubscription', async () => {
```
    // Alternative to `registerRequest` that awaits on authentication changes to
    // propagate before calling the method handler.
    public registerAuthenticatedRequest<M extends RequestMethodName>(
...
```

It sounds correct to use `registerAuthenticatedRequest`

2024-01-27 17:41 UTC, pkukielka commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentUser: {
I was wondering about `applyProRateLimits` because name sounds like boolean but it is a string.
And it's not mentioned in the doc.

2024-01-27 17:42 UTC, pkukielka commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentUser: {
Actually I see it's laso not in the `CURRENT_USER_CODY_SUBSCRIPTION_QUERY`

2024-01-27 17:44 UTC, mkondratek commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentUser: {
good point! it's boolean

2024-01-27 17:45 UTC, mkondratek commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    currentUser: {
there is more context there: https://github.com/sourcegraph/sourcegraph/pull/59816/files

2024-01-27 17:49 UTC, pkukielka approved these changes
LGTM

2024-01-29 15:24 UTC, merged