Autocomplete: add more stop-reason values to autocomplete responses
sourcegraph/cody pull request #2946
Opened 2024-01-30 05:45 UTC by valerybugakov

## Context

- Adds `STOP_REASON_REQUEST_ABORTED` and `STOP_REASON_REQUEST_FINISHED` to completion responses to enable better observability locally and improve our analytics events analysis capabilities.
- Adds early exit for aborted requests to ollama HTTP client.

## Test plan

CI

2024-01-30 08:29 UTC, dominiccooney requested changes
Some ideas inline.

2024-01-30 08:29 UTC, dominiccooney commented on lib/shared/src/inferenceClient/misc.ts
> +export const STOP_REASON_REQUEST_FINISHED = 'cody-request-finished'
Make this an enum with string values so you can use the enum type to refer to "a stop reason."

Also referring to a streaming chunk boundary as a *stop* is a bit surprising... is there a better name? What is "stopping" exactly at a chunk boundary?

2024-01-30 08:29 UTC, dominiccooney commented on lib/shared/src/ollama/ollama-client.ts
> +    STOP_REASON_REQUEST_ABORTED,
This sort order doesn't look right.

2024-01-30 08:29 UTC, dominiccooney commented on lib/shared/src/ollama/ollama-client.ts
> +                        yield { completion: insertText, stopReason: STOP_REASON_STREAMING_CHUNK }
I realize you're just tidying here, but is a yield a *stop*?

2024-01-30 08:29 UTC, dominiccooney commented on vscode/src/completions/client.ts
> +                log?.onComplete(completionResponse)
This seems odd... We log `onComplete`... but only on abort errors?

2024-01-30 08:29 UTC, dominiccooney commented on vscode/src/completions/client.ts
> +        let completionResponse: CompletionResponse | undefined = undefined
This would be neater if you had the CompletionResponse | undefined type only in the streaming branch. Only problem with that is the weird abort error logging in the catch clause. Can this be simplified?

2024-01-31 02:34 UTC, valerybugakov commented on lib/shared/src/inferenceClient/misc.ts
> +export const STOP_REASON_REQUEST_FINISHED = 'cody-request-finished'
> Make this an enum with string values so you can use the enum type to refer to "a stop reason."

There's a TODO above these variables, and I planned to do it in a follow-up PR with more values added to the `enum`. I migrated the existing one to the enum here https://github.com/sourcegraph/cody/pull/2946/commits/97902c4cfbeff46fbec4802f30b6e726414928d4

> Also referring to a streaming chunk boundary as a stop is a bit surprising... is there a better name?

We need to do a bigger refactor to address this. This comes from the fact the `CompletionResponse` has `stopReason` as a required property, so we use a specific value in our code to signal to the processing logic that this is a partial response. Ideally, we have `stopReason: undefined` for this case and remove the streaming chunk stop reason. Do you think it makes sense? I added a comment about that here: https://github.com/sourcegraph/cody/pull/2946/commits/59b616794dbf48d79f2711240e13d8f990298561

2024-01-31 02:35 UTC, valerybugakov commented on lib/shared/src/ollama/ollama-client.ts
> +                        yield { completion: insertText, stopReason: STOP_REASON_STREAMING_CHUNK }
Let's continue the discussion in another thread: https://github.com/sourcegraph/cody/pull/2946#discussion_r1472235755

2024-01-31 02:38 UTC, valerybugakov commented on vscode/src/completions/client.ts
> +                log?.onComplete(completionResponse)
This is the existing behavior that I did not refactor in this PR. AFAIU, we call `onComplete` here because we want to log the completion we generated before the request was aborted.

2024-01-31 02:59 UTC, valerybugakov commented on vscode/src/completions/client.ts
> +        let completionResponse: CompletionResponse | undefined = undefined
I looked into it and moved `log.onComplete` to the `finally` clause because this is what we want. In case the request was aborted but we got a completion response, we still want to have it in the Cody output channel. Added a comment about that too: https://github.com/sourcegraph/cody/pull/2946/commits/dd02323424ec8f0a2d37d2c2fadc54f2e267267b

It removes duplicate `onComplete` calls but still needs the `completionResponse` variable.

2024-01-31 05:58 UTC, dominiccooney approved these changes
Splendid.

One nit inline.

2024-01-31 05:58 UTC, dominiccooney commented on vscode/src/completions/client.ts
> +            /**
I have always associated `/**` with documentation comments (as in, class and member documentation.)

In general, `/*` is an unfriendly comment syntax to use in Type/JavaScript because `/*`-style comments don't nest, but they're convenient when hacking to comment out swathes of code. Having `/*`-style comments in the code breaks that.

So let's write less `/*` in general, and `/**` for member-level documentation if we feel we must. But not here.

2024-01-31 06:16 UTC, valerybugakov commented on vscode/src/completions/client.ts
> +            /**
I like `/**` more for its readability and automatic expansion handled by the editor when typing multiline comments, but I agree that it's associated with docs comments, so I changed it to `//` 👍

2024-01-31 06:27 UTC, merged