feat: Custom Commands in Agent
sourcegraph/cody pull request #3089
Opened 2024-02-08 21:09 UTC by abeatrix

Add Custom Commands support to Agent.
- This includes getting the commands from the `.cody/commands.json` file.
  - vs code client should migrate from using `.vscode/cody.json` to `.cody/commands.json`, will do this in follow up
- Execute a custom command in either chat mode or inline edit mode.

Current supported context options for Custom Commands in agent covered by the agent tests:
- none: exclude all context
- current directory
- open tabs
- current file
- selection

## Test plan

CI should be green with the newly added tests for Custom Commands.

2024-02-08 22:00 UTC, abeatrix commented on agent/src/index.test.ts
> +        it.skip('commands/custom, chat command, open tabs as context', async () => {
@olafurpg do you have any idea why the tests are passing locally for me but not when running in CI? 
![image](https://github.com/sourcegraph/cody/assets/68532117/80243440-e2cb-4b29-a4cf-126e08d6189e)

2024-02-09 00:11 UTC, abeatrix commented on agent/src/index.test.ts
> +              1. src/example.test.ts
Is there a way to clear current chat history before running this command?
when running with `.only` this would produce the correct answer (2 files only), but it would use all the tests that have been opened before this test was run when i remove `.only`.

2024-02-09 09:58 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'commands/custom': [{ key: string }, string | EditTask]
To simplify JSON serialization/deserialization across all clients, we avoid using union types like `string | EditTask`. While it's possible to decode this type in some languages like Kotlin, it requires custom code and is often awkward to work with. It's better to design the protocol in a way that has simple types.

2024-02-09 10:02 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'commands/custom': [{ key: string }, string | EditTask]
We can support unions of structural types

```ts
type CustomCommandResult = ChatResult | EditResult
interface ChatResult {
  kind: 'chat'
  foo: number
...
}
interface EditResult {
  kind: 'edit'
  bar: number
...
}
```

In other languages, this pattern has a natural encoding in as data classes or structs
```kotlin
data class CustomCommandResult(
  kind: String,
  foo: Int,
  bar: Int
)
```

2024-02-09 10:13 UTC, olafurpg commented on agent/src/index.test.ts
> +        it.skip('commands/custom, chat command, open tabs as context', async () => {
The tests are also passing for me locally. The CI failures are a sign that the LLM prompt is different when running in CI because there is no matching recording. If you look at the prompt in the HTTP recording file, you see there's an absolute path leaking in the prompt

![CleanShot 2024-02-09 at 11 04 29@2x](https://github.com/sourcegraph/cody/assets/1408093/a2739288-e984-459c-aca3-dd2558f5238f)

I pushed a commit to use `displayPath`, which I hope fixes the problem.

2024-02-09 10:15 UTC, olafurpg commented on agent/src/index.test.ts
> +              1. src/example.test.ts
We do a best-effort to "reset" the environment between tests to avoid this exact problem. You can see how we implement `testing/reset` here, which tries to fire VS Code events to mirror the equivalent of closing all file tabs

https://sourcegraph.com/github.com/sourcegraph/cody@0fcf8a998c1716e23622ee9e8ae3ec1522325509/-/blob/agent/src/agent.ts?L450

You might be able to fix this problem by finding where these files are "leaking" between tests, and add a `vscode.workspace.onDidCloseTextDocument` handler to remove those files from the context's internal state.

2024-02-09 10:24 UTC, olafurpg commented on agent/src/index.test.ts
> +        it.skip('commands/custom, chat command, open tabs as context', async () => {
Looks like that helped fix the issue on macOS/Linux. The Windows tests are still failing because the ordering of the context files is not deterministic. It's more tricky to spot this, I copy pasted the HTTP request body in the error message and re-printed it with indentation inside a Scala repl (any repl or notebook works fine)

<img width="841" alt="CleanShot 2024-02-09 at 11 22 43@2x" src="https://github.com/sourcegraph/cody/assets/1408093/87f30cad-939a-4564-9268-5e1a1fd6d51d">

![CleanShot 2024-02-09 at 11 23 43@2x](https://github.com/sourcegraph/cody/assets/1408093/ac7dc7d8-5e98-413f-b016-30cb4eff86c0)
![CleanShot 2024-02-09 at 11 23 17@2x](https://github.com/sourcegraph/cody/assets/1408093/9373fad6-2ba6-4684-969e-372d337ed6fd)

2024-02-09 12:01 UTC, olafurpg commented on agent/src/index.test.ts
> +        it.skip('commands/custom, chat command, open tabs as context', async () => {
Doesn't look like sorting was enough, but I think the fix for Windows is something similar. Worst case, we can disable this test on Windows

2024-02-09 12:02 UTC, olafurpg reviewed
Only blocking comment is removing the union type in the protocol. Not using "request changes" so you can merge this PR even when I'm offline

2024-02-09 14:00 UTC, abeatrix commented on agent/src/index.test.ts
> +        it.skip('commands/custom, chat command, open tabs as context', async () => {
Thank you so much for looking into this and for the debugging tips! I'll see if I can fix the windows issue first 😄

2024-02-09 18:39 UTC, abeatrix commented
@olafurpg thank you so much for the debugging tips! I was able to locate the issue and sort the context files for chat messages and that seems to fix the issue we were seeing!

2024-02-09 21:39 UTC, olafurpg requested changes
Great that you were able to fix the windows issue. I would absolutely never have been able to figure that diff out myself 😅

2024-02-09 21:39 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +export type CustomChatCommandResult = string
This needs to serialize as a JSON object to have a simple encoding in other languages.

2024-02-09 21:40 UTC, abeatrix commented on vscode/src/jsonrpc/agent-protocol.ts
> +export type CustomChatCommandResult = string
Ohhhh so it has to be interface? Will update it!

2024-02-09 21:44 UTC, olafurpg approved these changes
Stamp to unblock merge after protocol moves to interface

2024-02-12 09:46 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    result: string
One more blocking comment: using different types for the `result` property is also problematic. It's better to use unique property names for every unique type
```suggestion
    panelID: string
```

BTW, I am working on a code generation tool that automatically catches these errors and will fail CI with an error message on how to fix the problem

2024-02-12 09:48 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    result: string
I'm not sure if `panelID` is the best property name, just added a suggestion to give an example of a diff that would resolve the issue. We encode discriminated unions as flat data classes in other languages. For example:

```
data class CustomCommandResult(
    type: String,
    chatResult: String? = null,
    editResult: EditTask? = null,
)
```

2024-02-12 16:54 UTC, merged