context-ranking support
sourcegraph/cody pull request #3111
Opened 2024-02-09 21:09 UTC by hitesh-1997

## Test plan

2024-02-14 02:56 UTC, dominiccooney requested changes
We've got some copy-pasta from the local embeddings controller here. That class needs to be simplified a bunch.

Let's start by having local embeddings and the re-ranker share a process, instead of each spawning their own processes, because they're doing a similar job at a similar time. So I would:

1. Split the local embeddings controller into two parts: One part for spawning cody-engine; the other part for all the embeddings stuff.
2. Make one instance of the cody-engine. Right now it has one job, starting the engine up. But later we need to build in some reliability for crashes, etc. and this will be the natural place to do it.
3. Have the context ranker and local embeddings share the cody-engine spawner and share one process spawned by it.

2024-02-16 00:57 UTC, hitesh-1997 commented
> We've got some copy-pasta from the local embeddings controller here. That class needs to be simplified a bunch.
> 
> Let's start by having local embeddings and the re-ranker share a process, instead of each spawning their own processes, because they're doing a similar job at a similar time. So I would:
> 
> 1. Split the local embeddings controller into two parts: One part for spawning cody-engine; the other part for all the embeddings stuff.
> 2. Make one instance of the cody-engine. Right now it has one job, starting the engine up. But later we need to build in some reliability for crashes, etc. and this will be the natural place to do it.
> 3. Have the context ranker and local embeddings share the cody-engine spawner and share one process spawned by it.

Hi @dominiccooney 
Added the changes, could you please check once

2024-02-22 05:02 UTC, dominiccooney requested changes
- Major thing missing is a flag to turn this off by default.
- Needs rebasing.
- If you want to avoid getting broken by changes, adding a test is advised but up to you. Maybe you don't need one at first if your test audience is small.

Earlier today @beyang mentioned putting these files in their own directory. I think that makes sense, but we can do it later.

2024-02-22 19:38 UTC, hitesh-1997 commented on vscode/src/extension.node.ts
> +        createContextRankingController: (config: ContextRankerConfig) => createContextRankingController(context, config),
Added the changes domonic.

2024-02-23 12:39 UTC, philipp-spiess reviewed
This is some great stuff here! I left a few comments (and _a lot_ of nits which you are free to ignore). 

The only two big thing standing out that IMO should be adresed before we land this is:

- This currently requires two flags to be enabled where maybe one is enough?
- I’m unsure if we should include the `priorityContext` in the reranking for the reason I mentioned inline.

Awesome work otherwise!

2024-02-23 12:39 UTC, philipp-spiess commented on lib/shared/src/configuration.ts
> +    experimentalChatContextRanker: boolean | undefined
Might want to move this up to the other experimental flags on Line 49-52

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                                  contextRanking: this.contextRanking,
If we already pass the context reranking module through here, would we want to make it optional and remove the `testingContextRanking` instead?

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +        void this.contextRanking?.start()
Should this be gated behind `experimentalChatContextRanker` too?

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/configuration.ts
> +            getHiddenSetting('experimental.chatContextRanker', false),
Again unclear why we need to enable two flags here.

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/cody-engine.ts
> +export class CodyEngineService {
This is nice! Is there a reason for this not also being used by the bfg implementation? cc @valerybugakov

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +    // type FileURI,
```suggestion
```

leftover

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +// import { URI } from 'vscode-uri'
```suggestion
```

leftover

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +    private service: Promise<MessageHandler> | undefined
Is there a reason why this is a Promise and not the awaited value? Would prevent a micro event tick for every caller when we await it before we store it in the class properties

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +        if (this.accessToken) {
Maybe an else case with some logging so we can debug when this is not the case?

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +            logDebug('LocalEmbeddingsController', 'spawnAndBindService', 'initialized', initResult)
Maybe we can consolidate the debug logs since it's getting quite noisy in the output log. E.g. the previous log for ``overriding index library path` could be part of the results here like this:

```suggestion
            logDebug('LocalEmbeddingsController', 'spawnAndBindService', 'initialized', JSON.stringify({ initResult, indexPath })
```

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +            filePath: item.uri?.path ? path.relative(baseRepoUrl, item.uri?.path) : '',
I remember we had issues with relying on `Uri#path` before and we started to use `Uri#toString()`. Is that still the case? We might want to consider the lessons learned here right from the start. cc @dominiccooney who I remember running into this

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +        const orderedContextItems: ContextItem[] = [] // Initialize the array
```suggestion
        const orderedContextItems: ContextItem[] = []
```

nit: these type of comments are usually a distraction when the code is obvious

2024-02-23 12:39 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +                )
Maybe this should throw instead and we capture it via sentry or in the tracing APIs? Otherwise this is going to just create noise in the users console and we won't be notified about it.

2024-02-23 12:41 UTC, philipp-spiess commented on vscode/src/chat/chat-view/context.ts
> +        const rankedContext = contextRanking.rankContextItems(text, allContext)
Let's create a sub-span for this step using `wrapInActiveSpan` so we can see in our tracing data how long this takes for our users

```suggestion
        const rankedContext = wrapInActiveSpan('chat.enhancedContextRanker.reranking', () => contextRanking.rankContextItems(text, allContext))
```

2024-02-23 12:41 UTC, dominiccooney commented
@hitesh-1997 , I've approved your cody-engine PR so land that, tag it to start a release, and then update the BFG version in download-bfg.ts. After @philipp-spiess 's feedback (thanks Philipp!) you should be good to go.

2024-02-23 12:43 UTC, philipp-spiess commented on vscode/src/chat/chat-view/context.ts
> +        const editorContext = await getPriorityContext(text, editor, searchContext)
The priority context, IIRC, refers to the context that is explicitly selected in the editor and/or added via `@` mentions in the chat message. If we add it to the `allContext` array here and then re-rank, wouldn't it be possible to end up not having _any_ of the priority context items in the final context list? 

I would assume this would result in a major regression when you ask "what does this code do" and this code is never added 🤔

2024-02-23 12:44 UTC, philipp-spiess commented on vscode/src/chat/chat-view/context.ts
> +async function getEnhancedContextFromRanker({
One last nit: I think, conceptually, this does the same as the `getEnhancedContextFused` just with a different implementation of _how to fuse_. Maybe instead of forking everything we can just make the last line of the `getEnhancedContextFused` dynamic? This way, if we change something in the context sources, we don't have to update 3 places

2024-02-23 12:56 UTC, dominiccooney commented
I forgot to add: AWESOME demo in the video @hitesh-1997 . Looks amazing. I am so excited to see this working end to end. 🎉

2024-02-23 12:58 UTC, dominiccooney commented on vscode/src/chat/chat-view/context.ts
> +async function getEnhancedContextFromRanker({
Following up from earlier comments about ML prototype code: This is the kind of feedback I *do* think should be addressed. We should try to minimize the maintenance burden that the experimental code puts on the shipping product.

2024-02-23 13:00 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +        void this.contextRanking?.start()
Think it is OK as-is, the `contextRanking` will be null, right? So the call is a no-op.

2024-02-23 13:05 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +        void this.contextRanking?.start()
Ah, yes you're right but right now these use two different gates. the context ranking service is enabled if `experimentalChatContextRanker` is set: https://github.com/sourcegraph/cody/pull/3111/files/4e8e2c4beb13cf6170575aa677e90760d0973fc8#diff-13b80d92afa9fb014e0ffc69e6f1bc179bb4516b003c4916456af49d8fc22fe1R82-R84 but the gating below depends on `experimentalChatContextRanker && internalUnstable`. Should be fine if we unify the condition 👍

2024-02-23 13:06 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +        void this.contextRanking?.start()
I think it's fine if we just remove `testingContextRanking` from the `getEnhancedContext` and then check on the presence of `contextRanking`

2024-02-23 13:43 UTC, philipp-spiess commented on vscode/src/chat/chat-view/context.ts
> +        const editorContext = await getPriorityContext(text, editor, searchContext)
Ahh, gotcha, yeah this makes sense. 👍

2024-02-23 13:51 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/context.ts
> +        const editorContext = await getPriorityContext(text, editor, searchContext)
Also, just to cross check @rishabhmehrotra can provide additional inputs if adding all context source in the ranker is okay ?

2024-02-23 13:55 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                                          this.config.experimentalChatContextRanker,
@philipp-spiess I think it makes sense to just keep this.config.experimentalChatContextRanker flag. Making this change. Thanks for the input :)

2024-02-23 13:55 UTC, hitesh-1997 commented on lib/shared/src/configuration.ts
> +    experimentalChatContextRanker: boolean | undefined
done

2024-02-23 14:06 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                                          this.config.experimentalChatContextRanker,
Thanks changing to only `this.config.experimentalChatContextRanker` as per discussion

2024-02-23 14:08 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                                  contextRanking: this.contextRanking,
that makes sense, since contextRanking is initialized only if the flag is true, we can check only on `this.contextRanking` condition. let me know if sounds good.

2024-02-23 14:16 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +        void this.contextRanking?.start()
this makes sense @philipp-spiess only relying on single condition

2024-02-23 14:17 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                                  contextRanking: this.contextRanking,
Sounds great!

2024-02-23 14:22 UTC, hitesh-1997 commented on vscode/src/jsonrpc/context-ranking-protocol.ts
> +    filePath?: string
ahh, I did not notice this. I have added a todo here and i can do it later, since this would also involve chaning bfg protocol code.

2024-02-23 14:23 UTC, hitesh-1997 commented on vscode/src/local-context/cody-engine.ts
> +export class CodyEngineService {
We introduced this class in the current PR and i think others haven't adapted to this yet and I only changed the local embeddings to use this.

2024-02-23 14:26 UTC, hitesh-1997 commented on vscode/src/local-context/context-ranking.ts
> +    private service: Promise<MessageHandler> | undefined
This implementation of this is very much [similar to local embeddings](https://github.com/sourcegraph/cody/blob/main/vscode/src/local-context/local-embeddings.ts#L70) I wanted to keep it same as for this first version. Is it okay if try to improve this logic in the future iterations ?

2024-02-23 14:27 UTC, philipp-spiess commented on vscode/src/local-context/cody-engine.ts
> +export class CodyEngineService {
Oh yeah this is more of a follow-up for @valerybugakov if we can adapt BFG to use that, too! Sorry for the confusing wording.

2024-02-23 14:27 UTC, philipp-spiess commented on vscode/src/local-context/context-ranking.ts
> +    private service: Promise<MessageHandler> | undefined
Totally!

2024-02-23 14:29 UTC, hitesh-1997 commented on vscode/src/local-context/context-ranking.ts
> +        if (this.accessToken) {
done

2024-02-23 14:30 UTC, hitesh-1997 commented on vscode/src/local-context/context-ranking.ts
> +            logDebug('LocalEmbeddingsController', 'spawnAndBindService', 'initialized', initResult)
makes sense, changed

2024-02-23 14:38 UTC, hitesh-1997 commented on vscode/src/local-context/context-ranking.ts
> +            filePath: item.uri?.path ? path.relative(baseRepoUrl, item.uri?.path) : '',
Thanks for letting know. I have changed to use `fsPath` here and changed `baseRepoUrl` to `baseRepoPath`.

2024-02-23 14:39 UTC, hitesh-1997 commented on vscode/src/local-context/context-ranking.ts
> +        const orderedContextItems: ContextItem[] = [] // Initialize the array
removed the comment

2024-02-23 14:44 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/context.ts
> +        const rankedContext = contextRanking.rankContextItems(text, allContext)
nice, this would be great to have !!
Added

2024-02-23 17:17 UTC, hitesh-1997 commented
> I forgot to add: AWESOME demo in the video @hitesh-1997 . Looks amazing. I am so excited to see this working end to end. 🎉

Thanks Dominic for helping us land this !!

2024-02-23 19:27 UTC, hitesh-1997 commented
> @hitesh-1997 , I've approved your cody-engine PR so land that, tag it to start a release, and then update the BFG version in download-bfg.ts. After @philipp-spiess 's feedback (thanks Philipp!) you should be good to go.

Hi @dominiccooney and @philipp-spiess 
I have updated the [release tag](https://github.com/sourcegraph/bfg/releases/tag/v5.3.1781) and also updated the PR description to reflect the same. In addition, I did manually integration test described in the PR description on both Mac and Linux and they seem to be working fine. Although i haven't tested on windows, Local embeddings does e2e test on windows so i think it should be covered. Please let me know if I should add unit test on cody-engine or any other test to make sure new release tag is working as expected.

2024-02-23 23:14 UTC, philipp-spiess approved these changes
🚢

2024-02-23 23:31 UTC, merged