fix: truncate context files
sourcegraph/cody pull request #3118
Opened 2024-02-09 22:49 UTC by abeatrix

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1707508300392389
CLOSE https://github.com/sourcegraph/cody/issues/2636 & https://github.com/sourcegraph/cody/issues/2965

Update chat UI to provide better file size awareness and ensure that truncated context is still included in prompts without being ignored due to length limitations.

![largeAt](https://github.com/sourcegraph/cody/assets/68532117/38177388-08ec-4992-95bc-80b70a731ab3)

Changes include:
- Adding content to sorted results in the `getFileContextFiles` function that's used to display if the file exceeded token limit.
- Truncating prompt messages in the PromptBuilder class to include truncated context without all context being ignored due to excessive length.
- Use exisiting truncatePrompt function and MAX_AVAILABLE_PROMPT_LENGTH constant for truncating prompts.
- Display large file will be truncated warning in at-mentions selector

## Test plan

1. @-mentioned a large file [SimpleChatPanelProvider](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@916ef190bf286505c5dcb254b87c0ad142b86c5a/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts)

### Before

![image](https://github.com/sourcegraph/cody/assets/68532117/05123bcf-09e7-42e7-a94b-718d7e7ef866)

### After

![image](https://github.com/sourcegraph/cody/assets/68532117/7ea38043-c148-45d7-9a00-1d6aeb53f552)

https://github.com/sourcegraph/cody/assets/68532117/4f7eab15-240d-4bb3-b1b9-89e4c8c896a9

2024-02-09 23:00 UTC, abeatrix commented on vscode/webviews/UserContextSelector.tsx
> +                                    ? 'Large file will be truncated.'
```suggestion
                                    ? 'Large file will be truncated.'
```

@toolmantim feel free to update this copy

2024-02-09 23:07 UTC, abeatrix commented on vscode/webviews/UserContextSelector.tsx
> +                                    ? 'Large file will be truncated.'
Getting the file content for all search results is most likely going to cause performance issues in large repos / large files, so I'm wondering if we should just show this warning at the top instead.

2024-02-09 23:50 UTC, dominiccooney requested changes
Some ideas on making the size check scale better inline.

2024-02-09 23:50 UTC, dominiccooney commented on vscode/src/editor/utils/editor-context.ts
> +    return vscode.workspace.fs.readFile(uri).then(
You can use `vscode.workspace.fs.stat(uri)` and check `size`. Performance is O(number of files) not O(size of all the files) so it's better. Downside is it's a byte count, not a character count... I haven't looked at tokenizer rates for non-Latin character sets but I would be surprised if character count is a better factor than byte count.

2024-02-09 23:50 UTC, dominiccooney commented on vscode/webviews/UserContextSelector.tsx
> +                                    ? 'Large file will be truncated.'
The principle is: don't disappoint/frustrate the user. So we should keep them informed as early as possible. Ideally, tell them what's going on, without bogging down the machine, before they commit to an action.

I suggested stat-ing the filesystem above, which will reduce the load a bit, but stat is not free. So maybe you could just stat items in the viewport and display the labels just in time.

With the way we do context assembly (see detail in #2769) we can't predict accurately whether we'll truncate any given file. So we could inform the user before they pick an item if we're likely going to truncate it, and after the prompt is assembled, too if we did. But we have to do that informing in a way that they can understand—one problem with the first iteration of the error banner is people thought it was a rate limit, etc. We don't want to do that again.

@toolmantim do you have ideas here?

2024-02-10 00:10 UTC, abeatrix commented on vscode/src/editor/utils/editor-context.ts
> +    return vscode.workspace.fs.readFile(uri).then(
Ahh that makes sense! I've updated to use fs.state instead and that seems to work:

![image](https://github.com/sourcegraph/cody/assets/68532117/9a6404f4-8583-415e-9a23-08ab1ead8659)

Will continue next week, thank you for your the suggestion!

2024-02-12 18:29 UTC, abeatrix commented
@toolmantim updated to follow your design on figma:

![image](https://github.com/sourcegraph/cody/assets/68532117/aa830553-9c5a-47e5-8e4b-27ec3ca494d5)

2024-02-12 23:21 UTC, abeatrix commented on vscode/webviews/UserContextSelector.tsx
> +                                    ? 'Large file will be truncated.'
updated the behavior based on Tim's figma design

2024-02-13 00:16 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const MAX_RESULTS = 10
since it'd take longer to find more results, especially in large repositories, i think we should lower this number from 20 to 10 until the underlying issue is resolved (slow @-mentioned in large repositories)

2024-02-13 00:27 UTC, abeatrix commented
@dominiccooney i've updated to use `vscode.workspace.fs.stat` instead of `vscode.workspace.fs.readFile`. Can I get your review again on this change, please?

2024-02-13 04:44 UTC, beyang commented
We're approaching crunch time—WDYT if we just display a warning for now and postpone getting the truncation logic right until after launch?

2024-02-13 04:50 UTC, abeatrix commented
> We're approaching crunch time—WDYT if we just display a warning for now and postpone getting the truncation logic right until after launch?

Yea I think that'd be the best. I'll update the PR to remove the truncation logic.

2024-02-13 04:57 UTC, toolmantim approved these changes

2024-02-13 04:57 UTC, toolmantim commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const MAX_RESULTS = 10
Would be better not to degrade this for everyone just due to the symlink performance issues… but I'm not sure if there's a better solution. Maybe at least add a todo?

2024-02-13 05:00 UTC, toolmantim commented
@beyang @abeatrix I think it also makes sense to include a warning at display time if something was excluded. Here's a design for that if you think it's easier/faster: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1590-34814&mode=design&t=ZSpfaRg2b9wfCOfP-4

2024-02-13 05:02 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const MAX_RESULTS = 10
i've reverted the change so that this PR focuses on adding the warning for large @-files. once the fix for findFiles is merged, this shouldn't be an issue 👍

2024-02-13 05:25 UTC, abeatrix commented
> @beyang @abeatrix I think it also makes sense to include a warning at display time if something was excluded. Here's a design for that if you think it's easier/faster: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1590-34814&mode=design&t=ZSpfaRg2b9wfCOfP-4

@toolmantim i think that makes sense too. This is for after the release, right?
(I can try, but I'm not sure if I can get the new design in by the end of tomorrow.)

2024-02-13 14:32 UTC, umpox approved these changes
Looks good! I think we can show a similar UI in the Edit quick pick too. I left a comment [here](https://github.com/sourcegraph/cody/issues/2965#issuecomment-1941644011)

I don't think this need to be done before this release but just added so we don't forget

2024-02-13 15:17 UTC, merged