Chat: remove last assistant response to avoid consecutive messages error
sourcegraph/cody pull request #3228
Opened 2024-02-20 21:53 UTC by abeatrix

FIX: https://github.com/sourcegraph/cody/issues/3126

Update to remove consecutive assistant messages after a human message cannot be added due to context limit reach.

Currently, we will stop adding old transcript messages when the limit has been reached, which was causing `found consecutive messages with the same speaker 'assistant'` error because we are not removing the (assistant) response that is associated with the (human) message we are not adding (as we loop through them from back to front).

This PR updates to removing the last assistant message responding to the current human message when the limit has been reached, instead of keeping assistant response without adding human message. This prevents the error when adding the preamble ending in 'assistant'.

## Test plan

Keep asking Cody questions until you have reached the context limit (check output channel for something similar to `DefaultPrompter.makePrompt: Ignored 19 transcript messages due to context limit`). You should not encountered the `found consecutive messages with the same speaker 'assistant'` error.

#### After

![Screenshot 2024-02-20 at 1 35 30 PM](https://github.com/sourcegraph/cody/assets/68532117/3736fdd9-0ba2-4933-b9df-e48dacc5c897)

```
█ DefaultPrompter.makePrompt: Ignored 19 transcript messages due to context limit
█ logEvent (telemetry disabled): CodyVSCodeExtension:chat-question:executed VSCode {"properties":{"requestID":"33bda8b1-1a9a-45b3-81c3-97d59973c294","chatModel":"anthropic/claude-2.0","traceId":"c165b0facf0167c1398dc34f2ec413b0","contextSummary":{}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.chat-question/executed: {"parameters":{"version":0,"metadata":[{"key":"recordsPrivateMetadataTranscript","value":1}],"privateMetadata":{"properties":{"requestID":"33bda8b1-1a9a-45b3-81c3-97d59973c294","chatModel":"anthropic/claude-2.0","traceId":"c165b0facf0167c1398dc34f2ec413b0","contextSummary":{}},"promptText":"hey"}},"timestamp":"2024-02-20T21:51:45.960Z"}
█ CompletionLogger:onComplete: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/stream","status":"success","duration":9126}  {
  "result": " Hello!",
  "params": {
    "temperature": 0.2,
    "maxTokensToSample": 1000,
    "topK": -1,
    "topP": -1,
    "model": "anthropic/claude-2.0",
    "messages": [
      {
        "speaker": "human",
        "text": "You are Cody, an AI coding assistant from Sourcegraph."
      },
      {
        "speaker": "assistant",
        "text": "I am Cody, an AI coding assistant from Sourcegraph."
      },
      {
        "speaker": "human",
        "text": "\nReview and analyze this terminal output from the `node` process and summarize the key information. If this indicates an error, provide step-by-step instructions on how I can resolve this:\n\n```\n\n*  Executing task: pnpm --silent run build:dev:desktop \n\n[1] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n[0] All wasm modules are in place, have a good day!\n[0] \n[0]   dist/extension.node.js      10.7mb ⚠️\n[0]   dist/extension.node.js.map  18.9mb\n[0] \n[0] ⚡ Done in 368ms\n[0] pnpm run -s _build:esbuild:desktop --alias:@sourcegraph/cody-shared=@sourcegraph/cody-shared/src/index --alias:@sourcegraph/cody-shared/src=@sourcegraph/cody-shared/src --alias:@sourcegraph/cody-ui=@sourcegraph/cody-ui/src/index --alias:@sourcegraph/cody-ui/src=@sourcegraph/cody-ui/src exited with code 0\n[1] pnpm run -s _build:webviews --mode development exited with code 0\n *  Terminal will be reused by tasks, press any key to close it. \n\n *  Executing task: pnpm --silent run build:dev:desktop \n\n[1] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n[0] All wasm modules are in place, have a good day!\n[0] \n[0]   dist/extension.node.js      10.7mb ⚠️\n[0]   dist/extension.node.js.map  18.9mb\n[0] \n[0] ⚡ Done in 349ms\n[0] pnpm run -s _build:esbuild:desktop --alias:@sourcegraph/cody-shared=@sourcegraph/cody-shared/src/index --alias:@sourcegraph/cody-shared/src=@sourcegraph/cody-shared/src --alias:@sourcegraph/cody-ui=@sourcegraph/cody-ui/src/index --alias:@sourcegraph/cody-ui/src=@sourcegraph/cody-ui/src exited with code 0\n[1] pnpm run -s _build:webviews --mode development exited with code 0\n *  Terminal will be reused by tasks, press any key to close it. \n\n *  Executing task: pnpm --silent run build:dev:desktop \n\n[1] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n[0] All wasm modules are in place, have a good day!\n[0] \n[0]   dist/extension.node.js      10.7mb ⚠️\n[0]   dist/extension.node.js.map  18.9mb\n[0] \n[0] ⚡ Done in 405ms\n[0] pnpm run -s _build:esbuild:desktop --alias:@sourcegraph/cody-shared=@sourcegraph/cody-shared/src/index --alias:@sourcegraph/cody-shared/src=@sourcegraph/cody-shared/src --alias:@sourcegraph/cody-ui=@sourcegraph/cody-ui/src/index --alias:@sourcegraph/cody-ui/src=@sourcegraph/cody-ui/src exited with code 0\n[1] pnpm run -s _build:webviews --mode development exited with code 0\n *  Terminal will be reused by tasks, press any key to close it. \n\n *  Executing task: pnpm --silent run build:dev:desktop \n\n[1] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n[0] All wasm modules are in place, have a good day!\n[0] \n[0]   dist/extension.node.js      10.7mb ⚠️\n[0]   dist/extension.node.js.map  18.9mb\n[0] \n[0] ⚡ Done in 337ms\n[0] pnpm run -s _build:esbuild:desktop --alias:@sourcegraph/cody-shared=@sourcegraph/cody-shared/src/index --alias:@sourcegraph/cody-shared/src=@sourcegraph/cody-shared/src --alias:@sourcegraph/cody-ui=@sourcegraph/cody-ui/src/index --alias:@sourcegraph/cody-ui/src=@sourcegraph/cody-ui/src exited with code 0\n[1] pnpm run -s _build:webviews --mode development exited with code 0\n *  Terminal will be reused by tasks, press any key to close it. \n\n *  Executing task: pnpm --silent run build:dev:desktop \n\n[1] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n[0] All wasm modules are in place, have a good day!\n[0] \n[0]   dist/extension.node.js      10.7mb ⚠️\n[0]   dist/extension.node.js.map  18.9mb\n[0] \n[0] ⚡ Done in 426ms\n[0] pnpm run -s _build:esbuild:desktop --alias:@sourcegraph/cody-shared=@sourcegraph/cody-shared/src/index --alias:@sourcegraph/cody-shared/src=@sourcegraph/cody-shared/src --alias:@sourcegraph/cody-ui=@sourcegraph/cody-ui/src/index --alias:@sourcegraph/cody-ui/src=@sourcegraph/cody-ui/src exited with code 0\n[1] pnpm run -s _build:webviews --mode development exited with code 0\n *  Terminal will be reused by tasks, press any key to close it. \n\n *  Executing task: pnpm --silent run build:dev:desktop \n\n[1] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n[0] All wasm modules are in place, have a good day!\n[0] \n[0]   dist/extension.node.js      10.7mb ⚠️\n[0]   dist/extension.node.js.map  18.9mb\n[0] \n[0] ⚡ Done in 376ms\n[0] pnpm run -s _build:esbuild:desktop --alias:@sourcegraph/cody-shared=@sourcegraph/cody-shared/src/index --alias:@sourcegraph/cody-shared/src=@sourcegraph/cody-shared/src --alias:@sourcegraph/cody-ui=@sourcegraph/cody-ui/src/index --alias:@sourcegraph/cody-ui/src=@sourcegraph/cody-ui/src exited with code 0\n[1] pnpm run -s _build:webviews --mode development exited with code 0\n *  Terminal will be reused by tasks, press any key to close it.\n\n```\n\nProcess options: {\"name\":\"Build VS Code Extension (Desktop)\",\"shellPath\":\"/bin/zsh\",\"shellArgs\":[\"-l\",\"-c\",\"pnpm --silent run build:dev:desktop\"],\"cwd\":{\"$mid [...]

2024-02-20 22:28 UTC, beyang requested changes
Does this fix the underlying error? This seems like it would mask an error that happens earlier?

2024-02-20 23:00 UTC, abeatrix commented
> This seems like it would mask an error that happens earlier?

I don't think this is correct because we are handling the transcript in reverse, so we are currently adding the assistant response before we add the human question, which is causing the issue we are seeing because when the limit has been reached, and we skip adding the human question, the assistant response has already been added, which was causing the error message `found consecutive messages with the same speaker 'assistant'` to show up when we submit the `truncated` transcripts.

2024-02-23 17:19 UTC, beyang commented on vscode/src/prompt-builder/index.ts
> +     */
Why not just remove? It's unused.

2024-02-23 17:19 UTC, beyang approved these changes

2024-02-23 17:41 UTC, abeatrix commented on vscode/src/prompt-builder/index.ts
> +     */
Removed. I wasn't sure if it would affect other clients. Thanks!

2024-02-23 17:48 UTC, merged