Properly handle one or more ndjson records coming from Ollama
sourcegraph/cody pull request #3481
Opened 2024-03-20 17:51 UTC by peebles

## Test plan

The bug was verified using an isolated version of lib/shared/src/ollama/chat-client.ts running against a fast, local ollama server.  The changes were made and verified against same ollama server.

2024-03-21 05:24 UTC, dominiccooney requested changes
Looks good, one suggestion inline. Triggered CI for you.

It would be great if you could add some detail to your test plan to break it down step-by-step for someone to reproduce, or add a unit test.

2024-03-21 05:24 UTC, dominiccooney commented on lib/shared/src/ollama/chat-client.ts
> +                }
Cool but we can do this more succinctly, something like:

```suggestion
            // handle one or more ndjson records
            const parsedLines = decoded.split('\n').map(JSON.parse) as OllamaGenerateResponse[]
            for (const parsedLine of parsedLines) {
                if (parsedLine.message) {
                    insertText += parsedLine.message.content
                    cb.onChange(insertText)
                }
```

2024-03-21 21:38 UTC, peebles commented
I went back to my original way of breaking records.  Splitting on \n did not work in all cases, while /.+/ does work on all cases.
I also added a unit test to try all the important cases.

2024-03-26 19:00 UTC, peebles commented
Is there anything I need to do?

2024-06-07 01:50 UTC, closed without merging