Chat: sync token limit at model import time
sourcegraph/cody pull request #3486
Opened 2024-03-20 23:26 UTC by abeatrix

Building block for https://github.com/sourcegraph/cody/issues/3455

Previously, we had to check the `authStatus` and `config` every time we wanted to get the token limit for a model. This approach was inefficient as it required the caller to have access to authProvider and check the same config repeatedly.

With this change, we sync the token limit along with the model when we import models By including the `contextWindow` property in the model definitions, we can easily access the token limit for each model anywhere without the need for repeating the same checks we did when we import the model.

This approach eliminates the need for scattered token limit checks throughout the codebase, making the code more maintainable and accessible. It centralizes the token limit configuration within the model definitions, making it easier to understand and modify.

## Test plan

Check token limit

2024-03-21 04:53 UTC, dominiccooney requested changes
Thanks for working on this! Some suggestions for naming to help people catch mixing up byte/character and token counts.

2024-03-21 04:53 UTC, dominiccooney commented on agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ModelProvider.kt
> +  val contextWindow: Int? = null,
Put the (approximate) units in this name. You intend this as a character count or byte count, not a token count, but if people mix them up the type system won't save you!

Let's name it so reviewers can at least spot problems.

```suggestion
  val contextWindowSizeChars: Int? = null,
```

2024-03-21 04:53 UTC, dominiccooney commented on lib/shared/src/models/dotcom.ts
> +export const DEFAULT_CHAT_MODEL_TOKEN_LIMIT = 28000 // 7000 tokens * 4 bytes per token
Same feedback here, this naming is confusing. You say TOKEN but it is really a BYTE limit.

2024-03-21 04:53 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +        this.contextWindow = tokenLimit ? tokenLimit * 4 : DEFAULT_FAST_MODEL_TOKEN_LIMIT
It would be great to put `tokenLimit * 4` inside a function, say `tokenCountToByteCount(tokenLimit)`, so that when we make this accurate we don't have to hunt the codebase for the digit "4" and can instead find uses of that function.

2024-03-21 04:53 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +    public static getContextWindow(modelID: string): number {
Same naming feedback: Specify that this is a byte count in the name, don't leave people to guess.

2024-03-22 05:48 UTC, dominiccooney requested changes
Thanks for making it clear about tokens vs chars.

We can simplify this more. See how `ModelProvider.get` has a side effect, overwriting the primary models if the user is a dotcom user? It is surprising to have "get" change state. See *how many* auth status listeners push auth status to the model provider? That's too much. That can be simplified:

- Make a class for holding all the models.
- Move the statics from ModelProvider, so they become *instance* properties of the new class.
- Create an instance of the class when the extension starts.
- Subscribe this new instance to auth status changes.
- Do the dotcom handling along with the rest of the auth status change handling.
- You don't need to call setModelProvider from all the other places auth status changes.

Ideally, pass the instance of the new class to every place that needs models. But if that is too hard in one patch, you can make one static method to hang onto the single instance of it and we will clean it up later.

2024-03-22 05:48 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +        // NOTE: private instances can only support 1 provider atm
This method, "add", is mis-named. Let's call it `overrideModelList` or something like that, that is what it is really doing. Having a list of 3 models, calling "add", and getting a list of one model out is surprising.

2024-03-22 05:48 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +import { setModelProviders } from '../../models/utilts'
Let's rename that file "utils" for consistency with other similar files elsewhere.

2024-03-22 06:57 UTC, abeatrix commented on lib/shared/src/models/index.ts
> +        // NOTE: private instances can only support 1 provider atm
True! I've renamed this to `setProviders` instead.

2024-03-22 09:45 UTC, dominiccooney approved these changes
Very nice. Some more feedback inline I leave up to your judgement.

2024-03-22 09:45 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +        const models = ModelProvider.primaryProviders
This primary providers/ollama providers concatenation is duplicated on line 85.

Let's de-dup by adding a getter which does the concatenation and call it in both places.

2024-03-22 09:45 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +    // TODO (bee) watch file change to determine if a new model is added
There's no file to watch?

2024-03-22 09:45 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +    if (process.env.CODY_SHIM_TESTING === 'true') {
Why not? Wouldn't the network replay be able to capture and replay the connection errors, etc.?

2024-03-22 09:45 UTC, dominiccooney commented on vscode/src/chat/chat-view/ChatManager.ts
> +        setModelProviders(authStatus)
I guess one place is better than N places... Because the models are static, I think we should wire up setting the model providers to auth status at the top level. For example, say we make ChatManager lazier but still query models for edits, then we have a bug.

Having less global state, and giving the model provider object responsibility for keeping itself up-to-date instead of free-riding on nearby objects, will make it easier to keep evolving this code.

2024-03-22 14:46 UTC, abeatrix commented on lib/shared/src/models/index.ts
> +    // TODO (bee) watch file change to determine if a new model is added
I was thinking we can watch for changes in `~/. ollama/models/manifests/registry.ollama.ai/library` where the ollama models are stored.

2024-03-22 17:18 UTC, abeatrix commented on lib/shared/src/models/index.ts
> +    if (process.env.CODY_SHIM_TESTING === 'true') {
Removed!

2024-03-22 18:21 UTC, merged