Add chatExport endpoint & tests
sourcegraph/cody pull request #3487
Opened 2024-03-20 23:41 UTC by mkondratek

2024-03-20 23:42 UTC, mkondratek commented on agent/src/agent.ts
> +            return panel.chatHistory || {} // todo: proper handling
- [ ] TODO

2024-03-20 23:43 UTC, mkondratek commented on agent/src/index.test.ts
> +            const NUMBER_OF_CHATS_TO_RESTORE = 3
🟢 I tried with 300 - works - I did not notice any time difference.

🟡 I tried with 3000 - fails:
```
Error: Test timed out in 30000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
    at Timeout.<anonymous> (file:///Users/mkondratek/IdeaProjects/cody/node_modules/.pnpm/@vitest+runner@1.2.0/node_modules/@vitest/runner/dist/index.js:63:16)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
```

2024-03-21 05:13 UTC, dominiccooney requested changes
We should do this differently, for these reasons:

The Agent API for chat/export seems odd. It takes a panel ID, but returns all the local history. So is the intent here to export one chat (why return all the history?) or all the chats (why do you need a panel ID?)

I see the history, action = export web view message exists, but it seems to be no longer used. saveSession is called in a few places (initialization, restarting chats, submitting messages) so it doesn't fill me with confidence that the chat/export and history messages won't get crossed. And it seems odd that chat/export has a side effect of saving.

Can you clarify what the API for chat/export is intended to do? Then let's look at how we can add methods to the extension objects so that Agent can get the behavior it needs without having to hook WebView messages.

2024-03-21 05:13 UTC, dominiccooney commented on agent/src/index.test.ts
> +            // Step 4: delete the chat that corresponds to `exportHistoryChatId` as its id cannot be predicted or mocked
This is OK but would it be simple to load the object at `historyPath` and inject a clone of the new chat into it and match on that?

2024-03-21 05:13 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            case 'history':
This is interesting... so we used to have a history WebView -> extension message, it is unused, but you're adding it back?

2024-03-21 10:17 UTC, mkondratek commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            case 'history':
Oh, I did not realised due to two renames in the past:
`ChatViewProvider` ➡️  `SidebarChatProvider` ➡️ `SimpleChatPanelProvider` 

You are probably right - I am adding it back (I am not sure if it's wrong 😅 )

2024-03-21 10:17 UTC, mkondratek commented on agent/src/index.test.ts
> +            // Step 4: delete the chat that corresponds to `exportHistoryChatId` as its id cannot be predicted or mocked
test simplified

2024-03-21 10:18 UTC, mkondratek commented on agent/src/index.test.ts
> +            const reply1 = asTranscriptMessage(
fixed, thanks

2024-03-21 10:18 UTC, mkondratek commented on agent/src/index.test.ts
> +            if (key) delete chatHistory[key]
test simplified

2024-03-21 10:19 UTC, mkondratek commented on agent/src/agent.ts
> +            return panel.chatHistory || {} // todo: proper handling
I left that todo just to rethink it next day 😄 seeing it now - an empty chat history seems to be a valid case so it's ok

2024-03-21 11:26 UTC, pkukielka approved these changes
LGTM

2024-03-21 11:28 UTC, mkondratek commented
hello @dominiccooney 👋 thank you for your review! I do not feel very confident in this area so I really appreciate your input 

I agree with your points - I got some sleep, took a look at your comments, and managed to improve my solution.

Please, revisit my PR, close comments that you consider as fixed now, suggest me whatever you think makes more sense 🙏

2024-03-22 17:03 UTC, dominiccooney approved these changes
Fantastic, this is nice and clean.

2024-03-28 13:27 UTC, merged