Feature Flag: Hover Commands
sourcegraph/cody pull request #3585
Opened 2024-03-27 20:02 UTC by abeatrix

![hovercommanddoc](https://github.com/sourcegraph/cody/assets/68532117/d1fad011-5c0b-49c8-9824-8ad5b1b43fc7)

This PR adds a new feature to display Cody commands in a pop-up window on hover for the [Hover Commands](https://docs.google.com/document/d/1G5koKO6MoZflObkkcsjcYfexfSY8fWC50BoT4k-BmZU/edit?usp=sharing) A/B test.

The feature is currently controlled by a new feature flag, `cody-hover-commands` on DotCom; however, users with the feature flag enabled can turn off this feature via VS Code configuration with: 
```
"cody.experimental.hoverCommands": false,
```

NOTE: Configuring this setting alone will not enable the feature as it depends on the feature flag.

![image](https://github.com/sourcegraph/cody/assets/68532117/229a932f-884b-42b4-91d6-236faf8a376c)

![image](https://github.com/sourcegraph/cody/assets/68532117/9047c890-b1bd-4d29-9d5a-41297ddec077)

New events: 
- CodyVSCodeExtension:hoverCommands:visible
  - When a hover command is visible
- CodyVSCodeExtension:hoverCommands:clicked
  - When a hover command is clicked
- All commands invoked by clicking on the hover commands will have event source set to `hover`.

## Test plan

1. Connect to DotCom
2. Enable the 'cody-hover-commands' feature flag for your user account
3. Reload VS Code
4. In Cody, open a file and hover over some code to see the Cody Commands showing up in the pop-up

## Expected Behavior

- When hovers over a symbol, the Explain command will show up.
- When hovers over a symbol that has an empty space above, the Document command will show up.
  - ![image](https://github.com/sourcegraph/cody/assets/68532117/3098972a-c189-443f-91ea-af4bbcf4c3a9)
- When hovers over a highlighted block of code, the Chat command will show up.
- When hovers over a highlighted block of code with multiple lines, the Edit command will show up.
  - ![image](https://github.com/sourcegraph/cody/assets/68532117/5493c603-8419-4cbf-b7a2-10c79cbad26f)

2024-03-28 11:09 UTC, umpox requested changes
This is an awesome idea, and I totally agree that there's a lot of value to be unlocked by catering for mouse-only users.

I have left some comments, I think as this is a really high-visibility change we should be super careful to nail the UX so it's not annoying for users.

WDYT about starting v1 of the experiment for just "Document" and then we can add enhancements onto it? I think we'll need a couple of tree-sitter changes to support some of the other cases without it possibly being annoying for users (e.g. explain)

Excited to see where this goes and happy to pair on this to help!

2024-03-28 11:09 UTC, umpox commented on vscode/src/commands/HoverCommandsProvider.ts
> +            vscode.languages.registerHoverProvider('*', { provideHover: this.onHover.bind(this) }),
We should only register this for files otherwise it may show in weird places (e.g. the commit message )

<img width="169" alt="image" src="https://github.com/sourcegraph/cody/assets/9516420/c8d93397-9d63-4f6e-96d1-29182b9a91f5">


```suggestion
            vscode.languages.registerHoverProvider({ scheme: 'file' }, { provideHover: this.onHover.bind(this) }),
```

2024-03-28 13:15 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        commandsOnHovers.doc.enabled = !document.lineAt(symbol.startPosition.row - 1)?.text.trim()
Haha yea 100%! I was going to add the comments detection bit but decided to do that in a follow-up since we want to make the same changes for the actual doc command. Thanks for creating the issue so we won't forget!

2024-03-28 13:17 UTC, abeatrix commented on vscode/src/main.ts
> +    }
Ah good catch! I'll update to remove this await!

2024-03-28 16:18 UTC, chenkc805 commented on vscode/src/commands/HoverCommandsProvider.ts
> +        commandsOnHovers.edit.enabled = true
+1 we chatted about this live. Making this more aggressive helps test the discoverability hypothesis, so I'm supportive of it. 

For power users, let's include a checkbox in the user settings where users can turn this off if they want.

2024-03-28 16:24 UTC, umpox commented on vscode/src/commands/HoverCommandsProvider.ts
> +        commandsOnHovers.edit.enabled = true
@chenkc805 We chatted about this with @chillatom too. We agreed to show this where there are _existing_ hovers for now, rather than add lots of new ones from Cody. This will still be aggressive and get loads of visibility, but has less chance of being annoying to users. We can look at the idea of showing them everywhere as a follow up

2024-03-28 16:54 UTC, PriNova commented
When hovering over multiple lines and choosing 'New Chat' will these lines 

1. be included in the Chat window as an @-mention context?
2. if a chat window already has focus included as @-mention context?

One potential downside could be, that users use the web version of VSCode (and it is a not-PWA) that hovering will mostly not work.

2024-03-28 17:35 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +    }
I don't think that's possible as the hover provider is shared with other extensions, so we can only not show something but we won't be able to close it automatically afaik

2024-03-28 17:37 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +            vscode.languages.registerHoverProvider('*', { provideHover: this.onHover.bind(this) }),
Good catch!!

2024-03-28 17:50 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +            vscode.languages.registerHoverProvider('*', { provideHover: this.onHover.bind(this) }),
@umpox i wasn't able to reproduce this actually, do you have a reproduce steps I can follow?

The hover provider only works inside an editor so i'm wondering if the one from your screenshot is some bug on the VS Code side 🤔

2024-03-28 17:55 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +const throttledHover = throttle((document: vscode.TextDocument, position: vscode.Position) => {
good point! Removed!

2024-03-28 20:32 UTC, toolmantim commented
I’d love a chance to properly review this.

At a glance from the description, don’t experimental settings get filtered out by the production build? (so there’d be no visible way for users to disable this in settings if they didn’t like it)

2024-03-28 20:38 UTC, abeatrix commented
> I’d love a chance to properly review this.
> 
> At a glance from the description, don’t experimental settings get filtered out by the production build? (so there’d be no visible way for users to disable this in settings if they didn’t like it)

The setting is undocumented so they can still set it in their User settings JSON file to disable it. I've tested and confirmed that'd work 👍 

After discussing with @umpox @chenkc805 @chillatom , we have agreed to show the commands on existing hovers so that it'd be less likely for users to find it distractive.

2024-03-28 20:41 UTC, toolmantim commented
Users should be able to see it in settings so they can disable it if they wish. Can we make sure they have a visible way to disable (in user settings)?

I’d still like a chance to review this please!

2024-03-28 21:13 UTC, toolmantim commented
(Given its feature flagged, can review on main before a user rollout too)

2024-03-28 21:15 UTC, umpox commented
@toolmantim @abeatrix Let’s catch up next week and discuss, I think we’re getting to a good place but would be good to get your eyes from a design POV. We can discuss how this can work alongside the ghost text too

2024-03-28 21:52 UTC, abeatrix commented
@toolmantim @umpox @chenkc805 Yea i'll also start a thread on Slack so we can do this async since i'm not sure if we can find a time that would work for everyone. I'll make sure not to enable the feature flag for users until then.

In the meantime, we can still roll this out to main so that we can test this internally (I've enabled this feature flag for all Sourcegraph teammates).
 
@umpox At least for phase 1 (v1), IMO this experiment should be treated independently from ghost text, as any additional changes to existing features would add new variables to the outcome, and the main goal of this experiment is to see how users behave with mouse v.s. keyboard shortcuts. We should then use the data we get back from phase 1 to make further improvements and adjustments to the experiment and features accordingly if that makes sense.
I just added a new `Phases` section to the doc so we can discuss further there if anyone disagrees 😃

2024-03-29 00:51 UTC, abeatrix commented
@umpox ive updated the behavior to match what we discussed earlier:
- display doc and explain commands on top level symbols on hover (matches ghost text)
- display chat and edit commands on the rest of document symbols on hover
- display chat and edit commands on any of the highlighted code

On telemetry side:
- log enrollment event for first hover event

Let me know if I missed anything 😃

2024-03-29 01:03 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        commandsOnHovers.chat.enabled = false
Yea let's pair on this and use that for commands! for v1 i will just use what we have for Doc command with the explain command

2024-03-29 04:45 UTC, abeatrix commented
@toolmantim added status bar toggle
<img width="901" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/ef553c10-aa31-4cd8-87d4-82f5706a6f91">

2024-04-02 03:16 UTC, toolmantim commented
Similarly to how Opt-k works now, can we make sure not to mess with people's selections when they run Edit Code or New Chat? Currently it changes your selection, and doesn't restore when you hit escape, whereas Opt-K doesn't seem to change it.

https://github.com/sourcegraph/cody/assets/153/e322fc2f-f264-48da-bed4-0fa443f20999

2024-04-02 03:42 UTC, abeatrix commented
> Similarly to how Opt-k works now, can we make sure not to mess with people's selections when they run Edit Code or New Chat? Currently it changes your selection, and doesn't restore when you hit escape, whereas Opt-K doesn't seem to change it.
> 
>  CleanShot.2024-04-02.at.14.13.53.mp4

@toolmantim updated.

2024-04-02 07:58 UTC, umpox commented
Can we include "New Chat | Edit Code" on all hovers, I think this makes sense given these actions are always available, whereas documentation and explain is dependent on the active symbol. I immediately noticed that I went to edit a function but this action wasn't available

<img width="488" alt="image" src="https://github.com/sourcegraph/cody/assets/9516420/9d1dfead-72eb-4fb4-a730-7edd36bfac86">

There seems to be a bug with "Edit code". I think we may need a wrapper command here that calls `executeEdit` with something like:
```
range: new vscode.Range(hoverPosition.start, hoverPosition.start)
```

https://github.com/sourcegraph/cody/assets/9516420/05a5fc8c-da52-4cfb-a966-76357d697eca

2024-04-02 10:01 UTC, umpox reviewed
Feels good! Left some comments I think we should address

2024-04-02 10:09 UTC, umpox commented on vscode/src/commands/HoverCommandsProvider.ts
> +        }
My understanding is that this means we only update the `symbolStore` when the active document changes, not after the user has edited the text in the file.

Did we observe a noticeable performance hit when updating on text changes? It could be worth seeing has VS Code handles this to make sure we can do this for new code.

My concern is that we wouldn't be showing correct hovers on any _new_ code that is being added to a document, which may be a poor UX even for the experiment.

2024-04-02 11:35 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +            vscode.languages.registerHoverProvider('*', { provideHover: this.onHover.bind(this) }),
Thanks! Are the cody commands showing up on the top of the hover window for you after this change?

2024-04-02 11:36 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        // Show Socument and Explain commands on documentable nodes
🥴

2024-04-02 12:09 UTC, toolmantim commented on vscode/src/commands/HoverCommandsProvider.ts
> +        }
Can we make "New Chat" start a new chat with the message input containing the line range? e.g. "@some-file.ts:42-43" if you clicked "New Chat" from a const statement on line 42

2024-04-02 12:11 UTC, toolmantim commented on vscode/src/commands/HoverCommandsProvider.ts
> +        } else {
Yeah 100% agree — here's my suggestion: https://github.com/sourcegraph/cody/pull/3585#discussion_r1547744298

I don't think we should add just a generic command though that just opens a blank chat. These hover cards should be for operating on the thing you're hovering over… not just shortcuts for global commands.

2024-04-02 15:46 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        } else {
Updated so that all the new chat created will include the information from the hover symbols.

2024-04-02 15:46 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        editor.selection = new vscode.Selection(this.currentPosition, this.currentPosition)
done

2024-04-02 15:51 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        }
I won't be able to get it to work in v1, but i added a workaround for now where we just start a new chat and say `I have a question about @file` so that users can just ask questions after that.

2024-04-02 15:53 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +        }
> Hmm, I don't think symbol store is adding anything here.
yea i removed it and just going to call it on ever hover

2024-04-02 16:01 UTC, abeatrix commented on vscode/src/commands/HoverCommandsProvider.ts
> +            vscode.languages.registerHoverProvider('*', { provideHover: this.onHover.bind(this) }),
With this change, the commands are showing up at the top of the hover instead of the bottom:

![image](https://github.com/sourcegraph/cody/assets/68532117/d7ec582e-4c32-43b7-bf5a-0e5c895b75d2)

Updated to move the filtering to the `onHover` method

2024-04-03 08:20 UTC, umpox commented on vscode/src/commands/HoverCommandsProvider.ts
> +    },
@abeatrix This is pretty last minute, can we exclude this from this change as it'll likely interfere with the experiment?

We'd need to discuss if we should remove "Ask Cody to Explain" in this case, that's likely a separate A/B test that we'd run beyond the hover command hints

2024-04-03 08:47 UTC, umpox commented on vscode/src/commands/execute/doc.ts
> +        }
```suggestion
        const { range, insertionPoint } = getDocumentableRange(editor)
```

Is this required? We should only use `getDocumentableRange` if possible. This will break for Python functions where we need to determine the insertion point depending on the syntax


https://github.com/sourcegraph/cody/assets/9516420/b65cd24e-8a36-41ef-9c1c-249408ff0cfb

2024-04-03 09:10 UTC, umpox commented
Just re-adding my comment from above:

Can we include "New Chat | Edit Code" on all hovers, I think this makes sense given these actions are always available, whereas documentation and explain is dependent on the active symbol. I immediately noticed that I went to edit a function but this action wasn't available

<img width="488" alt="image" src="https://github.com/sourcegraph/cody/assets/9516420/9d1dfead-72eb-4fb4-a730-7edd36bfac86">

cc @toolmantim for thoughts here

2024-04-03 13:26 UTC, abeatrix commented on vscode/src/commands/execute/doc.ts
> +        }
Yea good point! I've updated it to create a new editor with the document URL from args and let `getDocumentableRange` determine the correct range and insertionPoint

2024-04-03 14:00 UTC, abeatrix commented
> I think this makes sense given these actions are always available, whereas documentation and explain is dependent on the active symbol. I immediately noticed that I went to edit a function but this action wasn't available

I personally would find that helpful but I believe they want us to be less aggressive/spammy for the first round which is understandable 😆 I think we should add `Edit Code` for all nodes with show hint tho:
![image](https://github.com/sourcegraph/cody/assets/68532117/1eec3907-81e4-46e5-8992-d98555f7b982)
Skipping New Chat since it's basically doing the same thing as Explain?

2024-04-03 15:21 UTC, umpox commented
🚀

2024-04-03 15:32 UTC, abeatrix commented
@umpox thank you for sharing your feedback and for your through review as well <3

2024-04-03 15:32 UTC, merged