Add very basic proxy support for agent
sourcegraph/cody pull request #3695
Opened 2024-04-04 16:32 UTC by pkukielka

## Test plan

1. Install [squidman](https://squidman.net/squidman/) - you can leave all default options. It will give you a local proxy server.
2. Set `http_proxy` and `https_proxy` variables:

```
export https_proxy=http://127.0.0.1:8080
export https_proxy=http://127.0.0.1:8080
```

Both point to the same http squid endpoint which handles both https and https, that is not a mistake.

3. Use that cody version with either [jetbrains plugin](https://github.com/sourcegraph/jetbrains/blob/main/CONTRIBUTING.md) or with [agent tests](https://github.com/sourcegraph/cody/blob/main/agent/src/index.test.ts).
If everything is working properly either should cause new entries appearing in squid access log:
/Users/USERNAME/Library/Logs/squid/squid-access.log
----

**TBD**
1. Make sure my changes does not break normal VSC, and if they does add branched logic for agent
2. Test with better proxy (e.g. with user login/pass and with ports 80 and  443 completely blocked [1])
3. add some automatic tests with proxy in the CI
4. ???
----

[1] I was trying to do that using firewall but I failed, pf was not respecting my `pass` squid rule:

```
# 1. Install squidman: brew install --cask squidman
# 2. Setup squidman to work on 8080 HTTP port
# 3. Apply this firewall config: sudo pfctl -e -f proxy_firewall.conf
# 4. To disable it: sudo pfctl -d

# Set the interface to be used
if="en0"

# Default Deny Policy
pass out quick inet proto tcp from any to any port { 8080, 3128 }
block out quick inet proto tcp from any to any port { 80, 443 }

# Skip the loop back interface
# set skip on lo

# Set http proxy (8080) port
# web_ports = "{8080}"
```

2024-04-04 16:56 UTC, aramaraju commented
Basic user authentication can be tested by following instructions [here](https://wiki.squid-cache.org/Features/Authentication)

2024-04-04 17:18 UTC, chwarwick reviewed
Just a warning that this fetch is not exclusively used, there is some usage of native fetch, axios, and https.request so this may only cover some requests.

2024-04-04 17:18 UTC, chwarwick commented on vscode/src/fetch.node.ts
> +        return new HttpsProxyAgent(process.env.https_proxy ?? "")
Won't this now create a new https.Agent instead of reusing the configured agent that should already have a connection from the keepalive?

2024-04-04 17:18 UTC, chwarwick commented on vscode/src/fetch.node.ts
> +        // For some reason adding 'keep-alive' in the constructor was causing proxy to not be picked up.
I believe the keepalive was added as large a performance improvement based on the number of requests that are generated by autocomplete

2024-04-04 23:14 UTC, dominiccooney requested changes

2024-04-04 23:14 UTC, dominiccooney commented on vscode/src/fetch.node.ts
> +        // For some reason adding 'keep-alive' in the constructor was causing proxy to not be picked up.
Yes, we should continue advertising keep-alive, at least for VSCode non-proxy users in the short term.

> adding 'keep-alive' in the constructor ... to not be picked up

Would be great to be specific... which constructor? In what way was the proxy not picked up? ...wondering if you were watching connections or requests.

@philipp-spiess FYI

2024-04-04 23:14 UTC, dominiccooney commented on vscode/src/fetch.node.ts
> +        return new HttpsProxyAgent(process.env.https_proxy ?? "")
&uarr; This

We need to use the same agent so something is hanging onto the connection to reuse.

@philipp-spiess had to work around VSCode breaking keep-alive by reusing this object, see:

ae2b292940b2e1f2347047a064dacd6f9facf40b
https://github.com/microsoft/vscode/issues/173861

@pkukielka for now, let's simply early return the now object, *only* when `http_proxy` or `https_proxy` are set, this like we do for SOCKS proxies above, and add a TODO or file an issue that proxy users may have slower autocomplete because there's no keep-alive. (How hard could it be for a proxy to support that... but never underestimate how broken proxies can be.)

2024-04-04 23:14 UTC, dominiccooney commented on agent/src/agent.ts
> +                // @ts-ignore
Why did we need to do this?

2024-04-05 07:04 UTC, pkukielka commented on vscode/src/fetch.node.ts
> +        return new HttpsProxyAgent(process.env.https_proxy ?? "")
Yes, we should check if we are in the agent or VSC and have different logic based on that.

2024-04-05 07:16 UTC, pkukielka commented on agent/src/agent.ts
> +                // @ts-ignore
This is interesting, I'm not sure how my other changes could cause problems there, but without changing this line I get the errors:

```
agent/src/agent.ts:442:35 - error TS18047: 'polly.persister' is possibly 'null'.

442                 const persister = polly.persister._cache as Map<string, Promise<Har>>
                                      ~~~~~~~~~~~~~~~

agent/src/agent.ts:442:35 - error TS2352: Conversion of type 'Map<string, Har>' to type 'Map<string, Promise<Har>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Har' is missing the following properties from type 'Promise<Har>': then, catch, finally, [Symbol.toStringTag]

442                 const persister = polly.persister._cache as Map<string, Promise<Har>>
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

agent/src/agent.ts:442:51 - error TS2341: Property '_cache' is private and only accessible within class 'Persister<TOptions>'.

442                 const persister = polly.persister._cache as Map<string, Promise<Har>>
```

2024-04-05 07:22 UTC, pkukielka commented on vscode/src/fetch.node.ts
> +        // For some reason adding 'keep-alive' in the constructor was causing proxy to not be picked up.
Sorry, what I meant is this:
`new HttpProxyAgent(process.env.http_proxy, { keepAlive: true, keepAliveMsecs: 60000 })`
If I add `keepAlive` in the constructor `opts` param everything builds and starts normally, but in the `squid-access.log` I see no requests are forwarded to a proxy.
On which level of the stack this is failing I do not know, I did not had time yet to debug it as this PR was time-boxed limited WIP.

2024-04-15 09:49 UTC, dominiccooney requested changes
More feedback inline.

2024-04-15 09:49 UTC, dominiccooney commented on agent/src/agent.ts
> +                // @ts-ignore
Sigh, looks like we're hacking into polly implementation details to add something missing (enumerate entries/approximate matching) and those implementation details have changed, and because of our hackery we are now giving things the wrong type, etc.

So let's fix the types first... `_cache` has type `Map<string, Har>`, not type `Map<string, Promise<Har>>`. Since you're apparently using the correct type, we should get rid of `as Map<string, Har>` *and* the `(await har)` &rArr; `har` on line 445.

Second, `_cache` is private. You *do* need the `@ts-ignore` to suppress this, but add a comment about what we're doing here.

Third, `polly.persister` may be `null`. I guess the `|| {}` is fine but this also smells like something has changed in polly and we may be broken.

CC @steveyegge , because he was coincidentally looking at polly not recording traces—was that in agent?—maybe some of this rot is related.

2024-04-15 09:49 UTC, dominiccooney commented on vscode/src/fetch.node.ts
>  import http from 'node:http'
This apparently still broken, so `import type http from 'node:http'`

I would fix it for you but GitHub doesn't allow editing non-diff lines 🤷

2024-04-15 09:49 UTC, dominiccooney commented on vscode/src/fetch.node.ts
> +import {HttpsProxyAgent} from "https-proxy-agent";
Apparently the formatter didn't fix this 🤷 

```suggestion
import { HttpsProxyAgent } from "https-proxy-agent";
```

2024-04-15 09:49 UTC, dominiccooney commented on vscode/src/fetch.node.ts
> +        // For some reason adding 'keep-alive' in the constructor was causing proxy to not be picked up.
OK let's add a TODO or DONOTCOMMIT here so we know not to land this as-is.

2024-04-15 09:49 UTC, dominiccooney commented on vscode/src/fetch.node.ts
> +        return new HttpsProxyAgent(process.env.https_proxy ?? "")
> I think we rather should check if we are in the agent or VSC and have different logic based on that. VSC already have proper agent there so no point to tinker with it.

Agree with this part.

> Ideally we should probably hack node module loading and replace agent in http and https modules - I think that is what vscode proxy code is doing.

Disagree with this part. VSCode is probably doing that because they don't control a lot of extension code and their random dependencies.

We *do* control this code, so let's just use the existing hooks for adding proxies.

2024-04-15 13:49 UTC, pkukielka commented on agent/src/agent.ts
> +                // @ts-ignore
@dominiccooney FYI I'm not actively looking on this PR as agreed with @kalanchan and @taylorsperry .
I think @chwarwick and Ara will be taking over.

2024-05-01 12:58 UTC, closed without merging