WIP PromptString
sourcegraph/cody pull request #3734
Opened 2024-04-08 15:24 UTC by philipp-spiess

## Test plan

2024-04-09 01:50 UTC, dominiccooney commented on lib/shared/src/ollama/index.ts
> +import { PromptString } from '../prompt/prompt-string'
```suggestion
import type { PromptString } from '../prompt/prompt-string'
```

2024-04-09 02:19 UTC, dominiccooney requested changes
Feedback inline.

In general, while we're not guarding against untrusted JavaScript, let's be WAAAY more defensive with this. I want someone who uses this type to fall into the pit of success, not find an easy route around the protections like retrieving the reference set and clearing it out, etc.

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.test.ts
> +        const inner = createPromptString('i am from a file', new Set([uri]))
Let's not export createPromptString, the contract is too loose. We should have a helper for each use case instead, like

```
PromptString.fromDocument(doc: Document): PromptString
PromptString.fromDocumentFilename(doc: Document): PromptString
PromptString.fromUriPath(uri: URI): PromptString // gets uri.path, etc.
// any other helpers we need
```

These helpers should either be:
1. Safe (Document.text is safe because we're holding onto the document URI; maybe we want to treat virtual documents as ignored or whatever but we can work that out later...)
2. Named "unsafe" and something which will trigger extra human review steps. Cases where we are really taking a string and asserting "trust me." Hopefully we don't have many of these.

We should lock down the Document text accessor functions in the linter or with prototype hacking, so you can't just drive around the barriers:

TextLine.text
Document.getText
DiagnosticCollection.forEach, this should have a helper which filters
etc.

...guessing the edit event's text properties are OK to leave as strings.

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +        return new PromptString()
This is safe (if useless) because we're protecting access to the side pocket map.

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +    return pocket.get(s)!.references
Never return mutable objects from the side pocket. Return a defensive copy, immutable view, or frozen object.

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +    const handle = PromptString.unsafe_createInstance()
Think it is fine to leave the constructor visible. It is useless without the side pocket.

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +                // Ignore undefined values
The more we make this like JavaScript, the easier time we will have. So this should be `undefined`.

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +export function promptStringToString(s: PromptString): string {
Let's just have callers use `toString`?

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +export function createPromptString(value: string, references: Set<StringReference>): PromptString {
Let's avoid exporting anything this loose as long as possible. When we do:

- It should be named "unsafe" something
- It should have build/review integration so each call is getting flagged and reviewed

2024-04-09 02:19 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +        public references: Set<StringReference>
Let's freeze the set as we take it, or take a defensive copy and freeze that. I assume URI is immutable, for practical purposes?

Later on we may want some mutable state in the side pocket, not against that, but at this stage we definitely can't take a mutable object and pass out references to it.

2024-04-09 02:19 UTC, dominiccooney commented on lints/safe-prompts.ts
> +// Checks that prompts track the source of context from the editor through to
This could do with a bunch of TODOs, improvements as you see fit.

2024-04-09 08:15 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.ts
> +        return new PromptString()
Yeah but I would rather have a typescript error pointing me to this file where I can add docs than have people add `new PromptString` and not realizing it doesn't work.

2024-04-09 08:17 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.ts
> +                // Ignore undefined values
I don't understand, can you elaborate this comment? 
We have code in place where we conditionally spread context in prompt strings and I wanted to add support for it:

```ts
const foo = `foo${a == 1 ? 1 : undefined}bar`
```

2024-04-09 08:21 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.ts
> +        return new PromptString()
Maybe I can do that with a @deprecated notice on the constructor

2024-04-09 08:22 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.ts
> +export function promptStringToString(s: PromptString): string {
Yeah agree, to be fair this was already here 😅

2024-04-09 09:59 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.ts
> +                // Ignore undefined values
I see what you mean now! 

```
`${undefined}`
'undefined'
```

will fix it and the caller that was depending on it 👍

2024-04-10 13:39 UTC, dominiccooney reviewed
This is amazing @philipp-spiess , you're killing it.

2024-04-10 13:39 UTC, dominiccooney commented on .github/workflows/unsafe-function-alert.yml
> +              body: '‼️ Hey @philipp-spiess, please review this PR carefully as it introduces usage of \`unsafe_\` functions.'
Can we add a role for this and tag that role?

2024-04-10 13:39 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.test.ts
> +        expect(() => ps`foo${evil2}bar`).toThrowError()
Worth passing a `PromptString` which has a monkey-patched `toString`. Fine if that doesn't throw, but it should not invoke `toString`.

We should also test this:

```
let x = new Number(8)
x.toString = () => 'hey'
ps`${x}` // should be '8' or definitely not 'hey'
```

2024-04-10 13:39 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.test.ts
> +    it('detects invalid PromptStrings passed to utility types', () => {
🎉

2024-04-10 13:39 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +    public static fromDocumentText(document: vscode.TextDocument, range?: vscode.Range): PromptString {
🎉

2024-04-10 13:39 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +}
Brevity

```suggestion
    return pocket.has(promptString)
}
```

2024-04-10 13:39 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +    references: readonly StringReference[]
Should we use Sets here, and return defensive copies?

- `readonly` is a TypeScript-ism that is easy to `as` away.
- I expect we'll end up with multiple references to the same file, and Set de-dups.
- Taking and returning defensive copies is very robust... if we remember to do it.

2024-04-10 13:51 UTC, philipp-spiess commented on .github/workflows/unsafe-function-alert.yml
> +              body: '‼️ Hey @philipp-spiess, please review this PR carefully as it introduces usage of \`unsafe_\` functions.'
Yeah I wanted to get it working first before I annoy folks :D I also want to use your script so we can add the rule for e.g. not calling `ps()` too first.

2024-04-10 13:53 UTC, philipp-spiess commented on vscode/src/completions/text-processing/utils.ts
> +    const headEnd = s.toString().indexOf(trimmed.toString())
yessir

2024-04-10 14:37 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.test.ts
> +        expect(() => ps`foo${evil2}bar`).toThrowError()
```ts
 class FakePromptString extends PromptString {
    toString() {
        return '😈'
    }
}
```

he-he

2024-04-12 08:02 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +    pocket.set(handle, new PromptStringPocket(string, new Set(references)))
Tough one. For security, the frozen array you had was great. For de-duping, Set is nice. And we don't need the perfect representation in v0, as long as we don't leak anything mutable, we can always change it.

There's a bunch of places where we have PrompString &rarr; PromptString with the same references, so it would be nice to have an immutable object and avoid allocating a second one.

Seems like we don't need to check what's in the array much. So we could also construct a tree of them, where references are frozen arrays of `(URI | FrozenReferenceArray)[]`.

(Separately, if we used frozen arrays, think we could use types and a marker property to ensure we're freezing them all... something to think about but not critical.)

2024-04-12 08:05 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +    // TODO: Do we need to create an array or can we expose the iterator?
Returning the iterator sounds fine. This is the spec: https://tc39.es/ecma262/multipage/keyed-collections.html#sec-createsetiterator it is a view of the mutable underlying object, but it doesn't permit mutation. (I *assume* URI is locked down well?)

2024-04-12 08:11 UTC, dominiccooney commented on lints/safe-prompts.ts
> +                    report(node, `New \`${text}\` invocation found`)
Should we disallow aliasing these, by checking that the parent node is a function declaration and the node is the CallExpression.expression (and not CallExpression.arguments)? Or is that too strict?

(Would need to look into module imports as well. Another place you can alias, and maybe we want to allow `x.unsafe_m()` where x is a module.)

In theory, if we review all the aliases, then we're fine...

2024-04-12 08:17 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +// TODO: Should we also serialize the references?
We slam chats in and out of storage quite a bit, so it seems weird to have references on a chat transcript, but closing and opening the chat panel or restarting the IDE makes those references evaporate.

On the other hand, you might pull up an old chat transcript and all the file paths are different now because you moved a folder or something. I'm thinking maybe we should have a concept of "resolved" references where we keep (repo, repo relative path) pairs for the serialized representation or something.

Let's leave them OUT for now, because changing the serialized schema is a pain. Think we want something here but let's work it out in a follow-up to avoid thrashing the disk format.

@willdollman FYI. Background: When you chat, we store chat history on disk and reload it later, you can keep chatting.

2024-04-12 08:18 UTC, dominiccooney commented on vscode/src/context/remote-search.ts
> +        // TODO: Validate that prompt string has only allowed references before
❤️  it is so cool that we are now in a place to make checks like this a reality.

This is an interesting case though... that's Sourcegraph, not an LLM provider. So in theory it's cool to serialize anything up there? @aramaraju ?

2024-04-12 09:27 UTC, willdollman commented on lib/shared/src/prompt/prompt-string.ts
> +    public static unsafe_fromLLMResponse(string: string): PromptString {
The file in question will have already been sent to the LLM, so it does feel like an edge case and I think it's ok if we ignore it.

Equally, with the current system it seems like it would be possible to attach references to prompts and their responses and this might be generally useful to track?

2024-04-12 13:43 UTC, philipp-spiess commented on agent/src/index.test.ts
> +            expect(trimEndOfLine(lastMessage?.text?.toString() ?? '')).toMatchInlineSnapshot(
Will try that, ty!

2024-04-12 13:45 UTC, philipp-spiess commented on agent/src/index.test.ts
> +                            lastMessage?.text?.toString()?.toLocaleLowerCase().includes('quone')
Ohh yes you're right, TIL :)

2024-04-12 13:58 UTC, philipp-spiess commented on .github/workflows/safe-prompts-lint.yml
> +              body: '‼️ Hey @philipp-spiess, please review this PR carefully as it introduces usage of \`unsafe_\` functions.'
https://sourcegraph.slack.com/archives/C01CSS3TC75/p1712930238694689

2024-04-12 13:59 UTC, philipp-spiess commented on .github/workflows/safe-prompts-lint.yml
> +              body: '‼️ Hey @philipp-spiess, please review this PR carefully as it introduces usage of \`unsafe_\` functions.'
Maybe we can also use https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message here :)

2024-04-12 14:03 UTC, philipp-spiess commented on agent/src/index.test.ts
> +            const trimmedMessage = trimEndOfLine(lastMessage?.text?.toString() ?? '')
I tried this here but since we have to branch of the implementation (as `Array.prototype.join` wouldn't work for `PromptString`), TypeScript seemingly can't follow the branches correctly and I get something like:

```
Type 'string' is not assignable to type 'T'.
  'string' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'string | PromptString'.ts(2322)
```

2024-04-12 14:10 UTC, philipp-spiess commented on .github/workflows/safe-prompts-lint.yml
> +        run: pnpm ts-node lints/safe-prompts.ts `git diff --name-only main | grep -E "\.(ts|tsx)$"`
This runs in under 2sec on my machine (and this is a quite sizeable diff). Might not need parallel right now but I'll add an inline comment so we know how to improve it.

2024-04-12 14:22 UTC, philipp-spiess commented
testing @sourcegraph/cody-security

2024-04-12 14:44 UTC, philipp-spiess commented
@dominiccooney @willdollman it might get a bit spammy for you guys now, I promise I will keep it as minimal as possible 🥺

2024-04-12 14:46 UTC, philipp-spiess commented on lib/shared/src/prompt/prompt-string.ts
> +    // TODO: Do we need to create an array or can we expose the iterator?
@dominiccooney Yeah I’m not sure about URI especially since we know in the vs code runtime the URI type is different from the one in the vscode-uri package. Maybe we should serialize it as a string?

2024-04-12 15:33 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +// TODO: Should we also serialize the references?
Yep, agree. Note that this is not only used for storage, but also when communicating with the agent (the agent will query the transcript to get updates quite a bit), so agree that we should track this eventually.

I will move this into the `prompt-string` class and expose this as unsafe for now too. I did some investigation and for _new messages_ we do not deserialze from a chat message in the agent (rather we use the `chat/submitMessage` notification) but we might change the implementation at one point and forget about this, so I'd rather have this marked unsafe.

2024-04-12 16:09 UTC, philipp-spiess commented
@pkukielka  There are some renames in the kotlin typegen. Can you check if this is an issue of the JetBrains client? The actual types are kept the same (so the API will still expose prompts as strings when talking to the agent).

2024-04-12 16:18 UTC, philipp-spiess commented
@dominiccooney This is _almost_ done. I need to make the CI pass again and then document the follow-up tasks in your GitHub issue and "arm" the CI rule again (I temporarily disabled it). I also want to remove some of the TODOs from the `prompt-string` class as well (i.e moving the types). So I'll likely land this Monday my morning if that's alright.

2024-04-12 16:30 UTC, aramaraju commented on lib/shared/src/prompt/prompt-string.ts
> +    public static unsafe_fromLLMResponse(string: string): PromptString {
Just adding to Will's comment, wouldn't the content already be sent in that case? I think it's safe to say that the new configuration only gets applied on a new chat session (I have [called](https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz?type=design&node-id=1198-4702&mode=design#768413463) it out to Daniel on the UX side for his thoughts on this too)

Is there a benefit in the 'wash off' behavior here? Is there any other reason to track the references? I suspect that we will some reason like evaluating how good the context fetching -  to determine if we did find the right files or compare against different context sources, etc?

2024-04-12 17:07 UTC, philipp-spiess commented on agent/recordings/enterpriseClient_3965582033/recording.har.yaml
> -                  undefined:
We had a bug here before because of no errors when doing `${undefined}`. Glad this is now checked 😎

2024-04-12 17:28 UTC, aramaraju commented on vscode/src/context/remote-search.ts
> +        // TODO: Validate that prompt string has only allowed references before
Making sure I interpret this correctly, is this case where the content is sent to the SG instance? That should be fine (for the truly security conscious we provide self-hosted experience)

2024-04-15 10:29 UTC, philipp-spiess commented on lints/safe-prompts.ts
> +                    report(node, `New \`${text}\` invocation found`)
> In theory, if we review all the aliases, then we're fine...

Yeah that was my thinking too, because if we do `import { unsafe_m as m } ..` we would still get this to error in the first case (I tested this specifically).

2024-04-15 11:39 UTC, philipp-spiess commented on vscode/src/edit/manager.ts
> +        if (configuration.instruction && configuration.instruction.trim().length > 0) {
@dominiccooney I found a failure case that can bite us here. The conditions for these might happen at places that were not even edited by my change because we were relying on `if(string)` for empty string checks all over the place and now `PromptString` is coerced to `true`. Luckily we had an E2E test in this case but I wonder if you have ideas of how we can protect against more issues like this?

One idea I have is to add https://palantir.github.io/tslint/rules/strict-boolean-expressions/ on `main` and fix all issues.

2024-04-15 13:02 UTC, philipp-spiess commented
<img width="1357" alt="Screenshot 2024-04-15 at 15 01 56" src="https://github.com/sourcegraph/cody/assets/458591/1b73d538-79fc-4472-8b8c-820741f45712">
 
 Let's goooo

2024-04-15 13:46 UTC, philipp-spiess commented on vscode/src/edit/manager.ts
> +        if (configuration.instruction && configuration.instruction.trim().length > 0) {
<img width="1262" alt="Screenshot 2024-04-15 at 15 46 08" src="https://github.com/sourcegraph/cody/assets/458591/6080343a-8252-41d2-bdb4-5ac03bf96d79">

:sigh:

2024-04-15 14:07 UTC, philipp-spiess commented on vscode/src/edit/manager.ts
> +        if (configuration.instruction && configuration.instruction.trim().length > 0) {
Good news: I found a few more potential candidates for this issue with this approach
Bad news: since this was the type result of a function call it was _not_ found using this approach. 😬 

I want to this was still worth the time though :) [`456ab07` (#3734)](https://github.com/sourcegraph/cody/pull/3734/commits/456ab072b2cacb8691ae2797879580378a487435)

2024-04-15 15:04 UTC, dominiccooney commented on vscode/src/edit/manager.ts
> +        if (configuration.instruction && configuration.instruction.trim().length > 0) {
Oh how did I miss this, good find. It's too bad there's no @@toPrimitive, valueOf hook for Boolean coercion.

So one thing that comes to mind, we could make the objects non-empty. So there's

`type PromptString = '' | NonEmptyPromptString` (or some better names)

The prompt string creation helper would check if the result is empty, and return '' if so. This assumes the non-empty string is never sensitive, which might be a bit dodgy.

This would force us to stick closer to the interface for String in the convenience methods on NonEmptyPromptString, because accessing anything specific to NonEmptyPromptString is less convenient now.

Another thing we could do is leave PromptString including '', but use a linter to warn if you're using a type which includes PromptString in a Boolean-looking context (`!`, `&&' etc., `if (...)`.) But that would be a more expensive lint, because you would need types and not just syntax like we do now.

2024-04-15 16:32 UTC, philipp-spiess commented on vscode/src/edit/manager.ts
> +        if (configuration.instruction && configuration.instruction.trim().length > 0) {
Both are great ideas. I’m tempted to not go forward with any of these though and instead just deal with any potential fallout this has. The upside is that longer-term we won't have to maintain a different code path for empty strings and don't need the expensive lint rules.

My mental model is that any new code paths that will be added will be tested and issues like this won't be added anymore. If that's incorrect, we may indeed need to fix this.

 @dominiccooney Do you think this is a reasonable assumption? I’m happy to add more stuff to handle this but I am inclined to just ship this and deal with any potential issues.

2024-04-16 07:56 UTC, valerybugakov commented on vscode/src/chat/chat-view/prompt.test.ts
> +        chat.addHumanMessage({ text: ps`Hello` })
I love the coincidence that it's your initials @philipp-spiess 😀

2024-04-16 09:30 UTC, philipp-spiess commented on vscode/src/chat/chat-view/prompt.test.ts
> +        chat.addHumanMessage({ text: ps`Hello` })
@valerybugakov I worked on https://pspdfkit.com/ in the past and made this comment all the time :P

2024-04-16 11:08 UTC, merged

2024-04-16 13:12 UTC, umpox commented
@philipp-spiess Noticed a weird regression from this commit:


https://github.com/sourcegraph/cody/assets/9516420/9ff34037-55b2-4923-bcf5-aa4293465b8f


Seems like the "New Chat" command is automatically executing a chat

2024-04-16 13:24 UTC, philipp-spiess commented
@umpox thanks will fix asap, I’m sure it's a string coercion bug :(

2024-04-16 13:31 UTC, philipp-spiess commented
@umpox https://github.com/sourcegraph/cody/pull/3811