Expand context window for user-context
sourcegraph/cody pull request #3742
Opened 2024-04-09 01:13 UTC by abeatrix

## Test plan

Manual testing steps:
1. Build Cody from this branch
2. In Debug mode, open the sourcegraph/cody repository
3. Search for the `SimpleChatPanelProvider` file, previously this file will be listed as large file. Verify that it's no longer shown as large file in this branch
4. Now try to add CHANGELOG.md. it should show you that it's a large file and selecting it will ask you to enter a range:

<img width="738" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/663e2c2f-5a6b-46ff-9747-96160bbbee49">

5. Entering a range that exceeds the token limit will turn the @-mention into red:

<img width="740" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/c1ddb7e0-8119-467a-8c3d-47669859ca00">

6. If you hit enter now, you should see the invalid @-mentions is excluded from Context:

<img width="742" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/0db4ddbc-5b92-4710-b2b7-9220f8d9198b">

7. In the chat input, @-mentions CHANGELOG.md again, but this time enter a range that doesn't exceed the token limit. E.g. 1-100 

<img width="738" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/6865673a-7efe-4989-9b73-2c0f12a34f59">

8. Submit it and you can see it was used as context:

<img width="1984" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/760bdf3e-7324-4cc4-a962-46a0f4b6b0f0">

2024-04-09 01:28 UTC, abeatrix commented on vscode/src/chat/context/chatContext.ts
> -    maxChars?: number
removing maxChars here since we will use the standardized context windows for user-context instead of needing to pass the current characters usage from the chat model to this function

2024-04-09 02:20 UTC, abeatrix commented on vscode/src/chat/chat-view/prompt.ts
> -const ENHANCED_CONTEXT_ALLOCATION = 0.6 // Enhanced context should take up 60% of the context window
this is moved to the lib/shared/src/token/constants.ts file. the number remains unchanged

2024-04-09 03:07 UTC, dominiccooney requested changes
Great start. Some feedback inline. Let's try to push token-based truncation a bit further in this PR.

2024-04-09 03:07 UTC, dominiccooney commented on vscode/src/commands/context/directory.ts
> +                const truncatedContent = truncateText(decoded, USER_CONTEXT_TOKEN_BUDGET_IN_BYTES)
You need to make a version of `truncateText`, `truncateToTokens` which:

- Tokenizes the content, or a large enough chunk of it.
- Takes the first "limit" tokens
- Decodes those tokens to text

If the tokenizer has a stream interface you can do something better, but that should be fine for now.

2024-04-09 17:59 UTC, abeatrix commented on agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItem.kt
>    val size: Int? = null,
converted into token count

2024-04-09 18:01 UTC, abeatrix commented on lib/shared/src/token/index.ts
> +    public static getMessagesByteCount(messages: Message[]): number {
removed

2024-04-09 18:02 UTC, abeatrix commented on lib/shared/src/token/constants.ts
> +export const USER_CONTEXT_TOKEN_BUDGET_IN_BYTES = tokensToBytes(USER_CONTEXT_TOKEN_BUDGET)
updated to always use token instead of character count or bytes!

2024-04-09 19:19 UTC, abeatrix commented on vscode/src/commands/context/directory.ts
> +                const truncatedContent = truncateText(decoded, USER_CONTEXT_TOKEN_BUDGET_IN_BYTES)
updated

2024-04-10 13:00 UTC, dominiccooney approved these changes
Fantastic.

Some feedback inline about naming.

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/codebase-context/messages.ts
>      size?: number
In the earlier conversation (which I hit resolved on... whoops) you said you converted this to tokens, but here it says characters.

Let's put the units in the name of the field at least, might make it possible to detect some bugs with 👀  ... so `sizeTokens` or `sizeChars` (which is it?)

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/index.ts
> +    CHARACTERS_PER_TOKEN,
We need this because the "rest" of the context (not @-tagged files) uses it, is that right?

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/models/index.test.ts
> +        const maxToken = ModelProvider.getMaxTokenByID('unknown-model')
Let's rename `getMaxTokenByID` to be `maxRequestTokensForModel` or something like that?

Reason is the tokens also have numbers, and "max token" sounds like the largest token value.
```suggestion
        const maxTokens = ModelProvider.maxRequestTokensForModel('unknown-model')
```

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/models/index.ts
> +        public readonly maxToken: number = CHAT_TOKEN_BUDGET
```suggestion
        public readonly maxRequestTokens: number = CHAT_TOKEN_BUDGET
```

or `maxTokens` or something like that. `maxToken` sounds like "the biggest value a token could have."

I like `maxRequestTokens` because some models have different input and output token limits. If we have to handle them specially later, the purpose of `maxRequestTokens` is clear but `maxTokens` could be ambiguous (is it input, output, requests, something else?)

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/prompt/truncation.ts
> +    return TokenCounter.decode(encoded.slice(0, maxTokens))
This is awesome! 🎉

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/prompt/truncation.ts
> +    if (encoded.length < maxTokens) {
This could me more succinct and save some compute sometimes with `<=`
```suggestion
    return encoded.length <= maxTokens ? text : TokenCounter.decode(encoded.slice(0, maxTokens))
```

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/prompt/truncation.ts
> +    if (encoded.length < maxTokens) {
<= here too, as above. If it is exactly the right length, we don't need to decode it.

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/prompt/truncation.ts
> +    return TokenCounter.decode(encoded.slice(-maxTokens - 1))
This should be `-maxTokens`, you'll get exactly `maxTokens` (e.g. `'food'.slice(-2)` is `'od'`)
```suggestion
    return TokenCounter.decode(encoded.slice(-maxTokens))
```

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/token/constants.ts
> + * The total context window reserved for user-added context (e.g. @-mention).
Worth documenting how this relates to `(FAST_)CHAT_TOKEN_BUDGET`. This must be on top of those budgets.

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/token/constants.ts
> + * Enhanced context should take up 60% of the context window
Worth documenting how this relates to `(FAST_)CHAT_TOKEN_BUDGET` too. This must be within that budget?

2024-04-10 13:00 UTC, dominiccooney commented on lib/shared/src/token/index.ts
> +        if (!message) {
Can this happen, since the type is `Message` not `Message?` ?

2024-04-10 17:05 UTC, abeatrix commented on lib/shared/src/prompt/truncation.ts
> +    if (encoded.length < maxTokens) {
Oh wow i didn't know that, thank you for the tips!

2024-04-11 05:12 UTC, abeatrix commented on lib/shared/src/token/constants.ts
> +export const CHARACTERS_PER_TOKEN = 3.5
yea makes sense! I've moved it to the helper function and updated it to be non-export.

2024-04-11 05:13 UTC, abeatrix commented on lib/shared/src/token/index.ts
> +        if (!message) {
it did happen but maybe it was my code? Will test it again to confirm.

2024-04-11 05:14 UTC, abeatrix commented on lib/shared/src/index.ts
> +    CHARACTERS_PER_TOKEN,
moved CHARACTERS_PER_TOKEN to helper!

2024-04-11 05:36 UTC, abeatrix commented on lib/shared/src/codebase-context/messages.ts
>      size?: number
will try to switch it to sizeToken tomorrow and see if it detects any bugs 🐞

2024-04-11 05:39 UTC, abeatrix commented on vscode/src/editor/utils/editor-context.ts
> +        cf.size = fileStat.size / 4
@dominiccooney does this address your concerns on converting bytes into tokens for @-mention results? Happy to address them or explain more if this doesn't help!.

2024-04-17 16:14 UTC, merged

2024-04-21 05:56 UTC, sqs commented
Just sent up https://github.com/sourcegraph/cody/pull/3887 to fix a couple minor issues.