VS Code: Troubleshoot auth connection issues
sourcegraph/cody pull request #3750
Opened 2024-04-09 14:29 UTC by RXminuS

Description:
Fixes #3673 where we mistakingly show a signIn screen if there are connectivity issues to the Cody server.

Todo:
- [ ] Check if similar changes needed in JetBrains
- [ ] Add "connection issues" to mocks.
- [ ] Implement tests

Test plan
End2End test that verifies the correct screen is shown if the server does not respond.

2024-04-12 00:42 UTC, abeatrix reviewed
Left some comments inline. The only concern i have is about the reset function, but the rest looks good to me. Nice work!

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/chat/protocol.ts
> +      }
```suggestion
    | {
          command: 'troubleshoot'; action: 'output' | 'reset'
      }
```

Can this be simplified? We already have a [reload](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/protocol.ts?L74) command so i think we just need to add 'reset' and `output`?
We should always ask for confirmation before resetting, imo.

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/chat/protocol.ts
> +      }
```suggestion
```

There is already a command registered for [reload](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/protocol.ts?L74) that is unused, so i think we can just reuse that?

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/chat/chat-view/SidebarViewController.ts
> +            case 'troubleshoot/reloadAuth': {
```suggestion
            case 'reload': {
```

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/chat/chat-view/SidebarViewController.ts
> +                if (message.askConfirmation) {
i think we should always ask for confirmation before this function is run. Maybe we should move this to the function instead? We can just log the "clicked" event here (or in the fullReset()), and then log the "executed" event once it's been executed.

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/services/utils/troubleshoot.ts
> +    //TODO(rnauta): make available as command?
as mentioned above, i think we should move the confirmation window into this function 🙏

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/services/utils/troubleshoot.ts
> + * Resets the extension by clearing all storage data, secretStorage data
From what i can tell the function is only removing the tokens from the secret storage, but everything in the local storage stays, and the settings are not removed. Is that the expected behavior?

2024-04-12 00:42 UTC, abeatrix commented on vscode/src/services/utils/troubleshoot.ts
> +    }
```suggestion
    }
    await clearAccessToken()
```
`clearAccessToken()` removes the last used access token, but doesn't remove the token stored under the endpoint key. I think we will always want to run this for a full reset?

2024-04-12 00:42 UTC, abeatrix commented on vscode/webviews/App.tsx
> +    if (authStatus?.showNetworkError) {
```suggestion
    if (authStatus.showNetworkError) {
```

2024-04-12 08:57 UTC, RXminuS commented
Yeah I'll probably just change that to a sign out. I just didn't want someone to get stuck with bad settings and not get back to the sign in screen.

Thanks for taking a look

2024-04-13 20:59 UTC, RXminuS commented
I've decided to remove the "fullReset" and "showOutput" logs in favor of another feature coming soon to help users enable and navigate debug mode/troubleshooting mode more easily. So this screen will only allow you to retry or sign-out explicitly. I'd still like to keep the reloadAuth command under the troubleshoot namespace because there will be about 4-5 more commands added soon under that namespace.

2024-04-16 12:50 UTC, philipp-spiess commented
@RXminuS sorry regarding the message above, see: https://github.com/sourcegraph/cody/pull/3797#issuecomment-2058969736

2024-04-16 17:33 UTC, RXminuS commented on vscode/src/chat/protocol.ts
> +      }
I'll be adding a few more things under the troubleshooting namespace though. So I've just removed the reload command

2024-04-16 17:35 UTC, RXminuS commented
@philipp-spiess increasing the timeout fixed the e2e tests 👍  thanks for the help

2024-04-17 01:17 UTC, abeatrix commented on vscode/webviews/App.tsx
> +    if (view === 'login' || !authStatus.isLoggedIn || !userAccountInfo) {
This change seems to remove the current loading screen at initiate time:

<img width="444" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/ca981a50-55e2-47c0-8c94-97e4c2ebc834">


### Before

https://github.com/sourcegraph/cody/assets/68532117/1ad53805-82ff-4350-8ae1-162dad69239d



### After

https://github.com/sourcegraph/cody/assets/68532117/14fc5af4-ec67-4eeb-b018-6da4aa534d02

2024-04-17 01:18 UTC, RXminuS commented on vscode/webviews/App.tsx
> +    if (view === 'login' || !authStatus.isLoggedIn || !userAccountInfo) {
Derp...good point!

2024-04-17 01:26 UTC, toolmantim commented
Nice! This design is looking good too.

For the width/positioning, use VS Code’s Run & Debug panel and responsive breakpoints as the guide:

https://github.com/sourcegraph/cody/assets/153/40d49cc4-eec5-4934-9c0c-fff0632f833c

i.e. icon & buttons are full width until a point, then left aligned

2024-04-17 01:33 UTC, RXminuS commented on vscode/webviews/App.tsx
> +    if (view === 'login' || !authStatus.isLoggedIn || !userAccountInfo) {
Mmm...I'm a little confused by this as the condition for showing the <LoadingPage> hasn't changed :-/ I'll look into it

2024-04-17 12:51 UTC, RXminuS commented on vscode/webviews/App.tsx
> +    if (view === 'login' || !authStatus.isLoggedIn || !userAccountInfo) {
I still don't understand how my changes caused this change in behavior for you and I wasn't able to replicate it. However I did find that we didn't really show the loading screen at all until the full initialization was completed. So I've changed that slightly so that we no longer wait for the auth state to resolve before showing a view. That should show the loading state much earlier.

Although it feels a little bit of a bandaid solution, I think we might need to think about more declarative UI state / routing.

Here a video of the change of me pausing the HTTP response after a reload. Could you give this another go?

https://github.com/sourcegraph/cody/assets/3949285/e57f401c-3f34-4f13-90d6-0841a91d5034

2024-04-17 12:54 UTC, RXminuS commented
> Nice! This design is looking good too.
> 
> For the width/positioning, use VS Code’s Run & Debug panel and responsive breakpoints as the guide:

@toolmantim VScode had a few inconsistent breakpoints so I just picked `650px` as the max. They also have global flags for reduced motion that I didn't want to dive into now so I didn't add any animations. I think that's something we can globally define once we set up Tailwind helpers. But for now, I've tried to follow the spirit of it :-)

https://github.com/sourcegraph/cody/assets/3949285/3eef94e9-971b-4c27-a8be-97130ab4aed0

2024-04-17 12:55 UTC, RXminuS commented on vscode/webviews/App.tsx
> +    if (view === 'login' || !authStatus.isLoggedIn || !userAccountInfo) {
Dang...that seems to have broken all the tests 🤦

2024-04-17 13:54 UTC, abeatrix requested changes

2024-04-17 13:54 UTC, abeatrix commented on vscode/src/main.ts
> +    void authProvider.init()
I think this is the cause of the Loading screen getting skipped issue. 
Since other services can now initialized before the auth step has been completed, the sidebar is now starting with the rest of the services (specifically contextProvider that sends the sidebar init events). 

@philipp-spiess @umpox is there anything you can think of top of your head that would be affected by this change where services can be initialized before the initiate auth has been completed?

Another bug I noticed with this change is that my opened webview panel is now closed on reload:

https://github.com/sourcegraph/cody/assets/68532117/d70776c7-a6ad-4294-b19a-1757785a84e6

I think we should revert this change for now until we can improve the whole dependency situation, unless your other changes depend on this? What do you think?

2024-04-17 13:58 UTC, RXminuS commented on vscode/src/main.ts
> +    void authProvider.init()
It's not the cause of the original issue / video you posted because I only just added this to try and fix it at the root. I'm happy to revert it if it is causing issues but then I still don't understand how https://github.com/sourcegraph/cody/pull/3750#discussion_r1568093267 issue presents itself because I basically never get shown a loading screen in either version.

2024-04-17 14:02 UTC, RXminuS commented on vscode/src/main.ts
> +    void authProvider.init()
It's commit `56e1ab7` where I added this

2024-04-17 14:05 UTC, RXminuS commented on vscode/src/main.ts
> +    void authProvider.init()
Also I think that the `showNetworkError` is equally problematic as the `showLoading` in that I don't think any components other then the UI handle it. So if for some reason there's a network problem the auth would simply be assumed to b `signedOut` rather than `unknown`.

Probably the easiest way to find all the potential problem areas is if I set the AuthStatus to optional and follow the TS errors.

2024-04-17 14:29 UTC, RXminuS commented on vscode/src/main.ts
> +    void authProvider.init()
Ok, I've put up an issue here https://github.com/sourcegraph/cody/issues/3835 and tests seem to be passing again.

2024-04-17 17:36 UTC, abeatrix approved these changes
Thanks for working on this and for adding all those amazing tests! Confirm the chat panel is now showing up correctly on reload, and we can look into the Loading page issue separately 😄 well done!

2024-04-17 17:36 UTC, merged