Add support for using Sourcegraph Embeddings API
sourcegraph/cody pull request #3753
Opened 2024-04-09 15:49 UTC by rafax

Add's support for Sourcegraph Embeddings API.
Still WIP

## Test plan

- TODO

2024-04-10 12:23 UTC, dominiccooney requested changes
Exciting to see! Let's not pass booleans everywhere though.

2024-04-10 12:23 UTC, dominiccooney commented on vscode/src/local-context/local-embeddings.ts
> +        private readonly useSourcegraphEmbeddings: boolean,
LocalEmbeddingsConfig has:

```
    testingLocalEmbeddingsModel: string | undefined
    testingLocalEmbeddingsEndpoint: string | undefined
    testingLocalEmbeddingsIndexLibraryPath: string | undefined
```

Why not simply drop the "testing" prefix on those, and handle the experiment where the config object is set up?

2024-04-10 12:23 UTC, dominiccooney commented on vscode/webviews/Components/EnhancedContextSettings.tsx
> +                The repository&apos;s contents will be uploaded to {provider.useSourcegraphEmbeddings ? "Sourcegraph" : "OpenAI"}&apos;s Embeddings API and then
@toolmantim I've never been comfortable with this wording, because "uploaded ... and then stored locally" is confusing. It's *not* permanently stored remotely. Wouldn't it be clearer to say something like "uploaded, processed and then returned to you" or something?

2024-04-10 12:23 UTC, dominiccooney commented on vscode/src/local-context/local-embeddings.ts
> +                    providers: [{ kind: 'embeddings', state: 'indexing',useSourcegraphEmbeddings:this.useSourcegraphEmbeddings }],
I'm not a fan of booleans, it's such an easy type to mess up in TypeScript/JavaScript, so unfriendly to English as a second language speakers when there's negations (not to neglect to omit it's also not friendly to native English speakers...) ... can we just have a type like `type EmbeddingsProvider = 'sourcegraph' | 'openai'` and pass something like `embeddingsProvider: 'openai'` instead? More explicit and totally separate at the type level from `''`, 0, `undefined`, `null`, ...

And have a helper down in the UI that takes the constant and produces the string with the right branding for the provider like `'openai'` &rArr; `'OpenAI'` or whatever...

2024-04-10 12:24 UTC, dominiccooney commented
One more bit of feedback: When the flag flips on, we should direct the embeddings controller to a different index directory. Everything will Just Work without having to generalize cody-engine to handle heterogeneous sets of indexes. (I've done a bit of WIP on that but it got hard preempted by JetBrains GA.)

2024-04-10 12:26 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +                    providers: [{ kind: 'embeddings', state: 'indexing',useSourcegraphEmbeddings:this.useSourcegraphEmbeddings }],
Yes, that's exactly what I now have locally :) will fix

2024-04-10 12:32 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +        private readonly useSourcegraphEmbeddings: boolean,
One reason was the config object is currently set up in the constructur, but constructor can't be async, and resolving a flag needs to be async (so, I resolve the flag in createLocalEmbeddingsController, and use it to create config)

2024-04-10 12:34 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +        private readonly useSourcegraphEmbeddings: boolean,
But, your point about dropping testing* makes sense, will update

2024-04-10 19:15 UTC, rafax commented on vscode/src/local-context/enhanced-context-status.test.ts
> +                        useSourcegraphEmbeddings:false,
Right, I had prettier configured locally, will reformat with biome.

2024-04-10 19:16 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +        this.dimension = config.testingLocalEmbeddingsDimension || useSourcegraphEmbeddings? 768:1536
Right, removed testing altogether (using the feature flag)

2024-04-11 11:08 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +        private readonly useSourcegraphEmbeddings: boolean,
I dropped all `testingFOO` properties.

2024-04-11 11:08 UTC, rafax commented on vscode/src/local-context/enhanced-context-status.test.ts
> +                        useSourcegraphEmbeddings:false,
Reformatted

2024-04-11 11:08 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +                    providers: [{ kind: 'embeddings', state: 'indexing',useSourcegraphEmbeddings:this.useSourcegraphEmbeddings }],
Fixed

2024-04-11 11:09 UTC, rafax commented
> One more bit of feedback: When the flag flips on, we should direct the embeddings controller to a different index directory. Everything will Just Work without having to generalize cody-engine to handle heterogeneous sets of indexes. (I've done a bit of WIP on that but it got hard preempted by JetBrains GA.)

This is now implemented (with OpenAI getting the empty prefix).

2024-04-16 13:29 UTC, dominiccooney requested changes
Sorry for the slow response. 🙇 

Sharding the embeddings directory by model type looks good.

Removing the test override hooks has broken the VSCode e2e tests, specifically vscode/test/e2e/local-embeddings-test.ts which you can run with `pnpm -C vscode test:e2e`

Simplest thing is probably to put the test override hooks back... I earlier intended to suggest that you change the name and testing mode check so they are not "test only" overrides any more.

Otherwise, you can:
- Evolve the local-embeddings.test.ts forward however you want.
- Update the README in the embeddings crate about testing hooks since those settings aren't effective.
- Delete the settings in vscode/src/configuration.ts

2024-04-16 13:29 UTC, dominiccooney commented on vscode/src/local-context/local-embeddings.ts
> +                    (modelSuffix !== '' ? '/' + modelSuffix : '')
You could simplify this a bit by reversing the branches.

```suggestion
                    (modelSuffix == '' ? '' : '/' + modelSuffix)
```

2024-04-16 13:29 UTC, dominiccooney commented on vscode/src/local-context/local-embeddings.ts
> +                    (modelSuffix !== '' ? '\\' + modelSuffix : '')
```suggestion
                    (modelSuffix === '' ? '' : '\\' + modelSuffix)
```

2024-04-17 12:05 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> +        this.endpoint = 'https://cody-gateway.sourcegraph.com/v1/embeddings'
Done

2024-04-18 10:35 UTC, rafax commented
> Sorry for the slow response. 🙇
> 
> Sharding the embeddings directory by model type looks good.
> 
> Removing the test override hooks has broken the VSCode e2e tests, specifically vscode/test/e2e/local-embeddings-test.ts which you can run with `pnpm -C vscode test:e2e`
> 
> Simplest thing is probably to put the test override hooks back... I earlier intended to suggest that you change the name and testing mode check so they are not "test only" overrides any more.
> 
> Otherwise, you can:
> 
> * Evolve the local-embeddings.test.ts forward however you want.
> * Update the README in the embeddings crate about testing hooks since those settings aren't effective.
> * Delete the settings in vscode/src/configuration.ts

I brought the test overrides back (using a type instead of a bag of props), I assumed that these were only used for "human testing" of BFG integration, but supporting e2e tests without those would be tricky.

2024-04-19 10:35 UTC, rafax commented on vscode/src/local-context/local-embeddings.ts
> -    testingLocalEmbeddingsModel: string | undefined
No longer removing the options

2024-04-22 12:57 UTC, dominiccooney approved these changes
Sorry for the slow response, thank you for keeping the tests green.

2024-04-22 15:08 UTC, rafax commented on vscode/src/configuration.ts
> +                      provider: 'openai',
In practice, this is only used for showing the name of the API provider in the enhanced context selector, so I'll keep this as-is for now.

2024-04-22 15:08 UTC, merged