Move new user context window behind feature flag
sourcegraph/cody pull request #3781
Opened 2024-04-11 21:39 UTC by abeatrix

As discussed with @chillatom and @dominiccooney, we will move the new user context window budget behind a feature flag for internal testing before the limit is raised accordingly on the server.

## Test plan

Follow the Test Plan listed in https://github.com/sourcegraph/cody/pull/3742, and verify that everything works the same as it currently is until the feature flag has been turned on for Sourcegraph teammates

2024-04-12 02:04 UTC, dominiccooney requested changes
I think `allocateTokens` needs work. Let's add more tests.

2024-04-12 02:04 UTC, dominiccooney commented on lib/shared/src/token/counter.ts
> +        this.shareChatAndUserContextBudget = contextWindow.user === 0
I'm just re-reading `allocateTokens` and I think it is buggy.

If you're sharing the budget and you add a user context item, then you need to reduce the chat budget and enhanced context budget too. You only do it for the case where the chat budget reduces the user context budget. Same for adding an enhanced context item.

2024-04-12 02:47 UTC, abeatrix commented on lib/shared/src/token/counter.ts
> +        this.shareChatAndUserContextBudget = contextWindow.user === 0
Copied from slack: 
> this is the expected behavior. I’ll document it better in the docstring, but basically every time we construct the prompt, we always build the chat prompt first, and if we have tokens left, we will then build the context prompt with it. If there is no more chat token left, we simply won’t add any more context. 
That’s why adding new chat message will deduct the token limit from context, but not vice versa.

2024-04-12 02:50 UTC, abeatrix commented on lib/shared/src/models/dotcom.ts
> +export function getDotComDefaultModels(hasUserContextFeatureFlag = false): ModelProvider[] {
Ah that's a solid point I need to keep that in mind. Thank you!

2024-04-12 04:09 UTC, dominiccooney commented on lib/shared/src/token/counter.ts
> +        this.shareChatAndUserContextBudget = contextWindow.user === 0
Let me push back on that, because *at the call site* someone could come in and reorder that code and shoot themselves in the foot. The general idea is: make things where the easy use is the correct use.

It's pretty easy to make allocateTokens more robust, so let's do that.

If that's too hard, think of an API structure where you're forced to do things in order. Like maybe the budget has phases and it calls you back, forcing to count the chat tokens first. But seems simpler just to make it work regardless of call order.

2024-04-12 06:59 UTC, abeatrix commented on lib/shared/src/token/counter.ts
> +        this.shareChatAndUserContextBudget = contextWindow.user === 0
Yea that makes sense: I updated the logic so that it would work even when the prompt is constructed out of order, and added a test to reflect that: https://github.com/sourcegraph/cody/pull/3781/commits/3c87cb78952e6c799c3ef59b09c563072cfcbd2c

2024-04-15 10:01 UTC, dominiccooney requested changes

2024-04-15 16:13 UTC, abeatrix commented on lib/shared/src/token/counter.ts
> +        let { chat, user, enhanced } = this.usedTokens
Enhanced context budget is current [Chat Budget *  ENHANCED_CONTEXT_ALLOCATION](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/prompt.ts?L50).
In the code, we are not tracking the used token for enhanced context. I have updated the docstring and removed it from the this.usedTokens to avoid confusing.

2024-04-15 16:17 UTC, abeatrix commented on lib/shared/src/token/counter.ts
> +        let { chat, user, enhanced } = this.usedTokens
Here is the doc with the desired state written down: https://docs.google.com/document/d/1_rg8j4yfz1Ot-lQle8v_K_y8V3JDzpKYxO134X7MItc/edit

2024-04-15 19:32 UTC, abeatrix commented on lib/shared/src/token/counter.ts
> +     * so the enhanced token usage is not tracked separately but will count towards the chat token usage.
Done. Please see the latest file change

2024-04-16 11:16 UTC, philipp-spiess commented on lib/shared/src/models/types.ts
> +}
Can you add some documentation on what the difference is between these limits? It's not clear from the name alone (we might also want to consider renaming them to something more explicit).

2024-04-16 11:16 UTC, philipp-spiess commented on lib/shared/src/models/dotcom.ts
> +        contextWindow: { chat: CHAT_TOKEN_BUDGET, user: 0 },
What exactly does `user: 0` mean here? the user can not @-mention anything anymore? 🤔

2024-04-16 11:16 UTC, philipp-spiess commented on agent/recordings/enterpriseClient_3965582033/recording.har.yaml
>              maxTokensToSample: 1000
I don't understand why the recordings needed to change here if they still apply the same tokens? Can you point me to the difference in the request that required the regenration?

2024-04-16 11:16 UTC, philipp-spiess commented on lib/shared/src/token/counter.ts
> +        if (!message?.text) {
Let's not do unexpected string to boolean coercion, this is biting us quite hard right now in https://github.com/sourcegraph/cody/pull/3734

```suggestion
        if (message?.text && message?.text.length > 0) {
```

2024-04-16 11:16 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> -                                  hints: { maxChars },
It still seems useful for retrievers to know the limits?

2024-04-16 11:16 UTC, philipp-spiess commented on lib/shared/src/models/types.ts
> +}
Ah I saw that you changed this after setting the PR up for review. I think the new terminology is clearer, thank you!

2024-04-16 11:19 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> -                                  hints: { maxChars },
we noticed this is not being used currently, or did we miss something?

2024-04-16 11:20 UTC, abeatrix commented on lib/shared/src/models/dotcom.ts
> +        contextWindow: { chat: CHAT_TOKEN_BUDGET, user: 0 },
updated to make this more clear <3

2024-04-16 11:23 UTC, philipp-spiess commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> -                                  hints: { maxChars },
Hmm yeah you're right we don't (especially since I removed some code paths) so let's remove this until we need it :)

2024-04-16 11:32 UTC, abeatrix commented on agent/recordings/enterpriseClient_3965582033/recording.har.yaml
>              maxTokensToSample: 1000
I think it's because of the changes to the context items where we now add the (token) size to each Context Item that prompted the change.

2024-04-16 11:54 UTC, philipp-spiess commented on agent/recordings/enterpriseClient_3965582033/recording.har.yaml
>              maxTokensToSample: 1000
@abeatrix Hmm but wouldn't it result in the same prompts as before?

2024-04-16 12:20 UTC, abeatrix commented on agent/recordings/enterpriseClient_3965582033/recording.har.yaml
>              maxTokensToSample: 1000
ah you're right. i think it's because of this change from the upstream where we sort the context for agent testing where we move the selection to the last item: https://github.com/sourcegraph/cody/blob/3927cb06741f06b59c48c51bf0efc676c77ab199/vscode/src/chat/chat-view/agentContextSorting.ts 

do you think this is the case?

<img width="904" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/eb874b39-3d86-4f8f-851d-68cbb82794e4">

<img width="968" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/d861c31a-db11-4a0e-9181-1c9b616e0c1c">

2024-04-16 17:43 UTC, abeatrix commented on lib/shared/src/models/dotcom.ts
> +        contextWindow: { input: CHAT_TOKEN_BUDGET },
updated to `input` instead of `chat` for a clear naming and aligns with the upcoming changes for the output token expansion in https://github.com/sourcegraph/cody/pull/3797

2024-04-16 21:37 UTC, abeatrix commented on lib/shared/src/token/constants.ts
> +export const EXPERIMENTAL_USER_CONTEXT_TOKEN_BUDGET = 30000
Requested by @chillatom to raise limits for DotCom users with feature flag enabled:
- new 30k limit for user context
- increased from 7k to 15k for chat input

2024-04-17 06:24 UTC, dominiccooney approved these changes
Looks good.

2024-04-17 06:24 UTC, dominiccooney commented on lib/shared/src/token/counter.test.ts
> +    it('should update token usage and return true when within limits - chat and user context have separate budgets', () => {
This doesn't really test that it updates the limits... you need an assertion about the remaining tokens.

2024-04-17 06:24 UTC, dominiccooney commented on lib/shared/src/token/counter.test.ts
> +    it('should throw error when trying to update enhanced context token usage before chat input', () => {
👍

2024-04-17 06:24 UTC, dominiccooney commented on lib/shared/src/token/counter.test.ts
> +        expect(counter.updateUsage('enhanced', enhancedContextMessages)).toBe(false)
Theses tests would be shorter and more persuasive if, right after this, you added context that *did* succeed.

It's also good to test boundaries—for example 6 (just misses), 5 (just fits)

2024-04-17 06:24 UTC, dominiccooney commented on lib/shared/src/token/counter.ts
> + * NOTE: A new TokenCounter is created everytime a new PromptBuilder is created.
Why is this relevant?

2024-04-17 14:12 UTC, abeatrix commented on lib/shared/src/token/counter.test.ts
> +        expect(counter.updateUsage('enhanced', enhancedContextMessages)).toBe(false)
Good suggestion! I've extended the test as suggested to demonstrate context within boundaries can still be added successfully.

2024-04-17 14:12 UTC, abeatrix commented on lib/shared/src/token/counter.ts
> + * NOTE: A new TokenCounter is created everytime a new PromptBuilder is created.
removed!

2024-04-17 14:15 UTC, merged