Cody Ignore: Check reference violations at I/O boundaries
sourcegraph/cody pull request #3856
Opened 2024-04-18 13:03 UTC by philipp-spiess

This PR adds a "last-line-of-defense" that will throw when attempting to run an LLM query for cody-ignored files. I've added checks for references to all I/O boundaries (it should be close as close to the `fetch()` or `http/https` calls as possible so we never accidentally forget one if we copy-paste in the future.).

@valerybugakov I had to move some of your cody ignore work to `lib/shared` to make this work. Two notes:

- We make the git extension specific stuff dependency injectable so there's no hard requirement on vscode in `lib/shared`
- We need to validate that the WASM regex library actually works in the agent since it's loaded based on static data in the bundler. For now I kept the `re2-wasm` dependency in `vscode` too so the copy script has access to it. Let's add this as a todo item to check inside agent builds.

## Test plan

2024-04-18 14:37 UTC, philipp-spiess commented on lib/shared/package.json
> +  "files": ["dist", "src", "!**/*.test.*"],
I just did `pnpm add` and this was reformatted. 🤔 Do others change this file in their IDE maybe?

2024-04-18 14:37 UTC, philipp-spiess commented on lib/shared/src/cody-ignore/context-filters-provider.test.ts
> -            )
This seems unused

2024-04-19 02:47 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.test.ts
> -            )
Yep, since now `repoNameResolver` is an `init` parameter.

2024-04-19 03:02 UTC, valerybugakov reviewed
I got the same thoughts after looking at the PR diff! 

With both of the ideas, I'm concerned that we have many places where to instantiate prompt strings or call toString on them before filtering out the excluded URIs. In these places, we would need to update the logic to handle potential "URI is ignored" errors. 

Conversely, the risk of not applying the `isUriAllowed` is almost zero, which is excellent. As we want to be on the safer side of things, it makes sense to refactor the call sites to accommodate one of these ideas.

2024-04-19 04:03 UTC, valerybugakov commented
Heads up @philipp-spiess, I just rebased my changes on top of this PR: https://github.com/sourcegraph/cody/pull/3869

2024-04-19 04:44 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        this.getRepoNameFromWorkspaceUri = getRepoNameFromWorkspaceUri
If we move repoNameResolver to `lib/shared`, we should be able to remove `getRepoNameFromWorkspaceUri` from `init` parameters.

2024-04-19 05:44 UTC, dominiccooney requested changes
Some feedback inline.

There's too much duplication of the reference check. We should do that in PromptString and pass in the policy, so everyone is doing the same check. That will unit test in a more targeted way too.

I agree PromptString.toString is a risk, but I'm not worried about it in the short term as long as we rely on our invariants:
- Unsafe PromptString construction is audited, for example, that human input is something that just came out of a text box.
- Other PromptString construction is either safe (literals) or tracks its provenance.
- PromptStrings are what get sent to LLMs.

2024-04-19 05:44 UTC, dominiccooney commented on lib/shared/package.json
> +  "files": ["dist", "src", "!**/*.test.*"],
I see this flip back and forth, sadly. I'm unsure what the configuration difference is.

2024-04-19 05:44 UTC, dominiccooney commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        this.getRepoNameFromWorkspaceUri = getRepoNameFromWorkspaceUri
FWIW @valerybugakov  I'm removing the `check/isCodyIgnoredFile` Agent protocol method in #3858 and Agent protocol can now interact with vscode/... objects via [ExtensionClient and ExtensionObjects](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@63ae96cb4a7a430746cd383c1cc1d444dc2a050f/-/blob/vscode/src/extension-client.ts) There might be some startup ordering subtleties there but I'm sure we can iron them out.

2024-04-19 05:44 UTC, dominiccooney commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        if (!this.temporary_isEnabled) {
Can we expose a Promise for when this the temporary enablement is done?

If the repo fetcher starts churning it will want to wait before using the filters.

2024-04-19 05:44 UTC, dominiccooney commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +            return true
If we're in an uncertain configuration, wouldn't it be more secure to fail *closed* and disallow everything? CC @willdollman

2024-04-19 05:44 UTC, dominiccooney commented on lib/shared/src/cody-ignore/context-filters-provider.ts
>              return false
Not your change, but we really need a TODO here to follow up on cases like allowing unsaved documents.

2024-04-19 05:44 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/completions/browserClient.ts
> +        // Validate that no messages contain ignored context
What about instead passing the context filter into PromptString and having that do the check? So the "only" way to get a string is to call the function that applies a policy?

I realize we have `PromptString.toString()` calls all over the place right now, but I wonder how many of them we really need...

2024-04-19 05:56 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +            return true
This won't be needed once we merge https://github.com/sourcegraph/cody/pull/3869 into this branch

2024-04-19 05:57 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        if (!this.temporary_isEnabled) {
We should use the async `isUriAllowed` instead of this one.

2024-04-19 05:59 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
>              return false
I have a subtask for that here https://github.com/sourcegraph/cody/issues/3641: "Process non-file URIs instead of excluding all of them".

2024-04-19 06:53 UTC, valerybugakov commented
Hey @philipp-spiess, I just merged my changes into this PR. It should not introduce any extra work or conflicts because I rebased on top of your work.

2024-04-19 11:43 UTC, philipp-spiess commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        this.getRepoNameFromWorkspaceUri = getRepoNameFromWorkspaceUri
@valerybugakov I tried this at first but when I moved `repoNameResolver` to `lib/shared` I noticed it uses lots of vscode APIs (workspace/uri stuff/file type stuff). This is an easier boundary since it just means we need to dependency inject 1 function (which also makes testing simpler since we don't need mocking now!)

2024-04-19 11:45 UTC, philipp-spiess commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        this.getRepoNameFromWorkspaceUri = getRepoNameFromWorkspaceUri
If we need it for cody agent we should think about how to get rid of the vscode-isms maybe? Anyway seems like it might be good to do in a follow-up PR

2024-04-19 11:58 UTC, philipp-spiess commented on lib/shared/src/index.ts
> +    type SerializedCodeCompletionsParams,
I have it as a small follow-up task for me to rename these to `Serializeable` instead of `Serialized`. No need to add that to that PR though or to worry about merge conflicts (we use `Serialized` in a few places right now where it refers to the serializebale json representation). Just ignore for now and I'll fix 🥺

2024-04-19 12:07 UTC, philipp-spiess commented
(Quickly fixing up something; looks like we changed the API to async 😓  and need to add a unit test)

2024-04-19 12:24 UTC, philipp-spiess commented on lib/shared/src/sourcegraph-api/completions/browserClient.ts
> +        // Validate that no messages contain ignored context
The fact that the context filter chat is async makes it so that `toString` is no longer a good API boundary for this anyways, unfortunately.

2024-04-22 03:47 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        this.getRepoNameFromWorkspaceUri = getRepoNameFromWorkspaceUri
> I noticed it uses lots of vscode APIs (workspace/uri stuff/file type stuff)

The `workspace.fs` API should be supported by the agent: https://github.com/sourcegraph/cody/blob/d65d7c1a4af11e2c5c4e62b698be81ec236b1573/vscode/src/testutils/mocks.ts#L504 What kind of errors did you get?

> If we need it for cody agent we should think about how to get rid of the vscode-isms maybe?

We need to support this in the agent to make the Cody Ignore work for the JetBrains client. A follow-up PR for that sounds good 👍  I was hoping it would pick up the existing vscode mocks and work mostly out of the box without any additional logic.

2024-04-22 03:50 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/completions/browserClient.ts
> +        // Validate that no messages contain ignored context
Perfect!

Yes, passing in the context filter is the right approach.

2024-04-22 09:26 UTC, philipp-spiess commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +        this.getRepoNameFromWorkspaceUri = getRepoNameFromWorkspaceUri
@valerybugakov IIRC I got weird errors in the test where the vscode import would not export anything at runtime, I can look into this as a follow up, though. Do you mind reviewing this PR so we can get it into `main`? :)

2024-04-22 09:51 UTC, philipp-spiess commented
@valerybugakov @dominiccooney may I ask for a review once more? The PR is starting to diverge from `main` quite a bit 😬

2024-04-22 12:21 UTC, valerybugakov approved these changes
Looks great! 🙌

One thing that worries me is that we still depend on our discipline to avoid accidentally passing the excluded context snippet through the I/O boundary. We can think about how to make it stricter in a follow-up.

One idea from looking at `vscode/src/completions/client.ts`: if we want to ensure that unfiltered strings are not used as fetch bodies, the default `toString` could add a special `[CODY_UNFILTERED]` suffix to the return value. We can create a `fetch` wrapper that checks if `body` includes it and throws. It would ensure we always use `toFilteredString` (which deletes the suffix) before sending it over the network. Potentially, we can also monitor it on the Cody Gateway side and error.

The bad part is that it modifies the string value until it's sent. It has multiple annoying side effects. E.g., we will need to account for the redundant suffix length when we calculate the chars remaining in the context window. Is there a better way?

2024-04-22 12:21 UTC, valerybugakov commented on vscode/test/fixtures/mock-server.ts
> +                                        message: `Cannot query field "unknown" on type "${operation}".`,
TY!

2024-04-22 12:29 UTC, philipp-spiess commented
> One thing that worries me is that we still depend on our discipline to avoid accidentally passing the excluded context snippet through the I/O boundary. We can think about how to make it stricter in a follow-up.
> 
> One idea from looking at `vscode/src/completions/client.ts`: if we want to ensure that unfiltered strings are not used as fetch bodies, the default `toString` could add a special `[CODY_UNFILTERED]` suffix to the return value. We can create a `fetch` wrapper that checks if `body` includes it and throws. It would ensure we always use `toFilteredString` (which deletes the suffix) before sending it over the network. Potentially, we can also monitor it on the Cody Gateway side and error.
> 
> The bad part is that it modifies the string value until it's sent. It has multiple annoying side effects. E.g., we will need to account for the redundant suffix length when we calculate the chars remaining in the context window. Is there a better way?

What if we change all `PromptString.from*` methods to require the `ContextFilters` and to perform a check on the ignored path before we even construct the prompt string in the first place? This way we know that the final prompt string must also be of valid references. 

The issue this has is that:

- The policy could be outdated by the time toString is called 
  - Potentially fixable PromptString can be notified about policy changes?
- All callsites that use `PrompString.from` have to be made async (seems reasonable TBH)

So:

- All `PrompString.from*` methods return a Promise and require the `ContextFilterService` to be passed-in.
- Whenever we construct a prompt string from references, we check the references are valid. This pre-warms the cache
- Whenever toString is called, we check all references again (should be fast since the cache is warm?)

cc @dominiccooney

2024-04-22 12:29 UTC, philipp-spiess commented
BTW since I see @valerybugakov and me putting up more and more PRs against this branch, I'll go ahead and merge this. Let's continue the discussion on how to prevent issues of forgetting checks though.

2024-04-22 12:31 UTC, valerybugakov commented
>I'll go ahead and merge this.

YES!

2024-04-22 13:03 UTC, merged