Elaborate the agent protocol for Cody Ignore
sourcegraph/cody pull request #3858
Opened 2024-04-18 13:27 UTC by dominiccooney

- Removes `check/isCodyIgnored`, which was unused
- Adds client -> server method, `ignore/forUri` which gets a policy result (`'use'`, `'ignore'`)
- Adds server -> client notification, `ignore/didChange` for invalidating client cached policy results
- Adds client -> server method `testing/ignore/overridePolicy` for setting a cheesy regex-based policy, for testing

Part of #3641 

## Test plan

`pnpm -C agent test`

2024-04-19 07:03 UTC, valerybugakov approved these changes

2024-04-19 07:23 UTC, olafurpg requested changes

2024-04-19 07:23 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'ignore/didChange': [{}]
You can use `null` instead of `{}`

2024-04-19 07:23 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'testing/ignore/overridePolicy': [[[{ repoRe: string; uriRe: string } | null]]]
This type is very involved, I've looked at it for 2 minutes now and I'm still struggling to understand what the shape of the type is. Can we simplify this somehow? I recommend sticking with named interfaces as soon as you go beyond basic `{uri: string}` anonymous literals. What is the difference between this type and `{ repoRe: string; uriRe: string } | null`?

2024-04-23 02:05 UTC, dominiccooney commented
Thanks for your help with this @olafurpg .

@valerybugakov I'm aware this needs to be integrated with the async filter, I will do that in a follow-up. Just want this to for JetBrains development for now.

2024-04-23 08:38 UTC, olafurpg approved these changes
LGTM 👍🏻 Only minor comments, nothing blocking

2024-04-23 08:38 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'ignore/forUri': [{ uri: string }, IgnoreForUriResult]
nit: I generally try to use verbs in the second part of the RPC method name, and use nouns only if it's very awkward to use a noun. I think `codyignore` is also a bit easier to read since it's a noun.

```suggestion
    'codyignore/test': [{ uri: string }, IgnoreForUriResult]
```

Also, it should be fine to use an anonymous literal `{ policy: 'ignore' | 'use' }` here instead of `IgnoreForUriResult`. If it didn't work then I can look into fixing the bindings generator.

2024-04-23 08:38 UTC, olafurpg commented on lib/shared/src/cody-ignore/context-filter.ts
> +// listeners, etc. but lib/shared prevents doing that easily.
😢 This makes me want to move all of `lib/shared` into the `vscode/` directory. Alternatively, we can consider adding `@types/vscode` to `lib/shared` since it works anyways with the agent.

2024-04-24 02:39 UTC, merged

2024-04-25 05:49 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filter.ts
> +// listeners, etc. but lib/shared prevents doing that easily.
yes!