Chat: Fix prompt issue in Ollama chat client
sourcegraph/cody pull request #3881
Opened 2024-04-20 03:04 UTC by abeatrix

1. This PR fixes the issue of using PromptString as prompt text in the messages we send to the LLM, causing regression in chat response from some Ollama models.

2. Also updated the chat client for Ollama and Groq to have better error handling:
![image](https://github.com/sourcegraph/cody/assets/68532117/69645a9c-638c-4581-85c3-a6e23d2e6da3)

3. Log usage on complete for easier debugging purpose

Ollama:
![image](https://github.com/sourcegraph/cody/assets/68532117/d4b5a9f8-6089-41d2-81fa-13f77dcc95d3)

Groq:
![image](https://github.com/sourcegraph/cody/assets/68532117/57241cbb-181b-4613-979b-78749b20d845)

## Test plan

1. Run this branch in debug mode and follow our Ollama docs to set up Ollama with Cody
2. Try asking Cody a question

### Before

![image](https://github.com/sourcegraph/cody/assets/68532117/0d314ea1-3afc-498c-9608-6d25f9f67129)

### After

![image](https://github.com/sourcegraph/cody/assets/68532117/028d941f-78f3-4e69-8aa2-f116de79d021)

2024-04-22 02:23 UTC, dominiccooney requested changes
Could you tell me more about the specific reason PromptString was regressing ollama prompts?

2024-04-22 02:23 UTC, dominiccooney commented on lib/shared/src/llm-providers/ollama/chat-client.ts
> +                        cb.onChange(responseText)
This isn't right. You could read some data *and* reach the end of the stream, and you're discarding `value` here. This might only be working because the last message where ollama is done contains a hunk of data we don't use.

2024-04-22 02:23 UTC, dominiccooney commented on lib/shared/src/llm-providers/ollama/chat-client.ts
> +                    const data = textDecoder.decode(value, { stream: true })
I know you're just moving this around, but it does not look right. Either we are decoding `value` when we should be appending it to a buffer first and decoding the whole buffer, OR we don't need `stream: true` here because `value` is a complete value.

I expect it is the first case, and it is only working because the ollama server tends to flush at certain points.

You need to do something like:
- Use a `TextDecoderStream`
- Accumulate the decoded text into a string
- Break on newlines
- JSON.parse each chunk and act on it

2024-04-22 02:23 UTC, dominiccooney commented on lib/shared/src/llm-providers/ollama/utils.ts
> +export function getOllamaChatMessages(messages: Message[]): OllamaChatMessage[] {
We should not be converting these messages from PromptString to ordinary string here, that should happen right before we hit the network.

Yes, ollama is an interesting case because it is *probably* local. But there's 0 checks for that, let's just treat it like any other remote model for now.

2024-04-22 02:23 UTC, dominiccooney commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
Put a helper function here which converts the Ollama messages from PromptStrings to JSON. CC @philipp-spiess .

2024-04-22 15:46 UTC, abeatrix commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
Confirmed that the issue is fixed on main after @philipp-spiess 's PR 
![image](https://github.com/sourcegraph/cody/assets/68532117/bc2a7443-5deb-4f5c-af91-da99c3cdac2d)

2024-04-22 15:48 UTC, philipp-spiess commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
@abeatrix Do you have a log of what changed though? In both cases the serialized JSON should be the same? 🤔

2024-04-22 16:04 UTC, abeatrix commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
I cannot reproduce this issue on main after whatever you changed in your PR so it must be the helper function you added for here? 

Or are you able to reproduce this issue on main?

2024-04-22 16:25 UTC, philipp-spiess commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
I haven't tried to reproduce it before so it's unclear what the issue was in the first place. Your message makes it seem like there's some issue with the prompt being malformed but that's unexpected since it should be identical in the serlialized JSON string. Unless another change was made. 🤔

2024-04-22 16:40 UTC, abeatrix commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
none of my changes are available on main, and I couldn't reproduce the issue on main anymore when I can reproduce it consistently (as shown in my screenshot above) before.

> Your message makes it seem like there's some issue with the prompt being malformed but that's unexpected 

When i can reproduce it last week, where changing the promptString to a regular string fixed the issue for me that's why i assumed it was prompt being malformed. 

Maybe @dominiccooney can confirm if this is still an issue for him on main?

2024-04-25 08:27 UTC, dominiccooney requested changes
I believe there are still problems with ollama response decoding and this PR is on the right track. It just needs to go further in handling the incremental responses.

2024-04-25 08:27 UTC, dominiccooney commented on lib/shared/src/llm-providers/ollama/chat-client.ts
>          body: JSON.stringify(ollamaChatParams),
I have seen early truncation and repetition at 6db70c3fd28102900b75c66e4dac8966e85a28d2 but I have not had the opportunity to dig into whether it is the underlying model being weird, or our ollama adapter being weird.

Recalling our experience with UTF decoding of Anthropic completions, I would like to see the decoding hardened a bit per my earlier feedback:
- Don't assume network responses are chunked on UTF character boundaries.
- Don't assume that, having seen the end of the network response, that you have decoded all the characters in the response yet; the last packet may contain data.

2024-04-25 08:30 UTC, dominiccooney requested changes
Specific feedback inline.

2024-04-26 04:55 UTC, abeatrix commented on lib/shared/src/llm-providers/ollama/chat-client.ts
> +                        const parsedData = JSON.parse(value) as OllamaGenerateResponse
@dominiccooney hey Dom sorry i haven't got a chance to work on this since I''m still working on my sprint works, but I will try to pick this back up tomorrow. Will mark it as a draft until this is ready again, appreciate your feedback

2024-04-30 00:30 UTC, abeatrix commented
@dominiccooney i've applied your feedback to the PR:
- [x] Use a TextDecoderStream
- [x] Accumulate the decoded text into a string
- [x] Break on newlines
- [x] JSON.parse each chunk and act on it
- [x] Don't assume that, having seen the end of the network response, that you have decoded all the characters in the response yet; the last packet may contain data.
  - process `if (value)` where value will be decoded first, before checking for `if (done)`

2024-05-09 00:43 UTC, valerybugakov commented on lib/shared/src/llm-providers/ollama/chat-client.ts
> +                        const line = JSON.parse(chunk) as OllamaGenerateResponse
Similar to the completions client, we should buffer the chunks in case they are not cut on JSON boundaries. 

What do you think about reusing the response streaming/reading part from the completions client to keep this logic in one place?

2024-06-05 22:22 UTC, abeatrix commented
@dominiccooney @valerybugakov I've updated the PR to use the official Ollama js package for chat instead of implementing our own client. May I get your review again please?

2024-06-05 23:54 UTC, valerybugakov commented on lib/shared/src/llm-providers/ollama/chat-client.ts
> +        ollamaHost = endpoint
Do we need to mutate the `ollamaHost` variable?

2024-06-05 23:54 UTC, valerybugakov commented on lib/shared/src/llm-providers/ollama/chat-client.ts
> +        ollama = new Ollama({ host: endpoint })
Can we create `ollama` on every `ollamaChatClient` call and remove the mutable variable?

2024-06-05 23:54 UTC, valerybugakov commented on lib/shared/tsconfig.json
> +    "moduleResolution": "Bundler",
Is this addition required?

2024-06-06 00:01 UTC, abeatrix commented on lib/shared/tsconfig.json
> +    "moduleResolution": "Bundler",
I think so. Without it the client will complain with:

```
lib/shared/src/llm-providers/ollama/chat-client.ts:1:24 - error TS2307: Cannot find module 'ollama/browser' or its corresponding type declarations.
  There are types at '/Users/bwork/dev/cody-2/lib/shared/node_modules/ollama/dist/browser.d.mts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
  
  ```

2024-06-06 00:05 UTC, abeatrix commented
Verified Ollama still works with the latest commit:

![image](https://github.com/sourcegraph/cody/assets/68532117/bab79e9b-98db-4f57-8577-a6b7e8ac85a9)

2024-06-06 00:17 UTC, valerybugakov approved these changes
Nice!

2024-06-06 00:19 UTC, merged