adding context snippets and the repo name in the context summary
sourcegraph/cody pull request #3882
Opened 2024-04-20 20:26 UTC by hitesh-1997

## Test plan

2024-04-25 08:19 UTC, dominiccooney reviewed
Some questions and feedback inline.

2024-04-25 08:19 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const vscodeUri = vscode.workspace.workspaceFolders?.[0]?.uri
We are trying to avoid this API because it is rarely right. Workspaces can have multiple folders. What are you using `LOGGER_CONTEXT_REPO_NAME_FIELD` for?

2024-04-25 08:19 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                const gitUri = gitRemoteUrlFromGitExtension(vscodeUri)
I'm curious what the purpose of this data collection is. Would a hash be appropriate instead? Per-device or per-account salted hash? etc.

2024-04-25 08:19 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const contextSummary: { [key: string]: number | string } = {}
I'm not an expert in the logging system, but if you start logging strings you need to log into the "private" pocket of data that is ablated in the more widely accessible logs, see https://github.com/sourcegraph/cody/blob/main/ARCHITECTURE.md#telemetry

How have you tested that the logging works end to end?

@arafatkatze , is there a good person to tag on reviews for new logged data?

2024-04-26 13:09 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const contextSummary: { [key: string]: number | string } = {}
@dominiccooney is right.

- metadata: This gets sent to us on every event for both dotcom and enterprise users, but it can only contain numeric values
- privateMetadata: Only gets sent for dotcom users, but can contain arbitrary string values

Based on this, this should be moved to the new logging data out of contextsummary into privateContextSummary instead

2024-04-26 13:15 UTC, abeatrix requested changes
Comment inline

2024-04-26 13:15 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            contextSummary[LOGGER_CONTEXT_SNIPPET_SUMMARY_FIELD] = JSON.stringify(contextSnippetSummary)
This will not work iirc when contains value other than numeric values. 
Let's revert the change to the contextSummary and merge the new contextSnippetSummary with the privateContextStats on line 864 instead?

2024-04-26 13:34 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const contextSummary: { [key: string]: number | string } = {}
I found this guideline on data collection that might be of use: https://handbook.sourcegraph.com/departments/data-analytics/architecture/#transcript-events-from-dotcom-users

2024-04-26 14:21 UTC, hitesh-1997 commented
Hi @dominiccooney and @abeatrix 
Thanks a lot for your suggestions and response.
We had a discussion regarding the logging in standup and decided to modify the approach. I should have marked the PR maybe in draft while it was still work in progress. We currently want to log the `repo url`. Ideally, the repo name should be the one, from where the current context files are fetched. To this end, can you please help me with some questions:

1. Detecting if the repo is public or private: Since we only want to log the repo url if the repo is public, one solution i can think of is querying git api -- but that would involve a network call at every request -- do you know if there is a better way to do the same ? (I checked for some alternates like if we can get this via git cli etc -- but git cli doesn't have this support). I also tried exploring `vscodeGitApi` but can't seems to find solution there, but haven't explored in details. 

2. @dominiccooney I see we use the same api `vscode.workspace.workspaceFolders` in local-embeddings code to get the `repoPath` and further `repoName` in the bfg-private binary, and hence I tried to use the same api call. Can you please let me know if there is a better way to detect the `repoPath`  

I am marking the current PR in the draft state for now, and will change for review when I have the implementation ready for the points above.

2024-04-29 16:46 UTC, hitesh-1997 commented
> Hi @dominiccooney and @abeatrix Thanks a lot for your suggestions and response. We had a discussion regarding the logging in standup and decided to modify the approach. I should have marked the PR maybe in draft while it was still work in progress. We currently want to log the `repo url`. Ideally, the repo name should be the one, from where the current context files are fetched. To this end, can you please help me with some questions:
> 
> 1. Detecting if the repo is public or private: Since we only want to log the repo url if the repo is public, one solution i can think of is querying git api -- but that would involve a network call at every request -- do you know if there is a better way to do the same ? (I checked for some alternates like if we can get this via git cli etc -- but git cli doesn't have this support). I also tried exploring `vscodeGitApi` but can't seems to find solution there, but haven't explored in details.
> 2. @dominiccooney I see we use the same api `vscode.workspace.workspaceFolders` in local-embeddings code to get the `repoPath` and further `repoName` in the bfg-private binary, and hence I tried to use the same api call. I also noticied that symf uses, similar api `vscode.workspace.workspaceFolders?.[0]?.uri.fspath` to get the repoPath. Can you please let me know if there is a better way to detect the `repoPath`
> 
> I am marking the current PR in the draft state for now, and will change for review when I have the implementation ready for the points above.

Hi @dominiccooney 
Do you know if there is an alternate vscode git api we can use to check if a github repo is public or private. One solution we can do is build a local cache to store this data (which will query git api for the first time and store the git_repo_name to public/private status in the memory) Does this solution look alright for now ?

2024-05-01 17:41 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const vscodeUri = vscode.workspace.workspaceFolders?.[0]?.uri
Thanks for pointing this our Dominic, didn't know that.
For now to avoid getting blocked on training and get sufficient data, I added this condition:
```
const gitRemoteUrlList = gitRemoteUrlsFromGitExtension(vscodeUri)
            if (gitRemoteUrlList && gitRemoteUrlList.length === 1) {
```
With this condition although will miss logging some use cases, but some data should also be sufficient for training.

2024-05-01 17:46 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const contextSummary: { [key: string]: number | string } = {}
Thanks @dominiccooney and @abeatrix for pointing this out.
I changed the logging to the `privateMetadata` field. (Also added the logs in the example to confirm the logging works)
Although the field is getting logged correctly in the vscode debug console. Can you please let know if there any other modification I need to do, for eg: In pub/sub or sourcegraph backend (so that downstream processing pipeline does not ignore this). Adding @akalia25 to confirm this point.

2024-05-01 17:47 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            contextSummary[LOGGER_CONTEXT_SNIPPET_SUMMARY_FIELD] = JSON.stringify(contextSnippetSummary)
Thanks for pointing this out @abeatrix !!
I changed the actual logging to the `privateMetadata` field.

2024-05-02 04:57 UTC, abeatrix reviewed
Left some comments inline. I'm afraid I am still missing some context as in why we need to know if the repository is private or not before we log the codebase name. Can you elaborate more on that? I also notice your current approach would only validate git repositories that are hosted on github, is that the expected result?

Additional question: 
- are you trying to log that info for dot com users only, or also for enterprise users? 
-If it's only for dotCom users, could we just log the name of the codebase and do the private v.s. public matching offline?  
- since Sourcegraph.com doesn't support private repository, maybe we can just perform a one time check against dotCom to check if it's available there or not?

2024-05-02 04:57 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                    gitRemoteUrl: await this.getRepoGiturlIfPublic(),
Do we need to add the authStatus.isDotCom check here as well?

2024-05-02 07:02 UTC, hitesh-1997 commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +    private async queryGitApi(owner: string, repoName: string): Promise<RepoMetaData | undefined> {
done, changed to `queryGitHubApi `

2024-05-02 07:10 UTC, hitesh-1997 commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +                repoVisibility: repoData.private ? 'private' : 'public',
Hey @abeatrix 
Definitely, earlier whenver we get any error I was always returning `undefined` so that we don't log. But for specific case of `404` status code, I changed it to return `private` as repoVisibility.

2024-05-02 07:11 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                    gitRemoteUrl: await this.getRepoGiturlIfPublic(),
Thanks for noticing this !!
I added this condition

2024-05-02 07:27 UTC, hitesh-1997 commented
Hi @abeatrix 
Adding the response for your queries below :)

> I'm afraid I am still missing some context as in why we need to know if the repository is private or not before we log the codebase name
> are you trying to log that info for dot com users only, or also for enterprise users? 
> -If it's only for dotCom users, could we just log the name of the codebase and do the private v.s. public matching offline?
As per discussion on this internally with @chillatom @rishabhmehrotra, there were concerns about logging any information regarding private repos even for the dotcom users, as it could violate terms & condition on logging and decided that it would be best to start logging only for public repos.

> I also notice your current approach would only validate git repositories that are hosted on github, is that the expected result?
Yes,  this is expected for now. This should get us enough data and coverage of the repos to start with the training. Please note the goal of the PR is not to get the 100% coverage. Gettting this data for some repos should be enough to avoid getting blocked on training on cody prompt and repos.

> since Sourcegraph.com doesn't support private repository, maybe we can just perform a one time check against dotCom to check if it's available there or not?
Sorry I didn't get this. With this logging we get access to the tuples (`promptText`, `gitRepoUrl`) on which we can train offline. Can you please elaborate on this, what should we check against dotcom repos ?

2024-05-02 11:06 UTC, susnato commented
Hi @hitesh-1997 by the way are we logging the commit hash for the repos?

2024-05-03 20:59 UTC, hitesh-1997 commented
> Hi @hitesh-1997 by the way are we logging the commit hash for the repos?

yes, we are logging `giturl` and `commit` fields.

2024-05-04 04:03 UTC, abeatrix commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +export class RepoMetadatafromGitApi {
Maybe Beyang or Dom can confirm, but we probably don't need a new instance for tracking repo mapping since there is a [codebaseRepoIdMapper in CodebaseStatusProvider](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/CodebaseStatusProvider.ts?L45), or we can just update the current `CodebaseIdentifiers` to include repoVisibility?

2024-05-04 04:29 UTC, hitesh-1997 commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +export class RepoMetadatafromGitApi {
I think this is different from `codebaseRepoIdMapper`. 

This class just gets a repoVisibility (i.e. if a repo is public or private) and stores it in a local `Map` to avoid network calls. This class is used to set the value of [`isPublic` in the `CodebaseIdentifier`](https://github.com/sourcegraph/cody/pull/3882/files#diff-43f7103f58d4fafcd5079071965fd20533d583dbc0a65c4393efaa5c226a8b36R167).

So, in summary this class does what you suggested in your PR [here](https://github.com/sourcegraph/cody/pull/4043/files#diff-f58fc2635f09145f2bf5b08cd81122f890d4c5c9b8e6934558e3f60b81171f0dR110) and adds a cache on top of it to reuse the results.

Please let me know if the name of the class itself is confusing.

2024-05-04 04:33 UTC, abeatrix commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +    }
```suggestion
    private async queryGitHubApi(owner: string, repoName: string): Promise<RepoMetaData | undefined> {
        const apiUrl = `https://api.github.com/repos/${owner}/${repoName}`
        const metadata = { owner, repoName, repoVisibility: false}
        try {
            const response = await fetch(repositoryUrl, { method: 'HEAD' })
            metadata.repoVisibility = response.ok
            return metadata
        } catch (error) {
            return undefined
        }
    }
```
I think we can just check if the response returns `ok` here since it returns false if 404?

<img width="753" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/ca573d83-1254-4d25-adaf-dfe4feacf3cd">

Example from https://github.com/sourcegraph/cody/blob/44ae4407980ee21ae0793143bd92c0d137810bd7/vscode/src/repository/git-extension-api.ts#L110-L127

2024-05-04 05:25 UTC, hitesh-1997 commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +    }
Thanks for the suggestion, looks much cleaner now.
In addition to response.ok, I am also checking `repoData.private` as per [github api documentation](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository).
`metadata.isPublic = response.ok && repoData.private === false `

2024-05-06 10:30 UTC, hitesh-1997 commented
Hi @abeatrix 
Can you please let me know if there are any additional comments or it look good to be merged ?

2024-05-06 15:44 UTC, abeatrix approved these changes
approve to unblock. 
The logging side of things looks good to me. we are only logging this for non-enterprise users. 

I am not sure if we need a new class for mapping codebase visibility, so it would be great if you could get @dominiccooney 's confirmation on that first.

2024-05-06 15:44 UTC, abeatrix commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +    private async getRepoMetadataIfPublic(): Promise<string> {
nit: this method seems more relevant to CodybaseStatusProvider than SimpleChatPanel provider.

2024-05-06 16:08 UTC, hitesh-1997 commented
> approve to unblock. The logging side of things looks good to me. we are only logging this for non-enterprise users.
> 
> I am not sure if we need a new class for mapping codebase visibility, so it would be great if you could get @dominiccooney 's confirmation on that first.

Thanks for the review @abeatrix :)
My reasoning for making this in a separate class is to model a separate functionality which involves `github api` interactions and since such interactions results in additional network calls, we might want to add additional storage for payload giving the same output. For eg: `github repo` is either `public` or `private` should not change within a user session, so added a seperate map (For long term  persistence we can also use vscode local storage) etc etc. So, I was thinking, all this could be better to do in a different class rather than mixing with existing functionality.

But @dominiccooney @abeatrix please feel free to suggest any other alternatives you think would be better from architecture point of view, would be happy to incorporate the change :)

2024-05-07 10:24 UTC, merged

2024-05-08 08:36 UTC, keegancsmith commented on vscode/src/repository/repo-metadata-from-git-api.ts
> +}
@hitesh-1997 this implementation won't handle a bunch of cases, eg SSH clone URLs. Luckily we already have a pretty robust function for massaging a gitURL `convertGitCloneURLToCodebaseName`