VS Code: clarify ignore/exclude everything constants
sourcegraph/cody pull request #3892
Opened 2024-04-22 04:18 UTC by valerybugakov

## Context

- Clarify ignore/exclude everything constants and related helper methods
- Follow-up for review comments in https://github.com/sourcegraph/cody/pull/3869
- Part of https://github.com/sourcegraph/cody/issues/3641

## Test plan

CI

2024-04-22 08:21 UTC, taras-yemets commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +            throw error
In what case do we expect `error` that is not instance of `Error`?

2024-04-22 08:28 UTC, taras-yemets commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +            this.contextFilters?.exclude.length === INCLUDE_EVERYTHING_CONTEXT_FILTERS.include.length
I understand that we expect both `include` and `exclude` to be empty arrays, but this definition seems a bit confusing to me (especially the part where we compare `exclude` with `include`).

2024-04-22 08:53 UTC, taras-yemets reviewed
Using `INCLUDE_EVERYTHING_CONTEXT_FILTERS` and `EXCLUDE_EVERYTHING_CONTEXT_FILTERS` approach seems a bit confusing to me.

I think a simpler and more readable approach would be:
1. Make [`graphqlClient.contextFilters`](https://github.com/sourcegraph/cody/blob/00592623b8a93bc60e5c3d6587a4fc0e1b57f265/lib/shared/src/sourcegraph-api/graphql/client.ts#L555) return
- `ContextFilters` value received from the server (UPD: value can be `null` too if context filters are not defined in the site config)
- `null` in case of outdated API error
- `error` in case of an unexpected error
2. [`isUriAllowed`](https://github.com/sourcegraph/cody/blob/00592623b8a93bc60e5c3d6587a4fc0e1b57f265/lib/shared/src/cody-ignore/context-filters-provider.ts#L135) checks `this.contextFilters` value and:
- returns `true` if `this.contextFilters` is `null`
- returns `false` if `this.contextFilters` is an error (UPD: it can be either an error from `graphqlClient.contextFilters` or parsing result error, e.g. invalid regex)
- checks if repo name is allowed if `this.contextFilters` value is of `ContextFilters` type. 

WDYT?

2024-04-22 08:58 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +            this.contextFilters?.exclude.length === INCLUDE_EVERYTHING_CONTEXT_FILTERS.include.length
This is a typo. Fixing it now

2024-04-22 09:04 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +            throw error
Updated to always log errors 👍

2024-04-22 09:45 UTC, philipp-spiess commented
Agree w/ @taras-yemets, I also found this a bit confusing especially the comparison that just happens to work because the array has no elements (but there's no guarantee that any of the empty sets will stay empty 😬).

2024-04-22 13:13 UTC, dominiccooney requested changes
Some ideas to simplify and harden inline.

2024-04-22 13:13 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * Default value used on the client in case context filters are not set.
I'm still a bit uneasy about this. This policy can't be produced by the backend, because it requires include/exclude, if present, to have at least one value.

Wouldn't it reflect the RFC more closely if we made these types something like `null | readonly [T, ...T[]]` where `T` is the rule type?

2024-04-22 13:13 UTC, dominiccooney commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +     * Used to return early from `isUriAllowed` in case client encountered errors fetching context filters.
Could we keep it simple and say we'll set the filters to be exactly `EXCLUDE_EVERYTHING_CONTEXT_FILTERS` and then make the condition just `this.contextFilters === EXCLUDE_EVERYTHING_CONTEXT_FILTERS`? (Similarly for include everything?)

This is an even faster test than the length checking that happens here, and it is much simpler, too.

Explicit rules which include or exclude everything may fall off the fast path, but that seems fine. We could always elaborate the fast path later if it turns out to be a bottleneck.

2024-04-22 13:13 UTC, dominiccooney commented on lib/shared/src/sourcegraph-api/graphql/client.ts
>      exclude: [{ repoNamePattern: '.*' }],
You should `Object.freeze` the object literal and arrays here. (You need to do each, freeze is not deep.)

2024-04-23 02:47 UTC, valerybugakov commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> + * Default value used on the client in case context filters are not set.
The problem I wanted to solve here with virtual values is that the backend spec doesn't match the client states one-to-one. Here are potential `ContextFiltersProvider.contextFilters` values:

- `null,` we didn't fetch context filters yet, that's why we ignore everything (@taras-yemets, here's the difference with your proposed return values)
- `INCLUDE_EVERYTHING_CONTEXT_FILTERS,` we fetched and got `null` or an outdated API response.
- `EXCLUDE_EVERYTHING_CONTEXT_FILTERS`, we fetched and got unexpected errors.
- `ContextFilters` received from the backend with the correct structure

I will make the `INCLUDE_EVERYTHING_CONTEXT_FILTERS` and `EXCLUDE_EVERYTHING_CONTEXT_FILTERS` states compatible with the backend spec. Agree that it contributes to the confusion and it's easy to avoid that.

2024-04-23 03:25 UTC, valerybugakov commented on lib/shared/src/cody-ignore/context-filters-provider.ts
> +     * Used to return early from `isUriAllowed` in case client encountered errors fetching context filters.
We parse context filters before assigning them to `this.contextFilters` so we do not preserve the references equality.

2024-04-23 03:34 UTC, valerybugakov commented on lib/shared/src/sourcegraph-api/graphql/client.ts
>  }
Updated types to match the backend spec. Now shortcut constants are backend-spec-compliant.

2024-04-23 03:55 UTC, dominiccooney requested changes
Ok sounds good. 

I wanted immutability because these "constants" hang around indefinitely and if people mutate them we will be in for a bad time. But I can do it later if it is too hard right now.

2024-04-23 04:00 UTC, dominiccooney approved these changes
Really approving this time, whoops

2024-04-23 05:39 UTC, merged