Add V2 Telemetry check for E2E Tests
sourcegraph/cody pull request #3974
Opened 2024-04-29 19:07 UTC by akalia25

This PR adds V2 telemetry checking on our E2E tests, to ensure that with each test we are recording the right events. This will help prevent regressions and increase stability on our v2 analytics.

## Test plan
Test via `pnpm test:e2e` and ensure that all tests are logging the correct events

2024-04-29 20:53 UTC, bobheadxi approved these changes
overall LGTM, but I would prefer another way to set up the mock exporter instead of hijacking production code (graphql exporter) with testing mechanisms

2024-04-29 20:53 UTC, bobheadxi commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        }
nit - I would prefer that MockServerTelemetryExporter be used directly instead if possible (replacing the GraphQL exporter entirely if possible). This ensures that this exporter doesn't grow to become difficult to understand with various test scenarios (as v1 logging did)

2024-04-30 19:48 UTC, abeatrix approved these changes
YAY! Does this mean we can start removing `telemetryService`?

2024-05-01 14:14 UTC, akalia25 commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +                this.anonymousUserID || 'AnonymousTestUserId'
@abeatrix you raise a good point! - I think it would be valuable to continue capturing the actual `anonymousUserId` from our tests. Having the actual anonymous ID would allow us to validate that the ID persists correctly across the test session. And then, falling back to a value like `AnonymousTestUserId` can be used as an indicator that something may be wrong with the ID generation 🤔

2024-05-01 14:18 UTC, akalia25 commented
> YAY! Does this mean we can start removing `telemetryService`?

We are VERY close!!! Currently, we only need to log v2 events now 🚀, but for removing, we're holding off on that for now, just so we can remove it all in one big push :)

2024-05-01 14:21 UTC, akalia25 commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        }
Thanks for the recommendation @bobheadxi!! If you don't think this is a blocking change, I'd love to work on the above on a separate PR, and with someone who has more expertise than me on GraphQL 😅

2024-05-01 16:27 UTC, bobheadxi commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        }
It's not about expertise on GraphQL :) It's about using `MockServerTelemetryExporter` elsewhere - `MockServerTelemetryExporter` just implements our exporter interface, and it's meant to be plugged in at the recorder level. This makes it much easier to reason about when and where things go to a mock exporter rather than a real one, instead of having to deal with many levels of switches

Example: the default one _also_ checks for `CODY_TELEMETRY_EXPORTER`. One might read this now and meet surprise behaviour all the way down in the GraphQL client as well https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts?L58-60

2024-05-01 16:27 UTC, bobheadxi commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        }
Why don't we just update this condition here?

2024-05-01 16:29 UTC, bobheadxi requested changes
Sorry, I think https://github.com/sourcegraph/cody/pull/3974/files#r1583747661 might be a blocking change request after all, since the default one already has a condition for testing: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts?L58-60 

_And_ the recorder initialization func _also_ has conditions for testing: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@7d385240264090f7bfb0d502a76049fd6a05de58/-/blob/vscode/src/services/telemetry-v2.ts?L39-58

I'd prefer not to add a third level of "testing-or-not" toggle here 😬

2024-05-01 18:36 UTC, akalia25 commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +        }
Thanks for explaining this in detail. Removing `MockTelemetryExporter` here and confirmed that its being set correctly on debug mode [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@7d385240264090f7bfb0d502a76049fd6a05de58/-/blob/vscode/src/services/telemetry-v2.ts?L39)

2024-05-01 19:24 UTC, bobheadxi approved these changes
thanks for addressing feedback :)

2024-05-01 21:13 UTC, merged