agent: add editor/quickpick
sourcegraph/cody pull request #4
Opened 2023-07-10 14:04 UTC by tjdevries

2023-07-10 14:06 UTC, olafurpg requested changes

2023-07-10 14:06 UTC, olafurpg commented on agent/src/protocol.ts
> +    'editor/quickpick': [string[], string]
Can we add a docstring explaining how this works?

2023-07-10 14:12 UTC, olafurpg requested changes
What is the fallback behavior if the server doesn't support this functionality? Should we add a server capability so that the agent can pick the default when the client doesn't support quickpick?

2023-07-10 14:14 UTC, tjdevries commented
Hmm... can we say this is a required one? I'm not sure how we want to handle capabilities like this. Is there any way we can say some things "must" be implemented by a client?

2023-07-10 14:34 UTC, olafurpg approved these changes
LGTM 👍🏻 

We can address more advanced scenarios with a followup PR. For now, For now, I think it's reasonable to expect all clients to implement this functionality and we can figure out how to potentially avoid user interaction in the future. For example, if we're writing a Python benchmarking client then it would be desirable to be able to avoid interaction steps like this.

2023-07-10 19:44 UTC, SuperAuguste commented on agent/src/protocol.ts
> +    'editor/quickpick': [string[], string]
Note that the response might be null in some scenarios (if the user were to dismiss the quickpick prompt, for example) - this should be reflected here :)

2023-07-11 18:29 UTC, tjdevries commented
I changed it to be an object @olafurpg to give us a little more flexibility going forward. What do you think?

2023-07-12 18:20 UTC, olafurpg commented on agent/src/protocol.ts
> +    items: string[]
How about making these objects as well? This allows us to add more metadata in the future like icons or detailed text.
```suggestion
    items: QuickPickItem[]
```

2023-07-12 18:21 UTC, olafurpg commented on agent/src/protocol.ts
> +    items: string[]
Something in this direction, which avoids the `default?: string` property
```ts
interface QuickPickItem {
  id: string
  title: string
  default?: boolean
}
```

2023-07-14 09:45 UTC, olafurpg commented on agent/src/protocol.ts
> +    items: string[]
In the long-term, it might make sense to eventually have icons for things like fuzzy symbol finders. It's not something we need to have in the protocol right now, but I think it's nice to be able to add new properties to quickpick items if we want to.

In the short-term, having a separate ID and title is useful.

2023-07-17 11:19 UTC, tjdevries commented on agent/src/protocol.ts
> +    items: string[]
should the item have `default`? I guess it's fine for if we want to select more than one

2023-07-17 11:32 UTC, olafurpg commented on agent/src/protocol.ts
> +    items: string[]
I prefer `QuickPickItem.default: true` over `QuickPickParams.default`

2024-02-22 01:45 UTC, closed without merging