Command: new experimental command for generating commit messages
sourcegraph/cody pull request #4130
Opened 2024-05-10 01:31 UTC by abeatrix

The commit introduces a new experimental Cody command for generating commit messages:

<img width="797" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/5069148f-1d79-4bf3-bfdb-e87717f240dd">

- `cody.command.generate-commit`: Generates a commit message based on the staged changes.
- `cody.command.abort-commit`: Aborts the commit message generation process.

The commands are available in the Source Control view and the Command Palette when a Git repository is open.

(This commit was generated by the new Cody command 😍 )

### TBD

- [ ] Should we keep generating commit without including the ignored items? Current behavior is to display the error in the input box to let user know that there is an ignored file included.
- [ ] If there is no staged files, should we still generate commit for unstaged files?

## Test plan

#### From the Cody Commands sidebar

![cody_commit](https://github.com/sourcegraph/cody/assets/68532117/e9e17426-955c-480f-b4b7-40f0cebc787e)

1. Start Cody in dev mode from this branch
2. Make some changes in your editor, and leave them unstaged
3. Click on the `Generate Commit` in the `Cody Commands sidebar`
4. You should be redirected to the Source Control sidebar
5. The Source Control panel will be focused, and Cody's response will start streaming into the input box directly
6. Verify Cody's response

####  From the Source Control sidebar

![commit_pr](https://github.com/sourcegraph/cody/assets/68532117/6d247805-2282-4c66-a2ec-d99f50dcb768)

1. Start Cody in dev mode from this branch
2. Make some changes in your editor, and leave them unstaged
3. Open the Source Control sidebar, and make sure the commit input is empty
4. Hover over the commit input box to see Cody icon shows up in the title bar
5. Click on the Cody icon in the title bar
6. Cody's response will start streaming into the input box directly
7. Verify Cody's response

When an ignored file is detected

![codycommit](https://github.com/sourcegraph/cody/assets/68532117/b789d169-3028-4011-850c-49f2ec5de947)

1. Start Cody in dev mode from this branch
2. Make changes in a Cody ignored file
3. Click on the `Generate Commit` in the `Cody Commands sidebar`or Cody icon in the Source Control  panel.
4. You should be redirected to the Source Control sidebar
5. The Source Control panel will be focused
6. An error message will show up about the ignored file

2024-05-10 01:45 UTC, abeatrix commented on vscode/src/commands/context/git-api.ts
> +        const diffOutput = await gitRepo?.diff(true)
```suggestion
        const hasStagedChanges = gitRepo?.state?.indexChanges?.length
        const diffOutput = await gitRepo?.diff(hasStagedChanges)
```

@RXminuS @umpox this is what we need to change if we've decided to generate commit for unstaged files if there is no staged files

2024-05-10 01:48 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        throw new Error('Cody cannot generate commit for ignored files.')
```suggestion
        vscode.window.showWarningMessage('The commit message will not include changes made in ignored files.')
```

@RXminuS @umpox if we don''t want to block users from generating the commit when ignored files are detected

2024-05-10 13:07 UTC, umpox requested changes
Nice, left some comments of things I think we should do. I won't get further than this today (need to look into Edit issues on JetBrains), but will take a look next week hopefully.

Also cc @toolmantim for a design review here

2024-05-10 13:07 UTC, umpox commented on vscode/src/commands/scm/source-control.ts
> +        const isGenerating = abortController !== undefined
Could we possibly use something more specific? Like `this.inProgress` instead of checking for the presence of an abortController

2024-05-10 13:07 UTC, umpox commented on vscode/src/commands/scm/source-control.ts
> +        throw new Error('Cody cannot generate commit for ignored files.')
Yeah, let's do this!

2024-05-10 13:07 UTC, umpox commented on vscode/src/commands/scm/source-control.ts
> +                throw new Error(message?.error?.message)
```suggestion
                throw new Error(message.error.message)
```

2024-05-10 13:21 UTC, RXminuS commented on vscode/package.json
> +        "when": "cody.activated && cody.isGeneratingCommit"
Shouldn't have to as isGeneratingCommit can't be set otherwise

2024-05-10 13:24 UTC, umpox commented
Also, idea: We should use the typewriter `lib/shared/src/chat/typewriter.ts` to make the streaming of the text into the input box more fluid

2024-05-10 13:39 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        const sourceControlInputbox = scm?.inputBox ?? repository?.inputBox
We don't get the scm if this is called from the Cody sidebar 🕺

2024-05-10 13:42 UTC, umpox commented on vscode/src/commands/scm/source-control.ts
> +        const sourceControlInputbox = scm?.inputBox ?? repository?.inputBox
Ah that's annoying! :( Maybe we can check the type and do the additional placeholder and enabled UX if it's an `scm.inputBox`?

Would be useful to add telemetry to compare usage between the CTA in the scm area, and the CTA in the Cody sidebar!

2024-05-10 13:46 UTC, RXminuS commented on vscode/src/commands/scm/source-control.ts
> +                throw new Error(message?.error?.message)
I've changed this so that instead we show a notification that some files were skipped when generating the commit message, but the command still succeeds

2024-05-10 14:04 UTC, abeatrix commented on vscode/src/commands/scm/prompts.ts
> +Do not enclose the suggested commit message in backticks. Skip preamble. Only respond with the commit message.`
We can add the prompt for header and make it configurable so people can choose which option they prefer? 

Personally prefer the whole message instead of just the header, and I notice copilot is generating just the header while gitlens is doing whole message. I think both are valuable in different cases. What do you think? @RXminuS @umpox

2024-05-10 14:06 UTC, abeatrix commented on vscode/src/commands/scm/prompts.ts
> +Do not enclose the suggested commit message in backticks. Skip preamble. Only respond with the commit message.`
Or we can have two different commands for both 💃

2024-05-10 14:11 UTC, abeatrix commented on vscode/package.json
> +        "title": "Stop Cody from Generating Commit (Experimental)",
This is more for displaying in the command palette. But this should also work if I update the group, thanks!

2024-05-10 14:35 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +    private modelProvider = getDotComDefaultModels()[0]
Sure. I'll change it in the auth step below in `initializeGitAPI()`, since this is just a placeholder value to avoid type error 😆

2024-05-10 14:38 UTC, RXminuS commented on vscode/src/commands/scm/prompts.ts
> +Do not enclose the suggested commit message in backticks. Skip preamble. Only respond with the commit message.`
I think part of this needs to move to a Default Commit Template and we keep the instructions to follow the template and be as concise as possible whilst still following the guide.

2024-05-10 16:50 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        throw new Error('Cody cannot generate commit for ignored files.')
updated by Rik

2024-05-10 17:15 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        const generatingCommitTitle = 'Generating commit message...'
@toolmantim suggested [Generating commit message...](https://sourcegraph.slack.com/archives/C05AGQYD528/p1714624130667359?thread_ts=1714574779.941219&cid=C05AGQYD528)
 and iirc the reason is the format that other parts of VS Code are using 😄

2024-05-10 17:16 UTC, abeatrix commented on vscode/src/commands/scm/prompts.ts
> +Do not enclose the suggested commit message in backticks. Skip preamble. Only respond with the commit message.`
updated!

2024-05-10 17:43 UTC, abeatrix commented on vscode/src/commands/context/git-api.ts
> +        const diffOutputByFiles = diffOutput.trim().split('diff --git ')
i'll use the api to get the list of files instead

2024-05-11 06:29 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        const isGenerating = abortController !== undefined
@RXminuS and i chatted about this earlier and we think this is easier because we will still need to reset the abortController if we switch to use `this.inProgress`, but we can still change it if you don't agree :)

2024-05-11 06:30 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +    private modelProvider = getDotComDefaultModels()[0]
updated

2024-05-11 06:30 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        !stagedChanges && unstagedChanges && (await vscode.commands.executeCommand('git.stageAll'))
removed

2024-05-11 06:34 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        const generatingCommitTitle = 'Generating commit message...'
i think Rik tried earlier but it doesn't work, and we think it's ok to leave it enabled since the stream will just override what the users type during the stream, and hopefully learn not to do it again 😆

2024-05-11 06:35 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +                title: 'Generating commit message...',
This aligns with what tim suggested in the [thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1714624130667359?thread_ts=1714574779.941219&cid=C05AGQYD528), and IIRC, he mentioned this is the format that matches with the VS Code UI

2024-05-11 06:42 UTC, abeatrix commented on vscode/src/commands/index.ts
> +        description: 'Generate Commit (Experimental)',
I originally had it set to Generate Commit Message (Experimental) but then (Experimental) will get cut off in the sidebar, is that ok?

<img width="1987" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/e77f84ba-1c85-4f38-9914-96c8ae901f26">

2024-05-11 06:44 UTC, abeatrix commented on vscode/src/commands/scm/source-control.ts
> +        sourceControlInputbox.value = generatingCommitTitle
updated by @RXminuS !

2024-05-11 06:48 UTC, abeatrix commented on vscode/src/commands/context/git-api.ts
> +            const uri = vscode.Uri.joinPath(gitRepo.rootUri, uriFromOutput.trim())
i updated the code to use the API to get the list files from the working tree to match the split to verify if the split is valid. Feel free to change it to use parse-diff, but I think we can do that in a follow-up? wdyt?

2024-05-13 10:54 UTC, umpox commented on vscode/src/commands/context/git-api.ts
> +            const uri = vscode.Uri.joinPath(gitRepo.rootUri, uriFromOutput.trim())
Cool, thanks 👍

2024-05-13 10:55 UTC, umpox commented on vscode/src/commands/index.ts
> +        description: 'Generate Commit (Experimental)',
It may get cut off right now, but when we remove the "Experimental" it will be fine, and depends on the sidebar width too! I'll update, just because "Generate Commit" kinda feels like it's going to decide what files/lines should be included in the commit

2024-05-13 10:56 UTC, umpox commented on vscode/src/commands/scm/source-control.ts
> +        sourceControlInputbox.value = generatingCommitTitle
awesome :)

2024-05-13 11:05 UTC, umpox approved these changes
Awesome, great team effort! @abeatrix and @RXminuS

I think it's looking really good, the only thing I'm a little unsure about is the prompt right now. Still feels quite long, WDYT @RXminuS?

Happy to merge and iterate on this though :)

2024-05-13 12:42 UTC, RXminuS commented
I think let's merge the function and then iterate on the response quality. We can then also add a few different prompts and some metrics on which one's gets comitted as suggested (or hamming distance?).

2024-05-13 13:06 UTC, umpox commented
@RXminuS Sounds good, anything you want to add, or happy to merge this?

2024-05-13 13:08 UTC, RXminuS commented
I still need to merge my e2e test fix I think because they don't pass yet right?

2024-05-13 13:10 UTC, umpox commented
@RXminuS 👍 yep (only just noticed lol :D)

2024-05-13 22:12 UTC, RXminuS approved these changes

2024-05-14 15:40 UTC, merged