commands: getContextFileFromUri treats empty ranges as full file
sourcegraph/cody pull request #4443
Opened 2024-06-03 14:35 UTC by keegancsmith

"Add file to cody chat" command from a right click on a file would fail since we would have an empty range set. This treats any empty range as an indication the user wanted to add the whole file, which should plug the hole for other potential call sites on getContextFileFromUri.

Additionally if we do not have a range defined, we now do not set range on the returned ContextItem. This is so we render the file in chat as just the filename, rather than the filename with the range 1:lineCount.

Test Plan: Manually added and removed a file from chat. Then added the file via right click on the text area, right click on the explorer. Additionally tested that selecting text and right clicking correctly selected just the range.

2024-06-03 14:38 UTC, abeatrix approved these changes
ty!

2024-06-03 14:38 UTC, abeatrix commented on vscode/src/commands/context/file-path.ts
> -            range = range ?? new vscode.Range(0, 0, endLine, 0)
Hmm I thought this would treat the undefined range as the full file

2024-06-03 14:41 UTC, keegancsmith commented on vscode/src/commands/context/file-path.ts
> -            range = range ?? new vscode.Range(0, 0, endLine, 0)
it does, but it ends up rendering the item in the UI with line ranges. By leaving it off we just render the context item as the filename (which implies the full file)

2024-06-03 14:42 UTC, abeatrix commented on vscode/src/commands/context/file-path.ts
> -            range = range ?? new vscode.Range(0, 0, endLine, 0)
Oh gotcha, thanks for explaining!

2024-06-03 16:55 UTC, keegancsmith commented on vscode/test/e2e/command-custom.test.ts
> +        chatContext.getByRole('link', { name: withPlatformSlashes('lib/batches/env/var.go') })
@abeatrix I don't really understand how the code I change only affects these lines in the e2e test. But when looking at the behaviour this is better and really anytime we get something from the active editor state it should be the file without line ranges if there is no active selection.

2024-06-03 17:08 UTC, keegancsmith commented
hmm, I think I need to do a bit more work here. One of the agent tests detected some suspicious changes in the transcript we generate.

<img width="1728" alt="image" src="https://github.com/sourcegraph/cody/assets/187831/8c1e25e4-3bcf-4483-a96d-4a204785206e">

2024-06-03 18:03 UTC, abeatrix requested changes

2024-06-03 18:03 UTC, abeatrix commented on vscode/src/commands/context/file-path.ts
>              }
```suggestion
            const endLine = Math.max(doc.lineCount - 1, 0)
            range = range ?? new vscode.Range(0, 0, endLine, 0)
            
            const isFullFile = range.end.line === doc.lineCount - 1
```

I think we still want to check the existing range to see if it's full file. If yes, then we remove it from the `return` statement below instead?

```ts
            return [
                {
                    type: 'file',
                    content,
                    uri: file,
                    source: ContextItemSource.Editor,
                    range: isFullFile? undefined : toRangeData(range),
                    size,
                },
            ] satisfies ContextItem[]
```

2024-06-04 07:21 UTC, keegancsmith commented on vscode/src/commands/context/file-path.ts
>              }
aah nice catch. That probably explains some of the weirdness I was seeing.

2024-06-04 07:23 UTC, keegancsmith commented on vscode/src/commands/context/file-path.ts
>              const content = doc?.getText(range).trim()
It doesn't work the same. range being empty means that it has zero length not that it is undefined. So for example when you don't have a selection the vscode can return a range which has zero length but starts at the position of the cursor. This was leading to getText returning an empty string.

2024-06-04 13:07 UTC, keegancsmith reviewed
@abeatrix can I get a re-review. As I started fixing this the change grew into some fixes in unique-context as well.

2024-06-04 13:07 UTC, keegancsmith commented on vscode/src/commands/context/file-path.ts
> +            if (!content.trim()) {
I removed the trim from content since trailing newlines are actually part of the content and is how it works in other parts of our codebase when getting context. This also avoids how the range maps onto content not making sense. I believe the original intention of the trim call was to avoid adding content which was just an empty line. This will still be the case since we keep the check against trimmed content.

Note: removing the trim from the content affected the agent recording. The only difference in the recording is we now have the newline in the transcript we send to the LLM

2024-06-04 13:07 UTC, keegancsmith commented on vscode/src/prompt-builder/unique-context.test.ts
> +        }
I made this change so that `content` reflects the passed in range. Previously isUniqueContextItem would never look at content, but now that it does it needs to have reasonable values.

2024-06-04 13:07 UTC, keegancsmith commented on vscode/src/prompt-builder/unique-context.test.ts
> +        })
This test case demonstrates an issue before this PR which seemed to happen with openTabs and other custom commands. You could have the whole file as "selected" context, then as an opentab have the whole file again (but without ranges set). We would end up not deduplicating that. With this PR we now do.

2024-06-04 13:07 UTC, keegancsmith commented on vscode/src/prompt-builder/unique-context.test.ts
> +        })
This is a bug I noticed while doing this PR. If we do have 3 items in the same file, we only ever do the check against the first added file since we used to return early. Now we only return early if the item is indeed a duplicate.

2024-06-04 14:27 UTC, abeatrix approved these changes
Thanks for fixing and adding the tests with details!

Is the agent recordings needed for this PR? Asking because I noticed the only changes in the recordings are the `-` at the begging of the text which doesn't seem to be related to the changes you made (or maybe Github is not showing it in the diff view)

![image](https://github.com/sourcegraph/cody/assets/68532117/96a44e4d-8661-40b3-b570-227e8aabc827)

2024-06-04 14:27 UTC, abeatrix commented on vscode/src/prompt-builder/unique-context.ts
> +            if (item.range && !itemToAddRange && equalContent(item, itemToAdd)) {
```suggestion
            if (!itemToAddRange && equalContent(item, itemToAdd)) {
```

This is my bad, just noticed we already exit if `!item.range` on line 61.

2024-06-04 14:27 UTC, abeatrix commented on vscode/src/prompt-builder/unique-context.ts
> +    return !!item1.content && item1.content === item2.content
```suggestion
    return !!item1.content && item1.content === item2.content
```

QQ: should we compare the trimmed content for cases where the differences are new lines etc?

2024-06-04 14:36 UTC, keegancsmith commented
> Is the agent recordings needed for this PR? Asking because I noticed the only changes in the recordings are the `-` at the begging of the text which doesn't seem to be related to the changes you made (or maybe Github is not showing it in the diff view)

See my comment here https://github.com/sourcegraph/cody/pull/4443#discussion_r1625963303

That just tells yaml to not trim the final newline, so is an actual change.

2024-06-04 15:35 UTC, keegancsmith commented on vscode/src/prompt-builder/unique-context.ts
> +            if (item.range && !itemToAddRange && equalContent(item, itemToAdd)) {
Cool, will update this and line 72.

2024-06-04 15:35 UTC, keegancsmith commented on vscode/src/prompt-builder/unique-context.ts
> +    return !!item1.content && item1.content === item2.content
My initial reaction is to not treat whitespace as not significant. In particular I think about languages like python. However, in this case we are talking about the full file, so leading and trailing whitespace does indeed seem not significant. So I will update this check to match your suggestion.

2024-06-04 16:45 UTC, merged