adding additional logging for autocomplete feature
sourcegraph/cody pull request #4501
Opened 2024-06-08 13:57 UTC by hitesh-1997

## Test plan

2024-06-10 07:25 UTC, janhartman approved these changes

2024-06-10 07:25 UTC, janhartman commented on vscode/src/repository/git-extension-api.ts
> +            localFolder: currentFile,
Shouldn't you use [path.dirname()](https://nodejs.org/api/path.html#pathdirnamepath) if you want only the directory?

2024-06-10 07:25 UTC, janhartman commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +export interface InlineCompletionItemRetrivedContext {
```suggestion
export interface InlineCompletionItemRetrievedContext {
```

2024-06-10 10:19 UTC, rafax commented on vscode/src/completions/get-inline-completions.ts
> +    const gitIdentifiersForFile = await getGitRemoteUriForCurrentEditor()
Is it correct to assume that this will be called for every single completion attempt for all VSCode users? 
It seems that `getGitRemoteUriForCurrentEditor` walks files on disk + potentially makes remote RPCs, so, would it make sense to:

- disable this for Enterprise (where we won't log)?  
- cache the identifiers for a given file (so we avoid walking)
- (ideally) move this computation to happen async (when we switch files / load a repo)?

2024-06-10 10:21 UTC, rafax commented on vscode/src/completions/get-inline-completions.ts
> +        repoMetadataInstance.getRepoMetadataUsingGitUrl(gitIdentifiersForFile.remote)
You're not doing anything with the result of this call - are you calling it for side-effects only? Can it be removed? 

If it's needed for side-effects, maybe leave a comment (like `calling this so that `CompletionLogger.loaded` can use the data from a shared repoMetadataInstance`)?

2024-06-10 10:22 UTC, valerybugakov requested changes

2024-06-10 10:22 UTC, valerybugakov commented on vscode/src/repository/git-extension-api.ts
> +            ? (await repoNameResolver.getRepoNamesFromWorkspaceUri(currentFile))[0]
`getGitRemoteUriForCurrentEditor` is called unconditionally for enterprise and PLG users. `repoNameResolver.getRepoNamesFromWorkspaceUri` for enterprise users uses Sourcegraph API to resolve repo names instead of the local conversion function, which can significantly increase latency. 

Also, `getRepoNamesFromWorkspaceUri` uses `fs` internally to resolve the repo name if the Git extension is unavailable, which brings additional small latency. 

- We should ensure that remote calls are not used on the autocomplete critical path.
- Maybe consider collecting data only from PLG users with the Git extension enabled. It's the majority of users, so we would probably have enough data. The implementation would be simpler with no risk of introducing extra latency.

2024-06-10 10:22 UTC, valerybugakov commented on vscode/src/completions/logger.ts
> +        }
nit: concise version with the same level of type-safety:

```suggestion
        event.params.inlineCompletionItemContext = {
            gitUrl: inlineContextParams.gitUrl,
            commit: inlineContextParams.commit,
            prefix: params.docContext.prefix,
            suffix: params.docContext.suffix,
            triggerLine: params.position.line,
            triggerCharacter: params.position.character,
            context: inlineContextParams.context.map(snippet => ({
                    content: snippet.content,
                    startLine: snippet.startLine,
                    endLine: snippet.endLine,
                    filePath: snippet.uri.fsPath,
            })),
        }
```

2024-06-10 10:23 UTC, rafax commented on vscode/src/completions/logger.ts
> +        inlineContextParams?.gitUrl &&
Does `inlineContextParams?.gitUrl &&
        event.params.inlineCompletionItemContext === undefined` somehow mean that we're dealing with a public Github repo?

2024-06-10 10:25 UTC, rafax commented on vscode/src/completions/logger.ts
> +        inlineContextParams?.gitUrl &&
Ok, I see the public repo checks below, but it's not clear to me why we need `        event.params.inlineCompletionItemContext === undefined`

2024-06-10 10:29 UTC, rafax commented on vscode/src/completions/logger.ts
> +        const gitRepoMetadata = instance.getRepoMetadataIfCached(inlineContextParams.gitUrl)
Note: it seems that we have a race condition here, so it's possible that we won't log some completion events if the `repoMetadataInstance.getRepoMetadataUsingGitUrl` call is slow? It might be acceptable, but I think it's worth a comment (that we are aware of this, and not logging is fine)?

2024-06-10 13:03 UTC, hitesh-1997 commented on vscode/src/completions/get-inline-completions.ts
> +    const gitIdentifiersForFile = await getGitRemoteUriForCurrentEditor()
Thanks for pointing this out @rafax, Yes this would be called on every event, I didn't know the enterprise calls to sourcegraph api for repo names. When I measured the time, it was coming around ~0.5msec so I went ahead with this method earlier.

> (ideally) move this computation to happen async (when we switch files / load a repo)?
I tried to implement your suggested third solution. I added another class in file `git-metadata-for-editor` which updates `async` on  events: `vscode.window.onDidChangeActiveTextEditor`, `vscode.workspace.onDidChangeWorkspaceFolders`, `vscode.workspace.onDidChangeConfiguration`, so that we compute them async and get the value if they pre-exist (It would be okay even if we miss some events)

2024-06-10 13:05 UTC, hitesh-1997 commented on vscode/src/completions/get-inline-completions.ts
> +        repoMetadataInstance.getRepoMetadataUsingGitUrl(gitIdentifiersForFile.remote)
This is used as a side effect to precomputes the `gitRepoUrl` and store in its cache for query later.
Added the comment above the line :)

2024-06-10 13:11 UTC, hitesh-1997 commented on vscode/src/completions/logger.ts
> +        const gitRepoMetadata = instance.getRepoMetadataIfCached(inlineContextParams.gitUrl)
oh yes, this is exactly on point.
We should be okay to not log if the `getRepoMetadataUsingGitUrl` call us slow & we would eventually start populating context data after this value is available. Let me add this in the code comments :)

2024-06-10 13:20 UTC, hitesh-1997 commented on vscode/src/completions/logger.ts
> +        inlineContextParams?.gitUrl &&
This method could also be called when the results is already cached i.e. function call [from here](https://github.com/sourcegraph/cody/blob/1538dd2a26afacff5aa4369ec8053c3f3b1b7b32/vscode/src/completions/get-inline-completions.ts#L309)
In such case, we don't want to replace the earlier populated value.

2024-06-10 13:24 UTC, hitesh-1997 commented on vscode/src/repository/git-extension-api.ts
> +            ? (await repoNameResolver.getRepoNamesFromWorkspaceUri(currentFile))[0]
Thanks for pointing it out Valery, wasn't aware of that enterprise makes a call to backend on this.

I tried to implement your suggested third solution. I added another class in file git-metadata-for-editor which updates async on events: `vscode.window.onDidChangeActiveTextEditor` so that we compute them async and get the value if they pre-exist (It would be okay even if we miss some events)

Additionally, Also added the check that we only do this for dotComUsers since we wont log enterprise data anyway.
Can you please check if these conditions are sufficient.

2024-06-10 14:54 UTC, hitesh-1997 commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +export interface InlineCompletionItemRetrivedContext {
done

2024-06-10 22:12 UTC, akalia25 commented on vscode/src/completions/logger.ts
> +    const MAX_CHARACTERS = 4000
We can increase this to collect 40,000 characters or more (if needed). Doing the conversion, this will only be 0.38Mb and well within our bounds.

2024-06-11 10:34 UTC, valerybugakov approved these changes
Thanks, Hitesh! LGTM. I left a couple of minor suggestions inline.

2024-06-11 10:34 UTC, valerybugakov commented on vscode/src/repository/git-metadata-for-editor.ts
> +    public dispose(): void {
We do not use `dispose()` anywhere because `gitMetadataForCurrentEditor` is a singleton. We can remove everything related to disposables because only one listener is created during the instance lifetimes, and it's never cleaned up manually.

2024-06-11 10:34 UTC, valerybugakov commented on vscode/src/repository/git-metadata-for-editor.ts
> +                fileName: currentFile,
I suggest renaming `file` to `uri` where it's relevant to make it clear the URI is expected. 

```suggestion
                uri: currentFileUri,
```

2024-06-11 10:34 UTC, valerybugakov commented on vscode/src/repository/git-metadata-for-editor.ts
> +                fileName: currentFile,
Do we actually need `uri` anywhere outside of this class?

2024-06-11 10:34 UTC, valerybugakov commented on vscode/src/repository/git-metadata-for-editor.ts
> +                ? (await repoNameResolver.getRepoNamesFromWorkspaceUri(currentFile))[0]
You can consider using `repoNameResolver.getRepoRemoteUrlsFromWorkspaceUri(uri)` here since we need raw remote URLs. The conversion to the Sourcegraph repo name format is irrelevant here.

2024-06-11 10:34 UTC, valerybugakov commented on vscode/src/completions/get-inline-completions.ts
> +        gitUrl: gitIdentifiersForFile?.remote,
I recommend using consistent property names across all data structures to make it easier to follow the data flow. If the same things are named the same in different parts of the app, it's easier to reason about them. For example, use `gitUrl` everywhere instead of `gitUrl` and `remote`.

2024-06-11 10:34 UTC, valerybugakov commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +export interface InlineCompletionItemRetrievedContext {
These interfaces are specific to the completions logger. Thoughts on moving them to `vscode/src/completions/logger.ts`?

2024-06-11 11:07 UTC, hitesh-1997 commented on vscode/src/completions/logger.ts
> +    const MAX_CHARACTERS = 4000
Thanks for clarifying this Aditya !!

2024-06-11 11:07 UTC, hitesh-1997 commented on vscode/src/repository/git-metadata-for-editor.ts
> +    public dispose(): void {
Thanks for pointing this out, removed all related to disponse !!

2024-06-11 11:07 UTC, hitesh-1997 commented on vscode/src/repository/git-metadata-for-editor.ts
> +                fileName: currentFile,
that makes sense, we don't need this field for now, removed

2024-06-11 11:07 UTC, hitesh-1997 commented on vscode/src/repository/git-metadata-for-editor.ts
> +                ? (await repoNameResolver.getRepoNamesFromWorkspaceUri(currentFile))[0]
thanks, changed

2024-06-11 11:08 UTC, hitesh-1997 commented on vscode/src/completions/get-inline-completions.ts
> +        gitUrl: gitIdentifiersForFile?.remote,
makes sense, changed to `gitUrl` everywhere

2024-06-11 11:08 UTC, hitesh-1997 commented on vscode/src/completions/text-processing/process-inline-completions.ts
> +export interface InlineCompletionItemRetrievedContext {
makes sense, moved to logger

2024-06-11 11:08 UTC, hitesh-1997 commented
@akalia25 Is the PR looking for the logging perspective and is it okay to merge this ?

2024-06-11 15:52 UTC, rafax approved these changes

2024-06-11 16:21 UTC, akalia25 requested changes
When this sensitive data is being collected, we'll also need to update the metadata on the event cody.completion/suggested to include recordsPrivateMetadataTranscript:1.

2024-06-11 17:34 UTC, hitesh-1997 commented on vscode/src/completions/logger.ts
> +            inlineCompletionItemContext,
Thanks for pointing this out @akalia25 
Added the `recordsPrivateMetadataTranscript` field in the metadata field. Adding a snapshot here to quickly verify:

<img width="1052" alt="image" src="https://github.com/sourcegraph/cody/assets/20701220/816c074f-1e4d-45d0-a5f6-fdc0f6e63c0e">

Also, updated the PR description & output.

2024-06-11 21:01 UTC, akalia25 commented on vscode/src/completions/logger.ts
> +            inlineCompletionItemContext,
Amazing! Thank you @hitesh-1997 for the quick turnaround! I've updated the backend GCP pipelines to filter out `inlineCompletionItemContext` in `privateMetadata` now. Lets do a quick test together and then we can merge.

2024-06-15 00:13 UTC, hitesh-1997 commented
> When this sensitive data is being collected, we'll also need to update the metadata on the event cody.completion/suggested to include `recordsPrivateMetadataTranscript:1`. This ensures that the event is being sent to our ML pipeline. More info [here](url) :)

Thanks for pointing this out Aditya. Added this change along with logging only for v2 telemetry as discussed in the offline sync.

2024-06-17 15:04 UTC, akalia25 approved these changes
Thanks for all the edits @hitesh-1997!

Tested and confirmed the following:
- `recordsPrivateMetadataTranscript:1` is being logged on the event's `metadata` enabling the ML pipeline
- sensitive data stored within the event's `privateMetadata` in key `inlineCompletionItemContext`
- `inlineCompletionItemContext` is being redacted upon entering our prod data-warehouse and is only stored on our ML GCP Projects

2024-06-17 15:05 UTC, merged