added some support for client-side integration tests
sourcegraph/cody pull request #4512
Opened 2024-06-10 06:33 UTC by steveyegge

RPC 1:  Added a `textDocument/change` request, so the test can block on the editing operation.

This is the same as `textDocument/didChange` except that it returns a result.

I did not know what kind of meaningful result to return here, so it just returns an object with a `success' boolean that can be extended with more properties.

The reason integration tests need this is that they have no reliable way of knowing when the Agent finishes updating its `AgentWorkspaceDocuments' after a `textDocument/didChange` notification.

- added a `testing/workspaceDocuments` rpc for fetching the agent's current copy of a document, so it can be compared against the client's copy.
- This RPC allows you to specify zero or more uris for which to fetch the corresponding protocol document. Zero means get them all.

## Test plan

This is part of implementing the test plan for other PRs, so they are / will be testing this functionality.

2024-06-10 06:57 UTC, olafurpg requested changes
One blocking comments, otherwise looks good

2024-06-10 06:57 UTC, olafurpg commented on agent/src/agent.ts
> +                    .map(uri => {
nit: for..of loops are a lot more ergonomic to use in situations like these instead of map/filter

2024-06-10 06:57 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    uris?: string[]
needed to fix protocol.test.ts
```suggestion
    uris?: string[] | undefined | null
```

2024-06-10 06:57 UTC, olafurpg commented on agent/src/agent.ts
> +            await vscode_shim.onDidChangeTextDocument.cody_fireAsync({
There's an important behavioral difference in the new implementation even for existing clients that only use the `textDocument/didChange` notifications. We should not await on this promise here, we should call `pushPendingPromise()` instead like in the old implementation. We can optionally return this promise to `textDocument/change` and await on it there but I'm not yet 100% sure we want to do that. This promise is returned from `onDidChangeTextDocument` handlers, which can do anything including sending telemetry, ... 

We intentionally only await on this promise from tests because it makes the tests less flaky.

2024-06-10 06:58 UTC, olafurpg commented
`pnpm generate-agent-kotlin-bindings` should fix the Kotlin bindings CI check

2024-06-10 17:00 UTC, steveyegge commented on agent/src/agent.ts
> +                    .map(uri => {
Fixed and pushed.

2024-06-27 01:31 UTC, steveyegge commented on agent/src/agent.ts
> +            await vscode_shim.onDidChangeTextDocument.cody_fireAsync({
I have updated the code to only push the promises, and not await the promise in the new request.

2024-06-27 07:05 UTC, dominiccooney approved these changes
One nit inline.

2024-06-27 07:05 UTC, dominiccooney commented on vscode/src/jsonrpc/agent-protocol.ts
> + * Omitting uris parameter will retrieve all open documents for the
This comment more appropriate on the member than the type itself.

Easier to read if it is positive, like "Retrieves the specified URIs. If omitted, retrieves all open documents in the workspace root."

VSCode workspaces can have multiple roots... Guess this is sufficient for JetBrains?

2024-06-27 22:33 UTC, olafurpg approved these changes

2024-06-27 22:33 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +    'testing/workspaceDocuments': [GetDocumentsParams, GetDocumentsResult]
Is anyone using the old request name? If yes, then we should keep it and mark as `@deprecated`. As a rule of thumb, we should never have breaking changes in the protocol

2024-06-27 22:52 UTC, merged