Add ide version and proper Cody extension version to the telemetry
sourcegraph/cody pull request #4585
Opened 2024-06-17 14:03 UTC by pkukielka

## Changes

1. Raport proper extension version (previously Cody version was incorrectly used for both Jetbrains and NeoVim)
2. Add IDE version to the telemetry data 
 
## Test plan

1. Build [Jetbrains PR](https://github.com/sourcegraph/jetbrains/pull/1785) with this Cody changes
2. Run some ide actions like commands and edit.
4. Wait ~2h
5. Check if event with new field(s) containing correct versions will appear in looker

2024-06-17 14:31 UTC, mkondratek approved these changes
lgtm

2024-06-18 09:11 UTC, dominiccooney requested changes

2024-06-18 09:11 UTC, dominiccooney commented on agent/src/AgentWorkspaceConfiguration.ts
> +                return this.clientInfo()?.version
These don't look right...

`cody.advanced.agent.*ide*.version` is `this.clientInfo()?.version`, but
`cody.advanced.agent.*extension*.version` is `this.clientInfo()?.ideVersion` ?

If this is mixed up let's reverse them, if the data are right, let's rename some of these methods because it's confusing. 😰

2024-06-18 09:58 UTC, pkukielka commented on agent/src/AgentWorkspaceConfiguration.ts
> +                return this.clientInfo()?.version
Good catch, they were reversed by mistake!

2024-06-18 10:00 UTC, pkukielka commented on agent/src/AgentWorkspaceConfiguration.ts
> +                return this.clientInfo()?.version
BTW. here is example of the of event from looker before the reversal (I removed irrelevant content):

```
{
    "multiline": false,
    "triggerKind": "Automatic",
    "providerIdentifier": "fireworks",
    "providerModel": "starcoder-hybrid",
    "languageId": "kotlin",
    "testFile": false,
    "artificialDelay": 0,
    "multilineMode": null,
    "source": "Cache",
    "otherCompletionProviderEnabled": false,
    "otherCompletionProviders": [],
    "serverEndpoint": "https://sourcegraph.com/",
    "extensionDetails": {
        "ide": "JetBrains",
        "ideVersion": "6.0-localbuild",
        "ideExtensionType": "Cody",
        "platform": "macos",
        "arch": "aarch64",
        "version": "2024.1.2"
    },
    "tier": 1,
    "version": "2024.1.2",
    "hasV2Event": true
}
```

2024-06-18 11:57 UTC, merged