Add initial setup for cody web [second try]
sourcegraph/cody pull request #4605
Opened 2024-06-18 19:53 UTC by vovakulikov

Original PR https://github.com/sourcegraph/cody/pull/4227

## Test plan
- Check that Cody web demo and Cody-web package build work properly

2024-06-23 12:36 UTC, olafurpg commented on vscode/src/main.ts
> +        platform.createStorage ? await platform.createStorage() : context.globalState
Can we implement `context.globalState` under the hood with `platform.createStorage()`? As a rule of thumb, I want to keep the number of if/else conditions for the agent to an absolute minimum. These if conditions make it harder to reason about the system. The aspiration is that the agent implements the VS Code APIs and people working on the Cody VSC codebase should only have to reason about how things work in VSC.

2024-06-23 12:36 UTC, olafurpg commented on vscode/src/main.ts
> +    if (isRunningInsideAgent()) {
This logic should live inside the agent. We already implement `vscode.workspace.getConfiguration` in the agent, there is no need to add this condition in the VSC-part of the codebase.

2024-06-23 12:39 UTC, olafurpg commented on vscode/src/main.ts
> +    // during chat management services initialization
FYI, we already send quite a lot of blocking network requests on startup and I've wanted to reduce these requests. While it's convenient to perform this blocking request here, it slows down extension startup. It would be a better solution to await on the syncing from the locations where the runtime errors happened.

2024-06-23 12:45 UTC, olafurpg commented on vscode/src/services/LocalStorageProvider.ts
> +export interface AsyncMemento {
Are you certain that we need `AsyncMemento`? Most of the "high-risk" diffs in this PR are related to awaiting on the storage, I would feel more comfortable approving this PR if we can stick with `Memento`. We can implement non-async `Memento` by loading a JSON key from indexdb during startup and then performing get/keys synchronously. The `update` function is already async in the `vscode.Memento` API.

As a rule of thumb, we should try to stick with VS Code APIs wherever possible. We should have a high barrier to make exceptions to this rule.

2024-06-23 12:48 UTC, olafurpg requested changes
Thank you for this contribution! It's very exciting to see us trying to use this infrastructure in the browser. The main blocking comments are

- Let's try to avoid adding `AsyncMemento`
- Let's try to avoid blocking on `syncModels` during startup

In general, let's try to keep the diff in `vscode/src` as small and low-risk as possible. It's better to pay a complexity once in `agent/src` instead of requiring all Cody VSC devs to reason about different environments.

2024-06-23 12:49 UTC, olafurpg commented
Also, can you update the PR description to link to the Linear issue/project?

2024-06-23 12:51 UTC, olafurpg commented
Also, please tag the Cody Agent GH team for future PRs related to the agent. There is a lot of important context to why things are implemented the way they are. Just having a green CI and a stamp from somebody in Cody Web should not be enough to get a large PR like this merged.

2024-06-24 04:33 UTC, vovakulikov commented on vscode/src/main.ts
> +    if (isRunningInsideAgent()) {
Fun things that this seed-like logic fixes problems with double auth network requests flows. The problem with mocking configuration inside the agent is that it doesn't take into account the full logic in the extension main setup function. 

The problem with seeding this data in the agent comes from the fact that we don't have access (and we shouldn't have actually) to abstractions like `localStorage` and `secretStorage`. Storage for `SecretStorage` is created inside the agent but it provides just in-memory map implementation that doesn't know anything `SecretStorage` abstraction where we store keys and methods to set accessToken data. 

I understand the comment, this change though with isRunningInsideAgent seemed as the safest path to avoid the problem with auth/tokens problems in Cody Web Agent. (if you have any ideas on how to solve it better within the agent I would be happy to make a change, it might be I missed something obvious there)

2024-06-24 04:37 UTC, vovakulikov commented on vscode/src/services/LocalStorageProvider.ts
> +export interface AsyncMemento {
> Most of the "high-risk" diffs in this PR are related to awaiting the storage

Do you have any specific places where it concerns you? I can try the idea of loading data ahead during initialisation. Thanks for the suggestion

2024-06-24 04:40 UTC, vovakulikov commented on vscode/src/main.ts
> +    // during chat management services initialization
To be honest, I wanted to put this also behind the `isRunningInsideAgent` check, something happens inside the extension in the agent differently when we run pure extension logic in the VSCode. ChatManagement and other chat services expect to have non-empty chat models by the time we call them (later in this main.ts function). 

I could try to change logic around the creation of chat panels and simpleChatProviders but it seemed a big change (at least as I saw it) which I would like to avoid.

2024-06-24 04:41 UTC, vovakulikov commented
@olafurpg 
> Also, please tag the Cody Agent GH team for future PRs related to the agent

What do you mean? I tagged Cody's agent team in this PR, is there any other team rather than this one? 

<img width="543" alt="Screenshot 2024-06-24 at 01 41 12" src="https://github.com/sourcegraph/cody/assets/18492575/7968725b-581a-44a0-9591-fcefbe486cac">

2024-06-24 04:44 UTC, vovakulikov commented on vscode/src/main.ts
> +        platform.createStorage ? await platform.createStorage() : context.globalState
I have no preferences here about this API, it seemed to me that custom storage falls within platform context dependencies (which is a part of this extension API function). We could pass custom storage to the Agent class and then set it with custom `globalState` if you think this is more correct to do here.

2024-06-24 14:49 UTC, vovakulikov commented on vscode/src/services/LocalStorageProvider.ts
> +export interface AsyncMemento {
There might be a problem with the sync approach in IndexDB, so if we pull data from IndexDB during init we would have some in-memory internal field in IndexDB storage, so yeah as you said this makes get/keys methods synchronous, in update we could update value in IndexDB and then apply the same value to the storage. 

The problem here might be when we have more than one browser tab open, it looks like it would be a case when one tab writes one data but the other tab doesn't get this updated value and its get/key method (since it doesn't call any IndexDB API) will return just in-memory value (the old value)

Usually, I would say that we could subscribe on the table changes but it seems that IndexDBObserver never hit the wide support in most of the browsers

cc @olafurpg

2024-06-24 15:18 UTC, vovakulikov commented on vscode/src/services/LocalStorageProvider.ts
> +export interface AsyncMemento {
Just for the record (in defence of making storage async) most of the places (99% of cases) where get/keys methods are called already were async so the only change that I had to make there just to add `await`, which I doubt would cause big problems 

The change where I had to make more changes was class constructors, but the static create function was my way out of this which doesn't introduce anything new to the class creating logic but mostly duplicates logic from the constructor

2024-06-24 15:33 UTC, vovakulikov commented on vscode/src/main.ts
> +    // during chat management services initialization
I just noticed that we already called this `syncModels` fetch function later in the `main.ts`, I removed the second later call to avoid double fetching, but it seems that calling it early shouldn't affect performance in the extension, correct me if I'm wrong

2024-06-25 21:20 UTC, sqs commented
Symbols and chat history do not need to be in the initial version that ships to dotcom. Ideally they would make it in the July 10 release, but if they need to slip, I would still want to get everything else shipped on time rather than delay the whole thing.

2024-06-26 06:55 UTC, vovakulikov commented
@sqs I greened CI today, unit, integrations and e2e tests are finally passing, so now I know that these changes are actually possible and don't break core logic (but I haven't checked other agent's consumers but Cody web), We had a conversation today with @olafurpg and even these changes seem ok in terms of tests but there are still concerns about corners cases. I will split this PR into smaller ones today/tomorrow to make it a bit safer to merge

<img width="292" alt="Screenshot 2024-06-26 at 03 42 58" src="https://github.com/sourcegraph/cody/assets/18492575/dcec2adc-5b41-4e81-bd6a-ba2e6dcd5192">

While I'm doing this, on the other side we want to ship the new Cody Web as soon as possible on dotcom, @peterguy suggested that we actually could already ship this to dot com with publishing the updated Cody agent from the brunch, I already did this in sourcegraph PR here https://github.com/sourcegraph/sourcegraph/pull/62792

With this PR in sg repo, the new Cody web client will be available only for signed-in users on Dotcom, so no risks for any non-web agent's clients and we already use (used) the Cody-web package which exists only in the npm, so I think this is a low-risk good compromise at this point, while I'm splitting and merging big changes in Cody agent. 

cc @peterguy

2024-06-26 17:28 UTC, olafurpg commented on agent/recordings/chat-response-quality_413888585/recording.har.yaml
> +              query Repository($name: String!) {
I see we are already sending `query Repository` here https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/recordings/chat-response-quality_413888585/recording.har.yaml?L34360

Any idea why we are sending a new request?

2024-06-26 18:30 UTC, vovakulikov commented on agent/recordings/chat-response-quality_413888585/recording.har.yaml
> +              query Repository($name: String!) {
@olafurpg Yes, I actually think this is because of codebase checks in `configureExternalServices`
https://sourcegraph.com/github.com/sourcegraph/cody@df399f24938288144a7d026c1ca9edbd7dd98731/-/blob/vscode/src/external-services.ts?L49:23-49:48

We run this function unconditionally during extension initialisation. I see that in the TestClient we pass `codebase` field so I don't know why we didn't send it before. 

I will check the main behaviour to see what happens there, but my guess is this happens because on main, at the moment, we run this check config.codebase wasn't set yet properly by config watcher.

2024-07-01 08:17 UTC, dominiccooney requested changes
Some feedback inline. I've reviewed a chunk of this but will stop at this point so we can discuss.

I'd like to see more effort to generalize and simplify the design, instead of configuration variables here and if statements there to pick a path through the existing extension code.

2024-07-01 08:17 UTC, dominiccooney commented on lib/shared/src/chat/transcript/display-text.ts
> +            href: `/${item.uri.authority}/${item.uri.path}}`,
Don't these URIs have line number ranges which we bake into the query or hash?

2024-07-01 08:17 UTC, dominiccooney commented on lib/shared/src/chat/transcript/display-text.ts
> +            href: `/${item.uri.authority}/${item.uri.path}}`,
Below I get the impression that `path` starts with `/` but here you're adding a `/` before it...

2024-07-01 08:17 UTC, dominiccooney commented on vscode/src/chat/chat-view/ChatPanelsManager.ts
> +        const allowRemoteContext = vscode.workspace
More than a configuration flag, would it be simpler and more direct to just say "is enterprise or is cody web"? My concern with flags is there are certain sets of flags which are configurations anyone uses, are somewhat tested, etc.

When the flag is there it gives the impression that you can pick any point in flag space and stuff will work. But that is hard to achieve. What happens when a user drops `cody.allow-remote-context: true` into their configuration and connects to dotcom? I don't want to debug or support that.

2024-07-01 08:17 UTC, dominiccooney commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +                // Pass possible remote repository context in order to resolve files
Could we instead pass an object into SimpleChatPanelProvider that does the right thing, so SimpleChatPanelProvider doesn't need to care about this new concept? It just calls that object when it needs ... whatever this is. So we have one conditional to create that object, instead of passing nullable data and having conditionals on the creation side and the consumption side.

Looking at the symbol case specifically, you could have done this differently by, for example, creating an interface for symbol lookup, and instantiated one implementation with vscode.executeWorkspaceSymbolProvider and another with your remote query. This avoids the conditionals, passing the nullable data which we'll have to elaborate for different providers later, avoids the early return, etc.

2024-07-02 00:09 UTC, vovakulikov commented
I'm going to close this one since changes from these PR will be delivered separately

2024-07-02 00:09 UTC, closed without merging