Chat context observability improvements
sourcegraph/cody pull request #4702
Opened 2024-06-27 13:52 UTC by janhartman

I noticed that we didn't propagate ignored context items correctly, which caused us to always log 0 ignored items in our telemetry. However, after fixing this, we now show the count in the chat as shown on the image below. I don't think that this is really informative to the user so I'd remove this visual element, WDYT?
<img width="394" alt="image" src="https://github.com/sourcegraph/cody/assets/15076960/4a57d686-f22f-4921-82bb-b1eaca8488ed">

## Test plan

2024-07-04 12:21 UTC, hitesh-1997 requested changes

2024-07-04 12:21 UTC, hitesh-1997 commented on vscode/webviews/chat/cells/contextCell/ContextCell.tsx
> +    const contextItemCountLabel = `${itemCount} ${!isForFirstMessage ? 'new ' : ''}${pluralize(
Just tagging @toolmantim for the UI/UX related changes here

2024-07-04 12:21 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            gitMetadata: await this.getRepoMetadataIfPublic(),
@janhartman I think we shouldn't add the changes here. If I understand correcting, adding gitMetaData will start logging in the `metadata` fields instead of `privateMetaData` field which goes through normal pipeline.
Also, I would suggest a review from @akalia25 for any telemetry PR !!

2024-07-04 12:25 UTC, janhartman commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            gitMetadata: await this.getRepoMetadataIfPublic(),
Thanks for the review. I think the setup is OK - if you look at [sendTelemetry](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L781), `privateContextStats` is in `privateMetadata`. This is what we want, right?

2024-07-04 16:16 UTC, abeatrix reviewed
Left a comment inline. I had a similar PR opened for displaying the ignored items as well for awhile but was left forgotten, but there are some discussion happened that might be related: https://github.com/sourcegraph/cody/issues/4490

2024-07-04 16:16 UTC, abeatrix commented on vscode/src/chat/chat-view/prompt.ts
> +                context.ignored.push(...newEnhancedMessages.ignored)
```suggestion
               
```

This was excluded on purpose initially because we only want to show files that were added by user (Commented on line 96). Since users didn't choose the enhance context files the product team didn't think it'd be helpful for users to see the context they didn't know it'd be included.

2024-07-04 16:16 UTC, abeatrix commented on vscode/src/chat/chat-view/prompt.ts
> +                context.ignored.push(...newEnhancedMessages.ignored)
@toolmantim @danielmarquespt to confirm

2024-07-04 21:26 UTC, janhartman commented on vscode/src/chat/chat-view/prompt.ts
> +                context.ignored.push(...newEnhancedMessages.ignored)
That's why I removed the visual element. The problem with simply not adding the ignored items to this array is that they won't be propagated and logged correctly.

2024-07-04 21:26 UTC, janhartman commented on vscode/src/chat/chat-view/prompt.ts
> +                context.ignored.push(...newEnhancedMessages.ignored)
It's quite important that we can log this properly for AI research's sake :)

2024-07-04 21:30 UTC, janhartman commented on vscode/webviews/chat/cells/contextCell/ContextCell.tsx
> +    const contextItemCountLabel = `${itemCount} ${!isForFirstMessage ? 'new ' : ''}${pluralize(
To be clear - this change means that we keep the UI in the same state as it was. The difference is that now, the code passing the data around in the background works correctly :)

2024-07-04 22:27 UTC, abeatrix commented on vscode/src/chat/chat-view/prompt.ts
> +                context.ignored.push(...newEnhancedMessages.ignored)
Ah gotcha in that case would it be easier to do the logging in PromptBuilder instead? 🤔

2024-07-05 06:17 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            gitMetadata: await this.getRepoMetadataIfPublic(),
ah right, I missed that, thanks !!

2024-07-05 06:20 UTC, hitesh-1997 approved these changes
Looks good to me !!
We can also ask @akalia25 to give it a look for telemetry related changes

2024-07-05 06:22 UTC, janhartman commented on vscode/src/chat/chat-view/prompt.ts
> +                context.ignored.push(...newEnhancedMessages.ignored)
TBH I think the way it's done now is better since we can log it closer to where it's used. The webview also logs how many items were excluded so we do need to pass this info there as well.

2024-07-09 09:16 UTC, willdollman approved these changes
Looks fine to me, left a few small code style suggestions.

2024-07-09 09:16 UTC, willdollman commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +            const privateContextStats = await this.buildPrivateContextStats(context)
This var + method could be renamed to indicate that they no longer just contain stats - e.g. `privateContextTelemetry` / `privateContextSummary` / or similar

2024-07-09 09:17 UTC, janhartman commented on vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
> +        if (!(isDotCom && isPublic)) {
Interesting, for me it's the other way around 😄

2024-07-09 10:15 UTC, merged