[DRAFT] Chat: set theme provided by Agent IDE
sourcegraph/cody pull request #4709
Opened 2024-06-27 19:17 UTC by abeatrix

CLOSE https://linear.app/sourcegraph/issue/CODY-2462/implement-the-webview-side-of-dom-css-theme-plumbing

This change adds the ability to set the webview theme based on the theme provided by the Agent IDE. The `SimpleChatPanelProvider` now checks for a theme from the IDE and sends a `ui/theme` message to the webview with the CSS variables to apply the theme.

The `App` component in the webview then listens for the `ui/theme` message and applies the provided CSS variables to the root element.

This allows the webview to match the theme of the Agent IDE, providing a more consistent user experience.

## Test plan

TBC. Need to implement the changes on JB to test.

2024-06-28 04:02 UTC, dominiccooney requested changes
Like the direction this is going in, but some detailed feedback inline.

In addition, can you add a helper to Storybook so we can trigger it to flip to JetBrains styles?

That style flip, at the individual component level, should happen *all through CSS.* In particular:

- Set an attribute on a parent element (probably the same one you're setting the inline style rules on) like `element.dataset['ide'] = 'jb'`.
- Include a stylesheet which maps the IDE-specific theme variables into the closest VSCode ones... see the comment below.

CC @toolmantim

2024-06-28 04:32 UTC, abeatrix commented on lib/shared/src/themes/jetbrains.ts
> +        return cssVariables.replaceAll('--vscode', '--jetbrains')
I've generated the mapping in https://github.com/sourcegraph/cody/blob/f708f148881deb77bbcb629eb6c4e048b2b47c97/lib/shared/src/themes/jetbrains.json

Will replace --vscode with --jb instead of --jetbrains in the mapping as suggested!

2024-06-28 04:34 UTC, abeatrix commented on vscode/src/chat/utils.ts
> +    const config = await getFullConfig()
It's called this during the webview initialize step!

2024-06-28 04:38 UTC, abeatrix commented on vscode/webviews/App.tsx
> +                            document.getElementById('root')?.setAttribute('style', cssVariables)
I just inspected the element in the console to confirm these new styles were added to the styles attribute of the root element.

I can test and confirm if this works tomorrow and report back!

2024-06-28 07:56 UTC, dominiccooney commented on lib/shared/src/themes/jetbrains.ts
> +        return cssVariables.replaceAll('--vscode', '--jetbrains')
Let's not generate this. Just loop over all the keys you get, map them to valid CSS variable names, and set those variables.

The "mapping" should be done by hand in CSS as illustrated above.

2024-06-28 08:32 UTC, dominiccooney commented on vscode/webviews/App.tsx
> +                            document.getElementById('root')?.setAttribute('style', cssVariables)
Just tried this, and we need to use CSSOM as outlined above. Here's the result of setting the string:

![Screenshot 2024-06-28 at 17 28 52](https://github.com/sourcegraph/cody/assets/55120/4c39fe66-3ca6-450e-92cf-dc476255987a)

Why can VSCode do this, and JetBrains can't? I think VSCode is modifying the CSP attribute to use script-src a hash or nonce. We can reach in like that, too, but it will be simpler to set the variables explicitly.

2024-06-28 09:04 UTC, dominiccooney commented
@abeatrix , I've pushed a small update:

- Uses CSSOM to set the variables.
- Relies on the client producing valid CSS variable names.
- Renames `css` to `cssVariables` and gives it that `{[key: string]: string}` type.

I pushed 78cb8e06cf76d249c6e61aab93f74dd9b3613e96 to sourcegraph/jetbrains dpc/web-content branch which sends this. I'm also sending an "isDark" property, not sure if we need that...

Here's what the prototype webview looks like in the inspector now:

![Screenshot 2024-06-28 at 17 54 25](https://github.com/sourcegraph/cody/assets/55120/ca4f777a-6c55-4d31-b6c6-e91eb9fd9732)

You can test this, maybe this can be the start of a manual test plan for your PR:

1. `CODY_DIR=/Users/dpc/projects/cody ./gradlew :runIDE -PforceAgentBuild=true`
2. Open Cody Experimental Chat UX sidebar, right click, Open DevTools
3. Check that a ton of JetBrains theme variables appear.
4. Check that the values parse OK, for example `document.body.style.background = 'var(--jetbrains-textText)'` should change the background color to the same color as the label "Cody Experimental Chat UX"
5. Changing the theme and the background color should change.

(It takes forever to reach DOMContentLoaded, will worry about that later.)

2024-07-02 01:11 UTC, abeatrix commented
@dominiccooney moving to https://github.com/sourcegraph/cody/pull/4744 because running into issues with git 😅

2024-07-02 01:11 UTC, closed without merging