Interleave chat context items from different sources
sourcegraph/cody pull request #4769
Opened 2024-07-03 14:27 UTC by janhartman

Instead of concatenating them (`[emb1, emb2, ..., symf1, symf2, ... symf_n]`), we now interleave the lists (`[emb1, symf1, emb2, symf2, ..., emb_n, symf_n]`).

## Test plan

Tested locally.

2024-07-04 00:36 UTC, dominiccooney requested changes
Let's link to some evals showing this strategy is better in the PR or a linked Linear task.

2024-07-04 07:51 UTC, janhartman commented
Hey @dominiccooney, thanks for checking in! I linked a Linear issue in the description with some more details.

2024-07-04 08:23 UTC, PriNova commented
Hey @janhartman is it possible to insert them based on semantic logic? For example, if the fetched chat context has similarities/relations in regards to shared symbols, types, functions, interfaces or other kind of dependencies/abstractions?

To put it metaphorically, if the context narrates a story from the top down, it might seem the LLM would have a more profound understanding of the proceedings.

2024-07-04 09:14 UTC, janhartman commented
Hey @PriNova, great line of thought. This is exactly what we'll be doing in the coming weeks & months! However, it'll require some research & experimentation before we'll be able to ship anything 😄

2024-07-04 09:54 UTC, PriNova commented
> Hey @PriNova, great line of thought. This is exactly what we'll be doing in the coming weeks & months! However, it'll require some research & experimentation before we'll be able to ship anything 😄

Maybe with the research hat on exploring GraphRAG might be an option: https://github.com/microsoft/graphrag

2024-07-04 12:32 UTC, hitesh-1997 reviewed
Thanks for the changes @janhartman 
As @dominiccooney suggested, we can add offline evals on this and should be good to go.

2024-07-04 12:32 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/context.ts
> +        const searchContextBySource = [
@janhartman Just checking that we are committing this to `getEnhancedContext` which is not behind a feature flag.

2024-07-04 12:32 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/context.ts
> +        const searchContext = compact(flatten(zip(...searchContextBySource)))
@janhartman just cross checking since in python zip will trim the extra elements i.e. `zip([1, 2, 3], [4, 5]) -> [(1, 4), (2, 5)]`.
We might not want to trim such extra elements here for instance if `symf` returned only 1 element, we would want other context items from other providers. Can we confirm this extra trimming is not the behaviour with lodash.

2024-07-04 12:32 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/context.ts
> +        const searchContext = compact(flatten(zip(...searchContextBySource)))
Ah, please ignore the comment, Just tried this and saw your comment about adding undefined elements by lodash.
<img width="412" alt="image" src="https://github.com/sourcegraph/cody/assets/20701220/d2def8d1-2ef0-4837-84f1-a295f71d5986">

2024-07-04 12:33 UTC, hitesh-1997 approved these changes

2024-07-04 13:34 UTC, janhartman commented on vscode/src/chat/chat-view/context.ts
> +        const searchContext = compact(flatten(zip(...searchContextBySource)))
Yeah lodash does it completely differently to python, I was surprised as well 😄

2024-07-04 14:54 UTC, janhartman commented on vscode/src/chat/chat-view/context.ts
> +        const searchContextBySource = [
@hitesh-1997 sorry, don't understand what you mean here...

2024-07-05 06:19 UTC, hitesh-1997 commented on vscode/src/chat/chat-view/context.ts
> +        const searchContextBySource = [
Just checking if we are running a A/B test for it ?

2024-07-05 06:23 UTC, janhartman commented on vscode/src/chat/chat-view/context.ts
> +        const searchContextBySource = [
Oh no - @rishabhmehrotra said offline eval is enough (linked Slack thread in the Linear issue).

2024-07-09 02:09 UTC, dominiccooney commented
@janhartman if ML people are happy with the level of evals then LGTM.

2024-07-09 02:09 UTC, dominiccooney approved these changes

2024-07-09 10:14 UTC, merged