Chat UI: add navigation bar and views for history and commands
sourcegraph/cody pull request #4900
Opened 2024-07-16 22:27 UTC by abeatrix

Note: This PR is adding the new nav bar with commands view and history view as shown in [the figma design](https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/Universal-Cody?node-id=2179-3103&t=wu5mes2cZOgGAgKC-0). It does not remove the current Settings and Support tree view.

Summary:
- Add a navigation bar with icons for different views (Chat, History, Commands, Settings, Account)
- Implement new views for History and Commands
- Update the App component to handle the new views and navigation
- Update the WelcomeMessage component to handle the new views and commands
- Add new method in command controller for returning a list of commands
- Adjust existing styles for the new navbar and views

## Test plan

Added new views (CommandsView & HistoryView) and `NavBar` component to the storybook:
![image](https://github.com/user-attachments/assets/91462f57-451a-491c-bf3c-8e4ed6d6d2ce)

NavBar:

![image](https://github.com/user-attachments/assets/33653c50-a290-432b-8aae-85e4c088d361)

Commands View

![image](https://github.com/user-attachments/assets/589169f3-0118-4548-a173-ea0c8f38dfe2)

2024-07-17 12:35 UTC, toolmantim reviewed
Here's a few things I noticed quickly, will review properly tomorrow:

* SVG stroke width on icons should be 1.25px
* Border bottom on tab should be 1px
* Border bottom on tab header should be 1px
* Clicking the settings tab shouldn't take you back to the chat tab
* Repeatedly pressing the settings tab button seems buggy (may be related to the chat input auto-focus?)
* Tabs should use shadcn/ui tabs or at least Radix UI tabs for keyboard accessibility
* Remove the `tw-my-3` margin from the tab bar
* Add `tw-py-1` to the tab bar to bring it in 2px on left and right

Design things that need fixing/defining (I'll look into tomorrow):
* We need to add tooltips (using our Tooltip component) for the tabs and buttons
* Nav bar button spacing
* Tab content padding
* Adding all the links so we can remove "Settings & Support"

2024-07-17 13:55 UTC, abeatrix commented
WIP: 
- [ ] SVG stroke width on icons should be 1.25px
- [x] Border bottom on tab should be 1px
- [x] Border bottom on tab header should be 1px
- [x] Clicking the settings tab shouldn't take you back to the chat tab
- [ ] ~~Repeatedly pressing the settings tab button seems buggy (may be related to the chat input auto-focus?)~~
- [ ] Tabs should use shadcn/ui tabs or at least Radix UI tabs for keyboard accessibility - wip
- [x] Remove the tw-my-3 margin from the tab bar
- [x] Add tw-py-1 to the tab bar to bring it in 2px on left and right
  - tw-px-1 brought it 2px on left and right which makes the change not noticible. Should I try tw-px-4 instead? @taiyab @toolmantim 
  
with tw-px-1:
  
![image](https://github.com/user-attachments/assets/0f829c2c-837e-4ad6-ac44-1eb56d86dc0e)

2024-07-18 07:00 UTC, dominiccooney requested changes
- Restoring a chat seems to hang, unsure if this is related: https://www.loom.com/share/a259b1174e354e53a0332b0683ba7ff8?sid=4d2f21ea-95ca-4bb5-86aa-07766fa9aa08
- Is the order of commands in "Commands" what we want? I've got autoedits (experimental) and generate commit message (experimental) are at the top, clicking them apparently does nothing... is that putting our best foot forward? Custom commands are empty for me but there's a very expansive tooltip...
![Screenshot 2024-07-18 at 15 53 09](https://github.com/user-attachments/assets/29cacb5c-ede7-4b2b-b82c-05946eddfa13)
- The "commands" tab has *two* gears in the same tab bar which do different things... can we just follow the principles of Gestalt here and put the custom commands gear near custom commands?
![Screenshot 2024-07-18 at 15 59 33](https://github.com/user-attachments/assets/e84448b1-8f8f-42f7-aa73-36b4ef9c893e)

Probably not related to your change, but I noticed:
- Ollama icon despite chatting with Sonnet 
![Screenshot 2024-07-18 at 15 54 21](https://github.com/user-attachments/assets/41d74649-c308-4b89-9b94-faf12f7169b5)
- With a response streaming, clicking "move to panel" button kills the response.

2024-07-18 07:04 UTC, abeatrix commented on vscode/src/chat/chat-view/ChatController.ts
> -        if (view !== 'chat') {
Yeah, that's because we used to render the chat view once the user is logged in, but this is not the case anymore as we start creating the webview even when the user is not logged in for auth view.

2024-07-18 07:42 UTC, abeatrix commented
@dominiccooney Thanks for taking the time to review! A lots of the bugs are unrelated to the changes I made and are reproducible on main, will file separate issues for them to follow up:

- Restoring a chat seems to hang, unsure if this is related:
- With a response streaming, clicking "move to panel" button kills the response.

> Is the order of commands in "Commands" what we want? I've got autoedits (experimental) and generate commit message (experimental) are at the top, clicking them apparently does nothing... is that putting our best foot forward?

Woops filtered and removed from the list.

> Custom commands are empty for me but there's a very expansive tooltip...

I can't reproduce this, but i fixed some styling issues that might have caused this. Also added a new item for creating a new custom command: 

<img width="569" alt="image" src="https://github.com/user-attachments/assets/5e3d48b6-ff2c-4a60-87f1-f3c56cc23c45">


> The "commands" tab has two gears in the same tab bar which do different things... can we just follow the principles of Gestalt here and put the custom commands gear near custom commands?

this is from the figma design file: 

![image](https://github.com/user-attachments/assets/17d4310f-47aa-413e-b2e3-d5a0cfa86ad4)

I think they are working on the new design for prompt library that'd eventually remove the extra gear. 

> Ollama icon despite chatting with Sonnet

Yea I think this is related to the bug we just fixed on main in https://github.com/sourcegraph/cody/pull/4911

2024-07-18 07:46 UTC, toolmantim commented
I doesn't have to be this PR, but I was hoping we'd be a bit more systematic with creating UI components.

e.g. create a `shadcn/ui/tabs.tsx` via shadcn/ui, and make the necessary changes to the class names to have it match our style, in https://github.com/sourcegraph/cody/tree/main/vscode/webviews/components/shadcn/ui

Our [Figma component](https://www.figma.com/design/zNtJZZwuLn1RLgsNNL2C52/%E2%9C%B3%EF%B8%8F-wildcard-shadcn?node-id=22-8555&t=xJtr8GQinpHNRjIy-4) is generic too, as is the overall idea of our wildcard-shadcn Figma components.

Then all the view-specific logic can live outside of that pure UI component.

You can see the message input toolbar (https://github.com/sourcegraph/cody/blob/1cd4ba8a825d8b88a7d662f7997ed3792f097e48/vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx) uses the standard <Button> etc too.

2024-07-18 07:50 UTC, toolmantim commented
Sorry @abeatrix, I didn't get time to update the Figma yesterday… the command list on the new chat experience and the Commands tab should be the same. Let me update the Figma now…

2024-07-18 07:51 UTC, toolmantim commented
![image](https://github.com/user-attachments/assets/b18f0aa5-3075-4554-9a9a-967cfe91583d)

btw this component ^ is a standard shadcn/ui collapsible, that would use our standard `<Button>` etc: https://ui.shadcn.com/docs/components/collapsible

2024-07-18 08:21 UTC, abeatrix commented
> I doesn't have to be this PR, but I was hoping we'd be a bit more systematic with creating UI components.
> 
> e.g. create a `shadcn/ui/tabs.tsx` via shadcn/ui, and make the necessary changes to the class names to have it match our style, in https://github.com/sourcegraph/cody/tree/main/vscode/webviews/components/shadcn/ui
> 
> Our [Figma component](https://www.figma.com/design/zNtJZZwuLn1RLgsNNL2C52/%E2%9C%B3%EF%B8%8F-wildcard-shadcn?node-id=22-8555&t=xJtr8GQinpHNRjIy-4) is generic too, as is the overall idea of our wildcard-shadcn Figma components.
> 
> Then all the view-specific logic can live outside of that pure UI component.
> 
> You can see the message input toolbar (https://github.com/sourcegraph/cody/blob/1cd4ba8a825d8b88a7d662f7997ed3792f097e48/vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx) uses the standard `<Button>` etc too.

cool I wasn't aware we are moving toward this but I can refactor them in a follow up since i don't think I get to it this week. Is this documented somewhere I can refer to?

2024-07-18 08:22 UTC, toolmantim commented
> cool I wasn't aware we are moving toward this but I can refactor them in a follow up since i don't think I get to it this week. 

👍🏼

> Is this documented somewhere I can refer to?

I don't think this is documented anywhere, but something @taiyab and Code Search team were aware of

2024-07-18 08:29 UTC, toolmantim commented
I've just updated the Figma, including the example VS Code and Jetbrains frames below the main frames.

Here's a prototype link to understand the idea behind the hover states too: https://www.figma.com/proto/f078wFMKsIOaEwj7Iwj5xy/Universal-Cody?page-id=2179%3A3103&node-id=2802-44502&viewport=-12%2C531%2C0.93&t=QuwOoDxwNIK1a1v4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2802%3A44502

One thing that has changed is not listing out each custom command, but just loading up the menu… given it also has the buttons for creating, managing etc. No need for double-cog icon.

I'm sorry for the miscommunication on timing around this, and the design scoping! I hate changing something once you've already done so much of the PR.

2024-07-18 12:34 UTC, toolmantim commented
I actually do have some documentation here @abeatrix — not frontend dev specific though: https://linear.app/sourcegraph/project/wildcard-shadcn-7dad47f37fe7/overview

2024-07-19 00:58 UTC, jamesmcnamara approved these changes
Looks good! I didn't review the CSS or tailwind classes too closely (I don't really know much about those yet). But I played around with it locally and it works well and looks great! Love the hover styling.

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/test/e2e/command-core.test.ts
> +    const chatPanel = page.frameLocator('iframe.webview').last().frameLocator('iframe')
There is a utility for this: `getChatEditorPanel`

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/test/e2e/command-core.test.ts
> +    await chatPanel.getByText('hello from the assistant').hover()
I always find this a confusing way to do a test, I'd personally find:
```suggestion
    await expect(chatPanel).toContainText('hello from the assistant')
```
or 
```suggestion
    await expect(getChatInputs(chatPanel).first()).toContainText('hello from the assistant')
```

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/test/e2e/common.ts
> -    await expect(page.getByLabel('Settings & Support Section')).toBeVisible()
I looked at this for a while until I realized that the focusSidebar would hang forever if the user wasn't authenticated. Maybe we should add a comment about this?

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/src/chat/chat-view/ChatsController.ts
> +                this.panel && vscode.commands.executeCommand('cody.chat.focus')
Is there a reason to not `await` here?
```suggestion
                this.panel && await vscode.commands.executeCommand('cody.chat.focus')
```

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/test/e2e/auth.test.ts
> +    // instead of the chat panel.
Here too: `const sidebarFrame = getChatEditorPanel(page)`

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/webviews/App.tsx
> +            return
Out of curiosity, does this have any effect? If so we should definitely document it as I'd immediately delete it if I was editing this code.

2024-07-19 00:58 UTC, jamesmcnamara commented on vscode/webviews/Chat.module.css
> +    height: 100%;
Not 100vh? It's been a long time since I've done CSS, but I remember 100% never doing what I expected, unless you are in like an absolutely sized container.

Then again I'm messing around with the chat now and it looks fine.

2024-07-19 06:26 UTC, abeatrix commented on vscode/webviews/App.tsx
> +            return
It shouldn't! I don't even remember why I added this 🤣

2024-07-19 06:28 UTC, abeatrix commented on vscode/src/chat/chat-view/ChatsController.ts
> +                this.panel && vscode.commands.executeCommand('cody.chat.focus')
i've removed this logic because turns out this.panel needs to be initialized for the Login page to work, so i change back to using "when" clause for controlling when to show the sidebars or not

2024-07-19 16:12 UTC, abeatrix commented on vscode/test/e2e/auth.test.ts
> +    // instead of the chat panel.
Thank you! Just found out about `getChatSidebarPanel`!

2024-07-19 16:12 UTC, abeatrix commented on vscode/test/e2e/command-core.test.ts
> +    const chatPanel = page.frameLocator('iframe.webview').last().frameLocator('iframe')
Replaced with getChatSidebarPanel!

2024-07-19 16:23 UTC, abeatrix commented on vscode/test/e2e/command-core.test.ts
> +    await chatPanel.getByText('hello from the assistant').hover()
Ah my bad! Since this is not chatInput i just updated it to check for the Text :)

2024-07-19 16:24 UTC, abeatrix commented on vscode/test/e2e/common.ts
> -    await expect(page.getByLabel('Settings & Support Section')).toBeVisible()
Good point!I just added a expect and comment to reflect this.

2024-07-19 17:45 UTC, merged