Ak/add logging assertion in agent
sourcegraph/cody pull request #4923
Opened 2024-07-18 14:27 UTC by akalia25

## Test plan
Test via CI and locally with `pnpm run test` on `cody/agent/src/local-e2e`

2024-07-23 17:17 UTC, bobheadxi commented on agent/src/index.test.ts
> +        const testRunId = uuid.v4()
suggestion: uuid V7

2024-07-23 20:37 UTC, akalia25 commented on agent/src/index.test.ts
> +        const testRunId = uuid.v4()
Great suggestion, thank you!

Unfortunately, the `uuid` we have only supports up to `v5()`, since we are on `uuid@9.1`. `uuid@10` has `v5()` ([doc ref](https://www.npmjs.com/package/uuid)).

I believe with the timestamp coming through on the payload, this should suffice, and when cody team upgrades uuid, we can move over :)

2024-07-23 21:44 UTC, bobheadxi commented on agent/src/index.test.ts
> +        const testRunId = uuid.v4()
SGTM!

2024-07-28 16:58 UTC, olafurpg requested changes
Very exciting! I am very eager to start testing telemetry events for the agent. Thank you @akalia25 for kickstarting this 🙏🏻

2024-07-28 16:58 UTC, olafurpg commented on agent/src/index.test.ts
> +        telemetryExporter: 'graphql',
We intentionally disable the graphql telemetry exporter in our tests because telemetry network requests have been a big source of flaky failures. Have you considered using the `testing` telemetry exporter instead? We can add a new `testing/telemetryEvents` request to the agent protocol that automatically resets on `testing/reset` (which we only use in `index.test.ts` but should be using everywhere)

2024-07-28 16:58 UTC, olafurpg commented on agent/src/index.test.ts
> +    let expectedEvents: string[] | undefined
This logic should live in `TestClient` so that it can be reused for all agent integration tests (not only `index.test.ts`)

2024-07-29 19:50 UTC, akalia25 commented on agent/src/index.test.ts
> +    let expectedEvents: string[] | undefined
Great suggestion! Just updated to make `expectedEvents` a part of `TestClient`. Thank you!

2024-07-29 21:47 UTC, akalia25 commented on agent/src/index.test.ts
> +        telemetryExporter: 'graphql',
Hey @olafurpg, thanks for the context. I tried using the `testing` telemetry exporter, but when I was, none of the telemetry requests were getting sent 🤔, and I was having a hard time figuring out where the `testing` telemetry exporter was being set on the agent tests. I think we should be using the `MockServerTelemetryRecorderProvider` when `testing` is set. Could you point me to where the `testing` exporter is being set?

2024-08-15 05:24 UTC, akalia25 commented
Hey @olafurpg, implemented the changes we discussed during our call. Key highlights are using a delegated testing telemetry exporter to validate events fired. Please let me know if you have any further feedback I can work through 🙇 . 

Not sure why the kotlin bindings are failing 🤔 unable to run the `pnpm generate-agent-kotlin-bindings` command, will investigate/work through this.

2024-08-20 09:11 UTC, olafurpg approved these changes
Fantastic work @akalia25 ! LGTM 👍🏻 

I left a non-blocking comment about the use of `afterEach()`. We can address this separately, I may even do the change myself as I continue to take more tests out of `index.test.ts`

2024-08-20 09:11 UTC, olafurpg commented on agent/src/index.test.ts
> +        client.expectedEvents = [
😍 Very nice to capture that these events are logged in these cases

2024-08-20 09:11 UTC, olafurpg commented on agent/src/index.test.ts
> +    afterEach(async () => {
Non-blocking: I'm not a huge fan of using `afterEach` here. I think it might be cleaner to

- clear `expectedEvents` on `testing/reset`
- manually add `expect(await client.exportedTelemetryEvents()).toMatch(...)` at the end of test cases where we want to assert what events got exported

The benefit of this approach is that you get clearer error messages pointing to a relevant line of code in the tests. With the `afterEach()` approach, you need to hunt down the test name and reason about this `currentClient` logic. Also, this `afterEach()` block is only available in `index.test.ts`, it's not straightforward how to reuse this logic in other test files. My goal is to eventually remove `index.test.ts` in favor of more narrow/targeted test suites. This file has become a catch-all, which resulted in cryptic test failures that have been difficult to track down.

2024-08-20 09:14 UTC, olafurpg commented
@akalia25 FYI, I updated the PR title and PR description to match the style I recommend using in all PRs:

- Title: `WHAT_COMPONENT: WHAT_CHANGED_IN_PRESENT_TENSE`.
- Description: `Previously, EXPLAIN_PROBLEM. Now, EXPLAIN_SOLUTION`.

2024-08-20 16:49 UTC, akalia25 commented on agent/src/index.test.ts
> +    afterEach(async () => {
Thank you @olafurpg, this is great feedback, and definitely agree with your approach. I was primarily using the `afterEach` to avoid adding the assertions after each test, but seems like that would be the cleaner way to go. I'll address this in another PR, in favor of getting this merged :)

2024-08-20 16:49 UTC, merged

2024-09-06 15:05 UTC, akalia25 commented on agent/src/index.test.ts
> +    afterEach(async () => {
PR here to make the above change :) :
- https://github.com/sourcegraph/cody/pull/5455