Dan's CSS change
sourcegraph/cody pull request #4975
Opened 2024-07-23 00:17 UTC by abeatrix

Attempted to get the changes out of https://github.com/sourcegraph/cody/tree/dan-jetbrains-css 's branch in this PR

## Test plan

UI chat

## Changelog

2024-07-23 02:42 UTC, dominiccooney requested changes
@danielmarquespt we need these CSS changes to not break VSCode in addition to making JetBrains work... did you try these in VS Code? It seems surprising to introduce a `--jetbrains-` variable outside of a `html[data-ide=JetBrains] ...` selector.

It would be great to have a summary of the changes in the sheet, some screenshots, etc.

Here's the architecture we want for Webview CSS, but @vovakulikov and @taiyab feel free to correct me:

- Short term, we keep using the `--vscode-`... variables for colors, etc.
- Web and JetBrains are setting those to specific values, in JetBrains case it is in the `vscode/webviews/themes/jetbrains.css` sheet. I assume Web is just strategically including some other sheet somewhere?
- If more JetBrains-specific customization is needed, it would be by `html[data-ide="JetBrains"]` ancestor selector, but preferably keep this to an absolute minimum.
- Over time, the webview could move to CSS that reflects our own design system and so maybe it uses its own set of variables, not `--vscode-`.

2024-07-23 02:42 UTC, dominiccooney commented on vscode/webviews/components/modelSelectField/ModelSelectField.module.css
> +.model-title-with-icon:is(a) {
Why are we un-SASSing this?

2024-07-23 02:42 UTC, dominiccooney commented on vscode/webviews/components/modelSelectField/ModelSelectField.module.css
> +    border: 4px solid var(--jetbrains-Desktop-background);
This doesn't look right, because what's VSCode going to do here?

2024-07-23 11:49 UTC, danielmarquespt commented on vscode/webviews/components/modelSelectField/ModelSelectField.module.css
> +.model-title-with-icon:is(a) {
This is not SASS (AFAIK) its native CSS nesting https://caniuse.com/css-nesting

Which is not supported on the Chromium version of the webviews

2024-07-23 11:54 UTC, danielmarquespt commented on vscode/webviews/components/modelSelectField/ModelSelectField.module.css
> +    border: 4px solid var(--jetbrains-Desktop-background);
Good catch. Should not be here! I'll fix it

2024-07-24 18:14 UTC, danielmarquespt commented
I'm closing these PR as I included most of these changes on `dpc/web-content` taking into account the code review left here.

2024-07-24 18:14 UTC, closed without merging