First ugly working implementation
sourcegraph/cody pull request #5137
Opened 2024-08-08 05:58 UTC by RXminuS

## Test plan

## Changelog

2024-08-08 05:58 UTC, RXminuS commented
* **#5137** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5137?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RXminuS and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-14 11:43 UTC, olafurpg requested changes
Overall LGTM 👍🏻 Requesting changes for mostly basic changes. Let's get this merged behind a flag and get some feedback!

* Would be nice if we can remove `vscode/scripts/lint/tsguide.codylints.yaml`.
* Might be worth adding a feature flag so we can turn this on for the Sourcegraph org without asking people to fiddle with settings.

2024-08-14 11:43 UTC, olafurpg commented on agent/src/cli/command-lint.ts
> +        .option('-o, --output <output>', 'Output file')
What format is the output? I'm guessing we will add some kind of `--output-format` later.

2024-08-14 11:43 UTC, olafurpg commented on agent/src/cli/command-lint.ts
> +Examples:
Very helpful 👍🏻

2024-08-14 11:43 UTC, olafurpg commented on agent/src/cli/command-lint.ts
> +            if (!options.accessToken) {
Note to self, I want to provide a helper to do this so we don't copy-paste so much code between commands. Should be an easy refactor later, really no need to worry about it here.

2024-08-14 11:43 UTC, olafurpg commented on agent/src/cli/command-root.ts
> +        hidden: !(experimental.all || experimental.lint),
Nice 👍🏻

2024-08-14 11:43 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +        { targetFiles: string[]; lintFiles: string[]; model?: string },
should probably use "ruleFiles" to mirror `--rule` from the CLI. Also, need to specify these are URIs.

2024-08-14 11:43 UTC, olafurpg commented on agent/src/cli/command-lint.ts
> +    console.log('targetFiles', targetFiles)
Remove

2024-08-14 11:43 UTC, olafurpg commented on vscode/src/jsonrpc/agent-protocol.ts
> +        { success: boolean; diagnostics: { uri: string; diagnostics: ProtocolDiagnostic[] }[] },
Let's extract the nested anonymous struct into an interface type. Will be much cleaner in the generated bindings for Kotlin/Java.

2024-08-14 11:43 UTC, olafurpg commented on vscode/src/configuration.ts
> +        experimentalCodyLintEnabled: getHiddenSetting('experimental.lint.enabled', true),
Disable by default?
```suggestion
        experimentalCodyLintEnabled: getHiddenSetting('experimental.lint.enabled', false),
```

2024-08-14 11:43 UTC, olafurpg commented on vscode/src/lint/options/menu.ts
> +// const rangeSymbolsInput = createQuickPick({
Dead code

2024-08-14 11:43 UTC, olafurpg commented on vscode/src/lint/options/menu.ts
> +const ONBOARDING_LINT_TEMPLATE =
Can you elaborate what this is?

2024-08-14 11:43 UTC, olafurpg commented on vscode/src/configuration.test.ts
> +                    case 'cody.experimental.pre-r.enabled':
`pre-r`?

2024-10-20 02:05 UTC, closed without merging