Reindex embeddings if they are stale
sourcegraph/cody pull request #5141
Opened 2024-08-08 09:38 UTC by janhartman

TODO: BFG version upgrade.

## Test plan
Tested locally.

## Changelog
- Embeddings index is periodically rebuilt if it is stale.

2024-08-09 21:45 UTC, beyang requested changes

2024-08-09 21:45 UTC, beyang commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommitHash = vscodeGitAPI?.repositories[0]?.state.HEAD?.commit ?? ''
Is this the right thing to do? Or should we trigger an update for the index of the currently active repository (presumably the repository tagged in the user query)

2024-08-09 21:45 UTC, beyang commented on vscode/src/local-context/local-embeddings.ts
>      private async onHealthReport(repoDir: FileURI, health: IndexHealthResultFound): Promise<void> {
When is this function called? It looks like it's just called when the embeddings controller initializes, which suggests this check is only triggered when the editor restarts. Is that right?

2024-08-09 21:45 UTC, beyang commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommit = await vscodeGitAPI?.repositories[0]?.getCommit(currentCommitHash)
One of the cases that triggered poor results for symf is when the user checks out a revision that's different from the one that's indexed. Many devs do this fairly commonly (e.g., checking out an old revision to backport a bug). If the reindexing check happens when the very old branch is checked out, then we could go a full day before the index is updated, which means context will be very stale until then. For this reason, symf now has [update logic](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/local-context/symf.ts?L877) that triggers more aggressively, provided that the last index did not take too long, and depending on the magnitude of the delta. Can we implement something similar for local embeddings?

2024-08-11 07:27 UTC, PriNova commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommit = await vscodeGitAPI?.repositories[0]?.getCommit(currentCommitHash)
What about this approach: 
Generate a SHA-256 hash for each file based on its content. Store this hash in a metadata field within the index alongside the files. During checkout, only the files with changes are verified against their hashes. Additionally, `git diff --diff-filter=ACMRT --name-only` can be used with Git for potentially faster operations to discover the deltas. Moreover, store the Symf-generated index within the project repository so that each branch has its unique index file. This could also apply to the embeddings file for each project. If storing the index/embeddings in the repository is not preferred, then adopt a folder structure that uses the project name and branch as subfolders in the currently used folder structure, similar to how Gradle handles cached dependencies.

2024-08-12 13:56 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
>      private async onHealthReport(repoDir: FileURI, health: IndexHealthResultFound): Promise<void> {
It's called after the embeddings are loaded. Good point, I think we need to call it periodically to catch the case where people keep projects open for a long time.

2024-08-12 13:58 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommit = await vscodeGitAPI?.repositories[0]?.getCommit(currentCommitHash)
@PriNova thanks for the suggestion! Unfortunately this a bit too much to justify working on since we plan to deprecate local embeddings anyway.

2024-08-12 14:02 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommitHash = vscodeGitAPI?.repositories[0]?.state.HEAD?.commit ?? ''
I assumed `repositories[0]` would be the currently active repository, which is wrong - sorry, didn't look into the API enough since our shim has no documentation. Currently active repository should make sense.

2024-08-12 14:05 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommit = await vscodeGitAPI?.repositories[0]?.getCommit(currentCommitHash)
@beyang makes sense, will look into it.

2024-08-13 21:23 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
> +        const currentCommit = await vscodeGitAPI?.repositories[0]?.getCommit(currentCommitHash)
Fixed.

2024-08-13 21:23 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
>      private async onHealthReport(repoDir: FileURI, health: IndexHealthResultFound): Promise<void> {
Fixed - added a health check call on every querying with at least a minute in between.

2024-08-19 20:33 UTC, janhartman commented on vscode/src/chat/chat-view/ChatController.ts
> -
This was a bug and isn't necessary, we start it earlier.

2024-08-22 05:49 UTC, olafurpg requested changes

2024-08-22 05:49 UTC, olafurpg commented on vscode/src/extension.node.ts
> +        .get<boolean>('cody.advanced.agent.running', false)
There needs to be a way to disable embeddings on VSC. It's better to set that setting to false by default in the agent instead of disabling 100% for agent clients. I recall there was no strong technical reason for disabling embeddings in agent clients, BFG was just too buggy that it was slowing down progress on JetBrains. There is a class that sets default setting for the agent where we can disable embeddings.

2024-08-22 05:49 UTC, olafurpg commented on vscode/src/extension.node.ts
> +        createLocalEmbeddingsController: isLocalEmbeddingsDisabled
Nit: I recommend keeping the "enabled" variable name as it's easier to read the code that way.

2024-08-22 05:49 UTC, olafurpg commented on vscode/src/external-services.ts
> +        ? await platform.createLocalEmbeddingsController?.(initialConfig)
We should ideally listen to with events and initialize embeddings on the condition that the user is authenticated to dotcom. I believe isDotcom is true for enterprise users because they authenticate.

2024-08-22 05:49 UTC, olafurpg commented on vscode/src/local-context/local-embeddings.ts
> +        const repo = vscodeGitAPI?.getRepository(repoDir)
Non-blocking: BFG has full hit bindings so it might make sense to implement this on the Rust side. The VSC git APIs have spotty support for agent clients. The benefit of continuing investments in local embeddings is even smaller if we only aspire to support VSC.

2024-08-22 07:09 UTC, janhartman commented on vscode/src/external-services.ts
> +        ? await platform.createLocalEmbeddingsController?.(initialConfig)
Are you sure? I think `isDotCom` means PLG. At least that's what we use in at least 10 other places where the behavior is PLG/enterprise dependent.

2024-08-22 07:16 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
> +        const repo = vscodeGitAPI?.getRepository(repoDir)
This was a very minimum-possible-effort PR so I don't believe I'll be touching the Rust side any more than necessary. The VSCode-only situation is OK.

2024-08-22 07:18 UTC, janhartman commented on vscode/src/extension.node.ts
> +        .get<boolean>('cody.advanced.agent.running', false)
There is a `cody.experimental.localEmbeddings.disabled` setting which disables them everywhere.

2024-08-22 07:19 UTC, janhartman commented on vscode/src/extension.node.ts
> +        createLocalEmbeddingsController: isLocalEmbeddingsDisabled
Yeah agreed, negatives are harder to parse. In my defense, I just reverted your changes to this file 😄

2024-08-22 07:31 UTC, janhartman commented on vscode/src/extension.node.ts
> +        .get<boolean>('cody.advanced.agent.running', false)
@olafurpg Is there another elegant way I could do what you proposed - i.e. detect if I'm in VSCode or agent? The current config structure doesn't lend itself nicely to your ask.

2024-08-22 09:26 UTC, olafurpg approved these changes
stamp to unblock merging. The only hard requirement is that we don't re-introduce downloading BFG before authentication to dotcom. This needs to be tested manually, there are no integration tests for it. Make sure to handle the flow from unauthenticated->Enterprise (it's not enough to sign into Enterprise and reload, you need to sign out). It's also worth checking that embeddings work on the first run for the unauthenticated->PLG flow.

2024-08-22 09:26 UTC, olafurpg commented on vscode/src/extension.node.ts
> +        createLocalEmbeddingsController: isLocalEmbeddingsDisabled
It was a cleanup to remove the negatives and I'd prefer to not re-introduce it.

2024-08-22 09:26 UTC, olafurpg commented on vscode/src/external-services.ts
> +        ? await platform.createLocalEmbeddingsController?.(initialConfig)
`isDotCom` is true by default https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@a94f37d2b6c06bd75e991c84189b85df0dfc1cc7/-/blob/lib/shared/src/auth/types.ts?L47

We need to additionally guard against `isLoggedIn`.

2024-08-22 09:26 UTC, olafurpg commented on vscode/src/local-context/local-embeddings.ts
> +        const repo = vscodeGitAPI?.getRepository(repoDir)
Agreed, this is non-blocking. Just wanted to call out that the value of local embeddings from a product perspective is low when it's an exclusive feature for PLG on VSC only. In general, we want our projects to benefit all users across the board (PLG + Enterprise, also all clients).

2024-08-22 11:53 UTC, janhartman commented on vscode/src/external-services.ts
> +        ? await platform.createLocalEmbeddingsController?.(initialConfig)
Thanks for pointing it out. This feels like a footgun.

2024-08-22 11:55 UTC, janhartman commented on vscode/src/extension.node.ts
> +        .get<boolean>('cody.advanced.agent.running', false)
Thanks, fixed.

2024-08-22 11:56 UTC, olafurpg commented on vscode/src/external-services.ts
> +        ? await platform.createLocalEmbeddingsController?.(initialConfig)
There have been several attempts to refactor some of this logic. All the config passing code has lots of debt...

2024-08-22 11:57 UTC, janhartman commented on vscode/src/local-context/local-embeddings.ts
> +        const repo = vscodeGitAPI?.getRepository(repoDir)
Acknowledged. Let's make sure we deliver value everywhere with server-side context :)

2024-08-22 15:31 UTC, chenkc805 commented
Do we have telemetry that measures when an a codebase is re-indexed?

2024-08-26 06:48 UTC, janhartman commented
@chenkc805 No, but it's a good idea, let me add it 👍

2024-08-26 07:32 UTC, janhartman commented
@olafurpg I followed the procedure you wrote down in #5140 and it seems everything's in order - we only download the binary if the users is PLG and local embeddings are enabled.

2024-08-27 08:59 UTC, merged