WIP config/state listening
sourcegraph/cody pull request #5221
Opened 2024-08-18 10:06 UTC by sqs

Closes https://linear.app/sourcegraph/issue/CODY-3332/full-native-offline-mode-and-instant-config-reactivity-for-cody-in-vs.

See https://sourcegraph.slack.com/archives/C05AGQYD528/p1723791822404399.

## Test plan

TODO

## Changelog

2024-09-11 08:04 UTC, sqs commented
@Manouchehri We already have offline mode, but this (or a future PR) will support an ephemeral offline mode that is a bit smoother. Not a big new feature or anything, just something that makes it handle network connectivity issues better.

2024-09-17 02:27 UTC, beyang approved these changes

2024-09-18 21:36 UTC, vovakulikov commented
I am just flagging it here for the record (since this PR has been approved); before merging this, we have to check that this PR works against a clean run in Cody Web demo (by clean, I mean with reset data in Index DB in the Cody Web demo) and check that Cody Web chat loads. 

I think currently (this is the last commit b2749d4fbe53e4e47ac8cc24ba59db44383f8675) Cody Web fails with no auth runtime error

2024-09-18 21:51 UTC, sqs commented
> I am just flagging it here for the record (since this PR has been approved); before merging this, we have to check that this PR works against a clean run in Cody Web demo (by clean, I mean with reset data in Index DB in the Cody Web demo) and check that Cody Web chat loads.
> 
> I think currently (this is the last commit [b2749d4](https://github.com/sourcegraph/cody/commit/b2749d4fbe53e4e47ac8cc24ba59db44383f8675)) Cody Web fails with no auth runtime error

Just confirmed on the latest push that `pnpm -C web dev` works after I clear IndexedDB.

It still has a bit of SiteProductVersion and other GraphQL request spam, which I will fix before merging.

2024-09-18 22:10 UTC, dominiccooney commented
Just tried patching this and it breaks JetBrains in some trivial ways (some model tags are nullable) and maybe more complicated ways (some problem deserializing AuthStatus at com.sourcegraph.cody.agent.protocol_generated.AuthStatus.deserializer$lambda$0(AuthStatus.kt:22) ... this is generated, interesting that it can fail...)

2024-09-18 22:19 UTC, vovakulikov commented
@sqs

> Just confirmed on the latest push that pnpm -C web dev works after I clear IndexedDB.

This problem is tricky, you have to clear the index db each time you load cody chat because we seed the index db with some standard data structure after every chat load. 

This is how you can still reproduce this (this is the latest commit from this branch)

https://github.com/user-attachments/assets/c0e10c4e-8556-4a19-97dc-f6098b5065d8

2024-09-18 22:22 UTC, dominiccooney commented
> some problem deserializing AuthStatus ...

Looked at this a bit, and the bindings generator is confused by UnauthenticatedAuthStatus, AuthenticatedAuthStatus and the AUTH_STATUS_FIXTURE_AUTHED etc.

It has generated a type which appears to expect endpoint to always be https://example.com which is obviously not right.

2024-09-19 01:20 UTC, sqs commented
> @sqs
> 
> > Just confirmed on the latest push that pnpm -C web dev works after I clear IndexedDB.
> 
> This problem is tricky, you have to clear the index db each time you load cody chat because we seed the index db with some standard data structure after every chat load.
> 
> This is how you can still reproduce this (this is the latest commit from this branch)
> 
>  Screen.Recording.2024-09-18.at.19.16.17.mov

@vovakulikov Indeed, that is what I did. I just did it a few more times and it still worked, even when I simulated a Fast 4G internet connection. Can you try it on the latest commit here? Maybe I was on a newer commit.

2024-09-19 17:22 UTC, dominiccooney approved these changes
LGTM, would be nice to reenable the e2e enterprise-cody-ignore test if the autocomplete at cursor command is in fact being registered now.

2024-09-19 17:22 UTC, dominiccooney commented on lib/shared/src/misc/observable.test.ts
> +        expect(values).toStrictEqual<typeof values>([['c', 'y']])
Would be nice to test this where one or the other observable advances, but not both.

2024-09-19 17:44 UTC, vovakulikov commented
I've noticed one regression in one box logic, Cody Web demo is connected to s2 now where we have enabled one box feature flag, and I see that chat intent detection returns search intent (this means we produce an empty message from LLM) but we should render code snippets instead in this case which doesn't happen on this branch for some reason. I think something happened in the config event, which no longer produces the right value of one box. 

Probably due to `this.featureCodyExperimentalOneBox.value.last` change in ChatController 

cc @sqs

2024-09-19 17:50 UTC, vovakulikov commented
Also important thing is that the production build of Cody Web fails in the Sourcegraph Web app with no auth error 

<img width="1171" alt="Screenshot 2024-09-19 at 14 50 00" src="https://github.com/user-attachments/assets/1fe5b53d-119a-4a8f-a283-740148f5655a">

2024-09-19 17:53 UTC, vovakulikov commented
Instruction to reproduce 

In Cody Repo 
- Upgrade Cody web package.json version to `0.9.0`
- `pnpm build` in web directory 
- `pnpm link` --global in web directory 

In Sourcegraph Repo
- Specify 0.9.0 version in `@sourcegraph/cody-web` package
- `pnpm link @sourcegraph/cody-web --global`
- Run any sg command to serve client (`sg start web-standalone`)

2024-09-19 18:17 UTC, vovakulikov requested changes
This problem with Cody Web in production bothers me a lot, so I request changes to avoid any possible merges here for now

2024-09-19 18:53 UTC, vovakulikov commented on agent/src/agent.ts
>                      ? this.handleConfigChanges(clientInfo.extensionConfiguration, {
@sqs I think this is the place because of which it fails in the Sourcegraph Web app. In the web app, we don't have any access token, we use cookie auth flow instead so the access token is always null in the Sourcegraph Web app, but I think we still should run handleConfigChanges because otherwise we never emit auth value by `authProvider.validateAndStoreCredentials`

2024-09-19 19:23 UTC, vovakulikov commented on agent/src/agent.ts
>                      ? this.handleConfigChanges(clientInfo.extensionConfiguration, {
I think I found it, so I see that you already got CodyWeb special case inside `validateAndStoreCredentials` method. But I think `validateCredentials` ignores cody web since we don't pass agentIDE in handleConfigChanges. 

So I think we should
In Agent constructor parse and handle Cody Web case
```ts
const ide = AgentWorkspaceConfiguration.clientNameToIDE(clientInfo.name)
this.authenticationPromise = clientInfo.extensionConfiguration && (clientInfo.extensionConfiguration?.accessToken || ide === CodyIDE.Web)
    ? this.handleConfigChanges(clientInfo.extensionConfiguration, {
        ide,
        forceAuthentication: true
      })
    : Promise.resolve()
```

In handleConfigChanges make sure we pass config IDE
```ts
 private async handleConfigChanges(
        config: ExtensionConfiguration,
        // Pass ide param here in order to specify it in validateAndStoreCredentials
        params?: { forceAuthentication: boolean, ide?: CodyIDE }
    ): Promise<void> {
     // ... 
      await authProvider.validateAndStoreCredentials({
        configuration: { agentIDE: params?.ide, customHeaders: config.customHeaders },
        // ...
        }, always-store')
        // ...
    }
```

2024-09-19 19:32 UTC, sqs commented on agent/src/agent.ts
> -                this.webPanels.panels.clear()
JetBrains webview code is now the web app and auth changes are handled in a more standard way, so I thought this would be safe to remove.

2024-09-19 19:32 UTC, sqs commented on agent/src/cli/command-chat.ts
> +    await sleep(750)
I removed this

2024-09-19 19:40 UTC, sqs commented on agent/src/agent.ts
>                      ? this.handleConfigChanges(clientInfo.extensionConfiguration, {
Thanks! Applying now. `validateCredentials` still fetches the user info and cody-enabled status on Cody Web btw.

2024-09-19 19:45 UTC, vovakulikov commented on agent/src/agent.ts
>                      ? this.handleConfigChanges(clientInfo.extensionConfiguration, {
No problems, we also should run handleConfigChange in the agent constructor for Cody Web even if we don't have token (This commit edb254a9bb3f3b34f6bb07c782cc4c6eba5e3328 is missing it I think)

2024-09-19 21:36 UTC, dominiccooney commented on agent/src/agent.ts
> -                this.webPanels.panels.clear()
I am not sure why we needed this, but it is ancient. But `webPanels.panels` are the "agentic" ones, not the "native" ones, so it doesn't matter any more.

Now that "native" webviews have stuck, we should probably remove the "agentic" panels and add a structured chat API that emacs, neovim and cli/agent could use.

2024-09-20 15:12 UTC, vovakulikov commented
@sqs I don't want to block this PR, but I also don't know if you want to do anything extra here; if you can provide some todos progress, it would be useful (I also can help with something). From my side, it looks like
- [ ] Fix failing e2e tests 
- [ ] Fix Cody Web handle config change run (see the last comment https://github.com/sourcegraph/cody/commit/edb254a9bb3f3b34f6bb07c782cc4c6eba5e3328)
- [ ] Fix `this.featureCodyExperimentalOneBox.value.last` problem in ChatController (this comment https://github.com/sourcegraph/cody/pull/5221#issuecomment-2361815664)

After this, we probably would be ready to merge this. I did a round of manual testing and didn't find anything suspicious

2024-09-20 23:43 UTC, sqs commented
Re-posting @dominiccooney's comment https://github.com/sourcegraph/cody/pull/5637#discussion_r1767003860 here:

<blockquote>
This API seems prone to abuse.

The use case is legitimate, let me suggest something like:

```
localstorage.batchChangeEvent(() => {
  localStorage.set('foo', 'bar')
  localStorage.set('baz', 'quux')
})
```

You can probably think of a better name.

Within the scope of the callback (handle reentrancy) you should suppress change events and fire them when done.

This means callers can't suppress fire events unilaterally, only batch them. And their batches are limited to the same microtask...if they have async work to do, they have to prepare it first. AND it means you won't have a half-written state, interrupted by async, with someone else doing an async write and causing half written state to be observed. AND you can handle being robust to execptions etc. without forgetting to fire the event.
</blockquote>

2024-09-23 14:00 UTC, vovakulikov commented
@sqs (or anyone else here) have you seen context retriever errors like this on your machine 
<img width="1171" alt="Screenshot 2024-09-23 at 10 59 24" src="https://github.com/user-attachments/assets/61ff44f8-481c-4e00-bdec-bbce47ed9b58">

2024-09-23 16:04 UTC, sqs commented
> @sqs (or anyone else here) have you seen context retriever errors like this on your machine <img alt="Screenshot 2024-09-23 at 10 59 24" width="1171" src="https://private-user-images.githubusercontent.com/18492575/369909446-61ff44f8-481c-4e00-bdec-bbce47ed9b58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDUwNTIsIm5iZiI6MTcyNzEwNDc1MiwicGF0aCI6Ii8xODQ5MjU3NS8zNjk5MDk0NDYtNjFmZjQ0ZjgtNDgxYy00ZTAwLWJkZWMtYmJjZTQ3ZWQ5YjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOWJiYzc0NGY3MDIwZGQxZTkyYTJlN2ViNzMyNTY3NmRkZTBiZWE1MGU2MGNlOTE2ZTMwNjgwODA4MDM3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j0O-ChsXiLowQ5Xfx1ZVI7bmYMhWOeZjE2chjx1qSsU">

Weird, no, never seen that. I don't even know how it's reading those. Is it possible you have some agent unit test env vars set when you are running `pnpm -C web dev`?

2024-09-23 16:14 UTC, vovakulikov commented
It looks like something happened with context fetching but this problem is on the server side (I thought that it's this PR problem) 

I can confirm that this is the problem on main branch as well (something probably happened with context file cache on the instance)

2024-09-23 16:22 UTC, vovakulikov approved these changes
Ok, I've checked Cody Web demo and sg/sg linked version and I haven't noticed any problems (besides problems that are listed in this PR description)

2024-09-23 17:31 UTC, abeatrix reviewed
Found some potential bugs that I think can be fixed in follow-ups:
- [ ] Sign-out button does not work when logged in as DotCom Cody Free user. Here is the Loom  https://www.loom.com/share/09df6c9c85244c3ca8ddc6a99b2d0d39
- [ ] The current files will show up as "token limit exceeded" after reloading VS Cody until you switch model. Loom: https://www.loom.com/share/1dbc51aab40e4e72ac025c4e25af694f

![image](https://github.com/user-attachments/assets/a41c3028-7fff-4224-b0fd-a6e152effcf0)

Signed into Dotcom with Cody Free account:
- [x] Default Models are showing up correctly
- [x] Configured Models are showing up correctly and are updated on change
- [x] Chat is working (able to submit with response)
- [x] Chat command is working (able to submit with response)
- [x] Edit command is working (able to submit with response)
- [ ] BUG: Sign-out button does not work

![image](https://github.com/user-attachments/assets/da2ece0b-39c2-44b5-b6d2-a25ae70d0aae)

Signed into Dotcom with Cody Pro account:
- [x] Default Models are showing up correctly
- [x] Configured Models are showing up correctly and are updated on change
- [x] Chat is working (able to submit with response)
- [x] Chat command is working (able to submit with response)
- [x] Edit command is working (able to submit with response)
- [x] Sign out button works
- [ ] BUG: the current file will show up as "token limit exceeded" after reloading VS Code:
![image](https://github.com/user-attachments/assets/8d5f3d1d-3692-49f8-ab3e-62781db846c1)

S2: Unable to test due to model configuration issue?

![image](https://github.com/user-attachments/assets/a885b5e7-aad2-4b01-8c77-5b6fda2089f7)

Updated: It works if I reload VS Code and I am logged in to S2:
- [x] Server-side configured Models are showing up correctly
- [ ] BUG: Cannot select a different model?
- [x] Editor-side Configured Models are showing up correctly and are updated on change
- [x] Chat is working (able to submit with response)
- [x] Chat command is working (able to submit with response)
- [x] Edit command is working (able to submit with response)
- [x] Sign out button works

![image](https://github.com/user-attachments/assets/fd53f8be-6ed1-4e3a-856d-8ffc8ec5da27)

![image](https://github.com/user-attachments/assets/a4de7a6b-6224-40bc-9a19-b1022c5f1885)

2024-09-23 17:41 UTC, abeatrix approved these changes

2024-09-23 18:48 UTC, kalanchan commented
Feedback: Tested with Cody Pro (dotcom), and Enterprise (S2)

2024-09-23 19:26 UTC, abeatrix commented on vscode/src/chat/chat-view/ChatController.ts
> +                        accessToken: message.value,
```suggestion
                    await authProvider.validateAndStoreCredentials(
                        {
                            serverEndpoint: message.endpoint,
                            accessToken: message.value,
                        },
                        'store-if-valid'
                    )
```

Should we use `validateAndStoreCredentials` here when user tries to sign in via the UI?

2024-09-23 20:12 UTC, kalanchan commented
Tested with Cody Pro (dotcom), and Enterprise (S2), @sqs my experience were _slightly_ different than your known issues:

1. Switching from s2 to dotcom will not pickup new instance's model names and will sometimes retain the old instance's feature flags as well? 

example - Switching from S2 to Dotcom, seeing weird behaviour where the model list is pulled correctly but calls to the completions endpoint is using the wrong model name
![CleanShot 2024-09-23 at 15 22 32@2x](https://github.com/user-attachments/assets/3f1162d6-362f-40fc-8021-b3dcbcdfe304)

![CleanShot 2024-09-23 at 15 44 51@2x](https://github.com/user-attachments/assets/0f02ddd6-4097-4aa9-aebc-167d735aacb2)


2. Autocomplete doesn't work immediately when switching from dotcom to s2, I tried multiple times and each time seems to be a bit different everytime before the provider gets picked up. Usually >60s. Switching to dotcom works immediately

2024-09-23 21:28 UTC, abeatrix commented on lib/shared/src/models/sync.ts
> +    )
```suggestion
    const relevantConfig = combineLatest([
        resolvedConfig.pipe(
            map(
                config =>
                    ({
                        configuration: {
                            customHeaders: config.configuration.customHeaders,
                            providerLimitPrompt: config.configuration.providerLimitPrompt,
                            devModels: config.configuration.devModels,
                        },
                        auth: config.auth,
                        clientState: {
                            waitlist_o1: config.clientState.waitlist_o1,
                        },
                    }) satisfies PickResolvedConfiguration<{
                        configuration: 'providerLimitPrompt' | 'customHeaders' | 'devModels'
                        auth: true
                        clientState: 'waitlist_o1'
                    }>
            )
        ),
        authStatus.pipe(map(status => status.endpoint)),
    ]).pipe(
        distinctUntilChanged(
            (prev, curr) => JSON.stringify(prev[0]) === JSON.stringify(curr[0]) && prev[1] === curr[1]
        ),
        map(([config, endpoint]) => ({ ...config, endpoint }))
    )
```

Not sure if this is the right way to do it, but including the `authStatus.endpoint` in the distinctUntilChanged check for the relevantConfig observable fixed the issue where models are not resynced when switching from dotcom to S2 for me.

2024-09-23 22:31 UTC, abeatrix commented on lib/shared/src/models/sync.ts
> +    )
never mine it doesn't work after i reloaded my extension host.

2024-09-24 02:17 UTC, dominiccooney commented
@kalanchan I'm seeing that cross-account model choice issue too. Picking a different model gets it back in a good state for me (in JetBrains.) I don't think we should block landing this on that issue.

I don't repro the problem with autocomplete switching between dotcom and s2.

Status update from JetBrains: digging into an issue where there's no context for any chats, with this error:

```
2024-09-24 11:00:25,755 [  28826]   WARN - #com.sourcegraph.cody.agent.CodyAgent - Uncaught exception: Error: Cannot set new context used for bot message
2024-09-24 11:00:25,755 [  28826]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at ChatModel.setLastMessageContext (C:\Users\DominicCooney\dev\cody\vscode\src\chat\chat-view\ChatModel.ts:67:19)
2024-09-24 11:00:25,755 [  28826]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at ChatController.handleSearchIntent (C:\Users\DominicCooney\dev\cody\vscode\src\chat\chat-view\ChatController.ts:867:24)
2024-09-24 11:00:25,755 [  28826]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at <anonymous> (C:\Users\DominicCooney\dev\cody\vscode\src\chat\chat-view\ChatController.ts:786:43)
2024-09-24 11:00:25,755 [  28826]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

2024-09-24 03:41 UTC, sqs commented on vscode/src/chat/chat-view/ChatController.ts
> +                        accessToken: message.value,
In this case, no, since I think the desired behavior is for those creds to be stored no matter what, even if the user is (for example) temporarily offline and the creds can't be validated. I could see it going either way.

2024-09-24 04:06 UTC, valerybugakov approved these changes
Tested autocomplete with DotCom, sg02, sg04, and demo instances. Tried changing local settings, switching accounts, and generating completions. No noticeable issues so far!

2024-09-24 05:51 UTC, sqs commented
I believe I fixed the switch-accounts issues in the latest push (https://sourcegraph.com/github.com/sourcegraph/cody/-/commit/7d8816). I'm going to get breakfast then can test, but if anyone is around and can start as well, that'd be great. Post what you see here. Thanks!

2024-09-24 06:20 UTC, valerybugakov reviewed
It might be unrelated to reactivity changes. 

1. DotCom login.
2. Start a new chat.
3. Switch account to sg04.
4. Send `hello` with the default context to repro the error on the screenshot. 

<img width="239" alt="Screenshot 2024-09-24 at 14 17 56" src="https://github.com/user-attachments/assets/a20e1399-df5a-4c9b-9670-e919555e49ac">

2024-09-24 06:37 UTC, valerybugakov reviewed
It might be unrelated to reactivity changes.

Minor UX moment: when I reload my Cody-authenticated VS Code instance, I see a login sidebar for a few seconds before the new chat UI appears. It would be nice to avoid this layout thrashing.

Minor UX moment: the `New Chat` button doesn't focus on the chat panel if clicked (nothing happens).

<img width="239" alt="Screenshot 2024-09-24 at 14 40 08" src="https://github.com/user-attachments/assets/899e5ceb-ba34-41aa-95f9-6879041236c5">

2024-09-24 06:46 UTC, valerybugakov reviewed
It's possible to get Cody's data into an inconsistent state. I switched between sg04 and DotCom multiple times. `o1-preview` was the selected chat model on DotCom. On the sg04 account, the dropdown correctly shows available models, but the underlying logic tries to use `openai/cody-chat-preview-001` to send the chat message, which results in the error:

<img width="239" alt="Screenshot 2024-09-24 at 14 42 09" src="https://github.com/user-attachments/assets/3fc126b4-58c3-41ed-8b8d-f05fddcbc912">

```js
extensionHostProcess.js:155 Error: Request to https://sg04.sourcegraphcloud.com/.api/completions/stream?client-name=vscode&client-version=1.34.3 failed with 400 Bad Request: unsupported chat model "openai/cody-chat-preview-001" (default "fireworks::v1::llama-v3p1-70b-instruct")

    at IncomingMessage.<anonymous> (/Users/val/Desktop/sourcegraph-root/cody/vscode/src/completions/nodeClient.ts:179:33)
```

---------------------------------------------------

UPD: I can somewhat consistently repro this:

1. Select `o1-preview` on the DotCom account. 
2. Select `mixtral 8x7b` on the sg04 account. 
3. Send the chat message from the sg04 account.
4. Switch to DotCom.
5. Send a new chat message
6. `Request: the requested chat model is not available ("mixtral-8x7b-instruct", onProTier=true, hasFeatureFlags=true)`

I also did the same thing with account switching during the chat-response streaming. Try that if you can't repro the issue using the steps above.

2024-09-24 06:56 UTC, valerybugakov reviewed
Autocomplete is still stable and has no new issues. Tested on DotCom, sg04, sg02, and demo with account switching.

2024-09-24 08:40 UTC, merged

2024-09-24 16:30 UTC, PriNova commented
@sqs I want to add to the list of fixes that an existing chat history is completely empty after switching.