Fix issue with slow tests due to multi-startup
sourcegraph/cody pull request #5228
Opened 2024-08-18 15:59 UTC by RXminuS

## Test plan

## Changelog

2024-08-18 16:00 UTC, RXminuS commented
* **#5026** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5026?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5025** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5025?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5024** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5024?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4999** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/4999?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5003** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5003?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4992** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/4992?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4993** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/4993?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5120** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5120?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5228** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5228?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RXminuS and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-18 17:14 UTC, abeatrix commented
For the marketplace ranking, the only way to improve ranking is to change our extension name to "Cody" because it ranks matches by Display Name first, and then for extension that has the same Display Name, they are ranked by their description in alphabetical order.
So we'll need to change the name to Cody, with the description that starts with "A" 😔

2024-08-18 17:25 UTC, RXminuS commented
> For the marketplace ranking, the only way to improve ranking is to change our extension name to "Cody" because it ranks matches by Display Name first, and then for extension that has the same Display Name, they are ranked by their description in alphabetical order.

I don't think that's true entirely. Reading the discussions on the topic it's very confusing, but I noticed that we rank on certain keywords like `kotlin` even though that's not in the description or name so they aren't entirely discarded.

2024-08-19 02:35 UTC, abeatrix commented
> I don't think that's true entirely. Reading the discussions on the topic it's very confusing, but I noticed that we rank on certain keywords like `kotlin` even though that's not in the description or name so they aren't entirely discarded.
> 
> 
> 
> What's more if you combine ANY keyword with `cody` we're constantly top ranked. So my hope was that by having both the keyword and the name we would rank as expected.
> 
> 
> 
> ![CleanShot 2024-08-18 at 19 32 54@2x](https://github.com/user-attachments/assets/4b932b79-e196-4dc3-a045-46461a1a77ae)

Ah I think I misunderstood your intention, my bad! I thought you wanted to improve Cody's ranking when people search for just "Cody" (which I believe will rank the exact name match first). 

(I'm afk so can't check the package build for the ignore file change,  but can do it tomorrow if no one gets to it first! 😀 )

2024-08-19 09:45 UTC, RXminuS commented
@abeatrix No I am trying to bump the ranking on just "cody" but I don't think the assumption that it's only based on name is correct. For instance, this is what you get when searching for AI...even though there's an exact match
![CleanShot 2024-08-19 at 11 44 44@2x](https://github.com/user-attachments/assets/d6807e2f-ed16-4320-9197-b809997f1b9e)

2024-08-20 04:52 UTC, abeatrix commented
> @abeatrix No I am trying to bump the ranking on just "cody" but I don't think the assumption that it's only based on name is correct. For instance, this is what you get when searching for AI...even though there's an exact match
> 
> ![CleanShot 2024-08-19 at 11 44 44@2x](https://github.com/user-attachments/assets/d6807e2f-ed16-4320-9197-b809997f1b9e)
> 
> 

I just looked at my notes from the old ticket and you're right, it doesn't solely depends on the display name.

I got sidetracked by the visual studio issue today so haven't tested the vscode ignore file still (sorry about that). Will do it first thing tmr morning!

2024-08-21 07:20 UTC, abeatrix requested changes
Packaing from main:
```
 DONE  Packaged: /cody/vscode/cody-ai-1.30.3.vsix (637 files, 27.35 MB)
```

Packaging from this branch:

```
 DONE  Packaged: /cody/vscode/cody-ai-1.30.3.vsix (32 files, 15.47MB)
```

It looks like it's missing the tree sitters files though:

<img width="1499" alt="image" src="https://github.com/user-attachments/assets/7265d8e6-62bd-4572-b926-f2b9ea773430">

But the package size has reduced by a lot still after adding those files back, nicely done 🎉 

```
DONE  Packaged: /cody/vscode/cody-ai-1.30.3.vsix (60 files, 19.52 MB)
```

I think once those files are added back, it should be ok?

RE the keywords change:

I'm not sure if this change would help since I noticed there is another Cody extension with `cody` keywords attached but is still getting ranked in alphabetical order based, but I'm also not sure how it actually works BTS so I'm open to giving this a try (as long as it doesn't cause regressions 😃 )

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/a5f22046-933d-454b-bad4-72ddeb101dae">
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/9ab759f8-51c8-4599-83c8-c0ab9755678e">

2024-08-21 07:20 UTC, abeatrix commented on vscode/package.json
> +    "codey",
i wonder how much does the order of keywords matter in ranking.

Right now we are ranked number 1 in "coding assistant" & ai chatbot:
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/ebb25894-7725-4500-a516-66729f9abddc">
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/fd6de147-11d9-4b32-a758-78401a3b236c">

Number 5 in AI assistant:
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/bfff8266-204d-42c4-afe5-57c607a90183">

Just for our record to keep track if this change would cause other regressions 😁

2024-08-22 07:31 UTC, RXminuS commented on vscode/package.json
> +    "codey",
Looking at the results here the ranking does seem much more blended with rating & download counts. Apart from Fitten Code but I think it's because they have `AI Assistant` in their name, but that goes to show that we at least have a more fair chance of ranking higher with more downloads (e.g. > 1M)

2024-08-23 16:23 UTC, abeatrix commented
@RXminuS it looks like the issue where all the tree-sitter files are still missing in the package. Is it ok to exclude them? cc @valerybugakov 

![image](https://github.com/user-attachments/assets/af5cbe25-0bf4-4a9e-a857-a086c3f00770)

2024-08-23 16:24 UTC, RXminuS commented
Nope just from the resources folder...did I forget to push? 🤦‍♂️

2024-08-26 07:38 UTC, RXminuS commented
@abeatrix ok now it works...who knew that pushing your code has such a big impact 😅

2024-08-27 15:43 UTC, abeatrix approved these changes
Nice!

2024-08-28 07:30 UTC, merged