Improve repository mention search
sourcegraph/cody pull request #5277
Opened 2024-08-21 19:11 UTC by vovakulikov

Closes CODY-3370

This PR brings search mentions results closer to the Sourcegraph search experience (search API feels a bit faster and we also include fuzzy ranking similar to what we do in Sourcegraph search-box UI) 

## Test plan
- Check that all mention flows that require repositories mentions (such as repositories, files and directories) work properly

2024-08-21 19:13 UTC, vovakulikov commented on lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
> +                        item.mention?.data?.repoName &&
@thenamankumar I think it was a mistake on main, I checked, and the directory mention object, and it never contains the `repoID` field; let me know if `repoName` doesn't work here. (on main prior to this PR when I selected repository in directory provider it just selected this repository instead of letting me select an actual directory)

2024-08-21 19:17 UTC, vovakulikov reviewed
@thenamankumar I checked repository, file and directory providers and it work as expected but I saw that you merged directory mentions provider yesterday and it looks like it may not working correctly on dotcom, at least I got no context due to problem of CodyContext gql API (because it expects to have filePattern argument there) 

Full gql error 
```
Variable \"filePatterns\" has invalid value null.\nExpected type \"[String!]!\", found null.
```
Can you please check this in the Cody Web demo (it may look like that directory provider should exist only for non-dot com instances but I think in Cody Web it slips or maybe it's just Cody Web demo problem)

2024-08-22 05:18 UTC, thenamankumar commented on lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
> +                        item.mention?.data?.repoName &&
`/Users/naman/Work/cody/vscode/src/context/openctx/currentRepositoryDirectorySearch.ts`

The directory mention object should always contain the repoID. Check the implementation of `getDirectoryMentions` function. 

![CleanShot 2024-08-22 at 10 44 42@2x](https://github.com/user-attachments/assets/f006adb0-8482-4504-868a-00f2f145c8db)

2024-08-22 05:22 UTC, thenamankumar commented
@vovakulikov the directory providers are enabled only for non-web non-dotcom instances.

2024-08-22 05:27 UTC, thenamankumar commented on lib/shared/src/sourcegraph-api/graphql/client.ts
> +    public async searchRepoSuggestions(query: string): Promise<RepoSuggestionsSearchResponse | Error> {
Can we please parameterise count and default to 10?

2024-08-22 05:32 UTC, thenamankumar commented on vscode/src/context/openctx/common/get-repository-mentions.ts
> +    const dataOrError = await graphqlClient.searchRepoSuggestions(query)
Do we not need to escape the query before sending it for search?

2024-08-22 05:36 UTC, thenamankumar requested changes
Blocking due to https://github.com/sourcegraph/cody/pull/5277/files#r1725631553

Otherwise looks good. Added non blocking comments.

2024-08-22 07:34 UTC, vovakulikov commented on lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
> +                        item.mention?.data?.repoName &&
This is the second step of the directory mention you make screenshot from, but the fix is for the first step when you resolve repository. Check the main this repository resolve mention doesn't have repoID, I think this is why you rely on repo name for remote file resolution as well.

2024-08-22 07:42 UTC, vovakulikov commented on lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
> +                        item.mention?.data?.repoName &&
Here the handler you use for repo resolving in directories provider and it doesn't have repoID, only repoName

https://github.com/sourcegraph/cody/blob/main/vscode/src/context/openctx/remoteFileSearch.ts

2024-08-22 08:08 UTC, vovakulikov commented on vscode/src/context/openctx/common/get-repository-mentions.ts
> +    const dataOrError = await graphqlClient.searchRepoSuggestions(query)
I don't think we need, the handler itself is about accepting any generic regexp query, I think regexp sanitation exists on the backend in this case (at least we don't do anything about it in the sourcegraph client implementation about this)

2024-08-22 08:14 UTC, vovakulikov commented
> @vovakulikov the directory providers are enabled only for non-web non-dotcom instances.

@thenamankumar Hmm, I think I saw that you added directories for the cody web as well. Here https://github.com/sourcegraph/cody/blob/main/vscode/src/context/openctx.ts#L152-L156

Should I fix it here? The problem that we probably still need directories for web to solve problems like this https://linear.app/sourcegraph/issue/SRCH-940/cody-doesnt-fetch-context-for-specific-folder-questions-in-cody-web

2024-08-22 08:15 UTC, thenamankumar commented on lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
> +                        item.mention?.data?.repoName &&
Okay yeah this makes sense. I confused `getDirectoryMentions` with `getDirectoryItems`. Directory mentions need to provide the repoID because we need it to fetch the directory items. But we only need repo name to get the directory mentions, so getRepoMentions does not need to include the ID.

2024-08-22 08:16 UTC, thenamankumar approved these changes

2024-08-22 08:18 UTC, thenamankumar commented
> > @vovakulikov the directory providers are enabled only for non-web non-dotcom instances.
> 
> @thenamankumar Hmm, I think I saw that you added directories for the cody web as well. Here https://github.com/sourcegraph/cody/blob/main/vscode/src/context/openctx.ts#L152-L156
> 
> Should I fix it in this PR? The problem is that we probably still need directories for the web to solve problems like this https://linear.app/sourcegraph/issue/SRCH-940/cody-doesnt-fetch-context-for-specific-folder-questions-in-cody-web

Lets remove the provider from web as part of this PR for now and later after testing we can add it as part of a separate PR.

2024-08-22 08:18 UTC, thenamankumar commented
> @thenamankumar I checked repository, file and directory providers and it work as expected but I saw that you merged directory mentions provider yesterday and it looks like it may not working correctly on dotcom, at least I got no context due to problem of CodyContext gql API (because it expects to have filePattern argument there)
> 
> Full gql error
> 
> ```
> Variable \"filePatterns\" has invalid value null.\nExpected type \"[String!]!\", found null.
> ```
> 
> Can you please check this in the Cody Web demo (it may look like that directory provider should exist only for non-dot com instances but I think in Cody Web it slips or maybe it's just Cody Web demo problem)

I am testing  `Variable \"filePatterns\" has invalid value null.\nExpected type \"[String!]!\", found null` right now.

2024-08-22 08:24 UTC, merged