WIP: Agent: authentication capability
sourcegraph/cody pull request #5325
Opened 2024-08-25 00:18 UTC by abeatrix

WIP: Allows agent to set up http server to listen for authentication redirections when agent capabilities for authentication is enabled

TODO: store secrets in system secret storage
TODO: encryption key creation 

## Test plan

Example of this feature working in Visual Studio:

https://github.com/user-attachments/assets/d21c8c2f-2667-426a-9c4d-991b7645d2e5

## Changelog

2024-08-29 09:27 UTC, dominiccooney requested changes
Love the direction. Can we polish this a bit...

- Bind a dynamic port so we don't have port conflicts, assuming the site side supports different port numbers.
- Bind the loopback interface, some firewalls may be more lenient about this.
- Would be cool if the client requested focus when it has the token, although I guess that's a separate, per-client patch.
- I guess we can't remove the old app link method until a certain Sourcegraph server support window passes. Can you put TODOs or something mentioning specific versions being sunset when we can remove that? Can we turn off the app link method for dotcom and any compatible Sourcegraph version?

2024-08-29 09:27 UTC, dominiccooney commented on agent/src/AgentAuthHandler.ts
> +    private readonly port = 43452
Could we use a dynamic port? Does the web frontend support redirecting to other ports?

2024-08-29 09:27 UTC, dominiccooney commented on agent/src/AgentAuthHandler.ts
> +                    res.end('Token received. You can now close this window.')
We could consider opening a vscode:// redirect, or dropping a link, here to pop people back into the editor. (For editors that support it.)

For other editors which can request focus (...probably everything except vscode? ...) we could send the client a notification to request focus.

2024-08-29 09:27 UTC, dominiccooney commented on agent/src/AgentAuthHandler.ts
> +            setTimeout(() => this.closeServer(), 3 * 60 * 1000)
Shall we make this 5 or 10 minutes? Someone might need to go get their 2-factor keyring or whatever... 3 minutes sounds short.

2024-08-29 09:44 UTC, dominiccooney commented
Ah... one more thing we need to consider. When the extension is running remotely, like SSH hosts, we should take that opportunity to have a login method that works (or at least helpfully fails... link to docs, way to manually set a token, etc.)

2024-09-03 19:48 UTC, abeatrix commented on agent/src/AgentAuthHandler.ts
> +    private readonly port = 43452
updated to use dynamic port

2024-09-03 19:49 UTC, abeatrix commented on agent/src/AgentAuthHandler.ts
> +            setTimeout(() => this.closeServer(), 3 * 60 * 1000)
updated to 6 minutes and added a comment for the reason

2024-09-03 22:09 UTC, abeatrix commented on agent/src/AgentAuthHandler.ts
> +                    res.end('Token received. You can now close this window.')
> We could consider opening a vscode:// redirect, or dropping a link, here to pop people back into the editor. (For editors that support it.) 

I will add a TODO comment for this. For now, I have updated the code to send a notification to request focus via "window/focusSidebar"

2024-09-04 10:30 UTC, dominiccooney commented
> For the last item, which old app link method are you referring to?

The ones that read the querystring and redirect to URLs like [this](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx?L74)... vscode://sourcegraph.cody-ai etc.

High level question is, should we migrate to all http://localhost redirect logins? Or should we keep supporting the vscode:// etc. method forever. Simpler is better and localhost redirects mean we can ship new clients without updating old Sourcegraph instances.

2024-09-04 10:33 UTC, dominiccooney approved these changes
Great!

2024-09-04 22:47 UTC, abeatrix commented
> High level question is, should we migrate to all http://localhost/ redirect logins? Or should we keep supporting the vscode:// etc. method forever. Simpler is better and localhost redirects mean we can ship new clients without updating old Sourcegraph instances.

I agree that simpler is better. Right now, adding new IDE redirection support through the SG instance requires enterprise users to upgrade to the latest version of SG. Since that change would require a server-side change that is not covered by this PR, I will create a linear issue for it. Thanks for the review, Dom!

2024-09-04 23:16 UTC, merged