Agent: improve assertion of exported telemetry events within integration tests
sourcegraph/cody pull request #5455
Opened 2024-09-04 04:34 UTC by akalia25

Addresses feedback [here](https://github.com/sourcegraph/cody/pull/4923#discussion_r1722970638) 

## Test plan
CI, specifically `pnpm run test src/index.test.ts`

## Changelog

2024-09-16 09:38 UTC, olafurpg requested changes
I'm sorry, I had published pending comments a long time ago but forgot to "comment" the reviwe.

This is a nice cleanup! Only one blocking comment, otherwise LGTM

2024-09-16 09:38 UTC, olafurpg commented on agent/src/index.test.ts
> +            expect.arrayContaining(client.expectedEvents)
We should remove the mutable `TestClient.expectedEvents` property and inline the values into the assertions instead. This is the only blocking comment for the PR

2024-09-23 17:49 UTC, akalia25 commented on agent/src/index.test.ts
> +async function returnTelemetryEvents(currentClient: TestClient) {
Updated, thank you for the suggestion!

2024-09-23 17:50 UTC, akalia25 commented on agent/src/index.test.ts
> +            expect.arrayContaining(client.expectedEvents)
thank you for the comment, updated it so that the expectedEvents are inline values to the assertion :) ~ Saves a bunch of lines, great suggestion!

2024-09-24 10:17 UTC, olafurpg reviewed
LGTM 👍🏻 Thank you!

2024-09-24 10:17 UTC, olafurpg approved these changes
LGTM 👍🏻 Thank you!

2024-09-24 15:20 UTC, merged