Add option to disable ctx providers
sourcegraph/cody pull request #5481
Opened 2024-09-05 15:49 UTC by pkukielka

## Test plan

N/A, unittests should pass.

When it will get adopted in JetBrains test plan will be as follow: 
https://github.com/sourcegraph/cody/pull/5384

2024-09-06 08:50 UTC, dominiccooney requested changes
A nice generalization of what web and JetBrains needs.

Let's filter all the providers, not just the two built-in ones? (Or make the API design a bit clearer...)

Let's add a unit test.

2024-09-06 08:50 UTC, dominiccooney commented on lib/shared/src/mentions/api.ts
> +    disabledMentionsProviders?: OptionalProviderId[] | undefined | null
Making this an object so the providers are labeled with `disable` will be more readable now and evolvable in future, something like:

```
mentionProvidersMetadata({disable: [SYMBOL_CONTEXT_MENTION_PROVIDER]})
```

2024-09-06 08:50 UTC, dominiccooney commented on lib/shared/src/mentions/api.ts
>          ...providers,
Why only filter the `availableMentionProviders`? Why not others?

2024-09-10 10:36 UTC, pkukielka commented on lib/shared/src/mentions/api.ts
>          ...providers,
Fixed

2024-09-10 10:37 UTC, pkukielka commented on lib/shared/src/mentions/api.ts
> +    disabledMentionsProviders?: OptionalProviderId[] | undefined | null
Done

2024-09-10 23:08 UTC, dominiccooney approved these changes
Thank you for writing the test.

The test helper function can be de-duped with `firstValueFrom`, PTAL.

2024-09-10 23:08 UTC, dominiccooney commented on lib/shared/src/mentions/api.test.ts
> +function waitForObservable<T>(observable: Observable<T>): Promise<T> {
This already exists, it is `firstValueFrom`

2024-09-10 23:08 UTC, dominiccooney commented on lib/shared/src/mentions/api.test.ts
> +        const providers = await waitForObservable(mentionProvidersMetadata())
```suggestion
        const providers = await firstValueFrom(mentionProvidersMetadata())
```

2024-09-11 08:54 UTC, merged