Chat: add ability to execute terminal commands from chat
sourcegraph/cody pull request #5684
Opened 2024-09-24 23:34 UTC by abeatrix

![image](https://github.com/user-attachments/assets/2d79e4de-c13f-42f6-8b8d-dc5129dd6c46)

- Adds support for executing terminal commands generated by Cody directly from the chat interface on button click
- Updates the preamble to include instructions for formatting terminal commands in Markdown code blocks
- Modifies the ChatMessageContent component to detect and handle terminal commands in the generated code blocks
- Introduces a new "Cody Command Line" experimental command that allows users to ask Cody to generate terminal commands using natural language
  - This is only available when `cody.internal.unstable` is enabled

![image](https://github.com/user-attachments/assets/a9737bcb-4544-46ad-bb43-dac33c360bc1)

![image](https://github.com/user-attachments/assets/e4e2f09e-344d-4bcb-b032-bf9f996b37f0)

BREAKING CHANGE: This feature introduces a new experimental command that may change or be removed in future releases.

## Test plan

Execute button:

1. Ask Cody to "give me a command to list all the files in the current directory"
2. Verify Cody has responded with a command with an `Execute` button underneath the command
3. The command is not executed until you hit the button
4. Clicking on the `Execute` button will open a dialogue asking if you want to run the command in your terminal
5. Click "Run" to run the command in your terminal 
6. Verify the command that runs in your terminal is the same one you click `Execute` from

![image](https://github.com/user-attachments/assets/1a6effd6-b716-47fa-8675-31ee3c31858f)

Cody Command Line:

1. Enable `cody.internal.unstable` in your vs code user settings.
2. Open the "Cody Commands" menu and you should find the "Cody Command Line" command
3. Type "give me a command to list all the files in the current directory" and verify it provide you with a command as answer
4. clicking on the returned command will open a dialog that asks if you want to execute the command
5. Click "Run" to run the command in your terminal 
6. Verify the command that runs in your terminal is the same one you click `Execute` from

## Changelog

Chat: add ability to execute terminal commands from chat interface.

2024-09-24 23:53 UTC, ykdojo requested changes

2024-09-24 23:53 UTC, ykdojo commented on vscode/src/commands/services/command-line.ts
> +        const model = models.find(model => model.id === 'haiku')?.id ?? models[0]?.id ?? ''
Does this mean haiku is the default model?

If so, why not use 3.5 Sonnet instead?

2024-09-24 23:53 UTC, ykdojo commented on vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
> +                let fileName = codeElement?.getAttribute('data-file-path') || undefined
It might be helpful to change the variable name here to clarify what it's for.

Maybe something like:

fileNameOrCommand

or maybe separate it into two variables like:

smartApplyTargetFileName

and

isBashCommand

(or something similar)

2024-09-24 23:53 UTC, ykdojo commented on vscode/webviews/chat/ChatMessageContent/create-buttons.ts
> +    const isShellCommand = fileName === 'command'
Same thing as my earlier comment - will be helpful to have a more descriptive fileName

2024-09-24 23:53 UTC, ykdojo commented on vscode/webviews/chat/ChatMessageContent/create-buttons.ts
> +            button.innerHTML = isShellCommand ? 'Execute' : 'Apply'
Nice. For a future PR, it'd be nice to change the icon, too

2024-09-25 00:01 UTC, ykdojo commented
It works well, but a few comments:

1. It opens up a "Run command in terminal" dialogue every time, which I don't think is the ideal UX.

Can we simply have it send the command to the current terminal without opening up a specific "Cody Command Line" terminal?

![image](https://github.com/user-attachments/assets/89cbfaf2-c62d-4fa4-9057-b022d6db62ee)

As a developer, chances are, I'd be working in a terminal already. So why not send it to that?

2. It'd be great to clean up the "Ask Cody to explain" command so it simply sends the selected part of the terminal to the current chat instead of opening up a new chat as we discussed at the Merge - perhaps as a separate PR.

With these changes combined together, I think we're going to have really smooth DX - by letting the dev seamlessly jump / pass context between Cody and the terminal.

2024-09-25 00:01 UTC, abeatrix commented on vscode/src/commands/services/command-line.ts
> +        const model = models.find(model => model.id === 'haiku')?.id ?? models[0]?.id ?? ''
The user input should be small for this command, so any of the faster and cheaper model should be able to handle this type of request. We can change it if we notice any quality issue though. 

Note: this is only for the Cody Command Line that's hidden behind the internal feature flag:

![image](https://github.com/user-attachments/assets/45cc9f54-47d5-418f-8cd2-10eccda3a681)

2024-09-25 00:10 UTC, ykdojo commented on vscode/src/commands/services/command-line.ts
> +        const model = models.find(model => model.id === 'haiku')?.id ?? models[0]?.id ?? ''
Sounds good. Or maybe 4o? I'll test it more and I'll let you know what seems to work the best - but for now I trust your judgement!

2024-09-25 00:25 UTC, abeatrix commented
> Can we simply have it send the command to the current terminal without opening up a specific "Cody Command Line" terminal?

This is a limitation of the VS Code API iirc, unfortunately we can only send to the terminal we created 😞 

> It opens up a "Run command in terminal" dialogue every time, which I don't think is the ideal UX.

Let's wait for the security team's review to see what options we have here!

2024-09-25 12:30 UTC, ykdojo commented
> This is a limitation of the VS Code API iirc, unfortunately we can only send to the terminal we created 😞

Looks like we can send a command to an existing terminal

https://github.com/user-attachments/assets/527ae67f-324a-4995-aa47-7f442ebe2f11

Code I used: https://github.com/sourcegraph/cody/commit/7d8239800180fc189d5a3e782f14b83fd69cc243

2024-09-25 13:58 UTC, abeatrix commented
> > This is a limitation of the VS Code API iirc, unfortunately we can only send to the terminal we created 😞
> 
> 
> 
> Looks like we can send a command to an existing terminal
> 
> 
> 
> https://github.com/user-attachments/assets/527ae67f-324a-4995-aa47-7f442ebe2f11
> 
> 
> 
> Code I used: https://github.com/sourcegraph/cody/commit/7d8239800180fc189d5a3e782f14b83fd69cc243

Ohhh nice found! Will update, thank you!

2024-09-25 23:05 UTC, ykdojo commented
Love the new icon! Looks like the "Do not ask again" button is not working, though


https://github.com/user-attachments/assets/30f99f66-7b76-4888-8d91-cbf4615c8097

2024-09-25 23:11 UTC, ykdojo commented
Also I think we should go with bash, not shell. It looks like we only get syntax highlighting with bash, at least on the web.
![image](https://github.com/user-attachments/assets/eaca4628-091e-4daa-9db2-8a7e41339e05)

![image](https://github.com/user-attachments/assets/00011da3-0b85-45e6-ae78-69fa710f7014)

2024-09-26 00:24 UTC, abeatrix commented
> Love the new icon! Looks like the "Do not ask again" button is not working, though
> 
>  do.not.ask.again.not.working.mov

@ykdojo typo... was matching "Do not ask" against "Do not show" ... Thanks for catching this!

2024-09-26 03:07 UTC, aramaraju commented
> Also I think we should go with bash, not shell. It looks like we only get syntax highlighting with bash, at least on the web. ![image](https://private-user-images.githubusercontent.com/1811651/370919731-eaca4628-091e-4daa-9db2-8a7e41339e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjAzMTIsIm5iZiI6MTcyNzMyMDAxMiwicGF0aCI6Ii8xODExNjUxLzM3MDkxOTczMS1lYWNhNDYyOC0wOTFlLTRkYWEtOWRiMi04YTdlNDEzMzllMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDMwNjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI4MjFkNDk1YWRmOTJiNjlmN2MyODE0NjNjYWJhYWY5YzhmMjVkOWU5ODYzMzlkNTQ2MzBkYjIwMTRmMTNkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KvEAYKjTirq4tYiORQ7Zx7carIkTDqYcLRRHH16xIFc)
> 
> ![image](https://private-user-images.githubusercontent.com/1811651/370919825-00011da3-0b85-45e6-ae78-69fa710f7014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjAzMTIsIm5iZiI6MTcyNzMyMDAxMiwicGF0aCI6Ii8xODExNjUxLzM3MDkxOTgyNS0wMDAxMWRhMy0wYjg1LTQ1ZTYtYWU3OC02OWZhNzEwZjcwMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDMwNjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ3NjI0ZGI2ZmYwNDNlNWZiYzVlY2E5ZDkxYTNiYjU1ODFiMTIwYzI5NWViODM5Njc0MTJiMjNiOTc4ZGQ3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wJBs6Wn9sRxnyXk25hREsaAFskAHnJcUKCXaoyImyR0)

Isn't bash a type of shell? It feels like "shell" is the right term here?

2024-09-26 03:10 UTC, aramaraju commented on vscode/src/commands/services/command-line.ts
> +        const model = models.find(model => model.id === 'haiku')?.id ?? models[0]?.id ?? ''
Haiku or 4o-mini size should work decently well here IMO. It's okay starting with it

2024-09-26 03:11 UTC, aramaraju commented
> Introduces a new "Cody Command Line" experimental command that allows users to ask Cody to generate terminal commands using natural language
This is only available when cody.internal.unstable is enable

This feels like non-ideal UX, and I vote that we hold off on this piece. With things like Warp and GH integrated into Terminal, I think we should do it properly and integrate Cody directly into Terminal instead of this roundabout approach.

2024-09-26 15:33 UTC, abeatrix commented on vscode/src/commands/services/command-line.ts
> +        const model = models.find(model => model.id === 'haiku')?.id ?? models[0]?.id ?? ''
resoled since the Cody Command Line is removed

2024-09-26 18:58 UTC, vovakulikov approved these changes
TECH review is ok. I would like to change how we render our actions button (now it looks like a very big workaround and hack), but it's out of the scope of this PR, I guess.

2024-09-26 21:42 UTC, ykdojo approved these changes

2024-09-26 21:43 UTC, ykdojo commented
I was trying to dismiss my previous review but approved it by accident - just FYI!

2024-09-27 12:20 UTC, PriNova commented on lib/shared/src/chat/preamble.ts
> +For executable terminal commands: enclose in a Markdown code block with the language tag "bash".`
If Cody provides multiple commands then there are sometimes docstrings included:
![Screenshot 2024-09-27 131843](https://github.com/user-attachments/assets/bc124a32-85b3-4ef0-808d-f0822b15cb26)

This will not affect the execution of the commands, but could lead to potential issues:
```suggestion
For executable terminal commands: enclose in a Markdown code block with the language tag "bash". Avoid including documentation to the executable commands.`
```

2024-09-27 16:23 UTC, evict approved these changes

2024-09-27 17:29 UTC, abeatrix commented on lib/shared/src/chat/preamble.ts
> +For executable terminal commands: enclose in a Markdown code block with the language tag "bash".`
Good point! I've updated the prompt to include this rule with minor adjustment that hopefully would work with most LLMs 🙏

2024-09-27 19:35 UTC, merged