Fix Cody Chat UI rendering reconciliation
sourcegraph/cody pull request #5850
Opened 2024-10-08 23:48 UTC by vovakulikov

Fixes part of https://linear.app/sourcegraph/issue/CODY-3943/optimize-performance-for-large-chat-windows-in-cody

It looks like since https://github.com/sourcegraph/cody/pull/5036 we've lost memoization in a few places. As a result, our chat UI doesn't perform well with more than 4-5 messages (depending on how long these chat messages are)

This PR tries to improve it by fixing memoization on expensive components (Transcript, HumanMessage, ...etc)

| Before | After |
| ------- | ------- |
| <video src="https://github.com/user-attachments/assets/79e7b93c-ac82-4a8c-9b2e-6c712af3fb2c" /> | <video src="https://github.com/user-attachments/assets/223b3513-0f30-47cc-b24c-c54f4861329c" /> | 

This PR also fixes a problem with one-box intention detection; previously, it produced a state where we didn't have a follow-up message UI during intent resolution. 

## Test plan
- Check with the React profile that we don't render components during message response in places where we don't need to re-render anything
- Check that intent detection in one-box doesn't produce UI flashes

2024-10-09 01:44 UTC, abeatrix approved these changes
Tested locally and confirmed the states were not re-render.

I was looking into a similar issue for the editor state. Would appreciate your review on it as well since I think there are a few things I can clean up on my PR after yours is merged 😄  https://github.com/sourcegraph/cody/pull/5847

2024-10-09 02:11 UTC, abeatrix commented
(Not a blocker) would be great to have a test covering transcript rendering for regression if possible 😄

2024-10-09 05:13 UTC, thenamankumar approved these changes

2024-10-09 08:39 UTC, dominiccooney requested changes
We need a trivial renaming to keep the PromptString lint results accurate.

2024-10-09 08:39 UTC, dominiccooney commented on vscode/webviews/utils/debugger.ts
> +            (ps, [k, v]) => {
Our lints for PromptString rely on only using `ps` to refer to the PromptString formatter. This ensures we never alias `ps`, which can be used to defeat the static checks for correct PromptString usage.

We could write a more complicated check that understands JavaScript scoping to allow the use you have here, or only lint files which import "the" `ps`, but until we do that, can you rename these variables to anything else?

2024-10-09 14:45 UTC, vovakulikov commented on vscode/webviews/utils/debugger.ts
> +            (ps, [k, v]) => {
Sure, renamed it in my last commit

2024-10-10 01:39 UTC, dominiccooney approved these changes
Approving for the `ps` fixes, thank you. I have not reviewed the rest in detail but I have some questions and suggestions inline.

I think the message output stuttering has a different cause, see https://github.com/sourcegraph/cody/issues/5296#issuecomment-2402410782

2024-10-10 01:39 UTC, dominiccooney commented on vscode/webviews/utils/debugger.ts
> +export function useTracePropsUpdate(props: any) {
Let's add a comment here that this is for debugging with advice about how to use it.

From time to team people do mass-deletions based on use. You probably intend for this to stick around.

2024-10-10 01:39 UTC, dominiccooney commented on vscode/webviews/chat/Transcript.tsx
> +function useMutatedValue<T>(value?: T): [MutableRefObject<T | undefined>, setValue: (value: T) => void] {
You should document that this should not be used for rendering and won't cause re-rendering.

2024-10-10 01:39 UTC, dominiccooney commented on vscode/webviews/chat/Transcript.tsx
> +    const [intentResults, setIntentResults] = useMutatedValue<
Why isn't simply `useRef` enough here?

2024-10-10 02:44 UTC, merged