port settings from search extension
sourcegraph/cody pull request #5883
Opened 2024-10-12 02:13 UTC by RXminuS

## Test plan

## Changelog

2024-10-12 02:14 UTC, RXminuS commented
* **#5883** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/5883?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RXminuS and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-12 18:42 UTC, peterguy commented on lib/shared/src/configuration/environment.ts
> + *    would require a reload of the extension/platform if changed. might cause
> might cause ...
Don't keep us in suspense! ;-)

2024-10-12 18:42 UTC, peterguy commented on lib/shared/src/configuration/environment.ts
> + * So if you do need an invorment variable this should be the only location we
```suggestion
 * So if you do need an environment variable this should be the only location we
```

2024-10-12 18:43 UTC, peterguy commented on lib/shared/src/configuration/environment.ts
> + * 1. Settings that shouldn't be used by users
> Settings that shouldn't be used by users

Can we elaborate here? Debug/Test/Dev settings? Any examples?

2024-10-12 18:43 UTC, peterguy commented on lib/shared/src/configuration/environment.ts
> +     * Mirrors the HTTP_PROXY and HTTPS_PROXY environment varilables but can be
```suggestion
     * Mirrors the HTTP_PROXY and HTTPS_PROXY environment variables but can be
```

2024-10-12 18:47 UTC, peterguy commented on lib/shared/src/configuration/environment.ts
> +            logErrorOnce(`Ignoring NO_PROXY=${noProxy}`)
```suggestion
            logErrorOnce(`HTTPS_PROXY or HTTP_PROXY set; ignoring NO_PROXY=${noProxy}`)
```

2024-10-12 18:49 UTC, peterguy commented on lib/shared/src/fetch.patch.ts
> + * For read only access simply import the fetch.ts file
```suggestion
 * For read-only access simply import the fetch.ts file
```

2024-10-14 08:11 UTC, olafurpg requested changes
I only did a quick skim over the diff. My main recommendations:

- This is a large PR. Are there low-risk big-diff changes we can land separately to minimize the blast radius?
- Let's update the PR description following https://www.notion.so/sourcegraph/Write-a-good-pull-request-description-610a7fd3e613496eb76f450db5a49b6e TLDR; "Previously, PROBLEM. Now, SOLUTION". It does not have to be long. One important question to answer in the description: what is the risk of merging this change?

2024-10-14 08:11 UTC, olafurpg commented on vscode/src/completions/fast-path-client.ts
> +        // headers.set('Connection', 'keep-alive')
Intentional? Fastpath is disabled for Enterprise so this may not be needed in the first place

2024-10-14 08:11 UTC, olafurpg commented on vscode/src/completions/fast-path-client.ts
> +        // headers.set('Connection', 'keep-alive')
Alternatively, is this because we're enabling keep-alive elsewhere? I see we removed this in the default client too, and doing so may introduce perf regressions.

2024-10-14 08:11 UTC, olafurpg commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(v: string | undefined, k: string): string | undefined {
What does this function do? Does it return a proxy URL?
```suggestion
function codyProxyURL(v: string | undefined, k: string): string | undefined {
```

2024-10-15 00:10 UTC, RXminuS commented on vscode/src/completions/fast-path-client.ts
> +        // headers.set('Connection', 'keep-alive')
No this is because keep-alive doesn't actually work correctly with our implementation and the only reason it "seemed" to work was because VSCode was broken so it didn't actually re-use connections (thus there was no actual perf gain).

2024-10-15 00:14 UTC, RXminuS commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(v: string | undefined, k: string): string | undefined {
It's just a combination of NODE_HTTPS and NODE_HTTP proxy. It's needed for proxies to work on Agent

2024-10-15 00:15 UTC, RXminuS commented on vscode/src/completions/fast-path-client.ts
> +        // headers.set('Connection', 'keep-alive')
It's disabled on an agent level so even if you'd try to set it, it wouldn't work

2024-10-15 08:51 UTC, olafurpg commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(v: string | undefined, k: string): string | undefined {
A better function name or docstring would be helpful. The `k` parameter also seems unused? It's unclear what `v` is or where it comes from.
```suggestion
/** Returns the HTTPS_PROXY or HTTP_PROXY environment variables with optional ability to disable these settings  we respect these settings */
function nodeHttpProxyURL(settingValue: string | undefined): string | undefined {
```

2024-10-15 08:51 UTC, olafurpg commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(v: string | undefined, k: string): string | undefined {
I generally don't nitpick so much about these kinds of things, and I generally don't write many docstrings, but this function here stood out as a weird one

2024-10-15 08:55 UTC, RXminuS commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(v: string | undefined, k: string): string | undefined {
Yeah fair enough 😆

2024-10-15 08:59 UTC, RXminuS commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(v: string | undefined, k: string): string | undefined {
I'll rename it to something like `CODY_NODE_PROXY_DEFAULT` to indicate it's not really a "us" feature

2024-10-15 11:04 UTC, arafatkatze commented
<img width="983" alt="image" src="https://github.com/user-attachments/assets/9473a719-fff6-4b00-8834-36a92699cd2d">
<img width="788" alt="image" src="https://github.com/user-attachments/assets/cad20ee6-136c-4bd9-84d9-6ed087a4fb49">

Is this some sort of a redundancy or are you folks setting different proxies for using the SG Vscode app and the Cody Vscode app?

2024-10-16 01:09 UTC, peterguy commented
@olafurpg 

> Are there low-risk big-diff changes we can land separately to minimize the blast radius?

We could break out the new proxy settings. They were the inspiration for the network stack changes. I'm not eager to do that because of the added overhead and delays to landing them 😅, but definitely can-do. 

> what is the risk of merging this change?

It's gated behind the setting `cody.net.mode`, so other than some hooking into VSCode startup, normal usage won't be impacted.

2024-10-16 03:01 UTC, olafurpg commented
As discussed over Slack, I'm on board with landing this ASAP. Will do a last round of review today and approve.

2024-10-16 05:41 UTC, peterguy commented
> As discussed over Slack

I see that convo now; thanks.

> Will do a last round of review today and approve.

Great! I'm wrapping up merging conflicts and mollifying tests.

2024-10-16 09:48 UTC, mkondratek approved these changes

2024-10-16 09:51 UTC, merged

2024-10-16 09:54 UTC, olafurpg approved these changes
Let's merge this and be very careful with the rollout of this change as discussed [here](https://sourcegraph.slack.com/archives/C05AGQYD528/p1728982786019919?thread_ts=1728981853.764659&cid=C05AGQYD528).

I'm assuming people hesitated to approve this PR because it's doing a lot of advanced stuff with seemingly large accompanying risk, and the PR description and code implementation do not adequately address those concerns. I'm approving to unblock progress but expect you @RXminuS and @peterguy to closely follow through on the rollout of this change and make sure we rapidly rollback the PR if there are reported issues.

If the functionality is properly gated behind a setting, then we can consider fixing forward. An important goal that we should not compromise on is: let's make sure the functionality continues to work as before for users who can already successfully use Cody. We've shipped several regressions over the past weeks and we can't afford to ship more.

2024-10-16 09:54 UTC, olafurpg commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(envValue: string | undefined): string | undefined {
My comments on about this function missing clarity are still unaddressed.

2024-10-16 09:54 UTC, olafurpg commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(envValue: string | undefined): string | undefined {
Not a blocking comment. However, if I'm asked to review a PR I'd expect a resolution on the comment. The original thread is here https://github.com/sourcegraph/cody/pull/5883#discussion_r1800740537

2024-10-16 09:54 UTC, olafurpg commented on lib/shared/src/fetch.patch.ts
> + * 🚨 Do not import this file unless you're specifically patching the variable.
Does this module actually do patching on import? Looking at the file, there seem to be no side-effects during module loading. It's unclear where the patching actually happens

2024-10-16 09:54 UTC, olafurpg commented on vscode/src/net/net.patch.ts
> +function patchNetworkStack(): void {
IIUC, this module unconditionally patches stuff during module initialization in `extension.node.ts`. This comment [here](https://github.com/sourcegraph/cody/pull/5883#issuecomment-2415478043) from @peterguy indicates the functionality is gated by `cody.net.mode`. What is the risk of this function crashing making the extension fail to load even when everything is OK without network patching?

2024-10-16 09:54 UTC, olafurpg commented on vscode/src/net/net.patch.ts
> +// 🚨 This patch file mast have NO additional dependencies as import order
```suggestion
// 🚨 This patch file must have NO additional dependencies as import order
```

2024-10-16 12:13 UTC, RXminuS commented on lib/shared/src/configuration/environment.ts
> +function codyProxy(envValue: string | undefined): string | undefined {
Yeah sorry, this was a bit messy because Peter and I kept pushing to the same branch but lost some things when I did a graphite sync