Hitesh/autoedits improvements
sourcegraph/cody pull request #5956
Opened 2024-10-21 09:45 UTC by hitesh-1997

Do not review Yet, Experimental changes + Saving some intermediate work 

## Test plan
todo

2024-10-23 04:20 UTC, dominiccooney requested changes
Some feedback inline.

2024-10-23 04:20 UTC, dominiccooney commented on vscode/src/autoedits/prompt-utils.ts
> +        endLine: completePrefixLines + suffixContext.codeToRewriteEndLines - 1,
Note, above you can just write `codeToRewrite` instead of `codeToRewrite: codeToRewrite` 

How is `endLine` used? Can we get some unit test coverage of this?

2024-10-23 04:20 UTC, dominiccooney commented on vscode/src/autoedits/providers/fireworks.ts
> +            codeToReplace: codeToReplace,
When the property name and the variable name are the same, you can just write it once as a shorthand.
```suggestion
            codeToReplace,
```

2024-10-23 04:20 UTC, dominiccooney commented on vscode/src/autoedits/renderer.ts
> +function combineRanges(ranges: vscode.Range[], n: number): vscode.Range[] {
Give `n` a more descriptive name, and consider documenting what the function does.

2024-10-23 04:20 UTC, dominiccooney commented on vscode/src/autoedits/renderer.ts
> +                currentRange.intersection(nextRange))
What are the constraints on the input ranges? Why not handle intersections in general where nextRange intersects with currentRange but doesn't happen to start on the line that the other one ends on?

2024-10-23 04:20 UTC, dominiccooney commented on vscode/src/autoedits/renderer.ts
> +                nextRange.end.character > currentRange.end.character ? nextRange.end : currentRange.end
There's a danger here that if someone makes a change to the `currentRange.end.line === nextRange.start.line` constraint above then this result is going to be garbage. Consider something semantic, like:

```
currentRange.end.isAfter(nextRange.end) ? currentRange.end : nextRange.end
```

2024-10-23 04:20 UTC, dominiccooney commented on vscode/src/autoedits/renderer.ts
> +            await this.dismissProposedChange()
The following method is pretty long, and you rely on there being no `await` after this point and before you set decorations, otherwise you might render two different ones at once.

Could you introduce some helper methods and a comment to point that out and reduce the reading gap between when the old changes are dismissed and the new ones are rendered?

2024-11-04 19:15 UTC, hitesh-1997 commented on vscode/src/autoedits/prompt-utils.ts
> +        endLine: completePrefixLines + suffixContext.codeToRewriteEndLines - 1,
Nice suggestion, Added several unit tests to cover various sceneraios.

2024-11-04 19:16 UTC, hitesh-1997 commented on vscode/src/autoedits/providers/fireworks.ts
> +            codeToReplace: codeToReplace,
done

2024-11-04 19:17 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer.ts
> +function combineRanges(ranges: vscode.Range[], n: number): vscode.Range[] {
This function was no longer needed, hence removed the function.
Also, updated the documentation on similar functions to clarify the logic

2024-11-04 19:17 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer.ts
> +                currentRange.intersection(nextRange))
The function was no longer required, removed it

2024-11-04 19:17 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer.ts
> +                nextRange.end.character > currentRange.end.character ? nextRange.end : currentRange.end
The function was no longer required, removed it

2024-11-04 19:19 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer.ts
> +            await this.dismissProposedChange()
nice suggestion, the whole file was a bit of mess before, so refactored the file into smaller function and seperate `manager` and `renderer` class. Please let me know if you think we can improve it further :)

2024-11-04 22:08 UTC, beyang commented on vscode/src/autoedits/autoedits-provider.ts
> +        }
Shouldn't this go through the Sourcegraph instance, rather than be hard-coded here?

2024-11-04 22:09 UTC, beyang commented on vscode/src/autoedits/autoedits-provider.ts
> +        }
(I suppose it's fine to merge for dogfooding, but we'll need to update this before we roll out more widely.)

2024-11-04 22:39 UTC, beyang approved these changes

2024-11-05 10:37 UTC, hitesh-1997 commented on vscode/src/autoedits/autoedits-provider.ts
> +        }
do we mean the model id here `cody-model-auto-edits-fireworks-default` ?
The actual config is defined in the instance only, this is just the `model_Id` which client sends to the backend

2024-11-06 02:17 UTC, dominiccooney requested changes
Sorry for the slow reply on this.

To make PromptStrings useful we need the document contents and their URIs to stick together like glue. Pulling the content out, manipulating it over many lines/functions and asserting the URIs when you join them isn't the right approach. The code is right today but it is prone to error as the code evolves and other context or strings get mixed in there.

The repetitive calls to fromAutoEditsCurrentFileContext, that method basically exposing one of the internal constructors, etc. are a clue you're swimming upstream.

The right approach is to take the string methods you need... looks like `match`... and implement it on PromptString. Unwrap the string, call String match, and lift the result back into PromptStrings using the internal constructor over a very limited scope. (You may want to only provide a subset of the Regexp result--just the array, not the extra properties, for now...)

Then your calling code will look like typical string manipulation without the repetitive calls to `fromAutoEditsCurrentFileContent`. You won't need to expose a PromptString constructor that's so easy to misuse (just a string and a URI which it asserts instead of some meaningful object.) etc.

2024-11-06 02:17 UTC, dominiccooney commented on vscode/src/autoedits/prompt-utils.ts
> +    const codeToRewriteLines: string[] = []
These repetitive calls to `fromAutoEditsCurrentFileContext` below are a problem:

- The string content is separated from the document URI, then re-asserted here. You should keep the URIs with together with the strings all the time by using `PromptString[]` instead of `string[]` for `codeToRewriteLines`, etc.
- It's also just tedious to have `options.document.uri` everywhere. If you start with a PromptString, split it apart, then rejoin them all the URI handling is done for you by PromptString.

2024-11-06 02:17 UTC, dominiccooney commented on vscode/src/autoedits/utils.ts
> +export function splitLinesKeepEnds(s: string): string[] {
Add a `match` method to PromptString which unwraps the string, does `match`, and lifts the result back into PromptStrings using one of the internal constructors.

Same feedback above/below.

Then make this function be `splitLinesKeepEnds(s: PromptString): PromptString[]`. (You could even make handle both with some type constraints...)

2024-11-06 10:49 UTC, hitesh-1997 commented on lib/shared/src/prompt/prompt-string.ts
> +    public static fromAutoEditsCurrentFileContent(content: string, uri: vscode.Uri) {
removed the method, using existing method `PromptString.fromDocumentText`

2024-11-06 10:50 UTC, hitesh-1997 commented on vscode/src/autoedits/adapters/cody-gateway.ts
> +        // todo (hitesh): The finetuned model is messing up the identation of the first line.
done

2024-11-06 10:50 UTC, hitesh-1997 commented on vscode/src/autoedits/adapters/cody-gateway.ts
> +        // todo: correct it manully for now, by checking the first line of the code to rewrite and adding the same indentation to the first line of the completion
done

2024-11-06 10:50 UTC, hitesh-1997 commented on vscode/src/autoedits/prompt-utils.ts
> +    const codeToRewriteLines: string[] = []
This is a really good insights. Thanks for spotting this !!

2024-11-06 10:50 UTC, hitesh-1997 commented on vscode/src/autoedits/utils.ts
> +export function splitLinesKeepEnds(s: string): string[] {
I realized the importance of sticking string, uri else anyone mistakenly pass arbitrary string with different uri to create prompt string.
Since we are creating prompt from the current file, I used one of the existing prompt string method. please let me know if looks okay.

2024-11-06 12:02 UTC, dominiccooney commented on vscode/src/autoedits/adapters/fireworks.ts
> +        // Correct it manully for now, by checking the first line of the code to rewrite and adding the same indentation to the first line of the completion
```suggestion
        // Correct it manually for now, by checking the first line of the code to rewrite and adding the same indentation to the first line of the completion
```

2024-11-06 12:07 UTC, dominiccooney commented on vscode/src/autoedits/renderer.ts
> +        if (!this.activeEdit || event.document.uri.toString() !== this.activeEdit.uri) {
You could simplify slightly this way:

```suggestion
        if (event.document.uri.toString() !== this.activeEdit?.uri) {
```

2024-11-06 12:10 UTC, dominiccooney commented on vscode/src/autoedits/renderer.ts
> +        if (!this.activeEdit || event.textEditor.document.uri.toString() !== this.activeEdit.uri) {
Same here

2024-11-06 12:12 UTC, dominiccooney commented on vscode/src/autoedits/utils.ts
> +export function zip<T, U>(arr1: T[], arr2: U[]): [T, U][] {
Consider using lodash's `_.zip`

2024-11-06 12:19 UTC, dominiccooney commented on vscode/src/autoedits/utils.ts
> +        }
Isn't `mappedValue - (index - i)` = `mappedValue - index + i` = `mappedValue + i - index`? And when `i == index` then `i - index` is 0...

So can't you just replace this whole thing with `return range(mappedValue - index, mappedValue - index + originalList.length)`?

2024-11-06 12:21 UTC, dominiccooney commented on vscode/src/autoedits/utils.ts
> +    const match = text.match(/^\n+/)
Why do you handle `\r` in `trimNewLineCharsFromString` below, but not here or `countNewLineCharsEnd`? Might be worth a brief comment, particularly since these are exported.

Is it worth adding some unit tests for these utils, and include Windows and UNIX-style line endings?

2024-11-06 12:22 UTC, dominiccooney commented on vscode/src/autoedits/utils.ts
> +export function countNewLineCharsEnd(text: string): number {
Separate these top level functions with one blank line

2024-11-06 13:18 UTC, hitesh-1997 commented on vscode/src/autoedits/adapters/fireworks.ts
> +        // Correct it manully for now, by checking the first line of the code to rewrite and adding the same indentation to the first line of the completion
done

2024-11-06 13:18 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer.ts
> +        if (!this.activeEdit || event.document.uri.toString() !== this.activeEdit.uri) {
done

2024-11-06 13:18 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer.ts
> +        if (!this.activeEdit || event.textEditor.document.uri.toString() !== this.activeEdit.uri) {
done

2024-11-06 13:19 UTC, hitesh-1997 commented on vscode/src/autoedits/utils.ts
> +export function zip<T, U>(arr1: T[], arr2: U[]): [T, U][] {
Noticed that function is not used anymore after refactoring the prompt utility in previous commit. Removed the function

2024-11-06 13:20 UTC, hitesh-1997 commented on vscode/src/autoedits/utils.ts
> +        }
Thanks for noticing, changed to suggested logic

2024-11-06 13:21 UTC, hitesh-1997 commented on vscode/src/autoedits/utils.ts
> +    const match = text.match(/^\n+/)
Actually the prefix, suffix received from `docContext` already replaces `\r\n` or `\r` to standard `\n` chars. But I modified the logic to handled the `\r` as well to prevent any future regressions. Also included the relevant test cases in `utils.test.ts`

2024-11-06 13:21 UTC, hitesh-1997 commented on vscode/src/autoedits/utils.ts
> +export function countNewLineCharsEnd(text: string): number {
done

2024-11-06 23:43 UTC, dominiccooney approved these changes
Please briefly document the start/end newline character counting functions to mention that they also count `\r` and emphasize that they count characters, not lines. (The naming is good and the function suitable for the purpose. But if someone picked this up and called it, they might easily make the mistake that it counts lines and it coincidentally does that on macOS, Linux.)

I didn't dig into your comment about the line endings being normalized. If you can simplify the `\r` handling that is great but I leave it up to you.

2024-11-06 23:44 UTC, dominiccooney commented on vscode/src/autoedits/prompt-utils.ts
> +    const lineNumberMapping = mapLinesToOriginalLineNo(
It is wasteful to allocate that whole array just to get the min and max. You are already calculating the min and max + 1 to compute the range, just return those.

2024-11-08 08:54 UTC, merged