add `isCommand` to chat-question events metadata
sourcegraph/cody pull request #5959
Opened 2024-10-21 18:16 UTC by akalia25

Previously, `cody.chat-question` events did not include information whether this was command generated (i.e. explain code) or not. Now, this data will be included for these events, helping analytics distinguish between user chat submissions and command chat submissions.

## Test plan
CI + Locally and confirmed new fields are appearing as expected.
<img width="761" alt="image" src="https://github.com/user-attachments/assets/cfbecd1b-23f7-4150-8489-53a1c52ec44b">

## Changelog

2024-10-22 00:40 UTC, dominiccooney commented on lib/shared/src/telemetry-v2/events/chat-question.ts
> +                        isCommand: params.command ? 1 : 0,
Commands are being deprecated in favor of prompt library, so let's align the purpose, names, etc. with that.

2024-10-22 00:42 UTC, dominiccooney requested changes
Quick Sourcegraph search and I don't even see where we're setting `params.command` any more.

2024-10-22 03:09 UTC, akalia25 commented on lib/shared/src/telemetry-v2/events/chat-question.ts
> +                        isCommand: params.command ? 1 : 0,
Thanks! I would still love for us to collect this in the meantime, as we deprecate commands. Right now, we have no way of distinguishing if a `chat-question/executed` event came from a user vs command and this could impact chat submission metrics slightly. 

For prompts, I noticed that it is first added to the chat box and then the user has to click submit for it to go through ... wondering if that will be the behavior going forward? Might need to add some logic/telemetry for when a user inserts a prompt but then edits it before submitting. 

Similarly, for right-click "commands" (screenshot) will those go away for prompts and not be auto-submitted? 
<img width="589" alt="image" src="https://github.com/user-attachments/assets/a7ad5701-c147-42ad-9cea-f80649f9adbd">

Happy to ask these questions elsewhere if you're not directly involved with the depreciation of commands :)

2024-10-23 03:54 UTC, dominiccooney commented on lib/shared/src/telemetry-v2/events/chat-question.ts
> +                        isCommand: params.command ? 1 : 0,
> I would still love for us to collect this in the meantime, as we deprecate commands.

OK but I literally don't see where we set the `params.command` field any more.

> For prompts, I noticed that it is first added to the chat box and then the user has to click submit for it to go through ... wondering if that will be the behavior going forward?

@taiyab ^^^

> Similarly, for right-click "commands" (screenshot) will those go away for prompts and not be auto-submitted?

@kalanchan, @taiyab ^^^

2024-10-23 03:58 UTC, dominiccooney approved these changes
OK, sounds like:

- We want to track legacy commands even though they're going away at some point.
- We'll probably want to design some different logging for Prompts anyway, to know if they're edited.
- We confirmed that `params.command` is being set ✔️ 

So let's land this... you might want to put a TODO on there, like `TODO: Remove this field when the transition from commands to prompts is complete` so we remember to clean this up.

2024-10-23 17:33 UTC, merged

2024-10-24 14:27 UTC, taiyab commented on lib/shared/src/telemetry-v2/events/chat-question.ts
> +                        isCommand: params.command ? 1 : 0,
Apologies for the late response here.

> For prompts, I noticed that it is first added to the chat box and then the user has to click submit for it to go through ... wondering if that will be the behavior going forward?

Prompts can either be set to auto-run or not.

> Similarly, for right-click "commands" (screenshot) will those go away for prompts and not be auto-submitted?

Replaced with prompts, of which some have auto-run behaviour.