Fix issues with incorrect serialization of LocalStorageDB items
sourcegraph/cody pull request #5969
Opened 2024-10-22 11:48 UTC by pkukielka

## Changes

To avoid further doubts I adjusted behaviour and interface of `LocalStorageDB`to be more in sunc with `vscode.Memento`, that is:
* setting key to `null` or `undefined` removes key from the store
* get on non-existing key returns an `undefined`

Note that it means setting key to `null` and then doing get on it will result in `undefined` value, not a `null`.

I also added exception handling in the `LocalStorageDB::get` to make sure we won't fail on all previously incorrectly serialised values.

## Test plan

Unit tests which should cover all corner cases were added.

2024-10-22 11:49 UTC, pkukielka commented on agent/src/global-state/AgentGlobalState.ts
> +    public get<T>(key: string, defaultValue?: T): T {
Just so it have the same interface as `Memento` it inherits from.
That change is not really needed for that PR, so if someone disagrees I can revert.

2024-10-22 12:52 UTC, dominiccooney requested changes
Could we do this with fewer semantic changes, to be conservative? Ideally we want something that lines up with whatever VSCode does, after you project it through our many layers of wrappers.

Some ideas but I have not carefully checked the details:

- Leave all the valid JSON values alone (including `''`, `null`.)
- If we treat the invalid JSON serialized string `"undefined"` as a missing key, then don't return that key in the keys enumeration. (If we treat it as `null` then having it in keys is probably fine...)
- Treat setting `undefined` as deleting, IIRC the client wants behavior like that.

2024-10-22 12:52 UTC, dominiccooney commented on agent/src/global-state/AgentGlobalState.ts
> +            this.storage.removeItem(key)
WDYT about *not* removing these... we can keep running this `catch` branch. In the off chance there's some useful corrupt state...

2024-10-22 12:52 UTC, dominiccooney commented on agent/src/global-state/AgentGlobalState.ts
> +        if (value) {
This might go too far... we're swapping `''` for `undefined` here now.

2024-10-22 12:58 UTC, pkukielka commented on agent/src/global-state/AgentGlobalState.ts
> +            this.storage.removeItem(key)
Sounds good, I have no problem with that.

2024-10-22 13:01 UTC, pkukielka commented
> Ideally we want something that lines up with whatever VSCode does, after you project it through our many layers of wrappers.

> Leave all the valid JSON values alone (including `''`, `null`.)

We can pick one, but not both. 
I specifically did those semantic changes to make it very similar to VSCode, as I think that could reduce amount issues going forward. I do not think it is very risky either, as it only affects `null` / `undefined` values.

If we need to pick one of the above, I would rather go for correctness than tried to be conservative with changes, but possibly still wrong. But I'm open to other takes on it of course.

2024-10-22 13:01 UTC, pkukielka commented on agent/src/global-state/AgentGlobalState.ts
> +        if (value) {
Good point, I will add a test and fix it.

2024-10-22 13:04 UTC, dominiccooney commented
Ok! Bringing it into line with VSCode sounds good to me.

2024-10-22 13:35 UTC, dominiccooney approved these changes
It is tempting to not `setItem(key, JSON.stringify(value))` when `value` is `undefined` but I guess this is fine, the `catch` will handle it on reading.

2024-10-22 14:31 UTC, pkukielka commented
> It is tempting to not `setItem(key, JSON.stringify(value))` when `value` is `undefined` but I guess this is fine, the `catch` will handle it on reading.

Agree and fixed.
Problem was I did check `value != null && value != undefine` and then VSCode suggested me that I should replace it with value != null` because it test the same (which I did). But instead I should test for `value !== null && value !== undefine` which is clearly showing the intent (notice `!=` vs `!==`)

2024-10-22 14:35 UTC, merged

2024-10-23 02:37 UTC, dominiccooney commented
> Problem was I did check value != null && value != undefine and then VSCode suggested me that I should replace it with value != null because it test the same (which I did).  ...

Ah good point, I forgot that `undefined == null` is `true`.

I like the explicit version anyway, thank you for updating it.