fix(Blank Screen): Improve UTF-16 character handling in Typewriter class
sourcegraph/cody pull request #5982
Opened 2024-10-23 21:02 UTC by PriNova

### Problem
The Typewriter class, which provides the typing animation effect in chat responses, was not properly handling UTF-16 characters. This could lead to broken rendering of:
- Emoji characters 😀
- Characters outside the Basic Multilingual Plane
- Combined Unicode characters
- Other UTF-16 surrogate pairs

which resulted in a **blank screen** in the Cody chat.

### Solution
Added proper UTF-16 character boundary handling by:
- Implementing a new `getNextValidSlicePoint` method that respects code point boundaries
- Using `Array.from()` to properly handle UTF-16 code points
- Ensuring text slicing occurs at valid character boundaries

### Demo
Before fix:

https://github.com/user-attachments/assets/8f896b06-2546-4401-bf1d-44c1a5f1d101

- Shows broken emoji/special characters during typing animation

After fix:

https://github.com/user-attachments/assets/1f0bc0fc-92ed-4309-910c-6607b5bed9cc

- Shows proper rendering of all Unicode characters

## Test plan

**All tests were performed with the 'Temperature' setting equal to 0 (zero) to obtain deterministic results.**

- Tested with various Unicode characters including:
  - Emoji sequences
  - Combined characters
  - Characters outside BMP
  - Multi-code point characters

### Notes
- No breaking changes to the Typewriter interface
- Maintains existing typing animation timing and behavior
- Only affects the character boundary handling

## Changelog

2024-10-23 22:53 UTC, jamesmcnamara requested changes
This is nice! Thanks for contributing :)

I'd prefer if we kept the comments in place, they are helpful for new comers to the code.

If you pull the latest main, you should get [this change](https://github.com/sourcegraph/cody/pull/5984) which should fix the failing unit tests.

2024-10-23 23:06 UTC, PriNova commented
> This is nice! Thanks for contributing :)
> 
> I'd prefer if we kept the comments in place, they are helpful for new comers to the code.
> 
> If you pull the latest main, you should get [this change](https://github.com/sourcegraph/cody/pull/5984) which should fix the failing unit tests.

This was accidental because Cody deleted them, but I will add them back now.

2024-10-23 23:32 UTC, jamesmcnamara approved these changes

2024-10-23 23:33 UTC, merged

2024-10-24 00:02 UTC, jdorfman commented
Amazing work @PriNova