Remove repo chip from default context
sourcegraph/cody pull request #6034
Opened 2024-10-30 22:35 UTC by beyang

## Test plan

## Changelog

2024-10-31 01:32 UTC, sqs approved these changes
Approved for dogfooding on prerelease asap. Will need migration and more design work for the transition in the release.

2024-10-31 06:48 UTC, dominiccooney requested changes
Looks like there are some related test failures.

Sounds like this was motivated by engagement metrics... How do you plan to separate the effect of this from all the other changes in the product? Would you A/B test this to find out if it worked?

2024-10-31 06:48 UTC, dominiccooney commented on lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts
> +                            initialItem.uri.toString() === item.uri.toString() &&
This doesn't look right for different line range references to the same/whole file, which are both files with the same URI.

If it is not possible to have line range additional items, add an assertion to that effect so if someone changes the assumption they'll get a clear, explicit failure.

2024-10-31 06:48 UTC, dominiccooney commented on vscode/package.json
> +        "key": "shift+ctrl+l",
Use separate changes for separate purposes.

2024-10-31 06:48 UTC, dominiccooney commented on vscode/webviews/App.tsx
> +        () => getAppWrappers(vscodeAPI, telemetryRecorder, config, undefined, undefined),
Consider using an object for these parameters; the meaning of `undefined, undefined` is unclear at the callsite but a property name or explaining variable would help.

2024-10-31 06:48 UTC, dominiccooney commented on vscode/webviews/chat/Transcript.tsx
> +                        Rerun with repository context
The "play" button on chats is labeled "Send", maybe "Resend with ..." for consistency? Also, the button only appears if there's no repository context; but it resends with the *current* repository context... is it worth saying "current repository"?

@toolmantim , @taiyab FYI on labels, alignment, etc. of this button.

2024-10-31 06:56 UTC, dominiccooney commented
@sqs 

> Approved for dogfooding on prerelease asap. Will need migration and more design work for the transition in the release.

We (me, Grace, et al) have a proposal to use the prerelease channel to "soak" versions before going to stable. We would patch ship blocking bugs on that channel, and the next stable release would be based on that. The motivation is to reduce the serious defects reaching our customers and use time that had been spent firefighting on more productive things. However it does come at the cost of adding some latency between commits on main and wide distribution.

In practice in this case, it means dogfooding on prerelease would have to wait up to a week. Design work would not be merged to release branches unless it was a ship blocking bug.

I appreciate having a low-latency way to get feedback is very valuable but I believe we need more reliable low-latency quality indicators before we can do that. We are working on it.

2024-10-31 16:33 UTC, beyang commented on lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts
> +                            initialItem.uri.toString() === item.uri.toString() &&
FYI, the behavior here isn't actually changing. All the change does here is is factor out the `...(value?.items` expression into a separate variable. The original behavior appears valid, because the `initialContext` always includes the current file and only files are at-mentionable, so the file URI comparison is enough. But I agree, it feels brittle so I'll look into cleaning this up a bit.

2024-11-02 12:43 UTC, DashaBochkar approved these changes

2024-11-04 03:49 UTC, merged