Command bench modify
sourcegraph/cody pull request #6087
Opened 2024-11-07 14:58 UTC by AyushmunotSG18

Modify the code in command-bench to support both old format and new clickable format of links in context-items. The corresponding link for PR in cody-leaderboard is [Added modified csv with clickable link and corresponding script #21](https://github.com/sourcegraph/cody-leaderboard/pull/21)

## Test plan
No tests plan required

2024-11-08 09:18 UTC, janhartman requested changes
Why can't we just reprocess "old" files to change all context items into a clickable format instead of supporting them here indefinitely?

Also, we hardcode sourcegraph.sourcegraph.com and github.com in a few places which isn't really the best practice.

2024-11-08 10:45 UTC, AyushmunotSG18 commented
> Why can't we just reprocess "old" files to change all context items into a clickable format instead of supporting them here indefinitely?
I am not super sure about this, but Beyang asked me to do it, and 1 main reason was maybe he don't want to change the format for all suddenly. 

> Also, we hardcode sourcegraph.sourcegraph.com and github.com in a few places which isn't really the best practice.
Yes, this though came in my mind because all repositories will never be present at sourcegraph.sourcegraph.com, can we just send them to gihub.com where they will actually present?

2024-11-08 12:37 UTC, janhartman commented
> I am not super sure about this, but Beyang asked me to do it, and 1 main reason was maybe he don't want to change the format for all suddenly.
I would still encourage preprocessing the old results rather than adding and having to maintain a separate code path.
> Yes, this thought came in my mind because all repositories will not be present at sourcegraph.sourcegraph.com, can we just send them to gihub.com where they will actually present?
github.com isn't a perfect choice either, we might have repositories not hosted there. Also, we should encourage using Sourcegraph, so I'd prefer S2 to GH.

2024-11-08 13:53 UTC, AyushmunotSG18 commented
> I would still encourage preprocessing the old results rather than adding and having to maintain a separate code path.
>
We anyways having that thing as this code will work with both format. 
@beyang Can you once clarify whether we should do this changes to handle both current non-clickable links format and clickable-link format, or we have a list of csv that we want to do preprocessing.

> github.com isn't a perfect choice either, we might have repositories not hosted there. Also, we should encourage using Sourcegraph, so I'd prefer S2 to GH.
>
Can you elaborate which are those repo which are not hosted on github.com, any such example?  Also what exactly these means "we should encourage using Sourcegraph, so I'd prefer S2 to GH"

2024-11-12 15:20 UTC, beyang commented
@janhartman I think it's for convenience in these cases:
1. Manual dataset construction: There's an extra step where conversion from the URL you copy from your browser to the format
2. Dataset review: This is often done by loading the CSV into Google sheets. If the URLs were openable in your browser, it would reduce the friction to inspecting the snippets for each example

It's actually quite helpful in these two cases to be able to quickly create and open context snippets.

2024-11-13 00:08 UTC, jtibshirani reviewed
+1 to this change overall. I also find the clickable results very useful for dataset review.

Suggestions:
* Can we just have one code path, the new one? We can remove the old parsing logic and just convert all the old data to the new format. Also, we should fail hard if anything is not in the format we expect, instead of flexibly trying to make it work. This makes it easier to debug problems, and it's not a huge lift to make sure the format is correct everywhere.
* There isn't a perfect choice for the URL, but I also prefer S2 over GitHub. We prefer Sourcegraph internally, and links to S2 are considered "stable" -- for example we also include links to S2 in internal docs.

2024-11-13 20:45 UTC, beyang commented
@AyushmunotSG18 are you blocked on anything else?

2024-11-18 12:06 UTC, janhartman commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
Could you please explain again why are we not reprocessing already existing files?

2024-11-29 09:32 UTC, AyushmunotSG18 commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
@janhartman Do you want me to change it so that all files after processing gives clickable format only, beyang asked to support for both formats. So, I have kept the format same as the intial csv one. Like if it is clickable format then output will also be clickable else on other way of plain format.

2024-11-29 09:36 UTC, janhartman commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
@beyang Could you please elaborate why would we want both formats instead of just one? IMHO (Julie said the same [here](https://github.com/sourcegraph/cody/pull/6087#pullrequestreview-2431167932)) one code path is preferrable.

2024-12-01 00:06 UTC, beyang commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
My original thinking is that we'd want to preserve backwards compatibility with old formats, but if we're discarding those anyway in favor of the new input tables, then I'm fine with consolidating on the new format.

2024-12-02 17:58 UTC, AyushmunotSG18 commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
@beyang @janhartman , I will change the code to output csv with only new format and will remove the backwards compatibility with old formats.

2024-12-02 18:04 UTC, janhartman commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
Great! Make sure to reprocess the files and verify that nothing gets broken :)

2024-12-04 15:49 UTC, janhartman commented on agent/src/cli/command-bench/strategy-chat-context-types.ts
> +    format?: 'url' | 'old'
Yes, once the preprocessing is done please delete it the old one so we don't need to support two code paths.

Right now we just have golden queries + all the snapshots generated from it.

2024-12-05 17:39 UTC, AyushmunotSG18 commented
@jtibshirani, I have removed backward compatibility for older versions and now it will support only new version as well as command bench will return also new version csv. 
I am not getting why 3 unit tests are failing. Can you have a look over it.

2024-12-06 04:14 UTC, jtibshirani commented
@AyushmunotSG18 sometimes these end-to-end tests are just flaky. It doesn't look related to your changes. I just tried retriggering the failed jobs -- hopefully that resolves it!

2024-12-06 04:15 UTC, jtibshirani approved these changes

2024-12-06 04:16 UTC, AyushmunotSG18 commented
> @AyushmunotSG18 sometimes these end-to-end tests are just flaky. It doesn't look related to your changes. I just tried retriggering the failed jobs -- hopefully that resolves it!

cool, got it.

2024-12-06 06:11 UTC, merged