Trace export
sourcegraph/cody pull request #6100
Opened 2024-11-08 23:35 UTC by arafatkatze

## Test plan

## Changelog

2024-11-13 05:14 UTC, dominiccooney requested changes
A good start, feedback inline.

Instead of adding lots of low quality spans, let's concentrate on a good chat latency: from hitting submit to when we paint the first token. This is interesting because:

- Core product scenario.
- Has an extension-side metric we can compare and contrast to learn a bit about webview latency specifically.
- Easy, in the sense that it starts and ends in the webview.
- ...but still interesting. These "how long does it take to run postMessage" don't reflect user latency.

2024-11-13 05:14 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +    return getRootSpan(spanMap, parentSpan)
Tail recursion might be OK, but try this as a loop. The compiler is more likely to do something decent with it.

Worth commenting that you return `null` for spans with parent IDs, but that are not found, expecting them to be completed later.

2024-11-13 05:14 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +        if (typeof value === "object" && value !== null) {
Be consistent about single and double quoted strings.

2024-11-13 05:14 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +function saveToLocalStorage(data: string, key: string = 'myData') {
Why are we doing this? local storage isn't free so what's the plan to use, expunge, etc. this?

2024-11-13 05:14 UTC, dominiccooney commented on vscode/webviews/App.tsx
> +    // Add this near the top with other state declarations
???

2024-11-13 05:14 UTC, dominiccooney commented on vscode/webviews/App.tsx
> +    // Add this effect to configure telemetry based on config changes
??? what is this tutorial style content in big comment blocks?

2024-11-13 05:14 UTC, dominiccooney commented on vscode/webviews/App.tsx
> +        telemetryService.configure({
this indentation is weird.

2024-11-13 05:14 UTC, dominiccooney commented on vscode/webviews/Chat.tsx
> +            return tracer.startActiveSpan('submit-feedback', async span => {
Consider mimicking something like our `wrapInActiveSpan` to cut down on the try-catch-finally boilerplate

2024-11-13 05:14 UTC, dominiccooney commented on vscode/webviews/Chat.tsx
> +            return tracer.startActiveSpan('copy-code', async span => {
This isn't what I'd call user latency. The copy button gives you feedback by adding a checkmark and changing the text to "copied." The perceived latency ends for the user after that point.

Same with feedback above.

2024-11-13 05:14 UTC, dominiccooney commented on vscode/webviews/Chat.tsx
> +                const tracer = trace.getTracer('cody-webview')
OK, I'm going to stop commenting on these spans. The definitions need work, this one in particular is complicated because the activity runs into the editor. The time to send a postMessage isn't very interesting. I'm curious how we ended up here?

Let's concentrate on getting chat from submit (key up on enter or click event on button) to when we paint the first token (we render a token plus one requestAnimationFrame.)

2024-11-13 20:44 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +const MAX_TRACE_RETAIN_MS = 60 * 1000
> TIL that ms is more popular than msec in cases like this in the cody codebase.

TIL that msec is even a thing, I always only knew ms.


> Is one minute too short, BTW?
You are right and I have had scenarios where there are long chats that are started on the barrier and they would go past the limits so I had to figure out ways to tweak the span collection so that they get sent together properly with the root span. This is something I am still tweaking though so for now lemme set it to 5 minutes.

2024-11-13 21:01 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +            const response = await fetch(traceUrl, {
💯

2024-11-13 21:01 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +                logError('ChatController', 'Cannot send trace data: not authenticated')
💯

2024-11-13 21:01 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +            case 'trace-exporter':
makes sense

2024-11-13 21:11 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +                await this.sendTraceData(message.myspan)
💯

2024-11-13 23:47 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +            const traceUrl = new URL('/-/debug/otlp/v1/traces', auth.serverEndpoint).toString()
💯

2024-11-14 00:44 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +            saveToLocalStorage(safeData)
This was just for my experimentation and local debugging. 
IT helped me have a lot of trace json that can I copy paste and properly inspect elsewhere.

2024-11-14 00:58 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +            console.log('[CodyTraceExporterWeb] Exporting spans:', {
Just a temp thing for local debugging with console

2024-11-14 01:03 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +            const safeData = JSON.stringify(exportData, getCircularReplacer())
<img width="335" alt="image" src="https://github.com/user-attachments/assets/fc9fc787-86db-43c1-b3cc-96224d3abdd3">
I got errors like these when I would try to stringify the spans and they made no sense  so I added this new function with the help of LLMs and then those errors stopped.

2024-11-14 01:27 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +    return getRootSpan(spanMap, parentSpan)
Fair point

2024-11-14 01:29 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +                this.queuedSpans.delete(spanId)
Makes sense

2024-11-15 04:48 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +            return tracer.startActiveSpan('copy-code', async span => {
These were just test spans and I got rid of them.

2024-11-15 04:50 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +        // Build span hierarchy map
Backend can't specifically deal with the special logic that I have here and the span ordering+parent child relationships and while I can send the spans to the backend to do the computation there i think its better to do here here before the serialization deserialization operations.

2024-11-16 01:34 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +                const tracer = trace.getTracer('cody-webview')
These were just test spans and I got rid of them.

2024-11-16 01:35 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +            return tracer.startActiveSpan('submit-feedback', async span => {
Good advice and I did that

2024-11-16 01:41 UTC, arafatkatze commented on vscode/webviews/App.tsx
> +    // Add this effect to configure telemetry based on config changes
Removed such stuff

2024-11-16 01:42 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +function saveToLocalStorage(data: string, key: string = 'myData') {
This was just for testing purposes and I got rid of it.

2024-11-16 04:37 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +        if (typeof value === "object" && value !== null) {
💯

2024-11-19 04:16 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +                throw new Error(`Failed to send trace data: ${response.statusText}`)
I shifted this elsewhere and made it non blocking

2024-11-19 04:21 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +            if (hasRenderSpan && hasCompletedRender) {
fair point

2024-11-19 05:02 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +            span.attributes.agentIDE = this.agentIDE
We can probably name AgentIDE differently

2024-11-19 05:02 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +    private isSpanGroupComplete(spanGroup: Set<ReadableSpan>): boolean {
Added a TODO here but this looks okayish for now

2024-11-19 13:07 UTC, dominiccooney requested changes
This is shaping up very nicely.

The conditions for what state we're in look arduous, any ideas about abstractions there so it is simpler?

This is still not user latency in the sense that HumanMessageEditor onSubmitClick is probably when we could start measuring something. Looks like we have already undergone some state changes by the time we start a span in what you have here?

2024-11-20 00:52 UTC, arafatkatze commented on vscode/webviews/utils/webviewOpenTelemetryService.ts
> +    public dispose(): void {
Thanks for pointing that out! I've added a guard clause to the dispose method to ensure it only affects the global instance when appropriate. This should help maintain simplicity and prevent any unintended modifications to the global state.
Let me know if you have any other suggestions!

2024-11-20 01:02 UTC, arafatkatze commented on vscode/webviews/utils/webviewOpenTelemetryService.ts
> +        if (!WebviewOpenTelemetryService.instance) {
> Why not have the singleton, initialize it, and make it convenient to use. Then the constructor doesn't need conditional side effects...

Great question: I actually spent some time with this.
So for this code
https://github.com/sourcegraph/cody/blob/c4972693f9c6152421946f217d6b4f4bc63b3ac0/vscode/webviews/App.tsx#L159-L173



I had to wait for config to fully load and only then do i get the value of `config.clientCapabilities.agentIDE` and `config.clientCapabilities.agentExtensionVersion` because they are needed to figure out which OS and IDe the request is coming from: so I had to make use of useEffect for that to load fully and only then I could do the configuration(although Ideally I would have just done the initialization once and be done with it). This seemed like a good enough way to pass config values in the configuration. 

> Why have configure exit early?
Once the configuration is loaded and set up, I want it to be globally accessible for the webview. This approach ensures that subsequent changes—such as those triggered by useEffect—don’t introduce unnecessary complications that make debugging issues (like traces not rendering correctly) more difficult. By enforcing a singleton pattern and using a fixed configuration after initialization, we can guarantee the stability of the trace pipeline. This way, you only need to focus on potential errors in trace handling, rather than worrying about misconfigurations or unstable configurations.

2024-11-20 01:11 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +                // Also set on parent span for backwards compatibility
Sorry it was just a bad LLM comment so I removed it, NOTE: its still a child of the parent trace of chat-interaction.

2024-11-20 01:41 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +                    'render.total_time': Date.now() - (renderStartTime.current ?? Date.now()),
Fixed that it was a classic typechecking ai fix

2024-11-20 02:04 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +                            'chat.total_time': Date.now() - (renderStartTime.current ?? Date.now()),
Done

2024-11-20 02:33 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +    const setActiveChatContextCallback = useCallback((context: Context | undefined) => {
Fair point

2024-11-20 03:49 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +        for (const [spanId, { enqueuedAt }] of this.queuedSpans.entries()) {
> How often is it called? 
Its called whenever 2+ chats are finished(coz buffer is full) so not that often but I can see how this can blow up as we add a lot of stuff. 

> How fast is it in practice?
Its fast but I changed it to only be called every 5 minutes or if the export buffer is full.

2024-11-20 04:14 UTC, arafatkatze commented on vscode/src/services/open-telemetry/trace-sender.ts
> +        throw new Error('Not authenticated')
> Why do we require this?



```
    const traceUrl = new URL('/-/debug/otlp/v1/traces', auth.serverEndpoint).toString()
    const response = await fetch(traceUrl, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            ...(auth.accessToken ? { Authorization: `token ${auth.accessToken}` } : {}),
        },
        body: spanData,
    })
```

When we send the telemetry data to the Otel Collector endpoint it does require the auth token so that's why. 


> What's the plan for performance around login, which we will probably want to do soon.

I gotta think through this to be honest, I can't tell you much right now unless I explore the code first

2024-11-20 05:12 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +        // Build span hierarchy map
You are right, and I had a misunderstanding regarding the context propagation in React. I've since fixed the code, addressed the span closure condition, and I believe we no longer need the special logic I previously discussed.

Here's what I found:

- Span Ordering: The key is to ensure that the parent span is started first and is the last one to be closed. This way, the context naturally handles the parent-child relationships. In React, this requires careful management of when spans are started and ended, especially given the asynchronous nature of component rendering.

- Node.js vs. React: In Node.js, context propagation is more straightforward because the execution flow is more "linearish" and  making it easier to maintain a tree-like structure of spans. In React, however, components can start and end at different times, so we need to manually manage context propagation to maintain the correct span hierarchy and make sure I open and close them in the right order(So for example if I closed the root span BEFORE the assistant render finishes then root+time to first token is sent along and we get an erroneous metric that missed out on the assistant render span)

Thanks again for noting this.

2024-11-20 05:12 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
> +                span.name === 'assistant-message-render'
Fixed

2024-11-20 05:50 UTC, arafatkatze commented
> The conditions for what state we're in look arduous, any ideas about abstractions there so it is simpler?

Yes, I will do that super soon to put things together separately. It might not change the logic but atleast it will make the code a lot more understandable. That's just one last step. 


> This is still not user latency in the sense that HumanMessageEditor onSubmitClick is probably when we could start measuring something. Looks like we have already undergone some state changes by the time we start a span in what you have here?

Fixed that.

2024-11-20 14:05 UTC, dominiccooney approved these changes
Some feedback inline. Let's land this and iterate on any niggling details.

2024-11-20 14:05 UTC, dominiccooney commented on vscode/webviews/chat/Transcript.tsx
> +                        'chat.total_time': chatTotalTime,
I'm fine with this as-is for now, but we will need to add the number of tokens (or something indicative of response length), and maybe the number of updates we produced and frames dropped. The terrible jank we saw in chat last time would show up with those metrics.

2024-11-20 14:08 UTC, dominiccooney commented
Kudos for writing a detailed test plan.

It may make sense to unit test the span construction. It's fine to do that in a follow-up PR. The whole mechanism will be continuously observed by the alerts, so an integration test is less critical for this.

2024-11-20 22:47 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +    const setActiveChatContextCallback = useCallback((context: Context | undefined) => {
Sorry, I thought I had pushed the fix but it got missed. I fixed it now.

2024-11-20 22:51 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +        performance.mark('startSubmit')
Good catch!!

2024-11-20 22:59 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +            timeToFirstTokenSpan.current?.end()
Classic copy paste schlob mistake and great catch from you. 

That code wasn't being touched because the time to first token was already ended when the first token actually appeared a couple of lines below at 
```

  const endFirstTokenSpan = () => {
            if (renderSpan.current && timeToFirstTokenSpan.current) {
                // Mark the first token
                performance.mark('firstToken')
                // Measure the time to first token
                performance.measure('timeToFirstToken', 'startRender', 'firstToken')
                const firstTokenMeasure = performance.getEntriesByName('timeToFirstToken')[0]
                if (firstTokenMeasure.duration > 0) {
                    // Set attributes and end the time-to-first-token span
                    timeToFirstTokenSpan.current.setAttributes({
                        'time.to.first.token': firstTokenMeasure.duration,
                    })
                    timeToFirstTokenSpan.current.end()
                    timeToFirstTokenSpan.current = undefined
                    hasRecordedFirstToken.current = true
                }
            }
        }
```

So we end the first token span  when a rendering first appears. In the mistake above I was also removing it again on the finishing of the rendering but its NOT needed.

2024-11-20 23:06 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +            hasRecordedFirstToken.current = false
Absolutely, React cannot be trusted so doing this is good.

2024-11-20 23:11 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +                        'chat.total_time': chatTotalTime,
Absolutely will keep this in mind for the next PRs

2024-11-21 00:10 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +            startSpanAndSubmit('edit', editorValue, intentFromSubmit)
Fair point, so I added it like this 
```

    const onUserAction = (action: 'edit' | 'submit', intentFromSubmit?: ChatMessage['intent']) => {
        // Start the span as soon as the user initiates the action
        const startMark = performance.mark('startSubmit')
        const spanManager = new SpanManager('cody-webview')
        const span = spanManager.startSpan('chat-interaction', {
            attributes: {
                sampled: true,
                'render.state': 'started',
                'startSubmit.mark': startMark.startTime,
            },
        })

        if (!span) {
            throw new Error('Failed to start span for chat interaction')
        }

        const spanContext = trace.setSpan(context.active(), span)
        setActiveChatContext(spanContext)

        // Serialize the editor value after starting the span
        const editorValue = humanEditorRef.current?.getSerializedValue()
        if (!editorValue) {
            console.error('Failed to serialize editor value')
            return
        }

        const commonProps = {
            editorValue,
            intent: intentFromSubmit || intentResults.current?.intent,
            intentScores: intentFromSubmit ? undefined : intentResults.current?.allScores,
            manuallySelectedIntent: !!intentFromSubmit,
        }

        if (action === 'edit') {
            editHumanMessage({
                messageIndexInTranscript: humanMessage.index,
                ...commonProps,
            })
        } else {
            submitHumanMessage({
                ...commonProps,
            })
        }
    }
```
so that serialization is within span. Hope that's better than before?

2024-11-21 00:11 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +            startSpanAndSubmit('edit', editorValue, intentFromSubmit)
Happy to make more changes in followup PR too.

2024-11-21 00:43 UTC, merged