Pre-windows fixes
sourcegraph/cody pull request #6101
Opened 2024-11-08 23:52 UTC by RXminuS

## Test plan

## Changelog

2024-11-08 23:52 UTC, RXminuS commented
* **#6101** <a href="https://app.graphite.dev/github/pr/sourcegraph/cody/6101?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RXminuS and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-11 03:16 UTC, dominiccooney requested changes
Wow that's a lot of work to call `load_native_certs`. But `load_native_certs` does a lot of useful stuff so it's probably worth it, and having this capability to dip into Rust and system APIs more easily is very appealing.

# Build
I assume this still builds on Windows? Let's not make life hard for those teammates. 

Would be great to have some docs, even better lints, that remind you to update the binaries if you touch certain paths. And to produce those binaries in CI in official builds.

IIRC some of our customers use musl, do we need to add a variant for it? (For example check out the incidental MUSL in this log https://github.com/sourcegraph/cody/issues/2893 , and I recall bug reports about musl in the BFG days.)

# Runtime
Any thoughts about how to collect crashes and panics from this?

# Distribution

I'm glad that these binaries are relatively small. How big do they get when you pull in cronet/rust networking * platform * architecture? How confident are you that Rust networking is the way forward?

Given the scope of this change, let's not rush it for the Nov 13 release. Yes, it is basically calling one function but there's a lot of moving parts. Instead it would be great to have it off by default in main... the `.node` binary files lying around in prerelease in Nov 13—can you monitor for reports of problems (could be failures, could be CPU use) with Windows Defender, etc. from these new binary files? And look at turning it on after that maybe.

# Docs
Could we make it more transparent to customers/technical support about when and how we get system certs, maybe link to https://github.com/rustls/rustls-native-certs?tab=readme-ov-file#platform-support so technical support know what's going on?

2024-11-11 08:56 UTC, RXminuS commented on vscode/src/net/DelegatingAgent.ts
> +        .pipe(map(normalizeSettings), distinctUntilChanged(), map(this.resolveSettings.bind(this)))
We never did before either, that would be new bonus functionality. However now every time you change settings it will actually re-check so it's already more dynamic than it was before

2024-11-11 08:57 UTC, RXminuS commented on agent/src/esbuild.mjs
> +        //TODO: Handle this based on the vscodeignore because it's very easy to
More that it's an unrelated change to this PR, but it should be changed at some point

2024-11-11 09:44 UTC, RXminuS commented
Yeah it's a lot of boilerplate, but most of that to make sure it's set up for success. It could have been done much smaller. But now there's logging, error handling, and a place for tests to go.

I've skipped the whole build & CI setup for now for a future PR as basically until this is verified to actually work well there shouldn't be any changes to the core lib. I've added a notice about this in the README.

In general I'm not too worried about windows defender or AV blocking things. That was definitely an issue with the binaries we loaded before. I've gone through an equally painful road to a nearly identical solution before within enterprise context at large law firms so at least I'm not flying entirely blind here. But I understand that it's untested and we should be cautious. At least if something does delete them or otherwise cause a panic the fallbacks seem to handle it just fine. I'll see if I can add a test to demonstrate that.

W.r.t. cronet I'm definitely not sure/advocating that is the correct solution at the moment; but it's at least a viable option to try with this boilerplate in place. I think the more important low hanging fruit would be to move our tree sitter parsing, slow-on-large-files-Jackard-similarity-autocomplete-context-window, and token counting (which could be 100x faster if using tiktoken boundary check instead of count) functions in here as they'll get rid of a lot of performance and dependency issues that have been a constant plague. But again, it's not that I think we should do all of those but we have the option now to easily benchmark and try it out.

2024-11-11 10:55 UTC, RXminuS commented on lib/fatcore/test/config.test.ts
> +    it('can load system proxy', async () => {})
Just checks that loading functions and there's no panic on function calls

2024-11-11 10:57 UTC, RXminuS commented on vscode/package.json
> +        "cody.experimental.fatcore.enabled": {
It was just legacy. Renamed it now to noxide (node + oxidize (rust) ... explained the name in Readme)

2024-11-11 11:03 UTC, RXminuS commented on vscode/src/extension.node.ts
> +        .get<boolean>('cody.experimental.fatcore.enabled', true)
I completely understand you sentiment @dominiccooney. However this needs to function as a workaround for several clients in both VSCode and the Cody Extension Host (e.g. agent) without additional config changes. 

Also currently in JB the options aren't passed until later and initialization, meaning there is no way at the moment of enabling this in JB without additional changes on the JB side.

I'm happy to change it if we really can't stomach the risk, but given that all the loading and invocation is wrapped in try/catches and I've tried it with the .node and imports missing I think we've adequately covered at least the same doomsday scenarios we'd cover by not enabling it. But maybe @graceshih-sg or @aramaraju can weigh in here as on a technical front I'm aligned with you Dominic but I'm also very aware there's non-technical constraints here.

2024-11-11 11:04 UTC, RXminuS commented on vscode/src/extension.node.ts
> +        logError('FatCore Loader', 'Could not load fatcore library', e)
The problem is that if this loading doesn't work (in an enterprise context) pings & telemetry would likely never arrive as the networking probably wouldn't work either. Or it would only work if it's not a critical issue, leading to inherent survivorship bias. I'd rather focus on good logs and easy collection with those that have actual issues with it.

2024-11-11 11:09 UTC, dominiccooney commented on vscode/src/extension.node.ts
> +        .get<boolean>('cody.experimental.fatcore.enabled', true)
>  the options aren't passed until later and initialization, meaning there is no way at the moment of enabling this in JB without additional changes on the JB side.

I see...

> I'm happy to change it if we really can't stomach the risk,

I think we can stomach it, it is just a question of timing.

Can we land this on main now enabled by default (which we have to do anyway in either case) and ship it to insiders/JetBrains nightly 7.2.x on the 13th?

> but given that all the loading and invocation is wrapped in try/catches and I've tried it with the .node and imports missing I think we've adequately covered at least the same doomsday scenarios we'd cover by not enabling it.

I agree, except for for one: Antivirus waking up and popping up alarms, etc.

> But maybe @graceshih-sg or @aramaraju can weigh in here as on a technical front I'm aligned with you Dominic but I'm also very aware there's non-technical constraints here.

Feel free to take this to slack if we need to go into non-technical constraints.

2024-11-11 11:11 UTC, dominiccooney commented on vscode/src/extension.node.ts
> +        logError('FatCore Loader', 'Could not load fatcore library', e)
Wait, doesn't the fallback just behave like fatcore is not configured? And if we have networking today that usually works, we could detect places that can't load it that way. What am I missing?

2024-11-11 11:11 UTC, dominiccooney commented on vscode/src/net/DelegatingAgent.ts
> +        .pipe(map(normalizeSettings), distinctUntilChanged(), map(this.resolveSettings.bind(this)))
Yep. Can we document these facts?

2024-11-11 11:13 UTC, RXminuS commented on vscode/src/configuration.ts
> +        experimentalFatcoreEnabled: getHiddenSetting('experimental.fatcore.enabled', true),
To be clear there's lots of other vscode extensions that include .node extensions. It's part of the core node spec/runtime

2024-11-11 11:14 UTC, RXminuS commented on vscode/src/extension.node.ts
> +// Sentry should be imported first
We need to fix this in Cody. Sometimes it makes unrelated edits. Thanks for spotting

2024-11-11 11:15 UTC, RXminuS commented on vscode/src/extension.node.ts
> +        logError('FatCore Loader', 'Could not load fatcore library', e)
That we would only detect it in places where it then doesn't cause network issues

2024-11-11 11:20 UTC, dominiccooney approved these changes
Approving to unblock.

I think we should land this on main. I don't think we should try to ship this to stable by the 13th but get interested parties to try it in insiders/nightly first.

The test plan would be better if it gave the specific commands to run the relevant tests.

I was most concerned about enabling this by default, but it seems we must enable because the flags values aren't set early enough in JetBrains effective anyway. (Why do we have the options at all, then—you *can* turn it off in some clients? Can we have some comments about these facts?)

Please work with JetBrains peeps to have JetBrains working on a patch ready to go.

2024-11-11 11:27 UTC, RXminuS commented
Exactly, option is there mainly that if someone is having issues with the new behavior they can disable it to fall back to previous behavior.

I'll clean up the final items and work in the JB team to see if someone else has time to validate before merge. That also leaves some time to see if we enable by default or just do a separate validation build for affected customers.

2024-11-11 11:27 UTC, RXminuS commented
Thanks so much for your help and eagle eye @dominiccooney 🙏 And REALLY appreciate your push and stewardship on new release process; I'm sure it's not nice to have to feel like you're constantly having to be the bad guy (and we need to formalize it so that no individual has to feel bad for saying "no"). I think it's super important we see this way of realsing through and without a champion like yourself I don't think we would.

2024-11-13 23:53 UTC, merged