feat(autoedit): refactor renderer code to simplify iteration on decor…
sourcegraph/cody pull request #6163
Opened 2024-11-20 19:01 UTC by hitesh-1997

WIP

## Test plan

## Changelog

2024-11-21 01:22 UTC, beyang requested changes

2024-11-21 01:22 UTC, beyang commented on vscode/src/autoedits/renderer/decorators/base.ts
> +export interface AutoeditsDecorator extends vscode.Disposable {
Please add documentation describing what the interface contract is. Interfaces generally should be documented thoroughly to indicate behavior/constraints/invariants that implementors and callers should satisfy.

I see two places where this interface is used, (1) one in the main auto-edits command and (2) the other in the test command. In (1), `clearDecorations` and `dispose` are called together. In (2), it doesn't appear that `dispose` is ever called. So some clarity around how concrete implementations should be used would clarifying here. Should instances be kept around and used for multiple rounds of displaying decorations, or should new instances be created whenever new decorations are shown.

2024-11-21 01:22 UTC, beyang commented on vscode/src/autoedits/autoedits-provider.ts
> +            DecorationStrategyIdentifier.DefaultDecorator
Here, we're passing an enum-switch around, which means that multiple places in code (here and then in AutoEditsRendererManager) have to be aware of this enum, which makes the code more brittle, hard to update, and hard to test. If more cases are added in the future, we need to remember to add the appropriate switch cases and handling in tests.

It would be cleaner to pass a function here that creates the Decorator instance we want the AutoEditsRendererManager instance to use. So something like this:

```
new AutoEditsRendererManager(
   (editor: vscode.TextEditor) => new DefaultDecorator(editor)
)
```

And then in `manager.ts`:

```
export class AutoEditsRendererManager implements vscode.Disposable {

    constructor(private createDecorator: (editor: vscode.TextEditor) => AutoeditsDecorator) { ... }

    public async showEdit(options: AutoEditsManagerOptions): Promise<void> {
        ...
        this.activeEdit = {
            uri: options.document.uri.toString(),
            range: options.range,
            prediction: options.prediction,
            decorator: this.createDecorator(editor),
        }
        ...
    }

```

2024-11-21 02:01 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer/decorators/base.ts
> +export interface AutoeditsDecorator extends vscode.Disposable {
Nice Insight !!
`clearDecorations` and `dispose` were coupled and `dispose` should anyways clear the decorations. 
Added in the documentation that each decorator instance should be used only for one decoration and disposed after the decoration is used, and we should clear the decoration on dispose.

Does the updated implementation look okay ?

2024-11-21 02:01 UTC, hitesh-1997 commented on vscode/src/autoedits/autoedits-provider.ts
> +            DecorationStrategyIdentifier.DefaultDecorator
That's a good insight. Modified the changes as per suggestion !!

2024-11-21 22:00 UTC, beyang commented on vscode/src/autoedits/renderer/decorators/base.ts
> + *   decorator.clearDecorations();
```suggestion
```
This should be removed, right?

2024-11-21 22:01 UTC, beyang approved these changes
Please address the one remaining change, otherwise LGTM!

2024-11-22 04:29 UTC, valerybugakov commented on vscode/src/autoedits/renderer/decorators/base.ts
> + *   decorator.clearDecorations();
Removing this in my PR: https://github.com/sourcegraph/cody/pull/6172

2024-11-22 04:30 UTC, valerybugakov commented
I'll merge this one to merge [my follow-up PR](https://github.com/sourcegraph/cody/pull/6172) into the main branch. It will be less risky because my PR refactors more logic for which we don't have test coverage yet.

2024-11-22 04:31 UTC, merged