Dist tracing
sourcegraph/cody pull request #6178
Opened 2024-11-22 11:11 UTC by arafatkatze

## Test plan

## Changelog

2024-11-25 09:46 UTC, arafatkatze commented on vscode/webviews/utils/webviewOpenTelemetryService.ts
> +                    [SemanticResourceAttributes.SERVICE_NAME]: 'cody-client',
We need to send traces to the same "service" and in that way both the webview traces and the extension host trace are shown as one in jaegar.

2024-11-25 09:52 UTC, arafatkatze commented on vscode/webviews/chat/Transcript.tsx
> +        const traceparent = `00-${currentSpanContext.traceId}-${
This is taken from [here](https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers) basically I have to pass this around so that in the extension host I can "pick it up " to set the parent trace to be the trace coming from here and that's how you join traces.

2024-11-25 09:59 UTC, arafatkatze commented on vscode/webviews/utils/telemetry.ts
> +export function getTraceparentFromSpanContext(spanContext: SpanContext): string {
This is taken from [here](https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers) basically I have to pass this around so that in the extension host I can "pick it up " to set the parent trace to be the trace coming from here and that's how you join traces.

2024-11-25 10:08 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +
@dominiccooney  Bit confused about what to do here honestly 
 
<img width="1475" alt="Screenshot 2024-11-25 at 2 05 16 PM" src="https://github.com/user-attachments/assets/ddb0d611-f44f-4081-b4ea-d2e75d9882be">

 The span for this looks like what I've shown in this photo. The first top span is a very small part that's in the UX, and everything else is in the extension host. So, basically, the first part is only testing the message passing from the react UI to the extension host. And because of that, it might not even be worth doing tracing on the react side at all, but I've done it anyway because I wanted to check distributed tracing.

2024-11-25 10:12 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +        return context.with(extractedContext, () => {
Adding distributed tracing in chat so now the trace looks like 

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/72bc0a5c-5fe8-4587-9c95-49dba31c5fb1">

This has both UX and extension host stuff together. See related comment

2024-11-25 10:12 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +        return context.with(extractedContext, () => {
@dominiccooney

2024-12-02 13:22 UTC, arafatkatze commented
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/6310b405-4ca2-44de-9259-2bd9f1b3938f">
Sadly there is a weird race condition that the traces don't always "link up" in a way that they should so I don't see some of them

2024-12-03 07:31 UTC, dominiccooney commented on vscode/webviews/Chat.tsx
> +
>  the first part is only testing the message passing from the react UI to the extension host.

2024-12-03 07:35 UTC, dominiccooney commented on vscode/webviews/utils/webviewOpenTelemetryService.ts
> +                    [SemanticResourceAttributes.SERVICE_NAME]: 'cody-client',
Why can't we make the webview and extension be separate? Below you have traces where there's cody-client and zoekt-webserver, why can't we have cody-webview and cody-client and ... etc.? I don't see how it follows that, because they're sent to the same service, they have to have the same name.

2024-12-03 07:47 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +                if (rootChildSpan && isSampled(rootChildSpan) && isContinued(rootChildSpan)) {
The naming conventions in this part could use some improvement because the logic I’m applying here is essential for linking the traces where the root is actually located in the webview. The key idea is that if the root isn’t present in the traces here, I want to measure the child of the root (the trace located in the extension host) and then send that one, as it effectively serves as the ‘root’ in this context. Hopefully, that clarifies things.

2024-12-03 07:54 UTC, dominiccooney requested changes
Some feedback inline.

It is GREAT that we're joining traces across these domains.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/chat/chat-view/ChatController.ts
> +                if (inputText.toString().match(/^\/reset$/)) {
Wouldn't it be simpler to just `inputText.toString() === '/reset'`?

I think it is also fine to lift String.match onto PromptString to make `inputText.match` more succinct for people who do need regexps.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/edit/manager.ts
> +        const getter = {
This carrier/getter thing:

- Is duplicated
- Is weird

So let's add some abstraction so people don't have to read it or deal with it.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/edit/provider.ts
> +            const mySpan = tracer.startSpan('cody.edit.provider.startTask')
`span`, `mySpan` are weak names, use a descriptive name if you must have more than one. Why wouldn't we just add events to the span we are handed?

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/edit/provider.ts
> +            let someTextConsumed = 0
Again, this name is weak. It is unclear, at this point, how "some text consumed" differs from "text consumed".

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/edit/provider.ts
> +                        if (someTextConsumed === 0 && message.text.length > 1) {
Evidently `someTextConsumed` could be a boolean instead of a number.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/edit/provider.ts
> +                        wrapInActiveSpan('cody.edit.provider.complete', async span => {
Do all `wrapInActiveSpans` set `'sampled', true`? If so, consider just making it part of `wrapInActiveSpan`. Or doing whatever you reasonably can to make this less repetitive.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +                console.log('span', span)
Use logging/delete this debug printing

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +                // the child of the root is sampled but root is not and the span is  continued
This comment seems apropos inside the `if` below, but not here.

Also, it reiterates the code. But leaves us mystified as to *why* these things are happening. Focus the comment on that.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +        return getRootChildSpan(spanMap, parentSpan)
Similar to my last feedback, often a nicely constructed loop is more readable than recursion. This is OK, at least it is tail recursive...

2024-12-03 07:54 UTC, dominiccooney commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +            return span
When does this happen? Seems iffy to end up here.

2024-12-03 07:54 UTC, dominiccooney commented on vscode/webviews/Chat.tsx
> +                span.setAttributes({
Is this different to the attributes passed to `startSpan`? If not, why not merge these and make the code more readable and succinct.

2024-12-03 07:55 UTC, arafatkatze commented on vscode/webviews/utils/webviewOpenTelemetryService.ts
> +                    [SemanticResourceAttributes.SERVICE_NAME]: 'cody-client',
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/8fb733e3-f07a-4022-988c-7600d9c532e6">
You are right. I made the fix

2024-12-03 10:06 UTC, arafatkatze commented on vscode/src/chat/chat-view/ChatController.ts
> +                if (inputText.toString().match(/^\/reset$/)) {
ITs the old code so I wanted to maintain consistency but yes I just pulled match in the prompt string.

2024-12-03 10:24 UTC, arafatkatze commented on vscode/webviews/Chat.tsx
> +
Makes sense.

2024-12-03 10:25 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +                if (rootChildSpan && isSampled(rootChildSpan) && isContinued(rootChildSpan)) {
@dominiccooney

2024-12-03 11:03 UTC, arafatkatze commented on vscode/src/edit/provider.ts
> +            const mySpan = tracer.startSpan('cody.edit.provider.startTask')
I wanted a proper time to first token span so I had to keep a span but you are very right, I thought I had fixed this stuff but I hadn't so I cleaned it all up and made it a lot more sensible. 
Apologies for the oversight.

2024-12-03 11:42 UTC, arafatkatze commented on vscode/src/edit/manager.ts
> +        const getter = {
Done

2024-12-03 11:42 UTC, arafatkatze commented on vscode/src/edit/provider.ts
> +            const mySpan = tracer.startSpan('cody.edit.provider.startTask')
<img width="1484" alt="image" src="https://github.com/user-attachments/assets/0da45f3f-0aa5-48bb-8ac3-8db6e18604bf">

2024-12-03 11:43 UTC, arafatkatze commented on vscode/src/edit/provider.ts
> +            let someTextConsumed = 0
Sorry lots of ugliness in this file but I cleaned it all up now

2024-12-03 11:43 UTC, arafatkatze commented on vscode/src/edit/provider.ts
> +                        if (someTextConsumed === 0 && message.text.length > 1) {
Fixed

2024-12-03 11:45 UTC, arafatkatze commented on vscode/src/edit/provider.ts
> +                        wrapInActiveSpan('cody.edit.provider.complete', async span => {
So I changed that here but basically you only do `sampled: true` for the[ root span](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/services/open-telemetry/CodyTraceExport.ts?L83:10-83:23) so that all the other spans are put under it. Perhaps I can change the attribute to `root: true` and that should be a much more sensible naming.

2024-12-03 11:45 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +                // the child of the root is sampled but root is not and the span is  continued
Fixed all this an added a much better comment

2024-12-03 11:53 UTC, arafatkatze commented on vscode/src/services/open-telemetry/CodyTraceExport.ts
> +            return span
Fixed an added better commentary

2024-12-04 23:17 UTC, dominiccooney approved these changes
Looks good, nice cleanup.

Can you remove the questions and concerns from the PR description? (If you still have questions and concerns, let's go through those.)

2024-12-04 23:17 UTC, dominiccooney commented on lib/shared/src/prompt/prompt-string.ts
> +        return internal_toString(this).match(regexp)
Ideally, we should lift the results of the matches so they're also PromptStrings. Could you add a TODO to do that?

2024-12-05 02:01 UTC, arafatkatze commented
> Can you remove the questions and concerns from the PR description? (If you still have questions and concerns, let's go through those.)

Removed

2024-12-05 02:02 UTC, merged