[WIP] feat/cody: Prevent Enterprise users from logging into dotcom/PLG (CODY-4295)
sourcegraph/cody pull request #6182
Opened 2024-11-23 01:19 UTC by julialeex

This PR does [Create mechanism to kick PLG logins/signup for user with email domains that below to enterprise customers](https://linear.app/sourcegraph/issue/CODY-4295/create-mechanism-to-kick-plg-loginssignup-for-user-with-email-domains).

**Problem:** We want to prevent enterprise customers from logging into PLG/dotcom

This PR checks whether the user is an enterprise customer using `UserShouldUseEnterprise`, and whether the user tries to login into PLG/dotom through `isDotCom`, and logs the enterprise user out of PLG logins.

**Things this PR does:**

- Add a new field `userShouldUseEnterprise: boolean`
- Sign out if the user should use enterprise and is logged into PLG
- Tests

## Test plan
**Test with debugger**
1. An enterprise user gets logged out for PLG/dotcom logins
2. An enterprise user that is already logged into PLG/dotcom gets logged out

**E2E test** 
Added test `test enterprise customers should get logged out for dotcomUrl` in `auth.test.ts`

## Changelog
**TODO**

2024-11-26 00:32 UTC, jamesmcnamara requested changes
Yeah I definitely gave you some bad advice here :) I left some comments in line but basically, we should: 
- [x] Add a direct call to check the client config singleton from the auth flow. 
- [x] Show an error notification when the flag is false
- [x] Fix the tests so that we only set userShouldUseEnterprise to true in tests where we want it

2024-11-26 00:32 UTC, jamesmcnamara commented on vscode/src/chat/chat-view/ChatController.ts
> +            }
I take your point on this now that I've seen it in action, and I think I gave you bad advice. The flash of the logged in screen before we're logged out looks janky and this code path is hard to follow for the next developer.

I think you're right that we should directly refresh this client config as part of the auth validation flow and stop the login with an error notification. I expect you'll need to add some methods to ClientConfigSingleton to achieve this.

2024-11-26 00:32 UTC, jamesmcnamara commented on vscode/test/e2e/auth.test.ts
> +})('requires a valid auth token and allows logouts', async ({ page, sidebar, nap }) => {
```suggestion
})('requires a valid auth token and allows logouts', async ({ page, sidebar }) => {
```

2024-11-26 01:01 UTC, julialeex commented on vscode/src/chat/chat-view/ChatController.ts
> +            }
1. To summarize, we want to add the logic to the auth validation flow, before we log in (like how we were checking userInfo in in the auth validation flow before)? 
> The flash of the logged in screen before we're logged out looks janky
2. I thought we have to log in first because of this comment on the [ticket](https://linear.app/sourcegraph/issue/CODY-4295/create-mechanism-to-kick-plg-loginssignup-for-user-with-email-domains#comment-2aee6292)

2024-11-26 01:09 UTC, jamesmcnamara commented on vscode/src/chat/chat-view/ChatController.ts
> +            }
1. Yes exactly.
2. I think that's more trying to capture that if a user is already logged in, and we refresh the client config and they are now supposed to be on an enterprise account, we should log them out. Which is a good point that that is another TODO.

2024-11-26 01:11 UTC, julialeex commented on vscode/src/chat/chat-view/ChatController.ts
> +            }
Got it, thanks for the clarification! Will update the code

2024-11-26 18:24 UTC, julialeex commented on vscode/src/chat/chat-view/ChatController.ts
> +            }
1. I read the code for a bit more yesterday, and found that clientConfig is not populated until the user is authenticated (see [code1](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/sourcegraph-api/clientConfig.ts?L77) and [code2](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/sourcegraph-api/graphql/client.ts?L1575-1578))
2. Because of what I found in 1), I double checked the feature requirements in the [ticket](https://linear.app/sourcegraph/issue/CODY-4295/create-mechanism-to-kick-plg-loginssignup-for-user-with-email-domains#comment-868d5cc5) and it turns out we do want to log in first and then log the user out. If this is true, I have a TODO of adding the error message after we log the user out

2024-12-04 20:21 UTC, jamesmcnamara requested changes
Looking good! The blockers are just not running the auth check unless it's dotcom and a test for logging out if the flag updates. Let me know if I can help with that!

2024-12-04 20:21 UTC, jamesmcnamara commented on vscode/test/e2e/auth.test.ts
> +    await sidebar!.getByRole('button', { name: 'Sign In' }).click()
Great test! The risk with this is that the signin code updates a lot (or at least is in the process of a big migration), so any change to that flow will require this test to be updated as well. I think we can just update the sidebar signin like 
```ts
interface SidebarSigninOptions {
    disableNotifications: boolean
    skipAssertions: boolean
}

// Sign into Cody with valid auth from the sidebar
export const sidebarSignin = async (
    page: Page,
    sidebar: Frame | null,
    options: Partial<SidebarSigninOptions> = {}
): Promise<void> => {
...
}
```
And then you can just use the standard signin flow without asserting that it works.

2024-12-04 20:21 UTC, jamesmcnamara commented on vscode/test/e2e/auth.test.ts
> +})
It looks like we're still missing a test that checks when the user is signed in and then we update the userShouldUseEnterprise to true and we test that they're logged out.

2024-12-04 21:07 UTC, julialeex commented on vscode/src/auth/auth.ts
> +
This is a great point, nice catch!

2024-12-04 22:00 UTC, julialeex commented on lib/shared/src/auth/types.ts
> +    userEnterprise?: string
This is a great suggestion and I did miss some places that are checking showNetworkError and showInvalidAccessTokenError! Since this is a refactor on the `UnauthenticatedAuthStatus`, would it be better to move the refactor to another PR, merge the refactor PR before this PR? This way, the current PR can focus just on the feature implementation.

2024-12-04 22:05 UTC, jamesmcnamara commented on lib/shared/src/auth/types.ts
> +    userEnterprise?: string
I don't think the refactor will be big enough to really overshadow this PR. It would have been more complicated if JetBrains or Eclipse used this value, but a quick grep seems to show that it doesn't.

I'd do it in this PR and if we think it's too big, we can split it out then.

2024-12-06 06:46 UTC, julialeex commented on vscode/test/e2e/auth.test.ts
> +})
Added the test!

2024-12-06 22:19 UTC, jamesmcnamara approved these changes
Still some cleanup but this works! Great stuff!

2024-12-06 22:19 UTC, jamesmcnamara commented on vscode/src/auth/auth.ts
> +    }
```suggestion
    if (authStatus?.error) {
        await vscode.window.showErrorMessage(getAuthErrorMessage(authStatus.error).message)
    }
```

2024-12-06 22:19 UTC, jamesmcnamara commented on vscode/src/services/AuthProvider.ts
> +                    })
```suggestion
                    abortableOperation(async (_, signal) => 
                        this.validateAndUpdateAuthStatus(await currentResolvedConfig(), signal)
                    )
```

2024-12-06 22:19 UTC, jamesmcnamara commented on vscode/webviews/App.tsx
> +                            config.authStatus.error?.type === 'enterprise-user-logged-into-dotcom') && (
```suggestion
                        (config.authStatus.error) && (
```

2024-12-06 22:19 UTC, jamesmcnamara commented on vscode/webviews/components/AuthenticationErrorBanner.tsx
> +            )}
```suggestion
            <span className="tw-flex-1 tw-text-xs">
                {errorMsg.title && (
                    <>
                        <span className="tw-font-bold">{errorMsg.title}</span> &mdash;
                    </>
                )}
                {errorMsg.message}
            </span>
```

And then just add 
```ts
const errorMsg = getAuthErrorMessage(error)
```
to the component.

2024-12-16 02:29 UTC, dominiccooney approved these changes
This looks good to me.

We should create some testing accounts that will trigger this, and have QA test this continually in JetBrains and VSCode (...at least until we can add an automated JetBrains test.)

2024-12-16 09:26 UTC, pkukielka commented on agent/src/auth.test.ts
> +            await new Promise(resolve => setTimeout(resolve, 500))
That looks suspicious. Why is that needed?

2024-12-17 02:02 UTC, dominiccooney approved these changes
Still LGTM.

Now that the authStatus/clientConfig are decoupled like that, do we need the timeouts in the tests?

2024-12-17 02:04 UTC, merged