feat(audoedit): inline renderer POC
sourcegraph/cody pull request #6214
Opened 2024-11-28 13:34 UTC by valerybugakov

- Implements an experimental autoedits inline render POC. It shows autoedit suggestions using the inline completion item provider (used for autocomplete) and line decorations. 
- I plan to improve this initial version with multiple smaller PR addressing one use case at a time to make the review easier. The main goal of the POC was to verify the number of cases we can cover with this approach, uncover unknown blockers, and show how it looks in practice.
- [Slack thread with more details and screenshots](https://sourcegraph.slack.com/archives/C07F8LLKE06/p1732793588108939).
- Part of [CODY-4413: Inline-renderer: support cases without suggested new lines](https://linear.app/sourcegraph/issue/CODY-4413/inline-renderer-support-cases-without-suggested-new-lines)
- Acceptance and disposal will be handled in follow up PRs separately. The current version relies on the logic of the default renderer. 
- Known bugs will be added to [the Linear project](https://linear.app/sourcegraph/project/cody-autoedits-dogfooding-to-ga-0a577390780d/issues) and tackled as follow-ups too.

## Test plan

- CI 
- Manual testing using cody-eval repo: 
    - Add `"cody.experimental.autoedits.inline-renderer": true,` to your `settings.json` to enable the experimental renderer.
    - `code-matching-eval/edits_experiments/examples/renderer-testing-examples`. Request suggestions from the server at the places where an autoedit is expected and observe that it's rendered somewhat correctly.

2024-12-09 13:27 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer/decorators/base.ts
> +    modifiedLineNumber: number
should we rename it to `addedLineNumber` ? 
Since we differentiate between `AddedLineInfo`, `RemovedLineInfo` and `ModifiedLineInfo`, Naming it modified it confusing for added lines

2024-12-09 14:28 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer/decorators/inline-diff-decorator.ts
> +    public clearDecorations(): void {
should this be `private` since at every dispose we clear the decorations and dont expose this method

2024-12-09 14:31 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer/decorators/inline-diff-decorator.ts
> +            // textDecoration: 'line-through',
should we initialize them while defining them, i.e.  `private readonly addedTextDecorationType `

2024-12-09 14:36 UTC, hitesh-1997 commented on vscode/src/autoedits/autoedits-provider.ts
> +            .get<boolean>('cody.experimental.autoedits.inline-renderer', false)
Instead of creating sperate configurations, does it make sense to define a single variable. We can set it to `default` or `inline`.

2024-12-09 14:43 UTC, hitesh-1997 commented on vscode/src/autoedits/renderer/inline-manager.ts
> +function getChangedTextAfterCursor(
can we add some test case for the function.

2024-12-09 14:44 UTC, hitesh-1997 requested changes
Most of the changes look good to me, Although there is some duplication, should be okay for now since this is still experimental.
Added examples where I had some issues with the [current renderer](https://sourcegraph.slack.com/archives/C07F8LLKE06/p1733753352917229?thread_ts=1732793588.108939&cid=C07F8LLKE06).

2024-12-10 00:39 UTC, hitesh-1997 approved these changes

2024-12-11 04:49 UTC, valerybugakov commented on vscode/src/autoedits/renderer/inline-manager.ts
> +function getChangedTextAfterCursor(
Added in a follow up 👍

2024-12-11 05:20 UTC, merged