Add bundle size limits and tracking to Github CLI
sourcegraph/cody pull request #6222
Opened 2024-11-29 09:31 UTC by arafatkatze

Add size limit enforcement and historical tracking for extension bundles to prevent unexpected size increases. This helps maintain performance and download speeds for users.

## Test plan
- Actually run the Github Actions CI 

## Changelog

2024-12-09 18:32 UTC, kalanchan commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
@sourcegraph/security-code-review can I get a review here?

Ideally I don't think we should be storing the service account keys locally, what is the risk here? 

can we use something like https://github.com/google-github-actions/auth instead

2024-12-09 23:36 UTC, kalanchan commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
@andreeleuterio

2024-12-10 00:05 UTC, andreeleuterio commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
yes, thanks for the great callour @kalanchan. You can find example [here](https://github.com/google-github-actions/auth/blob/main/docs/EXAMPLES.md#examples-for-authenticating-to-google-cloud-from-github-actions) and GCP workload identity [here](https://github.com/google-github-actions/auth?tab=readme-ov-file#setup). @arafatkatze lmk if you have trouble here.

2024-12-10 07:57 UTC, arafatkatze commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
Thanks for the super important callout. I fixed this and tested it too.

2024-12-10 07:57 UTC, arafatkatze commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
@kalanchan @andreeleuterio Can you take a look again?

2024-12-10 14:46 UTC, andreeleuterio commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
@arafatkatze not quite. You are using the correct gcloud auth action, but with the [Service Account Key JSON](https://github.com/google-github-actions/auth?tab=readme-ov-file#service-account-key-json) setup. We want the  [Direct Workload Identity Federation option](https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation). From what I see in the instructions, just get Entitle permissions for the GCP project in question and you should be able to follow the steps. If you run into issues let me know.

2024-12-12 18:51 UTC, andreeleuterio requested changes

2024-12-12 18:51 UTC, andreeleuterio commented on .github/workflows/bundle-size-tracker.yaml
> +  id-token: write
@arafatkatze can we remove them from here now?

2024-12-12 18:51 UTC, andreeleuterio commented on .github/workflows/vscode-insiders-release.yml
> +          credentials_json: ${{ secrets.GCP_BQ_CREDENTIALS }}
remember to update it here as well 😅

2024-12-12 18:52 UTC, arafatkatze commented on .github/workflows/vscode-insiders-release.yml
> +          credentials_json: ${{ secrets.GCP_BQ_CREDENTIALS }}
Done

2024-12-12 18:54 UTC, arafatkatze commented on .github/workflows/bundle-size-tracker.yaml
> +  id-token: write
No we need both the workflow level and the job level

2024-12-12 18:59 UTC, arafatkatze commented on .github/workflows/vscode-insiders-release.yml
> +          echo '${{ secrets.GCP_BQ_CREDENTIALS }}' > gcloud-service-key.json
Thanks to help from @andreeleuterio we are using [Direct Workload Identity Federation option](https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation).

2024-12-12 19:00 UTC, arafatkatze commented on .github/workflows/bundle-size-tracker.yaml
> +  id-token: write
No you are right, I got rid of it.

2024-12-13 18:52 UTC, andreeleuterio approved these changes

2024-12-13 19:52 UTC, merged