release: changelog generator + releaseregistry registration
sourcegraph/cody pull request #6243
Opened 2024-12-03 00:52 UTC by Chickensoupwithrice

This PR adds two more steps to the GHA release pipeline:
- Generate a Changelog, and PR it
- Register the release on the releaseregistry

Adding Cody to the releaseregistry allows us to integrate the changelog through that mechanism, but since no data is currently backported, we're using Git to determine previous release commit hashes in order to generate the new changelog.

## Test plan
Run the CI pipeline 😬

## Changelog
N/A

2024-12-09 14:43 UTC, jdpleiness reviewed
Looks like there are still some merge conflicts and CI is still running for some reason? 🤔

2024-12-09 14:43 UTC, jdpleiness commented on .github/workflows/vscode-stable-release.yml
> +          mv raw-changelog.md vscode/CHANGELOG.md
🤔 ?

2024-12-09 14:43 UTC, jdpleiness commented on .github/workflows/vscode-stable-release.yml
> +              "name": "cody-vscode",
Do we have this type in the release registry already?

2024-12-09 16:59 UTC, Chickensoupwithrice commented on .github/workflows/vscode-stable-release.yml
> +              "name": "cody-vscode",
Nope, it's new!

2024-12-09 18:32 UTC, Chickensoupwithrice commented on .github/workflows/vscode-stable-release.yml
> +          mv raw-changelog.md vscode/CHANGELOG.md
Changelog generator doesn't do "prepend" to file for existing changelogs. We're doing that part by hand in the shell file.

2024-12-09 20:27 UTC, Chickensoupwithrice commented
Yeah, CI on this repo is questionable, it's not expected to pass generally.

2024-12-12 05:46 UTC, DaedalusG commented on .github/workflows/vscode-stable-release.yml
> +          PREV_TAG=$( git tag --sort=-v:refname | grep '^vscode-v' |  head -n 2 | tail -n 1)
Does this assume we've already registered our new release version? i.e. 

vscode-v1.2.3
vscode-v1.2.2
vscode-v1.2.1
This would return 'vscode-v1.2.2'

Why are we selecting that one?

2024-12-12 06:22 UTC, kalanchan commented
will review this tomorrow, thanks for all the progress here my @sourcegraph/release boys 🫡

2024-12-13 22:42 UTC, kalanchan requested changes
thank you so much @Chickensoupwithrice !!!! I left some comments, I think we should pull the changelog generator into a separate workflow. 

i'll set up some time to pair with you to land this, but the direction is really good!

2024-12-13 22:42 UTC, kalanchan commented on .github/workflows/vscode-stable-release.yml
> +          mv raw-changelog.md vscode/CHANGELOG.md
can you provide a sample of what `raw-changelog.md` will look like? 

maybe instead of appending the entire `vscode/changelog.md` into `raw-changelog`, we can find a spot within `vscode/changelog.md` and append under it 

Example, this is what the current first 20 lines of `vscode/changelog.md` looks like:

```
# Changelog

This is a log of all notable changes to Cody for VS Code.

## Unreleased

### Added

### Fixed

### Changed

### Uncategorized

## 1.50.0

### Added
- Webviews: add new CTA for Sourcegraph Teams  [pull/6245](https://github.com/sourcegraph/cody/pull/6245)
- "Explain command" in context (existing conversation)  [pull/5986](https://github.com/sourcegraph/cody/pull/5986)
```

depending on what `raw-changelog.md` looks like, we could just append it right under `### uncategorized` using
```
awk '/### Uncategorized/{if (!found) {print; system("cat raw_changelog.md"); found=1; next}} 1' vscode/CHANGELOG.md > temp_changelog.md

# Replace original file with new content
mv temp_changelog.md vscode/CHANGELOG.md
```

maybe we can pair on this to be clear!

2024-12-13 22:42 UTC, kalanchan commented on .github/workflows/vscode-stable-release.yml
> +            --base main --head release/vscode-v$EXT_VERSION
hmm maybe we should pull this out as it's own separate workflow

2024-12-13 22:47 UTC, Chickensoupwithrice commented on .github/workflows/vscode-stable-release.yml
> +          PREV_TAG=$( git tag --sort=-v:refname | grep '^vscode-v' |  head -n 2 | tail -n 1)
Hmm, for me this returns `vscode-v1.46.0` which is currently the latest release, which is what we're trying to get. Once the releaseregistry is hooked up and has a bit of data, we can switch to using that

2024-12-13 22:47 UTC, Chickensoupwithrice commented on .github/workflows/vscode-stable-release.yml
> +          PREV_TAG=$( git tag --sort=-v:refname | grep '^vscode-v' |  head -n 2 | tail -n 1)
The list, without taking the second element exclusively, on my machine is:
<img width="924" alt="image" src="https://github.com/user-attachments/assets/49a4c38f-1be0-48bd-a434-fd4e4fa6d3cf" />

2024-12-13 22:48 UTC, Chickensoupwithrice commented on .github/workflows/vscode-stable-release.yml
> +          export RELEASE_LATEST_COMMIT=$GITHUB_SHA
Yep!

2024-12-13 22:48 UTC, Chickensoupwithrice commented on .github/workflows/vscode-stable-release.yml
> +            --base main --head release/vscode-v$EXT_VERSION
Hmmm, I hadn't considered that. Could be a good idea!

2025-01-02 22:38 UTC, kalanchan reviewed
thank you! almost there, I want to see what the end results look like before approving. Will find some time to pair :)

2025-01-02 22:38 UTC, kalanchan commented on .github/workflows/generate-changelog.yml
> +        description: 'Branch to generate the changlog for'
```suggestion
        description: 'Branch to generate the changelog for'
```

2025-01-02 22:38 UTC, kalanchan commented on .github/workflows/generate-changelog.yml
> +          CHANGELOG_CATEGORY_ACCEPTLIST: "added,changed,fixed"
if we left this as empty, it will group all categories in the PRs?

2025-01-02 22:38 UTC, kalanchan commented on .github/workflows/vscode-stable-release.yml
> +      - name: Generate changelog
I think we can remove this step now right, and have the generate changelog manually be run

2025-01-03 16:02 UTC, Chickensoupwithrice commented on .github/workflows/generate-changelog.yml
> +          CHANGELOG_CATEGORY_ACCEPTLIST: "added,changed,fixed"
I took this from `run_local.sh` but reading through the code I'm not convinced it actually does anything? 🤔  
The only place it exists is in `run_local.sh`

2025-01-15 22:04 UTC, Chickensoupwithrice commented
Closing in favor of https://github.com/sourcegraph/cody/pull/6659

2025-01-15 22:04 UTC, closed without merging