feat(prompt-editor): Add new ProseMirror-based implementation
sourcegraph/cody pull request #6272
Opened 2024-12-06 14:52 UTC by fkling

Pqrogress

Refactor

Progress

Better encapsulation

Refactor

Added react hooks abstraction layer

Progress

Finish api and implementation

Refector/rename mention view

Use floating ui to manage mentions menu position

Support missing behavior;add comments; add tests

Update dependencies

Run biome

Cleanup

Add separate story

fix mentions menu

## Test plan

## Changelog

2024-12-11 09:13 UTC, dominiccooney requested changes
Some feedback inline. I got 2/3 of the way through this but it is huge so let me send some feedback and look at the tests in a future iteration.

Let's be more helpful with comments and more consistent with lints.

A number of questions inline about the details of the triggering, etc.

2024-12-11 09:13 UTC, dominiccooney commented on lib/prompt-editor/src/v2/plugins/atMention.ts
> +                    // Trigger on @, at beginning or after space
Would be great to test this with multiple lines.

Also, today I can write multiple at-mentions without a space between them (one is inserted, but is not required...)

Also, today I can go to the middle of my composition and start typing at-mentions, but the terminal `$` is going to stop that (...unless it is interpreted as a multiline regex, in which case I can type them at the end of lines but not in the middle 🤷 )

2024-12-11 09:13 UTC, dominiccooney commented on lib/prompt-editor/src/v2/plugins/placeholder.ts
> +            view.dom.removeAttribute('data-placeholder')
Er... if I delete the text, shouldn't the placeholder come back? That's how the platform's placeholders work.

Or are these plugins pure functions or something, and ProseMirror is going to recreate the element and its `data-placeholder`?

2024-12-11 09:13 UTC, dominiccooney commented on lib/prompt-editor/src/v2/plugins/readonly.ts
> +                if (tr.getMeta(readonlyPluginKey)) {
Let's simplify this to `return tr.getMeta(readonlyPluginKey) || value`

Same above for the placeholderPlugin.

2024-12-11 09:13 UTC, dominiccooney commented on lib/prompt-editor/src/v2/promptInput-react.ts
> +                        // otherwise the editor's Shift-Enter keybinding will not be triggered.
...wouldn't that simply be the defaultPrevented doing its job? Or is the onEnterKey handler messing with focus or whatever...

2024-12-11 09:13 UTC, dominiccooney commented on lib/prompt-editor/src/v2/promptInput-react.ts
> +                if (focus) {
Lift `editor.send` and use a ternary.

2024-12-11 09:30 UTC, fkling commented on lib/prompt-editor/src/v2/MentionsMenu.module.css
> +    width: clamp(300px, 65vw, 440px);
I've copied this from the current implementation, so probably not.
However this new implementation uses a separate plugin for popover management, which includes logic to resize the popover to the available width of the viewport (which I assume is just the sidebar in an IDE).

2024-12-11 10:01 UTC, fkling commented on lib/prompt-editor/src/v2/promptInput-react.ts
> +                        // otherwise the editor's Shift-Enter keybinding will not be triggered.
No focus issue, I'll have to revisit this because it didn't actually work when I recorded the video.

2024-12-12 06:10 UTC, thenamankumar commented on lib/prompt-editor/src/v2/MentionView.tsx
> +function tooltipForContextItem(item: SerializedContextItem): string | undefined {
For future, we should make the context item define its tooltip.

2024-12-12 15:16 UTC, fkling commented on lib/prompt-editor/src/v2/MentionsMenu.tsx
> +        // This statement was added to prevent biome from flagging that selectedIndex is not used.
Seems like it's possible to ignore an individual dependency with biome: https://biomejs.dev/linter/rules/use-exhaustive-dependencies/#ignoring-a-specific-dependency

2024-12-13 14:53 UTC, fkling commented on lib/prompt-editor/src/v2/plugins/atMention.ts
> + * @param appendSpaceIfNecessary Whether to append a space after the node if necessary
FWIW I've removed that option since the function is called only in a single place that only passes `true`.

2024-12-13 16:47 UTC, fkling commented on lib/prompt-editor/src/v2/plugins/readonly.ts
> +                if (tr.getMeta(readonlyPluginKey)) {
Actually the condition was incorrect anyway.

2024-12-16 11:24 UTC, fkling commented on lib/prompt-editor/src/v2/plugins/atMention.ts
> +                            /\s{2,}/.test(tr.doc.textBetween(decoration.from, decoration.to))
FWIW, we can tweak the rules for when we want to remove the mention. We can also leave it in place and only remove it when the cursor moves outside or ESC is pressed. For now I changed it to replicate Linear's behavior, which removes it after three consecutive spaces.

2024-12-16 14:00 UTC, fkling commented on lib/prompt-editor/src/v2/promptInput-react.ts
> +                        // otherwise the editor's Shift-Enter keybinding will not be triggered.
It seems this was an issue with how responsive mode simulates a mobile device. shift-enter works just fine in normal desktop mode.

2024-12-20 15:28 UTC, vovakulikov approved these changes
I tested this manually and didn't find any big problems so approve to unblock. I tried the case when I switched on and then switched back to the older version and something is definitely going on there, some messages aren't picked up right with lexical probably because of some shifts in message schema (lexical state) 

But this problem is ok for now, I suppose we still have to live with the exical state for a while in Cody Agent lexical state serialization. (Not this PR problem)

2024-12-20 15:28 UTC, vovakulikov commented on lib/prompt-editor/src/index.ts
> +export { PromptEditor as PromptEditorV2 } from './v2/PromptEditor'
We probably should re-export this later independently so I could publish this package without a big amount of Cody Agent dependencies in order to use it in the Sourcegraph prompt library (can do this in the follow up PR though)

2024-12-20 15:28 UTC, vovakulikov commented on lib/prompt-editor/src/v2/MentionsMenu.module.css
> +    width: clamp(300px, 65vw, 440px);
Yeah, the old version uses radix popover which doesn't set any strict boundaries for popover elements (like max-width, max-height) and also does not shift popover properly if there is no enough space between target and viewport boundaries, floating UI should solve the problem

2024-12-21 13:09 UTC, merged