feat(audoedit): shrink autoedits on document suffix match
sourcegraph/cody pull request #6343
Opened 2024-12-13 08:46 UTC by valerybugakov

- Fixes an issue where autoedits were hidden if the last lines of the prediction matched the document's suffix. The updated logic trims the prediction to avoid suggesting duplicate code. This change ensures autoedit suggestions are displayed even when duplicate code exists at the end of the prediction (we now manually remove it) while allowing changes to previous lines to be shown.  
- For example, in the screenshot, the first line is modified by adding a new `email` argument. Previously, this suggestion was often hidden because the model included a duplicate `self.email = email` line in its prediction.
- Part of [CODY-4412: Implement experimental inline renderer](https://linear.app/sourcegraph/issue/CODY-4412/implement-experimental-inline-renderer)
- Closes [CODY-4523: Renderer: do not fully hide suggestions with code partially matching document suffix](https://linear.app/sourcegraph/issue/CODY-4523/renderer-do-not-fully-hide-suggestions-with-code-partially-matching)

<img width="485" alt="Screenshot 2024-12-13 at 16 39 31" src="https://github.com/user-attachments/assets/a2dd4cec-afea-4f7b-ac9f-c3385306a064" />

## Test plan

1. CI
2. New unit tests
3. Manual testing in the cody-chat-eval repo, specifically with `codium-add-email-field-autoedits.py`. See the exact cursor position to repro on the attached screenshots above.

## Changelog

2024-12-13 13:19 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +export function shrinkPredictionUntilSuffix(
nit: should we move this function to utils instead of creating a new file.

2024-12-13 13:20 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.test.ts
> +            `const a = 1
can we use `dedent` at all the places to ensure readability

2024-12-13 13:29 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.test.ts
> +    })
Can we restore the default test cases here. i.e. If the prediction exactly matches with the suffix, then the prediction should be empty.

2024-12-13 13:31 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +    const suffixLines = suffix.split(newLineChar)
can we use `lines` function here from `text-completions` ?

2024-12-13 13:39 UTC, hitesh-1997 requested changes
Added some minor comments.

2024-12-16 02:08 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.test.ts
> +    })
Added the case back. The behavior is different now. The function always returns the truncated prediction. If it equals to the text to rewrite we just return null early.

2024-12-16 02:12 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.ts
> +export function shrinkPredictionUntilSuffix(
Extracting helpers into separate files makes finding them and their tests easier using cmd+P + fuzzy search, wdyt?

2024-12-16 09:05 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +export function shrinkPredictionUntilSuffix(
sure, that works too

2024-12-16 09:10 UTC, hitesh-1997 approved these changes

2024-12-17 02:51 UTC, merged