fix(autoedit): fix shrink prediction logic
sourcegraph/cody pull request #6404
Opened 2024-12-18 04:34 UTC by valerybugakov

- Follow up for https://github.com/sourcegraph/cody/pull/6386

## Test plan

1. CI
2. New unit tests
3. Manually tested on cody-chat-eval examples

2024-12-18 07:07 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
>      const suffix = codeToReplaceData.suffixInArea + codeToReplaceData.suffixAfterArea
Should we use the platform to determine the newline in case prediction is single line.
I think better than prediction would be `codeToRewrite` to determine the new line character instead of prediction since prediction from the model can be single line if it deletes multiple lines from the code to rewrite.

2024-12-18 07:08 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +    const newLineChar = getNewLineChar(value)
can we resuse the same `newline` already computed in the function above.

2024-12-18 07:09 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +    const predictionLines = lines(stripLastEmptyLineIfExists(prediction))
can we add a comment why do we want to strip the last empty line

2024-12-18 07:13 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
Why are we only checking if `predictionSlice[j].startsWith(suffixSlice[j])`. If we want to see that prediction lines matches with suffix, shouldn't we check `===` condition

2024-12-18 07:15 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +                matches = true
I noticed we reversed the conditions and making `matches=true` inside if condition and have `break` after that.
This would lead to `matches=true` even if a single line matches, previous condition looked okay to me

2024-12-18 07:16 UTC, hitesh-1997 requested changes
I had confusion in some statements, added comments to clarify

2024-12-18 07:22 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
See the test case with `self.email = email` in `vscode/src/autoedits/shrink-prediction.test.ts`. I want to catch cases where something is added to the end of the suffix line, too.

2024-12-18 07:25 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.ts
> +    const predictionLines = lines(stripLastEmptyLineIfExists(prediction))
Added 👍

2024-12-18 09:09 UTC, hitesh-1997 requested changes
Added test case which would have issue with the current logic, please check [this commit](https://github.com/sourcegraph/cody/pull/6404/commits/e159e229c5b2b67e3876c9cbeab542d18f5b4bc5)

2024-12-18 16:34 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
I don't think that should be the expectation since suffix `self.email = ` and  not `self.email = email` which is in the prediction. There is risk of prediction getting trimmed just because suffix prefixed with prediction.

I added a test case [here](https://github.com/sourcegraph/cody/pull/6404/files#diff-26cd4dc38a058c50bc3caf336852c66a5348dc994e942d17ba5dce1dba894b8cR11) which will have issues because `.startsWith` logic just because the suffix had bunch of empty lines below and `prediction` added lines at the same indentation level.

(please note that I had to turn off `trim_trailing_whitespace = false` in `.editorconfig` in our code to add trailing spaces in the code, so if we `git pull` and save, the trailing space would get trimmed and test case might not work, so please turn off this settting before git pull)

2024-12-19 03:10 UTC, valerybugakov commented
The partial match logic is giving us too many false positives. Even after fixing the test case you pushed (thanks for that!), I found this behavior popping up in several places during manual testing. So, I reverted the logic back to an exact match.

Could we handle this at the model layer? Is there a way to nudge the model to only make changes within the code-to-rewrite block? I guess this issue comes from the training dataset, where suffix changes sometimes get duplicated in the updated code section. Could it be the case?

You can check the test case with `self.email = email` to see an example. Even though this line is part of the suffix, the model still modifies it and includes it in the response. Ideally, it should only return new line insertions.

2024-12-19 03:12 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
The partial match logic is giving us too many false positives. Even after fixing the test case you pushed (thanks for that!), I found this behavior popping up in several places during manual testing. So, I reverted the logic back to an exact match.

Could we handle this at the model layer? Is there a way to nudge the model to only make changes within the code-to-rewrite block? I guess this issue comes from the training dataset, where suffix changes sometimes get duplicated in the updated code section. Could it be the case?

You can check the test case with `self.email = email` to see an example. Even though this line is part of the suffix, the model still modifies it and includes it in the response. Ideally, it should only return new line insertions.

2024-12-19 03:22 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
The goal of the shrink-until-suffix logic was to ensure we still show parts of suggestions that are relevant, even if they only partially match the suffix. Previously, we had [logic using `startsWith()`](https://github.com/sourcegraph/cody/commit/de7d29e3a1c7b9b3fd62b569fa410a69fc633760#diff-bdee4431065cdb239f1b7b99fa0b6b5d0d1729f6a48ff8bfe630539d62da761fL81) that would hide the entire suggestion if its last lines were partially present in the document. Let’s chat about the best way to solve this over Zoom.

2024-12-19 03:28 UTC, valerybugakov commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
I traced the addition of this logic to the feature, which comes from [this PR](https://github.com/sourcegraph/cody/pull/5956), which does not give much context for this specific change. I wonder how critical was the `starsWith()` bit back then when it was introduced and why didn't we opt-in for the exact match instead.

2024-12-19 08:14 UTC, hitesh-1997 commented on vscode/src/autoedits/shrink-prediction.ts
> +                (suffixSlice[j].length > 0 && predictionSlice[j].startsWith(suffixSlice[j])) ||
The reasoning behind the old logic was that, if model includes the suffix code, than they can only be new added lines from the code to rewrite, and I used `startsWith` there because we were not doing the line level comparison, but the whole suffix is the whole suffix in the file.
But the logic earlier also had its flaws and not very well though, but it mitigated some issues I encountered while manual testing.
I think it would be okay to just let the model output wrong predictions and we can figure out the severity from the logs.

2024-12-25 10:14 UTC, hitesh-1997 approved these changes
Thanks for addressing the comments !!
When we add `noResponse` event whenever we are skipping prediction, that would give us more insights into false positive cases.

2024-12-26 01:52 UTC, valerybugakov commented on vscode/src/autoedits/autoedits-provider.ts
> +            codeToRewrite
I destructured it to use an object property shorthand in the `isPredictedTextAlreadyInSuffix`  call. If a variable is mentioned several times in the following code it makes it a bit easier to read:

```ts
            isPredictedTextAlreadyInSuffix({
                codeToRewrite: codeToReplaceData.codeToRewrite,
                decorationInfo,
                suffix: codeToReplaceData.suffixInArea + codeToReplaceData.suffixAfterArea,
            })

            // the updated version
            isPredictedTextAlreadyInSuffix({
                codeToRewrite,
                decorationInfo,
                suffix: codeToReplaceData.suffixInArea + codeToReplaceData.suffixAfterArea,
            })
```

2024-12-26 01:53 UTC, merged