feat(audoedit): implement basic analytics logger
sourcegraph/cody pull request #6430
Opened 2024-12-20 08:01 UTC by valerybugakov

- WIP  
- TODO: Improve tests; they're generated mainly by Cody, with a few manual tweaks.  
- The `AutoeditAnalyticsLogger` is a refactored version of the autocomplete analytics logger without persistence tracking. It's much more type-safe than its predecessor, with explicitly defined state transitions and required attributes for each stage. Plus, a lot of unused attributes and logic were removed.  

## Test plan

- CI + unit tests
- The integration with the actual autoedits provider will implemented in a follow-up PR.

2024-12-23 11:59 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    suggested: ['read', 'accepted', 'rejected'],
How can we transition from `suggestion` to `accepted` or `rejected` without `read` ?
If we think there is an intermediate stage where although we suggest a prediction but maybe user typed something so that it was not `read`, do you think we should introduce another state something like `noRead` so that `suggested` can have transition to either `read` or `noRead` and `noRead` would have empty transition ?

2024-12-23 12:40 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    | 'noResponse'
nit: can we add a very brief documentation on what each state mean.

2024-12-23 12:43 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    sessionId: AutoeditSessionID
should we call it `requestId`. `session` i think typically refers to when user starts vscode, does multiple requests and end the session.

2024-12-23 12:46 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +interface AutoeditStartedMetadata {
Should this extend `AutoeditBaseState` ?

2024-12-23 12:55 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    charCount: number
We typically use `lineCount` and `charCount` to calculate stats over newly added code in the editor. But for the `auto-edits` the values typically include existing code as well, so we may need to adjust the metrics accordingly.

2024-12-23 12:56 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    prediction?: string
I think we should add `codeToRewrite` to offline understand how the prediction is different from rewritten code.

2024-12-23 12:56 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    source?: string
nit: Should we make this a enum ?

2024-12-23 13:01 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    latency: number
Although this would be a new field, do you think we can also add `CGOverheadLatency` and `SGInstanceOverheadLatency`. This is different from `upstreamLatency` as that is only the ping latency and does not take into account the context and response lengths which are crucial in `auto-edits`. 
It should be fine to create a seperate PR for these fields as well

2024-12-23 13:03 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    /** Document language ID (e.g., 'typescript'). */
Can we add another field here like `source` which would indicate if the suggestion is from only the cursor movement or user typing something.

2024-12-23 13:05 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    /** True if we fuzzy-matched this suggestion from a local or remote cache. */
Another field which would be helpful here is:
`is code_to_rewrite` same as `prediction`. Since `auto-edits` trigger suggestion on cursor movement, a high value  suggestion could indicate irrelevant suggestion.

2024-12-23 13:08 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    /** The number of completions we requested until this one was suggested. */
does the documentation needs updation ?
`The number of completions requested` since when is unclear to me ?

2024-12-23 13:08 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +export type AutoeditSessionID = string & { readonly _brand: 'AutoeditSessionID' }
should we call it

2024-12-23 13:10 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +interface AutoeditNoResponseEventPayload extends AutoeditContextLoadedMetadata {}
what cases does no response happen ? Is this logged when the response is empty string from the model ? If yes, I would suspect this to not trigger since unlike autocomplete, the model atleast rewrite the `codeToRewrite` and empty response here means that we delete all the code in the codeToRewrite section.

2024-12-23 13:29 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    readAt: number
For all the states do you think we should just have 
1. phase 
2. payload 
All the payload at any state anyways extend the previous state. So we can move the specific fields like `startedAt`, `loadedAt` etc in the metadata itself. So, that we don't have to extend both the metadata and the states. 

So, after this the metadata would be incorporate additional ields like `loadedAt`, `readAt` etc and each state would have no need to extend previous state and Omit some fields from the previous state.

Currently, introducing any new start in between requires this duplication of extending metadata/state fields.

2024-12-23 13:45 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
For the `privateMetadata` should we add `recordsPrivateMetadataTranscript: 1` in the metadata ?
Also adding @akalia25 for a view here

2024-12-23 13:48 UTC, hitesh-1997 requested changes
Awesome 🚀🚀

2024-12-24 03:38 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                category: action === 'suggested' ? 'billable' : 'core',
Hey @kelsey-brown, @akalia25, could you take a look? The list of currently implemented event names:

```ts
type AutoeditEventAction =
    | 'suggested'
    | 'accepted'
    | 'noResponse'
    | 'error'
    | `invalidTransitionTo${Capitalize<Phase>}`

2024-12-24 03:44 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    suggested: ['read', 'accepted', 'rejected'],
We consider suggestions as read after a hard-coded timeout if they were not rejected during this time. Upon reviewing the code, I see that we don't need this data to send the existing event payloads. We use `displayDuration`, which does not require `readAt` to be computed. 

I'll remove this logic altogether. We can add it later if we think we need it.

2024-12-24 03:51 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    latency: number
How do you propose we compute these new fields?

2024-12-24 04:16 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    /** The number of completions we requested until this one was suggested. */
Updated the comment. This property computes how many requests we started since the last suggestion was shown.

2024-12-24 04:18 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +interface AutoeditNoResponseEventPayload extends AutoeditContextLoadedMetadata {}
In autocomplete, this happens when we hide a suggestion for whatever reason, such as when the suggestion duplicates the document suffix. We can extend this even with extra fields in follow-up PRs.

2024-12-24 04:34 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    readAt: number
Yeah, this structure requires a bit of extra code. However, based on our experience with the autocomplete analytics logger, it's necessary always to have a type-safe setup for the fields we send to our analytics backend. 

I updated a top-level comment explaining the rationale here. Here are the two most relevant points:

```
 * 3. The `payload` field in each state encapsulates the exact list of fields that we plan to send
 *    to our analytics backend.
 *
 * 4. Other top-level `state` fields are saved only for bookkeeping and won't end up at our
 *    analytics backend. This ensures we don't send unintentional or redundant information to
 *    the analytics backend.
 ```

That's why I'd like to separate payload and other bookkeeping fields (`startedAt`, etc).

2024-12-24 04:41 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
As per [the docs](https://github.com/sourcegraph/cody/blob/main/ARCHITECTURE.md#telemetry), it's required if we want to send `promptText` or `responseText`, which we don't have in this logger yet. Can we add `recordsPrivateMetadataTranscript` later when we need it?

2024-12-24 07:14 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    latency: number
We need to send them from backend in the request response, but we can skip them for now and can compute them later in a seperate PR

2024-12-24 07:15 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +interface AutoeditNoResponseEventPayload extends AutoeditContextLoadedMetadata {}
gotcha !!

2024-12-24 07:17 UTC, hitesh-1997 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
I noticed earlier that we log `prediction?: string` field which would be `responseText` so suggested the change. yes, we can add it later when we log `responseText`

2024-12-24 11:00 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
Ok, I reread [this Slack message](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1718914278731939?thread_ts=1718821081.192759&cid=CN4FC7XT4) and agree that we should add it here.

2024-12-24 11:03 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
It probably means we should add it to autocomplete events containing the `insertText` field too.

2024-12-24 11:11 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
https://github.com/sourcegraph/cody/pull/6430/commits/35706284071c8e7f58ea7aa854dd66bd37b0f9d4

2024-12-24 11:19 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    charCount: number
Agree, let's adjust in a follow-up PR.

2024-12-24 11:22 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    /** True if we fuzzy-matched this suggestion from a local or remote cache. */
Let's add this in a follow-up PR. We might want an enum field indicating the reason for a suggestion to be hidden.

2024-12-24 11:26 UTC, hitesh-1997 approved these changes
Thanks for addressing the comments !!

2024-12-24 12:09 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +interface AutoeditNoResponseEventPayload extends AutoeditContextLoadedMetadata {}
I changed this event name to `discarded` and added some comments to clarify it. We can adjust it follow-ups based on use cases.

2024-12-24 12:17 UTC, valerybugakov commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +    sessionId: AutoeditSessionID
I initially didn't like the `request` naming because it might be mistaken for network requests. However, after giving it some more thought, we can make the naming for autoedit network request-related types more explicit, which should clear up any confusion. Update to `request`.

2024-12-24 12:21 UTC, valerybugakov commented
Enabling auto-merge since the logger isn't integrated with the feature yet, and the rollout is still limited to S2 users only. @kelsey-brown and @akalia25, feel free to drop any review comments; I’ll handle them in follow-up PRs.

2024-12-24 12:21 UTC, merged

2025-01-02 15:53 UTC, kelsey-brown commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                category: action === 'suggested' ? 'billable' : 'core',
These should be categorized as follows: 

- suggested: billable
- accepted: core
- noResponse: billable
- error: null (uncategorized)
- invalid: null (uncategorized) 

Thanks for checking!

2025-01-02 16:08 UTC, kelsey-brown commented
@valerybugakov just to clarify, the event names here aren’t changing - just the way they’re logged technically, and some of the metadata? And similarly, we won’t still log events the old way in addition to this - this will be a full replacement?

> If you see anything important that's missing from the autocomplete logger, please call it out!

It's a bit hard for me to tell which metadata fields have been removed based on the code here - there are a lot 😅 Are these events live on S2? If so, I could fire some events there and compare the payloads side by side to what we're getting from other instances.

2025-01-02 18:17 UTC, akalia25 commented on vscode/src/autoedits/analytics-logger/analytics-logger.ts
> +                privateMetadata: { message: error.message, traceId },
Thanks for the tag, @hitesh-1997! 

Yes, when recording sensitive data (e.g., transcripts, or free-form text), we should always add `recordsPrivateMetadataTranscript: 1` to the metadata. This helps us keep track of where sensitive data is being logged and route the data correctly. More details [here](https://www.notion.so/sourcegraph/V2-telemetry-guidelines-for-the-Sourcegraph-application-350680a080924aadb2e7f309fb2fbd21?pvs=4#6bee46e2d5e34f8db57d6f1a9038fad9)

We need to know which key within `privateMetadata` contains the sensitive data, so if the key is not in the list below (i.e. `insertText`), then you'd simply need to message the discuss-analytics channel and we'd be happy to add the key.

> promptText
> responseText
> inlineCompletionItemContext
> privateContextSummary
> diff
> query

2025-01-10 14:32 UTC, valerybugakov commented
> @valerybugakov just to clarify, the event names here aren’t changing - just the way they’re logged technically

I'll share more information in a Slack thread today.