track notebook for auto-edits
sourcegraph/cody pull request #6449
Opened 2024-12-23 19:05 UTC by hitesh-1997

Add `notebooks` support for `auto-edits`.

## Test plan

## Changelog

2024-12-25 02:20 UTC, valerybugakov requested changes
Thanks for looking into it, Hitesh!

2024-12-25 02:20 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +            )
Here it's best to use `Promise.all()` to start all the async `getDiagnosticsPromptFromInformation` in parallel. 

```ts
const diagnostics  = await Promise.all(
  (notebookCells || []).map(cell => {
    const diagnostics = vscode.languages.getDiagnostics(cell.document.uri)
    return this.getDiagnosticsPromptFromInformation(
      cell.document,
      position,
      diagnostics
  )
)

return diagnostics.map(snippet => ({
  ...snippet,
  uri: activeNotebook!.uri
})

2024-12-25 02:20 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
> +    private getCurrentDocumentUri(document: vscode.TextDocument): vscode.Uri {
Let's rename `getCurrentFilePath` to `getCurrentDocumentUri` from the notebook utils, make it return uri, and reuse it here.

2024-12-25 02:20 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
>          return viewPortSnippets
We shouldn't do that because consumers will still rely on the function's return type and might try to use properties that aren't actually available, leading to runtime errors. Instead, we should update the `AutocompleteContextSnippet` type or the return type of the `RecentViewPortRetriever.retrieve()` method to make sure all cases can be validated statically by the TypeScript compiler.

2024-12-25 02:20 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +            return await this.getDiagnosticsForNotebook(position)
Can we update unit tests to cover this new code path?

2024-12-25 02:20 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.test.ts
> +                onDidChangeNotebookEditorVisibleRanges() {
Can we add a unit test for a recent view port retrieval for a notebook?

2024-12-25 13:57 UTC, hitesh-1997 commented on vscode/src/autoedits/prompt/prompt-utils.ts
> +    const indexCurrentCell = notebookCells.findIndex(cell => cell.document === document)
done

2024-12-25 13:57 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +        return await this.getDiagnosticsForDocument(document, position)
done

2024-12-25 13:57 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +        const activeNotebook = vscode.window.activeNotebookEditor?.notebook
done

2024-12-25 13:57 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +            )
done

2024-12-25 13:57 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
> +    private getCurrentDocumentUri(document: vscode.TextDocument): vscode.Uri {
done

2024-12-25 13:58 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
>          return viewPortSnippets
Thanks for pointing this out !!
It was used in bfg so used in the same here.
But I modified the `AutocompleteContextSnippet ` to make start line and end line optional and handled the behaviour.

2024-12-25 14:00 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +            return await this.getDiagnosticsForNotebook(position)
I though of adding a unit test, I think that requires implementing the mock editor for notebook and some related functionalities (similar to how we are using `vscode-languageserver-textdocument` for text document mocking). I think that could take a bit time and I wanted to prioritize other task here.
Do you think we should add this maybe in follow up PRs ?

2024-12-26 03:14 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +            return await this.getDiagnosticsForNotebook(position)
I took a stab at it and was able to create mocks pretty quickly with Cody's help. Created a PR [here](https://github.com/sourcegraph/cody/pull/6462), it contains required mocks + basic unit tests. Could you take it from here? I think we want to remove `getPrefixAndSuffixForAreaForNotebook` tests and just add a couple of notebook-focused ones to the `getCurrentFileContext` describe section.

2024-12-26 03:17 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.test.ts
> +                onDidChangeNotebookEditorVisibleRanges() {
We can skip this because it would be trickier. The unit tests from the previous comment should cover helpers that extract text from notebooks so that it will have _some_ coverage.

2024-12-26 03:18 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
>          return viewPortSnippets
TY! It was used in BFG because it was never fully rolled out to users.

2024-12-26 03:23 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
> +        return await Promise.all(snippetPromises)
`await` is redundant here. we can give control of the promise to the consumer right away

```suggestion
        return Promise.all(snippetPromises)
```

2024-12-26 03:32 UTC, valerybugakov commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
> -                endLine: viewPort.visibleRange.end.line,
Removing start and end lines limits us when we need to duplicate context before adding it to the final prompt. What do you think about creating a new `AutocompleteNotebookContextSnippet` type that would not have these fields but preserve them for the default `AutocompleteFileContextSnippet`?

2024-12-26 13:59 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
> +        return await Promise.all(snippetPromises)
done

2024-12-26 14:01 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
> -                endLine: viewPort.visibleRange.end.line,
I added a type field to each of the `AutocompleteSnippet` type, so that we can compare on the type before using the startline and endline fields.
Please note that, I had to change a bunch of files to return this `type` variable from each context.

2024-12-26 16:08 UTC, hitesh-1997 commented on vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts
> +            return await this.getDiagnosticsForNotebook(position)
Thanks for adding this, added test cases for notebooks

2024-12-27 04:16 UTC, valerybugakov approved these changes
NOICE! Thank you for addressing the comments 🙌

2024-12-27 07:01 UTC, merged

2024-12-27 13:17 UTC, valerybugakov commented on vscode/src/autoedits/prompt/prompt-utils.test.ts
> +            maxSuffixLength,
I don't see `maxPrefixLength` being used in `prompt-utils.ts`

2024-12-27 13:25 UTC, valerybugakov commented on vscode/src/autoedits/prompt/prompt-utils.test.ts
> +            maxSuffixLength,
Addressing it here: https://github.com/sourcegraph/cody/pull/6474/commits/1e6f4a0809e6bf714067dce051500222a3f4ea55

2024-12-27 13:39 UTC, hitesh-1997 commented on vscode/src/autoedits/prompt/prompt-utils.test.ts
> +            maxSuffixLength,
Ah sorry, I think it was a leftover from some debugging I was trying to do, thanks for fixing it !!