log charCount and lineCount for suggested text
sourcegraph/cody pull request #680
Opened 2023-08-15 00:38 UTC by abeatrix

Currently, we are logging suggestion only when a suggestion is accepted.

This PR makes an update to logs lineCount and charCount of each suggested text even if it is not accepted.

Since I am not familiar with the code on autocomplete, @vovakulikov can you confirm if this change would not cause performance issue with autocomplete or if this is the right place to add?

## Test plan

Check output channel and look for the `CodyVSCodeExtension:completion:suggested` event.

2023-08-15 00:39 UTC, abeatrix commented on vscode/src/completions/logger.ts
> -    logSuggestionEvents()
@vovakulikov do you know why we are logging suggestion event before the accepted event, only if the suggestion is accepted?

2023-08-15 01:00 UTC, vovakulikov reviewed
I don't have any big comments on adding count line and char count to logs (we don't have big numbers of suggestions to mess with performance in `processInlineCompletion` but deleting log suggested events call, I'm not so sure, It looks like we still want to have it to track their visible time) but let's check it with @philipp-spiess just to double check.

2023-08-15 01:06 UTC, abeatrix commented on vscode/src/completions/vscodeInlineCompletionItemProvider.ts
> +            const lineCount = suggestedText.split(/\r\n|\r|\n/).length
Good question. I added this only because this is what Philipp added for accepted events: https://github.com/sourcegraph/cody/pull/674/files#diff-b665c69d3614e6813525397f23bdaa80c3888bf9a96a55d6e5d245ab5dd744cdR215-R216 👀

2023-08-15 01:37 UTC, abeatrix commented on vscode/src/completions/logger.ts
> -    logSuggestionEvents()
Thanks! In this case, should I add `logSuggestionEvents()` back along with `clear()` for now?

2023-08-15 02:13 UTC, vovakulikov commented on vscode/src/completions/logger.ts
> -    logSuggestionEvents()
I think so, yes

2023-08-15 02:18 UTC, abeatrix commented on vscode/src/completions/logger.ts
> -    logSuggestionEvents()
Thanks  @vovakulikov ! I just added logSuggestionEvents() back as well as `clear()`

2023-08-15 13:17 UTC, vovakulikov approved these changes
I see that @philipp-spiess is out today, so just to unblock, if something will show up we can revert it later

2023-08-16 09:34 UTC, philipp-spiess requested changes

2023-08-16 09:34 UTC, philipp-spiess commented on vscode/src/completions/logger.ts
> +    clear()
```suggestion
```

All that `clear` does is call `logSuggestionEvents` so this is not needed

2023-08-16 09:34 UTC, philipp-spiess commented on vscode/src/completions/logger.ts
> -    logSuggestionEvents()
> @vovakulikov do you know why we are logging suggestion event before the accepted event, only if the suggestion is accepted?

The name is a bit misleading here. `logSuggestionEvents` goes over all events that are currently "in the view" and creates an event log. We do this in two cases:

- When a completion is accepted (which will REMOVE the current inline suggestion UI)
- When we get a new completion request and we can not serve the existing suggestion

We can't log these events right away because we have to calculate how long they were visible for, so instead we put it into a queue and then we flush that queue at those two points in time

2023-08-16 09:34 UTC, philipp-spiess commented on vscode/src/completions/vscodeInlineCompletionItemProvider.ts
> +            logCompletionEvent('suggested', { lineCount, charCount })
```suggestion
```

can't just put this here, otherwise we overlog suggested events (since they are now double logged) and we have no way of filtering how long a completion is visible.

Instead, what you want is to add the lines and characters to the `suggested` export for the logger.ts and add it to the map where we can later pick it up.

2023-08-16 09:34 UTC, philipp-spiess commented on vscode/src/completions/vscodeInlineCompletionItemProvider.ts
> +            const charCount = suggestedText.length
This also won't be right since it includes the `currentLinePrefix` - So text that is already visible and inside the editor. If the completion looks like this:

```
console.<log>
```

when `<>` is the insertion, this would now could `console.` too.

2023-08-16 09:35 UTC, philipp-spiess commented on vscode/src/completions/logger.ts
> -    logSuggestionEvents()
@abeatrix The doc for this is at the `suggested` method export of this file:

```
// Suggested completions will not be logged immediately. Instead, we log them when we either hide
// them again (they are NOT accepted) or when they ARE accepted. This way, we can calculate the
// duration they were actually visible for.
```

2023-08-16 14:38 UTC, abeatrix commented
@chenkc805 since I don't have the context on how autocomplete is structured, I think it'd be quicker if someone from the autocomplete team (@vovakulikov @philipp-spiess) picks this up and add the telemetry for all suggested text (vs current behavior where we only log suggested text when they are accepted) as I will be OOO for the next 2 days. Going to close this PR to avoid confusion, thanks!

2023-08-16 14:39 UTC, closed without merging

2023-08-16 14:53 UTC, philipp-spiess commented
https://github.com/sourcegraph/cody/pull/710