WIP File Driven Commands
sourcegraph/cody pull request #682
Opened 2023-08-15 03:22 UTC by arafatkatze

Original Issue -> https://github.com/sourcegraph/cody/issues/588 
Original PR (Thanks to @umpox ) -> https://github.com/sourcegraph/cody/pull/584 

### Explanation of the problem 
`Explain`|`Refactor`|`Document`|`Test` are special cases for commands. They should not open the sidebar. They should instead open up with a default prompt in command pallet or inline chat depending on the context.  Based on the use case, the user can tweak the default prompt for their own purposes. We shouldn't change these commands in the sidebar, but in the command palette and in inline chat for files we should provide a lot more control.

## Test plan
- Tested Locally
- Need the approval on the overall strategy of the PR before I design testing and clean up potentially redundant code.

2023-08-15 04:23 UTC, abeatrix commented on vscode/src/custom-prompts/utils/menu.ts
> +const chatOption: QuickPickItem = { label: 'Explain code' }
```suggestion
const chatOption: QuickPickItem = { label: 'Ask a Question' }
```
the ''Ask a Question'' option is for creating a new inline chat from the menu

2023-08-15 04:25 UTC, abeatrix commented on vscode/src/custom-prompts/utils/menu.ts
> +const docOption: QuickPickItem = { label: 'Generate Documentation' }
i think these new refactor options should be added to the Refactor menu, as this is the menu for custom commands🤔

2023-08-15 04:30 UTC, abeatrix commented on vscode/src/custom-prompts/CommandsController.ts
> +                    return await vscode.commands.executeCommand('cody.inline.new', 'Explain the selected code')
```suggestion
                    return await vscode.commands.executeCommand('cody.inline.new')
```

this is used for starting a new empty inline chat. if user wants to run the explain command, they can enter `/explain` so i don't think we will need to pre-fill this bit for them. what do you think?

2023-08-15 04:51 UTC, abeatrix requested changes
Thank you so much for initiating the changes! There might be a misunderstanding, as we still want to keep the default commands to work as /commands in chat, so i don't think any of the commands should be removed from the default command list unless there was another plan that I am not aware of. 😅 

@toolmantim are we going to replace the default /doc and /test commands with refactor commands? Or are we keeping both? 

Edit: I have also replied to the original PR as there are some moving pieces that might be worth waiting until they are finalized, sorry for the trouble caused 😞

2023-08-15 07:20 UTC, arafatkatze commented
@abeatrix Thank you for the detailed update, and I completely respect the need to align with design requirements before proceeding with the PR, so it's okay to wait. 

I'm genuinely fascinated by Cody and am eager to delve deeper into how it works by making meaningful contributions. In fact, I've earmarked some time this week to work on it.

Could you kindly guide me to an issue that would be suitable for someone looking to understand Cody better and contribute simultaneously? I noticed this list of issues (https://github.com/sourcegraph/cody/issues/582), but if there's anything specific you think would align well with my intention to understand Cody's working while contributing on it, then I'd be happy to take it on. 

Thank you!

2023-08-24 07:06 UTC, abeatrix commented
@arafatkatze im so sorry I missed your message! If you're still interested, we have a backlog of issues in the Cody project board that you can take a look and see if you find anything sparks your interests. (Might worth asking in the issue to confirm if it is still relevant before starting any works.)
Also, feel free to ping me anytime you have questions when working on an issue, always happy to help 😃

2024-01-26 03:28 UTC, arafatkatze commented
This issue has been fixed by the followup prs to this

2024-01-26 03:28 UTC, closed without merging