intelligent cody: vscode api
sourcegraph/cody pull request #692
Opened 2023-08-15 15:11 UTC by efritz

## Test plan

2023-08-17 21:13 UTC, beyang requested changes
Can you provide some screenshots and/or illustrative examples of where this improves response quality and where it hurts response quality?

Is it targeted at autocomplete, chat, or all of the above?

2023-08-17 21:13 UTC, beyang commented on vscode/src/chat/ContextProvider.ts
> +async function getGraphContextFromEditor(editor: Editor): Promise<PreciseContext[]> {
Should some part of this be checked by a unit test?

2023-08-17 21:13 UTC, beyang commented on lib/shared/src/graph-context/index.ts
> +        private backdoorFetcher?: IGraphContextFetcher
I can't find any usage of this class that doesn't go through the backdoor fetcher. Wouldn't it be clearer to have a concrete class providing this functionality, instead of wrapping it in this pass-through class?

2023-08-17 21:15 UTC, efritz commented on lib/shared/src/chat/transcript/index.ts
> +            const preciseContext = (msg as ContextMessage).preciseContext
It's also necessary on line 200 above, as `msg` has type `Message`, which has only `speaker` and `type` fields, not `file` or `preciseContext` (though we do overload the file and context fields when creating the objects in practice).

2023-08-17 21:16 UTC, efritz commented on lib/shared/src/codebase-context/index.ts
> +        // TODO(efritz) - open problem to figure out how to best rank these into a unified list
It currently depends entirely on the re-ranker. I need to dive more deeply into this part of the code to see how to effectively include the correct set of symbols.

I think we may want a classifier here of some sort to help determine which symbols are most useful for the given window and question type.

2023-08-17 21:16 UTC, efritz commented on lib/shared/src/graph-context/index.ts
> +        // due to the backdoor fetcher (and an unmerged Remote API).
Yeah, can clean up the boilerplate for what we're not currently shipping.

2023-08-17 21:16 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +async function getGraphContextFromEditor(editor: Editor): Promise<PreciseContext[]> {
Yes, can add tests. Was waiting for a general approach 👍 prior to this.

2023-08-17 21:17 UTC, efritz commented on lib/shared/src/graph-context/index.ts
> +        private backdoorFetcher?: IGraphContextFetcher
Yeah, this was all part of the "we're gonna replace this layer with something more sophisticated" strategy. Can clean it up (same [here](https://github.com/sourcegraph/cody/pull/692#discussion_r1297761039)).

2023-08-17 21:18 UTC, efritz commented
> Can you provide some screenshots and/or illustrative examples of where this improves response quality and where it hurts response quality?

Sure, will gather some and post in a comment on the PR.

> Is it targeted at autocomplete, chat, or all of the above?

Right now it's only set up for chat, but I'm currently working (between a few other tasks) to thread the graph context fetcher through autocomplete as well.

2023-08-17 23:20 UTC, efritz commented on lib/shared/src/graph-context/index.ts
> +        private backdoorFetcher?: IGraphContextFetcher
Fixed by [78fda72](https://github.com/sourcegraph/cody/pull/692/commits/78fda728734ea5deae20e64b31189d0b4a585a63).

2023-08-17 23:20 UTC, efritz commented on lib/shared/src/graph-context/index.ts
> +        // due to the backdoor fetcher (and an unmerged Remote API).
Fixed by [78fda72](https://github.com/sourcegraph/cody/pull/692/commits/78fda728734ea5deae20e64b31189d0b4a585a63).

2023-08-18 01:36 UTC, toolmantim commented
For the name, I'm trying to move to a single bit of UI that summarises all the context prep Cody did and was included (vs the separate drop-downs we're adding here). The name would sit alongside "Embeddings".

My ranked naming suggestions (instead of "Intelligent Cody"… Cody is already intelligent in lots of ways 😉)
1. Add experimental support for locally generated **Symbol Context**
1. Add experimental support for locally generated **Precise Symbol Context**
1. Add experimental support for locally generated **Code Intel Context**

imo from a product design POV calling it **"Symbol Context"** and using the word **"Symbols"** is probably best, alongside "Embeddings". And we can have other single-word bits of context, like "Ownership"and what-have-you.

2023-08-18 04:05 UTC, valerybugakov approved these changes
That's awesome! Since all the changes are behind the experimental flag, we can merge this one safely and iterate on improvements in follow-up PRs.

2023-08-18 04:05 UTC, valerybugakov commented on vscode/src/chat/ContextProvider.ts
> +                .slice(fr.start, fr.end + 3)
Why `+ 3`? 🙂

2023-08-18 04:32 UTC, valerybugakov reviewed
Also, we should add an entry about the new experimental setting to `vscode/CHANGELOG.md`.

2023-08-18 15:45 UTC, efritz commented on lib/shared/src/codebase-context/messages.ts
> +export interface PreciseContext {
It's meant to conform to the GraphQL schema we've [defined here](https://github.com/sourcegraph/sourcegraph/pull/51690), so keeping it in the same shape will make the Remote API integration easier since we can just return the same type directly.

2023-08-18 15:45 UTC, efritz commented on lib/ui/src/chat/PreciseContext.tsx
> +}> = memo(function PreciseContextsContent({ preciseContexts, symbolLinkComponent: SymbolLink, className }) {
I copied this from the FileContextContent component, which is also memoized (just to flag another possibly unnecessary use).

2023-08-18 15:46 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +    console.time(label)
Cool! This was just to get something on the console to see if we were creating a new bottleneck. Most of the time this function responds much faster than 100ms.

2023-08-18 15:48 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +            const foldingRanges = await foldingRangesPromise
Once promises are in-flight does awaiting one actually bring it to the front of the event queue for processing? Maybe I misunderstand the model here, but I would assume that forcing evaluation prior to the loop may only have an effect if the _remainder_ of the loop body was expensive.

Maybe that's what you're saying though. I'm fine doin a force evaluation if it's better practice.

2023-08-18 15:48 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +                .slice(fr.start, fr.end + 3)
I originally had the comment `// ??` which I think was more descriptive. I'm looking into this, but +1 and +2 tends to cut lines of the folding range off (one due to inclusive indexes, and another two for ... I don't know yet, but intend to find out before I merge).

2023-08-18 16:07 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +            const foldingRanges = await foldingRangesPromise
Updated.

2023-08-18 23:22 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +async function getGraphContextFromEditor(editor: Editor): Promise<PreciseContext[]> {
Updated in [0fd7ede](https://github.com/sourcegraph/cody/pull/692/commits/0fd7ede2f764169979088cdbd9b8613a990cbe0f).

2023-08-18 23:23 UTC, efritz commented on vscode/src/chat/ContextProvider.ts
> +                .slice(fr.start, fr.end + 3)
Updated, moved from folding ranges to document symbol ranges which are more stable and don't require the trickery.

2023-08-18 23:28 UTC, efritz commented
@beyang Here's a quick example. I highlighted the part of the code I wanted precise symbols to be extracted from, then asked something about the shape of the type of one of the struct members (defined in the stdlib).

![image](https://github.com/sourcegraph/cody/assets/103087/e1f554fd-4e49-43a0-a941-cd86cd6bf160)

Clicking on the sidebar jumps me to `~/go/pkg/mod/golang.org/x/crypto@v0.11.0/ssh/certs.go`:

![image](https://github.com/sourcegraph/cody/assets/103087/fc200cb1-01f6-46fa-9a38-0936115ecc42)

2023-08-21 05:06 UTC, valerybugakov commented on lib/shared/src/codebase-context/messages.ts
> +export interface PreciseContext {
Would it be helpful to leave a comment on that?

2023-08-21 06:00 UTC, valerybugakov approved these changes

2023-08-21 12:41 UTC, efritz commented on vscode/src/chat/GraphContextProvider.test.ts
> +                return Promise.resolve([])
How do you do this without an await expression?

2023-08-21 12:48 UTC, efritz commented on vscode/src/chat/GraphContextProvider.test.ts
> +            await Promise.all(definitions.map(async v => ({ symbolName: v.symbolName, locations: await v.locations })))
Updated in [b325a42](https://github.com/sourcegraph/cody/pull/692/commits/b325a4212283f1f575e2a1efb852547bd9ee41d5).

2023-08-21 12:51 UTC, efritz commented on vscode/src/chat/GraphContextProvider.test.ts
> +                return Promise.resolve([])
Threw an eslint disable on there in [9951a24](https://github.com/sourcegraph/cody/pull/692/commits/9951a24c0dfbe41f4501435db86a2eb475b935bc).

2023-08-21 13:39 UTC, beyang commented
> For the name, I'm trying to move to a single bit of UI that summarises all the context prep Cody did and was included (vs the separate drop-downs we're adding here). The name would sit alongside "Embeddings".

@toolmantim we should not use "embeddings" anywhere that's visible to the end user. Embeddings are an implementation detail and we need another descriptor for it, like "AI-enabled search" or "Intelligent search".

2023-08-21 13:55 UTC, beyang commented on lib/shared/src/codebase-context/index.ts
> +        // TODO(efritz) - open problem to figure out how to best rank these into a unified list
I don't believe there's a reranker. The part of the code that does the context selection from the list of the available messages is here: https://sourcegraph.com/github.com/sourcegraph/cody@1ec7076f205078e5b32d939bdadc67342b96c58c/-/blob/lib/shared/src/chat/transcript/index.ts?L196-209

I believe it just uses the order (or reverse order) of the messages as returned by the recipe implementation.

2023-08-21 13:56 UTC, beyang approved these changes

2023-08-21 13:57 UTC, beyang commented
How do I turn it on to try i tout?

2023-08-21 13:57 UTC, efritz commented
> How do I turn it on to try it out?

There's an extension setting, mentioned in the changelog. It's not reactive so you'll need to reload the extension once you enable it (for now).

2023-08-21 14:02 UTC, merged