feat(plugins): add client side cody plugins
sourcegraph/cody pull request #76
Opened 2023-07-11 15:43 UTC by erzhtor

## Test plan
- Add env vars
- Use the "Launch VS Code Extension" option to load environment variables properly

2023-07-13 19:07 UTC, almeidapaulooliveira approved these changes

2023-07-14 02:44 UTC, abeatrix requested changes
This is super cool! It works great with the chat recipe. It might be better if we can have an option to not include contextMessages when using certain plugins , maybe that could be something to explore in the future?

I did notice one issue though: I tried using inline fixups with the changes added in this PR and it looks like it removes the response from Cody?

Current Release version:
<img width="596" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/9b16d6b7-f05a-4554-9913-731c196c146d">

From this branch:
<img width="507" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/6268c516-e878-4e7e-8597-4d94f5ba876b">
Assistant message is removed

Loom: https://www.loom.com/share/6af2bc6719eb4157b5742b0de9f804b1?sid=bb689c35-fb42-4bc9-a6ff-333c5f85bd2f

CC @dominiccooney who would be able to provide more constructive feedback than I could 😁

2023-07-14 08:50 UTC, erzhtor commented on vscode/webviews/Plugins.module.css
> +    border-bottom: 1px solid var(--vscode-activityBar-border);
No, thanks for catching it. Fixed d3a49e50f37e636212fe214bc9f8bd53ca8ee829.

2023-07-14 08:51 UTC, erzhtor commented on lib/shared/src/chat/transcript/index.ts
> +            if (index === lastInteractionWithContextIndex && !onlyHumanMessages) {
This is because we use fast LLM for detect which plugin to run, and we are feeding previous messages too to get full context of the conversation. Only human here omits extra context files as messages because it confuses the LLM.

2023-07-14 08:53 UTC, erzhtor commented
> It might be better if we can have an option to not include contextMessages when using certain plugins , maybe that could be something to explore in the future?

Can you share an example use-case maybe?

> I did notice one issue though: I tried using inline fixups with the changes added in this PR and it looks like it removes the response from Cody?

Good catch, wasn't using recipes at all so missed this, thanks! Fixed d0e66c6dc142cbfd1c4c29209d64f9e791885d21 to include plugins only for chat messages.

2023-07-14 15:04 UTC, merged