feat: improved generate unit tests command
sourcegraph/cody pull request #907
Opened 2023-09-03 02:15 UTC by abeatrix

This PR contains changes that improve the current generate unit tests command:
- update the current unit test prompt to give it detailed directions on how to produce unit tests with higher quality consistently ([ref anthropic docs](https://docs.anthropic.com/claude/docs/claude-says-it-cant-do-something#give-explanatory-instructions))
- update language to let Cody know all files come from the same codebase. I noticed Cody currently does not know the shared context is from files, and certainly doe snot know the file path we shared with each context comes from a file that belongs to the same codebase. It just doesn't make that connection until we spell it out for them
- cleaned up the custom prompt recipe to use switch functions 
- added `addContentToTestFile` function to the MyToolProvider for creating temporary test files for unit tests that belong to an existing test file

## Test plan

- Start Cody from this branch
- Select a function in a file and run the `Generate Unit Tests` command
- You should see a new test file created if there is no test file exists for the file you run the command from
- If there is already a test file exists, a temporary file will be created with the new test in it

Try running other commands. The changes in this should not change the behavior of other commands.

https://github.com/sourcegraph/cody/assets/68532117/0779ce8a-713a-40e4-a92e-6fc612143798

2023-09-03 02:16 UTC, abeatrix commented on vscode/src/chat/MessageProvider.ts
> +                    void this.editor.controllers.command?.onCompletion(text)
this sends the response back to the command controller to create the test files when needed

2023-09-03 02:17 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        switch (true) {
from if functions to switch

2023-09-03 02:19 UTC, abeatrix commented on lib/shared/src/chat/prompts/templates.ts
> +- Do not make any assumptions about the code and file names or any misleading information.
this helps prevent Cody from "hallucinating"

2023-09-03 03:28 UTC, abeatrix commented
cc @kalanchan regarding the next release

2023-09-03 03:38 UTC, toolmantim commented
@abeatrix I’ll be writing this one!

Do you have a description of how the generate test output is improved by these changes? (E.g. Before and after examples? Cases that didn’t work well before, that do now?)

2023-09-03 06:01 UTC, abeatrix commented
@toolmantim Just added more demo videos at the end of the PR description and added a Before and After section with example test output. let me know if you need more info :)

2023-09-03 06:08 UTC, toolmantim reviewed
Super cool. I gave it a go w/ some ts and go files in various projects! The results I got were a little mixed… even though some output is really promising.

I spotted in some cases the chat output contained this for existing tests:

> I am writing these unit tests in the existing test file search_test.go which already contains tests for the search package.

Which makes it sound like Cody updated the existing file, which it doesn't (it opens the temporary file)

Also this happened when there was no existing file (one was created):

> I am not importing any new packages since this test file already exists and follows the patterns from the existing tests.

<img width="1468" alt="Screenshot 2023-09-02 at 10 46 49 pm" src="https://github.com/sourcegraph/cody/assets/153/2aa87ecf-ee91-4a19-acc5-53551bf552dd">

I feel like we might need some wider testing this week, rather than rushing it into the release. And give @beyang & @csells a chance to see how it's going too.

2023-09-03 06:11 UTC, toolmantim commented
> Just added more demo videos at the end of the PR description and added a Before and After section with example test output. let me know if you need more info :)

Just saw this after the review sorry! 😅

2023-09-03 06:24 UTC, abeatrix commented
> > Just added more demo videos at the end of the PR description and added a Before and After section with example test output. let me know if you need more info :)
> 
> 
> 
> Just saw this after the review sorry! 😅

Yea. Also included a note

> It doesn't always produce the perfect tests, but it generates better and higher quality tests consistently compared to the older version of the command. 

I don't think it's possible to get results that works perfectly for all cases. This is just an improved version of what we have now. I'd suggest compare the results between the current version and the improved version to see the quality improvements. 
Agree with giving more time for others to test and compare.

2023-09-03 06:28 UTC, abeatrix commented
I guess calling this a PR for improving context for the generate unit test command is more accurate 😅

2023-09-03 15:29 UTC, abeatrix commented on vscode/src/custom-prompts/ToolsProvider.ts
> +        await this.createTempFile([testFileName, testContent].join('\n'), language)
@toolmantim Im using the file name on top to create the new temporary file but i see what you're saying. 

I use a temporary file instead (copilot and codium do the same) because not all the test file located in the same directory as the current file for some languages, that's why we won't be able to generate a link that would work in all cases.

Maybe I can remove the file name from the top if you think that's less confusing?

2023-09-03 19:33 UTC, taras-yemets commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
> First, review the shared context to see if there is an existing test file that match the file path contains the selected code.

"...that matches the file path _and_ contains the selected code" - is _"and"_ missing in the original version?

2023-09-03 19:44 UTC, taras-yemets commented on lib/shared/src/chat/prompts/vscode-context.ts
> +            const isTestFile = testOnly ? fileName.includes('test') : true
nit: When `testOnly` is `false`, `isTestFile` variable name seems a bit misleading. Maybe we can think of another name better communicating that `fileName` satisfies `testOnly` condition 🤔

2023-09-03 19:46 UTC, taras-yemets commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    console.log(codebaseTestFiles)
```suggestion
    const codebaseTestFiles = await getCodebaseTestFilesContext(fileName)
```

2023-09-03 20:03 UTC, taras-yemets commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const fileNameWithoutExtension = filePathParts.pop()?.split('.').shift() || ''
Extracting dir name and file name without the extension from the file path logic is used in a few places and may be worth moving to a separate helper function.

2023-09-03 20:08 UTC, taras-yemets commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const packageJsonPath = await vscode.workspace.findFiles('**/package.json', undefined, 1)
> When `undefined`, default file-excludes (e.g. the `files.exclude` setting
but not `search.exclude`) will apply. When `null`, no excludes will apply.

nit: `package.json` is not likely to be excluded in any way, but still, `null` may be a safer choice here.

2023-09-03 20:11 UTC, taras-yemets commented on lib/shared/src/chat/prompts/vscode-context.ts
>              const truncatedContent = truncateText(decoded, MAX_CURRENT_FILE_TOKENS)
nit: This logic is repeated in a few places. Maybe we can move it to a helper function (e.g. `getTruncatedContent`)?

2023-09-03 20:21 UTC, taras-yemets approved these changes
Great work, @abeatrix! 
Left a few non-blocking comments.

2023-09-04 05:10 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const packageJsonPath = await vscode.workspace.findFiles('**/package.json', undefined, 1)
> When undefined, default file-excludes (e.g. the files.exclude setting but not search.exclude) will apply. 

I think `undefined` is safer and faster because when set to null, all the dot files and node_modules will likely be searched as well

2023-09-04 05:17 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const fileNameWithoutExtension = filePathParts.pop()?.split('.').shift() || ''
Yea there are a few things I will need to clean up in this file alone, will add this to my next PR to clean up this file!

2023-09-04 05:17 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
>              const truncatedContent = truncateText(decoded, MAX_CURRENT_FILE_TOKENS)
same as above, will add this to my next PR to clean up this file!

2023-09-04 05:18 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
> +            const isTestFile = testOnly ? fileName.includes('test') : true
Yea there are a few things I will need to consolidate for this particular file. I will add this to my next PR for cleaning this file up specifically!

2023-09-04 05:39 UTC, toolmantim commented on vscode/src/custom-prompts/ToolsProvider.ts
> +        await this.createTempFile([testFileName, testContent].join('\n'), language)
Is it possible to make the chat message more friendly?

For the temporary file, is the idea that people use the filename in the tab and the filename in the top of the file to search the codebase for the file, and copy and paste?

2023-09-04 18:26 UTC, beyang commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
Is there a reason why we have the term `framework&libraries`? It looks like a typo, but does it yield better results?

2023-09-04 18:39 UTC, beyang commented on lib/shared/src/chat/prompts/utils.ts
> +export function getHumanTextForCommand(text: string, fileName?: string): string {
I think the term "human" is overloaded here. Claude uses the `Human: ` tag, but is the output of this function fed directly into that? It's hard to tell, and the replacement of the `{humanInput}` string makes it more confusing. Perhaps the `text` argument should be renamed, as well.

Possible name (but double check my understanding of what's happening): `getClaudeHumanText(commandInstructions: string, currentFileName?: string)`

2023-09-04 18:43 UTC, beyang requested changes

2023-09-04 18:43 UTC, beyang commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        switch (true) {
I don't think this is an equivalent substitute, as the switch will fallthrough all subsequent cases once it encounters a true case, rather than checking subsequent cases: https://timmousk.com/blog/typescript-switch/

2023-09-04 18:44 UTC, beyang commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +                // TODO bee only top parts
What does this TODO mean?

2023-09-04 18:44 UTC, beyang commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +            // const truncatedTextWithCode = promptTextWithCodeSelection(codyPromptText, selection)
Delete?

2023-09-04 18:46 UTC, beyang commented on vscode/CHANGELOG.md
> +- The `Generate Unit Tests` command has been improved with an enhanced context fetching process that produces more consistent test results across languages. A new file containing the new tests will b
Does it actually create a new file? When I was testing the functionality, it only seemed to print the generated test in the sidebar—it didn't actually create a new file or make modifications to an existing file.

2023-09-04 18:56 UTC, beyang commented on vscode/src/custom-prompts/CommandsController.ts
> +    public getCurrentCommand(fileName?: string): CodyPrompt | null {
The logic around the "current command" feels a bit brittle and is hard for me to follow. Is the following the case?
* Some user action causes the `this.commandInProgress` to be set
* We rely on `this.commandInProgress` in other code to tell us what code to execute. This effectively constrains us to executing at most one command at a time?
* At some later point (which is unclear to me), `this.commandInProgress` is reset to null or empty?

2023-09-04 18:58 UTC, beyang commented on vscode/src/custom-prompts/ToolsProvider.ts
> +    private async createNewFile(fileUri: vscode.Uri, content?: string): Promise<void> {
Add a docstring

2023-09-04 18:58 UTC, beyang commented on vscode/src/custom-prompts/ToolsProvider.ts
> +    public async addContentToTestFile(content: string, currentFileName: string): Promise<void> {
Add a docstring

2023-09-05 14:20 UTC, abeatrix commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
@beyang I've documented most of the prompts I've tested so you can get an idea of how the prompt evolved: https://sourcegraph.sourcegraph.com/notebooks/Tm90ZWJvb2s6MTMz

It started from `framework/library` but ended up not working for some languages.
I haven't tried `framework & libraries` though. Maybe it'd be the same

2023-09-05 14:36 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +                // TODO bee only top parts
left over. will remove it

2023-09-05 14:56 UTC, umpox commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
More of a general thought: Should we consider changing this format from `json` to something else (maybe `yaml`? or something)

Writing a prompt in a JSON file doesn't feel nice at all.

Do we structure it this way so users can write their own too?

Is `{languageName}` a global that we always replace? Are there others? (Sorry if I've missed something!)

2023-09-05 14:56 UTC, umpox commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const excludePattern = '**/*{e2e,integration}*/**'
This feels quite specific, it obviously applies to our codebase but I'm curious how often this would apply elsewhere.

I feel like we should refrain from trying to fine tune this like this, it could lead to hard to debug situations. E.g.

This wouldn't include any files that are in a `/vscode-integration` folder, but the user might actually want those!

I guess the alternative would be to let the user specific their own patterns that are relevant to their own codebase

2023-09-05 14:56 UTC, umpox commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const packageJsonPath = await vscode.workspace.findFiles('**/package.json', undefined, 1)
This also feels quite specific to our setup and TypeScript files.

Do we suggest that generate tests works best for TS/JavaScript? I also feel like this could be an area where we let users actually specify patterns they want to include. Otherwise we'll have a _lot_ of logic where we want to apply similar patterns for different languages. (Like `go.mod`  for `Go`)

Likewise this wouldn't necessarily work for users who use yarn/npm workspaces. Idk what other scenarios exist for other languages

2023-09-05 14:56 UTC, umpox commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const fileName = vscode.workspace.asRelativePath(currentFile.fileName)
Should we try to make this general seeing as we're in `lib/shared` and not `vscode`? I feel like we should probably lint against using `vscode`! (I know we are already using it in a few places already)

2023-09-05 14:56 UTC, umpox commented on lib/shared/src/chat/prompts/vscode-context.ts
> +export async function getTestFileOfCurrentFileContext(fileName: string): Promise<ContextMessage[]> {
I think it'd be super helpful to have some simple unit tests for the functions in this file. Just like with examples of the files that are found and the files that aren't found.

2023-09-05 14:56 UTC, umpox commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        const commandName = command?.slashCommand || command?.description || promptText
`description` or `promptText` seems incorrect here, they will both likely be very long as it doesn't feel helpful to incldue this in the error message

2023-09-05 14:56 UTC, umpox commented on vscode/src/custom-prompts/CommandsController.ts
> +    public getCurrentCommand(fileName?: string): CodyPrompt | null {
Just to add, I think we should consider making this a `ViewProvider` like `ChatViewProvider` or `FixupViewProvider`.

We can still use the command controller for interactions, but I think it will clean up some of this logic, and mean that we can fire multiple commands at once instead of being restricted.

It will also mean we don't need to add command logic to the shared `MessageProvider`. That feels like it could cause bugs, e.g. if a user sends off a sidebar chat message or a fixup whilst a command is executing - it will still be sent to the command controller. Instead - `CommandViewProvider` would just be able to do this logic inside a `handleTranscript`

2023-09-05 14:57 UTC, abeatrix commented on vscode/src/custom-prompts/ToolsProvider.ts
> +    private async createNewFile(fileUri: vscode.Uri, content?: string): Promise<void> {
added

2023-09-05 14:57 UTC, abeatrix commented on vscode/src/custom-prompts/ToolsProvider.ts
> +    public async addContentToTestFile(content: string, currentFileName: string): Promise<void> {
added

2023-09-05 15:05 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const packageJsonPath = await vscode.workspace.findFiles('**/package.json', undefined, 1)
Yea `getPackageJsonContext` is only applied to [ts/js file ](https://sourcegraph.com/github.com/sourcegraph/cody@bee/unit-tests/-/blob/lib/shared/src/chat/recipes/custom-prompt.ts?L143).

For other language, the test files we fetch for a specific language is usually good enough to tell Cody what testing framework the project is using. But with ts and js because of all kind of different tests files it can have, we might not able to fetch the correct test files all the time so I thought adding package.json as context would help. Do you have other suggestions on what other approach we can take here?

2023-09-05 15:08 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +            // const truncatedTextWithCode = promptTextWithCodeSelection(codyPromptText, selection)
Deleted

2023-09-05 15:09 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        switch (true) {
switched back to use if statementd

2023-09-05 15:13 UTC, abeatrix commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
Yea it's using the same JSON file that the users would use to create a custom command.
Current `{languageName}` is the only global we always replace (for internal use)

2023-09-05 15:15 UTC, abeatrix commented on lib/shared/src/chat/prompts/utils.ts
> +export function getHumanTextForCommand(text: string, fileName?: string): string {
updated from getHumanTextForCommand getClaudeHumanText

2023-09-05 15:16 UTC, abeatrix commented on vscode/CHANGELOG.md
> +- The `Generate Unit Tests` command has been improved with an enhanced context fetching process that produces more consistent test results across languages. A new file containing the new tests will b
i'm going to meet with @toolmantim this afternoon to explore what the best way to handle this, will report back!

2023-09-05 15:18 UTC, abeatrix commented on vscode/src/custom-prompts/ToolsProvider.ts
> +        await this.createTempFile([testFileName, testContent].join('\n'), language)
Yea i will update the prompt and see if that works. Let's explore more options when we meet later to see what makes sense for tests generated that work for all the popular langauges

2023-09-05 15:34 UTC, umpox commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const packageJsonPath = await vscode.workspace.findFiles('**/package.json', undefined, 1)
I feel like it's easier just to ask the user to specific what testing framework they use. I think the ideal case this would work but in many cases it might just lead to more confusion (e.g. in the sourcegraph repo we have both `mocha` and `jest` in use, but really we want to be using `jest`).

This is beyond this PR, but in the longer term I really think we should consider building a form of template engine for these instructions. It could even be a Markdown format, so it's really easy for users to create their own commands.

We would provide certain globals that users can lean on to build their prompts, e..g:
- `{languageName}` like we already have, but also `{selection}`, `{fileName}` etc etc
- `{find("glob")}` we replace this with the results of a glob search before the prompt is sent to the LLM
- `{prompt("placeholder")}` we replace this with the outcome of an editor prompt, so users can build prompts that can take further input.

That's just some examples, but ideally we can have a set of base tools that lets us build new commands like this without ever having to write additional logic.

2023-09-05 15:35 UTC, umpox commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const packageJsonPath = await vscode.workspace.findFiles('**/package.json', undefined, 1)
Given that's likely out of scope and commands are the most high priority thing right now, I think that can wait - but just something we should think about

2023-09-05 15:45 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const excludePattern = '**/*{e2e,integration}*/**'
i've updated so that is exclude Pattern only applies to unit tests and not integration test or e2e test requests. 

The main goal of this function is to filter unhelpful contexts that would confuse Cody.

You can see how this is the case for the current test command:
![image](https://github.com/sourcegraph/cody/assets/68532117/5615a861-54aa-4c16-aca7-ff9d7a9a5ab1)

2023-09-05 17:17 UTC, abeatrix commented on vscode/src/custom-prompts/CommandsController.ts
> +    public getCurrentCommand(fileName?: string): CodyPrompt | null {
> This effectively constrains us to executing at most one command at a time?

1. We get the prompt text from commandInProgress during the [chatCommandsFilter step in MessageProvider](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/MessageProvider.ts?L527-529) that also sets `this.commandInProgress`
2. For the `/test` command, the `custom-prompt` recipe sets the file details for the `commandInProgress` for the post-response process (creating test files)
3. `commandInProgress` is reset when it's disposed or when a new command is run in step 1

This does not constrain users from running one command at a time (our Chat View does, users cannot submit a new request when a message is in progress).  However, if a user executes a command in Chat View, and then runs another command in the Inline-Chat, this would stop the new test file from creating, which I will look into now (thanks for pointing this out).

I can try the approach @umpox suggested, separating this into a CommandViewProvider. @umpox can you share more insights on how this is handled by the current inline-chat implementation?

>  That feels like it could cause bugs, e.g. if a user sends off a sidebar chat message or a fixup whilst a command is executing - it will still be sent to the command controller.

Regarding conflict with the fixup commands: The `CommandController` only handles custom commands and the `default` commands, so running fixup whilst a custom command is executing should not cause any issue as fixup is handled by the fixup controller that we catch through the [chatCommandsFilter in MessageProvider](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/MessageProvider.ts?L527-529)

2023-09-05 17:28 UTC, abeatrix commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
No i think what I have here is correct (and something the LLM understands). 
"the file path contains the selected code" is referring to _the current file that contains the selected code_ here.

Updating it to "an existing test file that matches the file path and contains the selected code" would means  asking Cody to check if there is an existing test file that contains the selected code, which would always be false because selected code exists in non-test files

2023-09-05 18:32 UTC, abeatrix commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of 5 unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that
Just updated from `framework&libraries` to `framework and libraries` to be clear.

You can see the test results for the updated prompt listed under the [Test 10 section in the Notebook](https://sourcegraph.sourcegraph.com/notebooks/Tm90ZWJvb2s6MTMz#test-10---latest-prompt-used-48aab2f1-793f-408a-86a8-0aa9a5a73a6e)

2023-09-05 18:55 UTC, abeatrix commented on vscode/src/custom-prompts/CommandsController.ts
> +    public getCurrentCommand(fileName?: string): CodyPrompt | null {
@umpox Does the Inline Chat currently use the same context as defined for each command?

I am currently getting different results for the `/test` command when running the command via Inline Chat, which seems to relate to the recent change to the Inline Chat Provider / Controller:

![image](https://github.com/sourcegraph/cody/assets/68532117/d6a783f6-4e06-4898-b3e3-0375408b9a2d)

2023-09-05 22:03 UTC, abeatrix commented on vscode/src/custom-prompts/CommandsController.ts
> +    public getCurrentCommand(fileName?: string): CodyPrompt | null {
Update: I've reverted changes made to `this.commandInProgress` so that it will not constrain us from executing more than one command at a time.

2023-09-06 04:05 UTC, abeatrix commented on vscode/src/custom-prompts/ToolsProvider.ts
> +        await this.createTempFile([testFileName, testContent].join('\n'), language)
will do this in a separate PR as discussed.

2023-09-06 04:16 UTC, abeatrix commented
## Update

Updated the PR to focus on improving:
- the quality of the context fetched for `/test` command
- the quality of the tests generated by the `/test` command

Working with @toolmantim to explore options for inserting the generated tests into new/existing test files, which will be included in a new PR.

2023-09-06 04:34 UTC, abeatrix commented on vscode/CHANGELOG.md
> +- The `Generate Unit Tests` command has been improved with an enhanced context fetching process that produces more consistent test results across languages. A new file containing the new tests will b
Updated the PR to focus on test output and context used for the /test command. 
Working with Tim on finding the "right behavior" for the /test command and will update that in a separate PR.

2023-09-07 07:55 UTC, dominiccooney reviewed
Some feedback inline.

I realize there's a lot of reviewers on this. Wanted to chime in to help but feel free to not block on me.

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that ma
I'd love to see some samples of this on codebases which don't have package.json, and more languages.

Grammar nit: "only includes mocks" => "only include mocks"

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/prompts/templates.ts
> +- Do not make any assumptions about the code and file names or any misleading information.
Since this is applied everywhere it feels like a roll of the dice. We need to record a battery of inputs and outputs to monitor for regressions. But since we don't have that yet, I guess YOLO?

Curious how you arrived at "any misleading information" being useful.

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/prompts/templates.ts
> +    packageJson: 'Noted. I will use the right libraries/framework already setup in your codebase for your questions.',
Not sure how much LLMs care about grammar, but libraries/framework*s* for consistent plurals, and *set up* instead of *setup*?

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/prompts/utils.ts
> +// Extract the word "unit" / "e2e" / "integration" from a test prompt text
There's a lot more relevant words here, what about: acceptance, functional, smoke, sanity (ableist but I guess we meet the user where they are), stress, performance, regression, stress, load, user acceptance, UAT, automated, security, accessibility, a11y, fuzz, ...

But since you only use this to look for "unit", why not simplify the code to just look for "unit"? You should also look for "unittest"... probably about 1/6th of "unit test" per Google Books ngrams but growing.

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +            : context.editor.getActiveTextEditorSelectionOrVisibleContent()
Doesn't `getActiveTextEditorSelectionOrVisibleContent` already get the selection, or if there's none, the visible content? Why do we need this ternary?

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        const selection = selectionContent
Adding a new binding for the same value makes sense if the name adds some documentation, but that's not the case here; let's simplify this!

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        const selectionContent = contextConfig?.selection
The name `selectionContent` doesn't seem great, it is actually an object, not the content of the selection. That is just one part of the object.

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/prompts/utils.ts
> +export function getClaudeHumanText(commandInstructions: string, currentFileName?: string): string {
We need a generic name for the "upstream LLM" because this is Claude less over time.

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/prompts/utils.ts
> +        return promptText
Should we fail if we're returning prompts containing uninterpolated strings like `{languageName}`? That would be a programming error and it is good to detect the problem close to the source.

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        if (promptContext.directoryPath !== undefined) {
Simplify this to `if (promptContext.directoryPath)`, undefined is also false; ditto below with `promptContext.filePath`

2023-09-07 07:55 UTC, dominiccooney commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +            if (selection?.fileName && getFileExtension(selection?.fileName).match(/ts|js/)) {
Maybe add tsx and jsx here on the off chance someone's using those exclusively? Are there any other template filename extensions we should add? ejs?

2023-09-07 18:49 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +            if (selection?.fileName && getFileExtension(selection?.fileName).match(/ts|js/)) {
this regex should match tsx and jsx and ejs  already?

2023-09-07 18:52 UTC, abeatrix commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Write a suite of unit tests only for the functions inside the <selected> tags of the shared context. First, review the shared context to see if there is an existing test file that ma
Yee here is a list of videos of me trying this out in different languages:
typescript: https://www.loom.com/share/3489f9ae811b41d08ca0329489580543?sid=379b3122-3ea7-4b1e-bed2-12721e1f09b6
go: https://www.loom.com/share/d1514db896c840989e05f7c74fd30b81?sid=60f8d4d6-2b6c-42d3-b016-b347666893e9
go 2: https://www.loom.com/share/952caef2067a4d748bcd10eef8a60800?sid=04ca3f58-e2c8-474f-86ee-08af03f00689
scala/java: https://www.loom.com/share/d28b1089ac8a4d9ea95816c3e476ec35?sid=adabd913-3811-4009-9391-ccd1406fe91d
python: https://www.loom.com/share/7a788b389ce84a4b85fbe2d31f4a0ab4?sid=11d9314d-31c3-4530-be6a-b4e9faa5de0b

2023-09-07 18:54 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +            : context.editor.getActiveTextEditorSelectionOrVisibleContent()
Good question! if the command is configured to have selection required, we will only accept `context.editor.getActiveTextEditorSelection()` to make sure we are not using visible content instead.  Will update the docstring to reflect this

2023-09-07 19:05 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        const selection = selectionContent
Good catch! I must be testing something and forgot to change it back lol Thanks!

2023-09-07 19:06 UTC, abeatrix commented on lib/shared/src/chat/recipes/custom-prompt.ts
> +        const selectionContent = contextConfig?.selection
updated to selection :)

2023-09-07 19:09 UTC, abeatrix commented on lib/shared/src/chat/prompts/utils.ts
> +        return promptText
I find claude would just replace the language name "in their head" if one is not provided so I think we are safe?

2023-09-07 19:17 UTC, abeatrix commented on lib/shared/src/chat/prompts/utils.ts
> +// Extract the word "unit" / "e2e" / "integration" from a test prompt text
My thinking was that not everyone puts unit tests in a directory called unit, but they most likely do not exist in directories called e2e 🤣  (or if they do, they hopefully aren't the only unit tests in the projects for us to find). The main goal is to find a couple of unit tests as examples for the LLM to see how unit tests are set up in the current project.
We try to find the test files in the current directory first, if we did find one, we will just stop there.
If we can't find any, then we will do a project level search

2023-09-07 20:06 UTC, abeatrix commented on lib/shared/src/chat/prompts/vscode-context.ts
> +    const fileName = vscode.workspace.asRelativePath(currentFile.fileName)
Yea I have added it to my follow-up items. Is editor the best place?

2023-09-09 05:03 UTC, abeatrix commented on lib/shared/src/chat/prompts/templates.ts
> +    packageJson: 'Noted. I will use the right libraries/framework already setup in your codebase for your questions.',
(prompt updated in https://github.com/sourcegraph/cody/pull/984 which will be merged back into this branch)

2023-09-09 05:06 UTC, abeatrix commented on lib/shared/src/chat/prompts/templates.ts
> +- Do not make any assumptions about the code and file names or any misleading information.
I think you are thinking about the one we use in premade? That one is applied everywhere but this one is only applied to prompts for custom commands, on top of the one in premade.

2023-09-09 05:49 UTC, abeatrix commented on lib/shared/src/chat/prompts/templates.ts
> +- Do not make any assumptions about the code and file names or any misleading information.
> Curious how you arrived at "any misleading information" being useful.

lol a teammate reported an issue  on [slack](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1692656525976169?thread_ts=1692649901.285349&cid=C04MSD3DP5L) about Cody hallucinated directory and file names, which I was able to reproduce. I saw that we already asked Cody not to make up file names, file path, only shows file paths that they are certain of their existence etc in the rules we set for Cody, which we can see are not doing much. 
I noticed Cody doesn't know the connections between the files, file name, file path etc we share with them. Long story short, refer anything I share with Cody as context / information has been working well for me, so I tried the `"any misleading information" `  approach by adding it to my custom command starter, asked Cody the same question and find it to be helpful so far.

<img width="2005" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/4d6516e1-09ca-4edf-b15e-28c70a319d15">

^ You can see it in the output channel where I added `Do not make any assumptions about the code and file names or any misleading information.` in front of the same question where teammate reported the hallucinating issue

Just tried asking Cody the same question on web and get the same hallucinating problem (the [codeownership](https://sourcegraph.com/search?q=context:global+src/components/CodeOwnership+r:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=standard&sm=1&groupBy=repo) it mentioned doesn't exist):
<img width="873" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/39fb68f6-7808-4646-809d-2f81b32d4a42">

If i prepend the statement to the question, I get the "honest" response. It would just refer to the actual shared context:
<img width="877" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/3f3900af-d993-4f7b-ba07-dcd7da385fb5">

2023-09-12 07:28 UTC, dominiccooney approved these changes
Looks good. Some minor feedback about the prompt inline.

2023-09-12 07:28 UTC, dominiccooney commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Review the shared code context and configurations to identify the test framework and libraries in use, then generate a suite of unit tests for the functions in <selected> using the d
Where you have "if it exists", do you find "it" makes the LLM squirrelly versus reiterating "if *a test file* exists"?

Why did we add flourishes like "shared code context *and configurations*"? I'm interested in how you arrived at these, determined the effect of them, because I am curious if we can scale it up.

These "think through" prompts for no new imports, importing test framework, etc. are super interesting too.

Spelling/grammar nits:
- `focuse on generate` &rarr; `focus on generating` (or maybe just `generate`?)
- `Only includes mocks` &rarr; `Only include mocks`

2023-09-12 12:47 UTC, abeatrix commented on lib/shared/src/chat/prompts/default-prompts.json
> +      "prompt": "Review the shared code context and configurations to identify the test framework and libraries in use, then generate a suite of unit tests for the functions in <selected> using the d
> Where you have "if it exists", do you find "it" makes the LLM squirrelly versus reiterating "if a test file exists"? Why did we add flourishes like "shared code context and configurations"? I'm interested in how you arrived at these, determined the effect of them, because I am curious if we can scale it up.

Good question! I noticed `"if a test file exists"` doesn't work in some languages; even if test files were shared, it would still refer to them as "shared Python code":

![image](https://github.com/sourcegraph/cody/assets/68532117/d5897dd3-2774-4f54-9a7b-c0586a96adf7)

So I tried to minimize the use of the word "file" and replace it with either "shared context" or "shared code". 

As for configurations, we are sharing package.json for ts/js tests when no test context is found, but for non-ts/js tests, we will just share a list of files located in their root dir to see if that would give them hints if a test framework is set up. Plus on top of that, i'm not familiar with how tests are set up in other languages so instead of listing each config file for the model to pick up, it seems like `configurations` has been working so far 🙏 

I am not sure if I am on the right track, though 😅 


And thanks for the grammar check and for taking the time to review 🙇‍♀️ Going to follow your suggestion and make sure the prompt still works before merging.

2023-09-13 00:16 UTC, abeatrix commented
Here is a demo run from the latest commit build: https://www.loom.com/share/a17c8c63d1284ac889cff2d0bdc93a9c?sid=aee107b7-bf23-4344-9235-a290d897e0f9

Tested the command with go, python, scala, and typescripts files as shown in the loom video above.

I have also worked on inserting the tests automatically to their test files (see video below) in https://github.com/sourcegraph/cody/pull/984, which was closed as we agreed more design works are required as well as code change with current behavior.
https://github.com/sourcegraph/cody/assets/68532117/610bce25-ab02-4fcb-a4b7-4700f71b62b9

I am going to merge what I have now for the quality improvement to focus on autocompletion works.
Will pick this back up after the oct release.

2023-09-13 00:30 UTC, merged

2023-09-13 02:02 UTC, dominiccooney commented
@abeatrix thanks for showing the output from those alternative prompts! It really illustrates how steep the drop off in performance is even changing single words.